package msfax

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FAX_JOB_ENTRY ([MS-FAX]). Generated by tools/idlgen; verify pointer/array tags.
type FAX_JOB_ENTRY struct {
	SizeOfStruct          ndr.DWORD
	JobId                 ndr.DWORD
	UserName              *ndr.WSTR `ndr:"unique"`
	JobType               ndr.DWORD
	QueueStatus           ndr.DWORD
	Status                ndr.DWORD
	Size                  ndr.DWORD
	PageCount             ndr.DWORD
	RecipientNumber       *ndr.WSTR `ndr:"unique"`
	RecipientName         *ndr.WSTR `ndr:"unique"`
	Tsid                  *ndr.WSTR `ndr:"unique"`
	SenderName            *ndr.WSTR `ndr:"unique"`
	SenderCompany         *ndr.WSTR `ndr:"unique"`
	SenderDept            *ndr.WSTR `ndr:"unique"`
	BillingCode           *ndr.WSTR `ndr:"unique"`
	ScheduleAction        ndr.DWORD
	ScheduleTime          SYSTEMTIME
	DeliveryReportType    ndr.DWORD
	DeliveryReportAddress *ndr.WSTR `ndr:"unique"`
	DocumentName          *ndr.WSTR `ndr:"unique"`
}
