package msfax

// FAX_ENUM_DEVICE_RECEIVE_MODE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FAX]).
type FAX_ENUM_DEVICE_RECEIVE_MODE uint16

const (
	FAX_DEVICE_RECEIVE_MODE_OFF    FAX_ENUM_DEVICE_RECEIVE_MODE = 0
	FAX_DEVICE_RECEIVE_MODE_AUTO   FAX_ENUM_DEVICE_RECEIVE_MODE = 1
	FAX_DEVICE_RECEIVE_MODE_MANUAL FAX_ENUM_DEVICE_RECEIVE_MODE = 2
)
