package msfax

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FAX_PORT_INFO_EXW ([MS-FAX]). Generated by tools/idlgen; verify pointer/array tags.
type FAX_PORT_INFO_EXW struct {
	DwSizeOfStruct      ndr.DWORD
	DwDeviceID          ndr.DWORD
	LpcwstrDeviceName   *ndr.WSTR `ndr:"unique"`
	LpwstrDescription   *ndr.WSTR `ndr:"unique"`
	LpcwstrProviderName *ndr.WSTR `ndr:"unique"`
	LpcwstrProviderGUID *ndr.WSTR `ndr:"unique"`
	BSend               ndr.BOOL
	ReceiveMode         FAX_ENUM_DEVICE_RECEIVE_MODE
	DwStatus            ndr.DWORD
	DwRings             ndr.DWORD
	LpwstrCsid          *ndr.WSTR `ndr:"unique"`
	LpwstrTsid          *ndr.WSTR `ndr:"unique"`
}
