package msfax

// FAX_ENUM_SMTP_AUTH_OPTIONS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FAX]).
type FAX_ENUM_SMTP_AUTH_OPTIONS uint16

const (
	FAX_SMTP_AUTH_ANONYMOUS FAX_ENUM_SMTP_AUTH_OPTIONS = 0
	FAX_SMTP_AUTH_BASIC     FAX_ENUM_SMTP_AUTH_OPTIONS = 1
	FAX_SMTP_AUTH_NTLM      FAX_ENUM_SMTP_AUTH_OPTIONS = 2
)
