package msfax

// FAX_ENUM_PERSONAL_PROF_TYPES is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FAX]).
type FAX_ENUM_PERSONAL_PROF_TYPES uint16

const (
	RECIPIENT_PERSONAL_PROF FAX_ENUM_PERSONAL_PROF_TYPES = 1
	SENDER_PERSONAL_PROF    FAX_ENUM_PERSONAL_PROF_TYPES = 2
)
