package msfax

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FAX_PORT_INFO ([MS-FAX]). Generated by tools/idlgen; verify pointer/array tags.
type FAX_PORT_INFO struct {
	SizeOfStruct ndr.DWORD
	DeviceId     ndr.DWORD
	State        ndr.DWORD
	Flags        ndr.DWORD
	Rings        ndr.DWORD
	Priority     ndr.DWORD
	DeviceName   *ndr.WSTR `ndr:"unique"`
	Tsid         *ndr.WSTR `ndr:"unique"`
	Csid         *ndr.WSTR `ndr:"unique"`
}
