package msfax

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FAX_JOB_PARAMW ([MS-FAX]). Generated by tools/idlgen; verify pointer/array tags.
type FAX_JOB_PARAMW struct {
	SizeOfStruct          ndr.DWORD
	RecipientNumber       *ndr.WSTR `ndr:"unique"`
	RecipientName         *ndr.WSTR `ndr:"unique"`
	Tsid                  *ndr.WSTR `ndr:"unique"`
	SenderName            *ndr.WSTR `ndr:"unique"`
	SenderCompany         *ndr.WSTR `ndr:"unique"`
	SenderDept            *ndr.WSTR `ndr:"unique"`
	BillingCode           *ndr.WSTR `ndr:"unique"`
	ScheduleAction        ndr.DWORD
	ScheduleTime          SYSTEMTIME
	DeliveryReportType    ndr.DWORD
	DeliveryReportAddress *ndr.WSTR `ndr:"unique"`
	DocumentName          *ndr.WSTR `ndr:"unique"`
	CallHandle            ndr.DWORD
	Reserved              [3]uint64
}
