package msfax

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FAX_RECEIPTS_CONFIGW ([MS-FAX]). Generated by tools/idlgen; verify pointer/array tags.
type FAX_RECEIPTS_CONFIGW struct {
	DwSizeOfStruct                       ndr.DWORD
	DwAllowedReceipts                    ndr.DWORD
	SMTPAuthOption                       FAX_ENUM_SMTP_AUTH_OPTIONS
	LpwstrReserved                       *ndr.WSTR `ndr:"unique"`
	LpwstrSMTPServer                     *ndr.WSTR `ndr:"unique"`
	DwSMTPPort                           ndr.DWORD
	LpwstrSMTPFrom                       *ndr.WSTR `ndr:"unique"`
	LpwstrSMTPUserName                   *ndr.WSTR `ndr:"unique"`
	LpwstrSMTPPassword                   *ndr.WSTR `ndr:"unique"`
	BIsToUseForMSRouteThroughEmailMethod ndr.BOOL
}
