package msfax

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_FAX_OUTBOUND_ROUTING_GROUPW ([MS-FAX]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_FAX_OUTBOUND_ROUTING_GROUPW struct {
	DwSizeOfStruct  ndr.DWORD
	LpwstrGroupName *ndr.WSTR `ndr:"unique"`
	DwNumDevices    ndr.DWORD
	LpdwDevices     []ndr.DWORD `ndr:"unique,size_is=DwNumDevices"`
	Status          FAX_ENUM_GROUP_STATUS
}
