package msfax

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_FAX_OUTBOUND_ROUTING_RULEW ([MS-FAX]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_FAX_OUTBOUND_ROUTING_RULEW struct {
	DwSizeOfStruct    ndr.DWORD
	DwAreaCode        ndr.DWORD
	DwCountryCode     ndr.DWORD
	LpwstrCountryName *ndr.WSTR `ndr:"unique"`
	Destination       FAX_RULE_DESTINATION
	BUseGroup         ndr.BOOL
}
