package msfax

// SYSTEMTIME ([MS-FAX]). Generated by tools/idlgen; verify pointer/array tags.
type SYSTEMTIME struct {
	WYear         uint16
	WMonth        uint16
	WDayOfWeek    uint16
	WDay          uint16
	WHour         uint16
	WMinute       uint16
	WSecond       uint16
	WMilliseconds uint16
}
