package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DATE_TIME ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DATE_TIME struct {
	DwLowDateTime  ndr.DWORD
	DwHighDateTime ndr.DWORD
}
