package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_SUBNET_INFO_VQ ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_SUBNET_INFO_VQ struct {
	SubnetAddress ndr.DWORD
	SubnetMask    ndr.DWORD
	SubnetName    *ndr.WSTR `ndr:"unique"`
	SubnetComment *ndr.WSTR `ndr:"unique"`
	PrimaryHost   DHCP_HOST_INFO
	SubnetState   DHCP_SUBNET_STATE
	QuarantineOn  ndr.DWORD
	Reserved1     ndr.DWORD
	Reserved2     ndr.DWORD
	Reserved3     INT64
	Reserved4     INT64
}
