package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_CLIENT_INFO_ARRAY_V4 ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_CLIENT_INFO_ARRAY_V4 struct {
	NumElements ndr.DWORD
	Clients     []*DHCP_CLIENT_INFO_V4 `ndr:"elem=unique,unique,size_is=NumElements"`
}
