package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_BIND_ELEMENT ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_BIND_ELEMENT struct {
	Flags                 ndr.DWORD
	FBoundToDHCPServer    ndr.BOOL
	AdapterPrimaryAddress ndr.DWORD
	AdapterSubnetAddress  ndr.DWORD
	IfDescription         *ndr.WSTR `ndr:"unique"`
	IfIdSize              ndr.DWORD
	IfId                  []uint8 `ndr:"unique,size_is=IfIdSize"`
}
