package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCPV6_BIND_ELEMENT_ARRAY ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCPV6_BIND_ELEMENT_ARRAY struct {
	NumElements ndr.DWORD
	Elements    []DHCPV6_BIND_ELEMENT `ndr:"unique,size_is=NumElements"`
}
