package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_CLIENT_INFO_V6 ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_CLIENT_INFO_V6 struct {
	ClientIpAddress         DHCP_IPV6_ADDRESS
	ClientDUID              DHCP_CLIENT_UID
	AddressType             ndr.DWORD
	IAID                    ndr.DWORD
	ClientName              *ndr.WSTR `ndr:"unique"`
	ClientComment           *ndr.WSTR `ndr:"unique"`
	ClientValidLeaseExpires DATE_TIME
	ClientPrefLeaseExpires  DATE_TIME
	OwnerHost               DHCP_HOST_INFO_V6
}
