package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_CLASS_INFO_ARRAY ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_CLASS_INFO_ARRAY struct {
	NumElements ndr.DWORD
	Classes     []DHCP_CLASS_INFO `ndr:"unique,size_is=NumElements"`
}
