package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_OPTION_DATA_ELEMENT ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_OPTION_DATA_ELEMENT struct {
	OptionType DHCP_OPTION_DATA_TYPE
	Element    DHCP_OPTION_ELEMENT_UNION
}

// DHCP_OPTION_ELEMENT_UNION is a discriminated union ([MS-DHCPM]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type DHCP_OPTION_ELEMENT_UNION struct {
	Tag                    DHCP_OPTION_DATA_TYPE `ndr:"switch"`
	ByteOption             uint8                 `ndr:"case=0"`
	WordOption             uint16                `ndr:"case=1"`
	DWordOption            ndr.DWORD             `ndr:"case=2"`
	DWordDWordOption       DWORD_DWORD           `ndr:"case=3"`
	IpAddressOption        ndr.DWORD             `ndr:"case=4"`
	StringDataOption       *ndr.WSTR             `ndr:"case=5,unique"`
	BinaryDataOption       DHCP_BINARY_DATA      `ndr:"case=6"`
	EncapsulatedDataOption DHCP_BINARY_DATA      `ndr:"case=7"`
	Ipv6AddressDataOption  *ndr.WSTR             `ndr:"case=8,unique"`
}
