package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_SUBNET_ELEMENT_INFO_ARRAY_V4 ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_SUBNET_ELEMENT_INFO_ARRAY_V4 struct {
	NumElements ndr.DWORD
	Elements    []DHCP_SUBNET_ELEMENT_DATA_V4 `ndr:"unique,size_is=NumElements"`
}
