package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_CLIENT_FILTER_STATUS_INFO ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_CLIENT_FILTER_STATUS_INFO struct {
	ClientIpAddress       ndr.DWORD
	SubnetMask            ndr.DWORD
	ClientHardwareAddress DHCP_CLIENT_UID
	ClientName            *ndr.WSTR `ndr:"unique"`
	ClientComment         *ndr.WSTR `ndr:"unique"`
	ClientLeaseExpires    DATE_TIME
	OwnerHost             DHCP_HOST_INFO
	BClientType           uint8
	AddressState          uint8
	Status                QuarantineStatus
	ProbationEnds         DATE_TIME
	QuarantineCapable     ndr.BOOL
	FilterStatus          ndr.DWORD
}
