package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_RESERVED_SCOPE ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_RESERVED_SCOPE struct {
	ReservedIpAddress       ndr.DWORD
	ReservedIpSubnetAddress ndr.DWORD
}
