package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_FILTER_ENUM_INFO ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_FILTER_ENUM_INFO struct {
	NumElements  ndr.DWORD
	PEnumRecords []DHCP_FILTER_RECORD `ndr:"unique,size_is=NumElements"`
}
