package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_POL_COND ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_POL_COND struct {
	ParentExpr  ndr.DWORD
	Type        DHCP_POL_ATTR_TYPE
	OptionID    ndr.DWORD
	SubOptionID ndr.DWORD
	VendorName  *ndr.WSTR `ndr:"unique"`
	Operator    DHCP_POL_COMPARATOR
	Value       []uint8 `ndr:"unique,size_is=ValueLength"`
	ValueLength ndr.DWORD
}
