package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_OPTION_ARRAY ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_OPTION_ARRAY struct {
	NumElements ndr.DWORD
	Options     []DHCP_OPTION `ndr:"unique,size_is=NumElements"`
}
