package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_MCLIENT_INFO_ARRAY ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_MCLIENT_INFO_ARRAY struct {
	NumElements ndr.DWORD
	Clients     []*DHCP_MCLIENT_INFO `ndr:"elem=unique,unique,size_is=NumElements"`
}
