package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_ALL_OPTIONS ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_ALL_OPTIONS struct {
	Flags            ndr.DWORD
	NonVendorOptions *DHCP_OPTION_ARRAY `ndr:"unique"`
	NumVendorOptions ndr.DWORD
	VendorOptions    []DHCP_ALL_OPTIONS_VendorOptions `ndr:"unique,size_is=NumVendorOptions"`
}

// DHCP_ALL_OPTIONS_VendorOptions ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_ALL_OPTIONS_VendorOptions struct {
	Option     DHCP_OPTION
	VendorName *ndr.WSTR `ndr:"unique"`
	ClassName  *ndr.WSTR `ndr:"unique"`
}
