package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_SERVER_CONFIG_INFO ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_SERVER_CONFIG_INFO struct {
	APIProtocolSupport      ndr.DWORD
	DatabaseName            *ndr.WSTR `ndr:"unique"`
	DatabasePath            *ndr.WSTR `ndr:"unique"`
	BackupPath              *ndr.WSTR `ndr:"unique"`
	BackupInterval          ndr.DWORD
	DatabaseLoggingFlag     ndr.DWORD
	RestoreFlag             ndr.DWORD
	DatabaseCleanupInterval ndr.DWORD
	DebugFlag               ndr.DWORD
}
