package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_CLASS_INFO_ARRAY_V6 ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_CLASS_INFO_ARRAY_V6 struct {
	NumElements ndr.DWORD
	Classes     []DHCP_CLASS_INFO_V6 `ndr:"unique,size_is=NumElements"`
}
