package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_SUPER_SCOPE_TABLE ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_SUPER_SCOPE_TABLE struct {
	CEntries ndr.DWORD
	PEntries []DHCP_SUPER_SCOPE_TABLE_ENTRY `ndr:"unique,size_is=CEntries"`
}
