package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_RESERVATION_INFO_ARRAY ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_RESERVATION_INFO_ARRAY struct {
	NumElements ndr.DWORD
	Elements    []*DHCP_IP_RESERVATION_INFO `ndr:"elem=unique,unique,size_is=NumElements"`
}
