package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_FILTER_ADD_INFO ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_FILTER_ADD_INFO struct {
	AddrPatt DHCP_ADDR_PATTERN
	Comment  *ndr.WSTR `ndr:"unique"`
	ListType DHCP_FILTER_LIST_TYPE
}
