package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_ATTRIB_ARRAY ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_ATTRIB_ARRAY struct {
	NumElements ndr.DWORD
	DhcpAttribs []DHCP_ATTRIB `ndr:"unique,size_is=NumElements"`
}
