package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_FAILOVER_STATISTICS ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_FAILOVER_STATISTICS struct {
	NumAddr          ndr.DWORD
	AddrFree         ndr.DWORD
	AddrInUse        ndr.DWORD
	PartnerAddrFree  ndr.DWORD
	ThisAddrFree     ndr.DWORD
	PartnerAddrInUse ndr.DWORD
	ThisAddrInUse    ndr.DWORD
}
