package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_MIB_INFO ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_MIB_INFO struct {
	Discovers       ndr.DWORD
	Offers          ndr.DWORD
	Requests        ndr.DWORD
	Acks            ndr.DWORD
	Naks            ndr.DWORD
	Declines        ndr.DWORD
	Releases        ndr.DWORD
	ServerStartTime DATE_TIME
	Scopes          ndr.DWORD
	ScopeInfo       []SCOPE_MIB_INFO `ndr:"unique,size_is=Scopes"`
}
