package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_OPTION_DATA ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_OPTION_DATA struct {
	NumElements ndr.DWORD
	Elements    []DHCP_OPTION_DATA_ELEMENT `ndr:"unique,size_is=NumElements"`
}
