package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_SERVER_CONFIG_INFO_V6 ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_SERVER_CONFIG_INFO_V6 struct {
	UnicastFlag           ndr.BOOL
	RapidCommitFlag       ndr.BOOL
	PreferredLifetime     ndr.DWORD
	ValidLifetime         ndr.DWORD
	T1                    ndr.DWORD
	T2                    ndr.DWORD
	PreferredLifetimeIATA ndr.DWORD
	ValidLifetimeIATA     ndr.DWORD
	FAuditLog             ndr.BOOL
}
