package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_OPTION ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_OPTION struct {
	OptionID      ndr.DWORD
	OptionName    *ndr.WSTR `ndr:"unique"`
	OptionComment *ndr.WSTR `ndr:"unique"`
	DefaultValue  DHCP_OPTION_DATA
	OptionType    DHCP_OPTION_TYPE
}
