package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCPV6_STATELESS_STATS ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCPV6_STATELESS_STATS struct {
	NumScopes  ndr.DWORD
	ScopeStats []DHCPV6_STATELESS_SCOPE_STATS `ndr:"unique,size_is=NumScopes"`
}
