package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_POL_EXPR_ARRAY ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_POL_EXPR_ARRAY struct {
	NumElements ndr.DWORD
	Elements    []DHCP_POL_EXPR `ndr:"unique,size_is=NumElements"`
}
