package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_FAILOVER_RELATIONSHIP_ARRAY ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_FAILOVER_RELATIONSHIP_ARRAY struct {
	NumElements    ndr.DWORD
	PRelationships []DHCP_FAILOVER_RELATIONSHIP `ndr:"unique,size_is=NumElements"`
}
