package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_IP_RESERVATION ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_IP_RESERVATION struct {
	ReservedIpAddress ndr.DWORD
	ReservedForClient *DHCP_CLIENT_UID `ndr:"unique"`
}
