package msdhcpm

// DHCP_OPTION_SCOPE_INFO6 ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_OPTION_SCOPE_INFO6 struct {
	ScopeType DHCP_OPTION_SCOPE_TYPE6
	ScopeInfo DHCP_OPTION_SCOPE_UNION6
}

// DHCP_OPTION_SCOPE_UNION6 is a discriminated union ([MS-DHCPM]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type DHCP_OPTION_SCOPE_UNION6 struct {
	Tag               DHCP_OPTION_SCOPE_TYPE `ndr:"switch"`
	SubnetScopeInfo   DHCP_IPV6_ADDRESS      `ndr:"case=1"`
	ReservedScopeInfo DHCP_RESERVED_SCOPE6   `ndr:"case=2"`
}
