package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_BOOTP_IP_RANGE ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_BOOTP_IP_RANGE struct {
	StartAddress    ndr.DWORD
	EndAddress      ndr.DWORD
	BootpAllocated  ndr.DWORD
	MaxBootpAllowed ndr.DWORD
}
