package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_ADDR_PATTERN ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_ADDR_PATTERN struct {
	MatchHWType ndr.BOOL
	HWType      uint8
	IsWildcard  ndr.BOOL
	Length      uint8
	Pattern     [255]uint8
}
