package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_MIB_INFO_V6 ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_MIB_INFO_V6 struct {
	Solicits        ndr.DWORD
	Advertises      ndr.DWORD
	Requests        ndr.DWORD
	Renews          ndr.DWORD
	Rebinds         ndr.DWORD
	Replies         ndr.DWORD
	Confirms        ndr.DWORD
	Declines        ndr.DWORD
	Releases        ndr.DWORD
	Informs         ndr.DWORD
	ServerStartTime DATE_TIME
	Scopes          ndr.DWORD
	ScopeInfo       []SCOPE_MIB_INFO_V6 `ndr:"unique,size_is=Scopes"`
}
