package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_POLICY_EX_ARRAY ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_POLICY_EX_ARRAY struct {
	NumElements ndr.DWORD
	Elements    []DHCP_POLICY_EX `ndr:"unique,size_is=NumElements"`
}
