package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_FILTER_RECORD ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_FILTER_RECORD struct {
	AddrPatt DHCP_ADDR_PATTERN
	Comment  *ndr.WSTR `ndr:"unique"`
}
