package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_FAILOVER_RELATIONSHIP ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_FAILOVER_RELATIONSHIP struct {
	PrimaryServer       ndr.DWORD
	SecondaryServer     ndr.DWORD
	Mode                DHCP_FAILOVER_MODE
	ServerType          DHCP_FAILOVER_SERVER
	State               FSM_STATE
	PrevState           FSM_STATE
	Mclt                ndr.DWORD
	SafePeriod          ndr.DWORD
	RelationshipName    *ndr.WSTR      `ndr:"unique"`
	PrimaryServerName   *ndr.WSTR      `ndr:"unique"`
	SecondaryServerName *ndr.WSTR      `ndr:"unique"`
	PScopes             *DHCP_IP_ARRAY `ndr:"unique"`
	Percentage          uint8
	PSharedSecret       *ndr.WSTR `ndr:"unique"`
}
