package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_PROPERTY ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_PROPERTY struct {
	ID    DHCP_PROPERTY_ID
	Type  DHCP_PROPERTY_TYPE
	Value DHCP_PROPERTY_VALUE_UNION
}

// DHCP_PROPERTY_VALUE_UNION is a discriminated union ([MS-DHCPM]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type DHCP_PROPERTY_VALUE_UNION struct {
	Tag         DHCP_PROPERTY_TYPE `ndr:"switch"`
	ByteValue   uint8              `ndr:"case=0"`
	WordValue   uint16             `ndr:"case=1"`
	DWordValue  ndr.DWORD          `ndr:"case=2"`
	StringValue *ndr.WSTR          `ndr:"case=3,unique"`
	BinaryValue DHCP_BINARY_DATA   `ndr:"case=4"`
}
