package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_HOST_INFO ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_HOST_INFO struct {
	IpAddress   ndr.DWORD
	NetBiosName *ndr.WSTR `ndr:"unique"`
	HostName    *ndr.WSTR `ndr:"unique"`
}
