package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_CLIENT_INFO_ARRAY_V5 ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_CLIENT_INFO_ARRAY_V5 struct {
	NumElements ndr.DWORD
	Clients     []*DHCP_CLIENT_INFO_V5 `ndr:"elem=unique,unique,size_is=NumElements"`
}
