package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCP_POLICY ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_POLICY struct {
	PolicyName      *ndr.WSTR `ndr:"unique"`
	IsGlobalPolicy  ndr.BOOL
	Subnet          ndr.DWORD
	ProcessingOrder ndr.DWORD
	Conditions      *DHCP_POL_COND_ARRAY `ndr:"unique"`
	Expressions     *DHCP_POL_EXPR_ARRAY `ndr:"unique"`
	Ranges          *DHCP_IP_RANGE_ARRAY `ndr:"unique"`
	Description     *ndr.WSTR            `ndr:"unique"`
	Enabled         ndr.BOOL
}
