package msdhcpm

// DHCP_SUBNET_ELEMENT_DATA ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCP_SUBNET_ELEMENT_DATA struct {
	ElementType DHCP_SUBNET_ELEMENT_TYPE
	Element     DHCP_SUBNET_ELEMENT_UNION
}

// DHCP_SUBNET_ELEMENT_UNION is a discriminated union ([MS-DHCPM]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type DHCP_SUBNET_ELEMENT_UNION struct {
	Tag            DHCP_SUBNET_ELEMENT_TYPE `ndr:"switch"`
	IpRange        *DHCP_IP_RANGE           `ndr:"case=0,unique"`
	SecondaryHost  *DHCP_HOST_INFO          `ndr:"case=1,unique"`
	ReservedIp     *DHCP_IP_RESERVATION     `ndr:"case=2,unique"`
	ExcludeIpRange *DHCP_IP_RANGE           `ndr:"case=3,unique"`
	IpUsedCluster  *DHCP_IP_CLUSTER         `ndr:"case=4,unique"`
}
