package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DWORD_DWORD ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type DWORD_DWORD struct {
	DWord1 ndr.DWORD
	DWord2 ndr.DWORD
}
