package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SCOPE_MIB_INFO ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type SCOPE_MIB_INFO struct {
	Subnet            ndr.DWORD
	NumAddressesInuse ndr.DWORD
	NumAddressesFree  ndr.DWORD
	NumPendingOffers  ndr.DWORD
}
