package msdhcpm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SCOPE_MIB_INFO_VQ ([MS-DHCPM]). Generated by tools/idlgen; verify pointer/array tags.
type SCOPE_MIB_INFO_VQ struct {
	Subnet             ndr.DWORD
	NumAddressesInuse  ndr.DWORD
	NumAddressesFree   ndr.DWORD
	NumPendingOffers   ndr.DWORD
	QtnNumLeases       ndr.DWORD
	QtnPctQtnLeases    ndr.DWORD
	QtnProbationLeases ndr.DWORD
	QtnNonQtnLeases    ndr.DWORD
	QtnExemptLeases    ndr.DWORD
	QtnCapableClients  ndr.DWORD
}
