// Package rpcinterface_7c44d7d431d5424cbd5e2b3e1f323d22_1_0 is the descriptor for the dsaop RPC interface, abstract
// syntax 7c44d7d4-31d5-424c-bd5e-2b3e1f323d22 version 1.0 ([MS-DRSR]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName, the status-code table, and doc comments are not derivable from
// the IDL and must be confirmed by hand (see the TODO markers).
package rpcinterface_7c44d7d431d5424cbd5e2b3e1f323d22_1_0

// IDL source: [MS-DRSR] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-drsr/3f5d9495-9563-44de-876a-ce6f880e3fb2
// A fetched copy is kept at ms-drsr.idl in the interface directory.

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is retained for descriptor uniformity, but dsaop (the directory-service
// administration interface used for RODC demotion scripting, [MS-DRSR]) is not a
// named-pipe interface: like drsuapi it is carried over ncacn_ip_tcp on a dynamic
// endpoint resolved through the endpoint mapper (TCP/135). This constant is not the
// standard binding for this interface.
const PipeName = `\drsuapi`

// Opnums for the on-the-wire methods.
const (
	OpnumIDL_DSAPrepareScript uint16 = 0
	OpnumIDL_DSAExecuteScript uint16 = 1
)

// Status codes returned by this interface. dsaop methods return Win32 error codes
// (a DWORD return value), NOT NTSTATUS — so StatusSuccess is ERROR_SUCCESS (0). Extend
// this table (and StatusString) with additional codes as each method is wire-validated.
const (
	StatusSuccess         uint32 = 0x00000000 // ERROR_SUCCESS
	ErrorAccessDenied     uint32 = 0x00000005 // ERROR_ACCESS_DENIED
	ErrorNotSupported     uint32 = 0x00000032 // ERROR_NOT_SUPPORTED
	ErrorInvalidParameter uint32 = 0x00000057 // ERROR_INVALID_PARAMETER
)

// SyntaxID returns the dsaop abstract syntax identifier:
// 7c44d7d4-31d5-424c-bd5e-2b3e1f323d22, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x7c44d7d4, B: 0x31d5, C: 0x424c, D: 0xbd5e, E: 0x2b3e1f323d22},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented status codes, otherwise the
// hex value.
func StatusString(status uint32) string {
	switch status {
	case StatusSuccess:
		return "ERROR_SUCCESS"
	case ErrorAccessDenied:
		return "ERROR_ACCESS_DENIED"
	case ErrorNotSupported:
		return "ERROR_NOT_SUPPORTED"
	case ErrorInvalidParameter:
		return "ERROR_INVALID_PARAMETER"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumIDL_DSAPrepareScript: "IDL_DSAPrepareScript",
	OpnumIDL_DSAExecuteScript: "IDL_DSAExecuteScript",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
