// Package rpcinterface_1ff706820a5130e8076d740be8cee98b_1_0 is the descriptor for the atsvc RPC interface, abstract
// syntax 1ff70682-0a51-30e8-076d-740be8cee98b version 1.0 ([MS-TSCH]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName and the doc comments are not derivable from the IDL and were
// filled in and verified by hand ([MS-TSCH] 2.1, 3.2.5).
package rpcinterface_1ff706820a5130e8076d740be8cee98b_1_0

// IDL source: [MS-TSCH] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tsch/6fc1f51a-26ec-43fa-a8bd-1c364657f110
// A fetched copy is kept at ms-tsch.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the atsvc interface. Per [MS-TSCH] 2.1
// the ATSvc and SASec interfaces share the well-known ncacn_np endpoint \PIPE\atsvc.
const PipeName = `\atsvc`

// Opnums for the on-the-wire methods.
const (
	OpnumNetrJobAdd     uint16 = 0
	OpnumNetrJobDel     uint16 = 1
	OpnumNetrJobEnum    uint16 = 2
	OpnumNetrJobGetInfo uint16 = 3
)

// The NET_API_STATUS (Win32) codes the ATSvc methods return ([MS-TSCH] 3.2.5.2,
// [MS-ERREF] 2.2) are not declared here. The whole of [MS-ERREF] 2.2 lives in
// github.com/TheManticoreProject/Manticore/windows/errors/win32 as the WIN32_ERROR
// type, and a subset repeated here would cover a fraction of that 2703-code table while
// drifting from it. Convert a returned status with win32.WIN32_ERROR(status) and compare
// against win32.ERROR_SUCCESS and the rest; NetrJobEnum returns win32.ERROR_MORE_DATA
// when the results do not all fit in the buffer, and callers resume with the returned
// pResumeHandle. Every value this interface used to declare has a row in [MS-ERREF] 2.2
// under the name the declaration carried, so nothing is kept local.

// SyntaxID returns the atsvc abstract syntax identifier:
// 1ff70682-0a51-30e8-076d-740be8cee98b, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x1ff70682, B: 0x0a51, C: 0x30e8, D: 0x076d, E: 0x740be8cee98b},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumNetrJobAdd:     "NetrJobAdd",
	OpnumNetrJobDel:     "NetrJobDel",
	OpnumNetrJobEnum:    "NetrJobEnum",
	OpnumNetrJobGetInfo: "NetrJobGetInfo",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
