package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// PORT_INFO_3 ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type PORT_INFO_3 struct {
	DwStatus   ndr.DWORD
	PszStatus  *ndr.WSTR `ndr:"unique"`
	DwSeverity ndr.DWORD
}
