package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_BIDI_RESPONSE_CONTAINER ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_BIDI_RESPONSE_CONTAINER struct {
	Version ndr.DWORD
	Flags   ndr.DWORD
	Count   ndr.DWORD
	AData   []RPC_BIDI_RESPONSE_DATA `ndr:"unique,size_is=Count"`
}
