package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_DRIVER_INFO_4 ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_DRIVER_INFO_4 struct {
	CVersion          ndr.DWORD
	PName             *ndr.WSTR `ndr:"unique"`
	PEnvironment      *ndr.WSTR `ndr:"unique"`
	PDriverPath       *ndr.WSTR `ndr:"unique"`
	PDataFile         *ndr.WSTR `ndr:"unique"`
	PConfigFile       *ndr.WSTR `ndr:"unique"`
	PHelpFile         *ndr.WSTR `ndr:"unique"`
	PMonitorName      *ndr.WSTR `ndr:"unique"`
	PDefaultDataType  *ndr.WSTR `ndr:"unique"`
	CchDependentFiles ndr.DWORD
	PDependentFiles   []uint16 `ndr:"unique,size_is=CchDependentFiles"`
	CchPreviousNames  ndr.DWORD
	PszzPreviousNames []uint16 `ndr:"unique,size_is=CchPreviousNames"`
}
