package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_BIDI_DATA ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_BIDI_DATA struct {
	DwBidiType ndr.DWORD
	U          RPC_BIDI_DATA_U
}

// RPC_BIDI_DATA_U is a discriminated union ([MS-RPRN]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type RPC_BIDI_DATA_U struct {
	Tag    ndr.DWORD            `ndr:"switch"`
	BData  int32                `ndr:"case=0"`
	IData  int32                `ndr:"case=1"`
	SData  *uint16              `ndr:"case=4,unique"`
	FData  float32              `ndr:"case=2"`
	BiData RPC_BINARY_CONTAINER `ndr:"case=7"`
}
