package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_BranchOfficeLogOfflineFileFull ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_BranchOfficeLogOfflineFileFull struct {
	PMachineName *ndr.WSTR `ndr:"unique"`
}
