package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_V2_NOTIFY_OPTIONS_TYPE ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_V2_NOTIFY_OPTIONS_TYPE struct {
	Type      uint16
	Reserved0 uint16
	Reserved1 ndr.DWORD
	Reserved2 ndr.DWORD
	Count     ndr.DWORD
	PFields   []uint16 `ndr:"unique,size_is=Count"`
}
