package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_BranchOfficeJobDataRendered ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_BranchOfficeJobDataRendered struct {
	Size         int64
	ICMMethod    ndr.DWORD
	Color        int16
	PrintQuality int16
	YResolution  int16
	Copies       int16
	TTOption     int16
}
