package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_BIDI_REQUEST_DATA ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_BIDI_REQUEST_DATA struct {
	DwReqNumber ndr.DWORD
	PSchema     *ndr.WSTR `ndr:"unique"`
	Data        RPC_BIDI_DATA
}
