package msraiw

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// WINSINTF_SCV_REQ_T ([MS-RAIW]). Generated by tools/idlgen; verify pointer/array tags.
type WINSINTF_SCV_REQ_T struct {
	Opcode_e WINSINTF_SCV_OPC_E
	Age      ndr.DWORD
	FForce   ndr.DWORD
}
