package msraiw

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// WINSINTF_ADD_T ([MS-RAIW]). Generated by tools/idlgen; verify pointer/array tags.
type WINSINTF_ADD_T struct {
	Type  uint8
	Len   ndr.DWORD
	IPAdd ndr.DWORD
}
