package msraiw

import (
	msdtyp "github.com/TheManticoreProject/Manticore/windows/ms-dtyp"
)

// WINSINTF_ADD_VERS_MAP_T ([MS-RAIW]). Generated by tools/idlgen; verify pointer/array tags.
type WINSINTF_ADD_VERS_MAP_T struct {
	Add    WINSINTF_ADD_T
	VersNo msdtyp.LARGE_INTEGER
}
