package msraiw

// WINSINTF_ACT_E is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-RAIW]).
type WINSINTF_ACT_E uint16

const (
	WINSINTF_E_INSERT  WINSINTF_ACT_E = 0
	WINSINTF_E_DELETE  WINSINTF_ACT_E = 1
	WINSINTF_E_RELEASE WINSINTF_ACT_E = 2
	WINSINTF_E_MODIFY  WINSINTF_ACT_E = 3
	WINSINTF_E_QUERY   WINSINTF_ACT_E = 4
)
