package fingerprint

import (
	"sync"

	"github.com/TheManticoreProject/Manticore/crypto/spnego/ntlm/version"
	"github.com/TheManticoreProject/Manticore/network/smb/smb_v20/capabilities"
	"github.com/TheManticoreProject/Manticore/network/smb/smb_v20/dialects"
	"github.com/TheManticoreProject/Manticore/network/smb/smb_v20/securitymode"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// windowsServer2012R2 is the identity a Windows Server 2012 R2 Standard 9600
// returns in its SESSION_SETUP_ANDX, read from a live host. The pair is
// self-consistent the way Windows makes it: the same product name, with the
// build number in one field and the major.minor version in the other.
const (
	windowsServer2012R2NativeOS     = "Windows Server 2012 R2 Standard 9600"
	windowsServer2012R2NativeLanMan = "Windows Server 2012 R2 Standard 6.3"
)

// defaultProfile is what this implementation emits.
//
// It is not a claim to resemble anything. Each value is either measured from a
// real peer, required by a specification, or a deliberate choice of this
// implementation, and the comments say which — a profile whose provenance is
// unstated invites exactly the guesswork this package exists to prevent.
var defaultProfile = Profile{
	Name: "manticore-default",
	Provenance: "identity strings measured from a Windows Server 2012 R2 Standard 9600; " +
		"dialects and salt length per [MS-SMB2]; capabilities limited to what this implementation honours",

	// Measured. Chosen over an empty pair because strict peers reject empty
	// native strings, and over a project name because that names the sender.
	NativeOS:     windowsServer2012R2NativeOS,
	NativeLanMan: windowsServer2012R2NativeLanMan,

	// A plausible Windows 10 build. The value matters less than its shape: a
	// build number of zero, which this implementation emitted for a long time,
	// corresponds to no Windows release that has ever existed.
	NTLMVersion: version.DefaultVersion(),

	// Used only when the local hostname cannot be read. "WORKSTATION" is a
	// generic NetBIOS name rather than a project name; it says nothing.
	CallingNameFallback: "WORKSTATION",

	// [MS-SMB2] 2.2.3 requires ascending order.
	Dialects: []dialects.Dialect{
		dialects.SMB2_DIALECT_2_0_2,
		dialects.SMB2_DIALECT_2_1_0,
		dialects.SMB2_DIALECT_3_0_0,
		dialects.SMB2_DIALECT_3_0_2,
		dialects.SMB2_DIALECT_3_1_1,
	},

	// Deliberately short of what a Windows client advertises. The bits omitted
	// here — DFS, persistent handles — stand for features this client does not
	// implement, and claiming a capability that is then refused is a louder
	// difference than not claiming it.
	Capabilities: capabilities.SMB2_GLOBAL_CAP_LARGE_MTU |
		capabilities.SMB2_GLOBAL_CAP_MULTI_CHANNEL |
		capabilities.SMB2_GLOBAL_CAP_ENCRYPTION |
		capabilities.SMB2_GLOBAL_CAP_LEASING |
		capabilities.SMB2_GLOBAL_CAP_DIRECTORY_LEASING,

	SecurityMode: securitymode.SMB2_NEGOTIATE_SIGNING_ENABLED,

	// AES-256-GCM, AES-128-GCM, AES-256-CCM, AES-128-CCM. GCM is preferred
	// within each key size for its hardware acceleration; 256-bit variants
	// are offered first for stronger encryption when the server supports them.
	Ciphers: []uint16{0x0004, 0x0002, 0x0003, 0x0001},

	// AES-GMAC, then AES-CMAC. AES-GMAC is faster (hardware-accelerated GCM)
	// and available from Windows Server 2022 / Windows 11. Offering both lets
	// the server pick GMAC when it can, falling back to CMAC otherwise.
	SigningAlgorithms: []uint16{0x0002, 0x0001}, // AES-GMAC, AES-CMAC

	// [MS-SMB2] 2.2.3.1.1; 32 bytes is what Windows sends.
	PreauthSaltLength: 32,
}

// Default returns the profile this implementation uses unless a caller chooses
// otherwise. The returned profile is a copy, so adjusting it cannot change what
// any other connection emits.
func Default() *Profile {
	return defaultProfile.Clone()
}

var (
	machineGuidOnce sync.Once
	machineGuid     [16]byte
)

// MachineGuid returns the GUID this process presents as its SMB2 ClientGuid.
//
// [MS-SMB2] 3.2.1.1 describes it as a GUID generated by the client, and a
// Windows client keeps one per machine across reboots. This implementation
// cannot persist anything without being told where, so it generates one per
// process instead: stable for every connection a process makes, which is what
// the field is for, and unlike the sixteen zero bytes it replaces it does not
// announce that nothing ever set it.
//
// A caller holding a persisted GUID should set it on the client directly rather
// than relying on this.
func MachineGuid() [16]byte {
	machineGuidOnce.Do(func() {
		copy(machineGuid[:], guid.NewGUID().ToBytes())
	})
	return machineGuid
}
