// Package rpcinterface_ea0a3165483411d2a6f800c04fa346cc_4_0 is the descriptor for the fax RPC interface, abstract
// syntax ea0a3165-4834-11d2-a6f8-00c04fa346cc version 4.0 ([MS-FAX]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName, the status-code table, and doc comments are not derivable from
// the IDL and must be confirmed by hand (see the TODO markers).
package rpcinterface_ea0a3165483411d2a6f800c04fa346cc_4_0

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the fax interface. [MS-FAX] section
// 2.1 (Transport) states the protocol uses an RPC well-known endpoint over a named
// pipe named SHAREDFAX.
const PipeName = `\SHAREDFAX`

// Opnums for the on-the-wire methods.
const (
	OpnumFAX_GetServicePrinters              uint16 = 0
	OpnumFAX_ConnectionRefCount              uint16 = 1
	OpnumFAX_OpenPort                        uint16 = 2
	OpnumFAX_ClosePort                       uint16 = 3
	OpnumFAX_EnumJobs                        uint16 = 4
	OpnumFAX_GetJob                          uint16 = 5
	OpnumFAX_SetJob                          uint16 = 6
	OpnumFAX_GetPageData                     uint16 = 7
	OpnumFAX_GetDeviceStatus                 uint16 = 8
	OpnumFAX_Abort                           uint16 = 9
	OpnumFAX_EnumPorts                       uint16 = 10
	OpnumFAX_GetPort                         uint16 = 11
	OpnumFAX_SetPort                         uint16 = 12
	OpnumFAX_EnumRoutingMethods              uint16 = 13
	OpnumFAX_EnableRoutingMethod             uint16 = 14
	OpnumFAX_GetRoutingInfo                  uint16 = 15
	OpnumFAX_SetRoutingInfo                  uint16 = 16
	OpnumFAX_EnumGlobalRoutingInfo           uint16 = 17
	OpnumFAX_SetGlobalRoutingInfo            uint16 = 18
	OpnumFAX_GetConfiguration                uint16 = 19
	OpnumFAX_SetConfiguration                uint16 = 20
	OpnumFAX_GetLoggingCategories            uint16 = 21
	OpnumFAX_SetLoggingCategories            uint16 = 22
	OpnumFAX_GetSecurity                     uint16 = 23
	OpnumFAX_SetSecurity                     uint16 = 24
	OpnumFAX_AccessCheck                     uint16 = 25
	OpnumFAX_CheckServerProtSeq              uint16 = 26
	OpnumFAX_SendDocumentEx                  uint16 = 27
	OpnumFAX_EnumJobsEx                      uint16 = 28
	OpnumFAX_GetJobEx                        uint16 = 29
	OpnumFAX_GetCountryList                  uint16 = 30
	OpnumFAX_GetPersonalProfileInfo          uint16 = 31
	OpnumFAX_GetQueueStates                  uint16 = 32
	OpnumFAX_SetQueue                        uint16 = 33
	OpnumFAX_GetReceiptsConfiguration        uint16 = 34
	OpnumFAX_SetReceiptsConfiguration        uint16 = 35
	OpnumFAX_GetReceiptsOptions              uint16 = 36
	OpnumFAX_GetVersion                      uint16 = 37
	OpnumFAX_GetOutboxConfiguration          uint16 = 38
	OpnumFAX_SetOutboxConfiguration          uint16 = 39
	OpnumFAX_GetPersonalCoverPagesOption     uint16 = 40
	OpnumFAX_GetArchiveConfiguration         uint16 = 41
	OpnumFAX_SetArchiveConfiguration         uint16 = 42
	OpnumFAX_GetActivityLoggingConfiguration uint16 = 43
	OpnumFAX_SetActivityLoggingConfiguration uint16 = 44
	OpnumFAX_EnumerateProviders              uint16 = 45
	OpnumFAX_GetPortEx                       uint16 = 46
	OpnumFAX_SetPortEx                       uint16 = 47
	OpnumFAX_EnumPortsEx                     uint16 = 48
	OpnumFAX_GetExtensionData                uint16 = 49
	OpnumFAX_SetExtensionData                uint16 = 50
	OpnumFAX_AddOutboundGroup                uint16 = 51
	OpnumFAX_SetOutboundGroup                uint16 = 52
	OpnumFAX_RemoveOutboundGroup             uint16 = 53
	OpnumFAX_EnumOutboundGroups              uint16 = 54
	OpnumFAX_SetDeviceOrderInGroup           uint16 = 55
	OpnumFAX_AddOutboundRule                 uint16 = 56
	OpnumFAX_RemoveOutboundRule              uint16 = 57
	OpnumFAX_SetOutboundRule                 uint16 = 58
	OpnumFAX_EnumOutboundRules               uint16 = 59
	OpnumFAX_RegisterServiceProviderEx       uint16 = 60
	OpnumFAX_UnregisterServiceProviderEx     uint16 = 61
	OpnumFAX_UnregisterRoutingExtension      uint16 = 62
	OpnumFAX_StartMessagesEnum               uint16 = 63
	OpnumFAX_EndMessagesEnum                 uint16 = 64
	OpnumFAX_EnumMessages                    uint16 = 65
	OpnumFAX_GetMessage                      uint16 = 66
	OpnumFAX_RemoveMessage                   uint16 = 67
	OpnumFAX_StartCopyToServer               uint16 = 68
	OpnumFAX_StartCopyMessageFromServer      uint16 = 69
	OpnumFAX_WriteFile                       uint16 = 70
	OpnumFAX_ReadFile                        uint16 = 71
	OpnumFAX_EndCopy                         uint16 = 72
	OpnumFAX_StartServerNotification         uint16 = 73
	OpnumFAX_StartServerNotificationEx       uint16 = 74
	OpnumFAX_EndServerNotification           uint16 = 75
	OpnumFAX_GetServerActivity               uint16 = 76
	OpnumFAX_SetConfigWizardUsed             uint16 = 77
	OpnumFAX_EnumRoutingExtensions           uint16 = 78
	OpnumFAX_ConnectFaxServer                uint16 = 79
	OpnumFAX_GetSecurityEx                   uint16 = 80
	OpnumFAX_RefreshArchive                  uint16 = 81
	OpnumFAX_SetRecipientsLimit              uint16 = 82
	OpnumFAX_GetRecipientsLimit              uint16 = 83
	OpnumFAX_GetServerSKU                    uint16 = 84
	OpnumFAX_CheckValidFaxFolder             uint16 = 85
	OpnumFAX_GetJobEx2                       uint16 = 86
	OpnumFAX_EnumJobsEx2                     uint16 = 87
	OpnumFAX_GetMessageEx                    uint16 = 88
	OpnumFAX_StartMessagesEnumEx             uint16 = 89
	OpnumFAX_EnumMessagesEx                  uint16 = 90
	OpnumFAX_StartServerNotificationEx2      uint16 = 91
	OpnumFAX_CreateAccount                   uint16 = 92
	OpnumFAX_DeleteAccount                   uint16 = 93
	OpnumFAX_EnumAccounts                    uint16 = 94
	OpnumFAX_GetAccountInfo                  uint16 = 95
	OpnumFAX_GetGeneralConfiguration         uint16 = 96
	OpnumFAX_SetGeneralConfiguration         uint16 = 97
	OpnumFAX_GetSecurityEx2                  uint16 = 98
	OpnumFAX_SetSecurityEx2                  uint16 = 99
	OpnumFAX_AccessCheckEx2                  uint16 = 100
	OpnumFAX_ReAssignMessage                 uint16 = 101
	OpnumFAX_SetMessage                      uint16 = 102
	OpnumFAX_GetConfigOption                 uint16 = 103
)

// Every method of the fax interface returns error_status_t, a Win32 error code
// ([MS-ERREF] section 2.2). Success is ERROR_SUCCESS (0). The codes below are the
// common Win32 errors these methods return plus the fax-specific FAX_ERR_* codes
// ([MS-FAX] section 2.2.52). StatusSuccess names ERROR_SUCCESS so the generated
// stubs' success test reads naturally.
const (
	StatusSuccess uint32 = 0x00000000 // ERROR_SUCCESS

	// Common Win32 error codes ([MS-ERREF] section 2.2).
	ErrorFileNotFound       uint32 = 0x00000002 // ERROR_FILE_NOT_FOUND
	ErrorAccessDenied       uint32 = 0x00000005 // ERROR_ACCESS_DENIED
	ErrorInvalidHandle      uint32 = 0x00000006 // ERROR_INVALID_HANDLE
	ErrorNotEnoughMemory    uint32 = 0x00000008 // ERROR_NOT_ENOUGH_MEMORY
	ErrorInvalidData        uint32 = 0x0000000D // ERROR_INVALID_DATA
	ErrorNotSupported       uint32 = 0x00000032 // ERROR_NOT_SUPPORTED
	ErrorInvalidParameter   uint32 = 0x00000057 // ERROR_INVALID_PARAMETER
	ErrorBufferOverflow     uint32 = 0x0000006F // ERROR_BUFFER_OVERFLOW
	ErrorInsufficientBuffer uint32 = 0x0000007A // ERROR_INSUFFICIENT_BUFFER
	ErrorInvalidLevel       uint32 = 0x0000007C // ERROR_INVALID_LEVEL
	ErrorAlreadyExists      uint32 = 0x000000B7 // ERROR_ALREADY_EXISTS
	ErrorNoMoreItems        uint32 = 0x00000103 // ERROR_NO_MORE_ITEMS

	// Fax-specific error codes ([MS-FAX] section 2.2.52).
	FaxErrSrvOutOfMemory        uint32 = 0x00001B59 // FAX_ERR_SRV_OUTOFMEMORY (7001)
	FaxErrGroupNotFound         uint32 = 0x00001B5A // FAX_ERR_GROUP_NOT_FOUND (7002)
	FaxErrBadGroupConfiguration uint32 = 0x00001B5B // FAX_ERR_BAD_GROUP_CONFIGURATION (7003)
	FaxErrGroupInUse            uint32 = 0x00001B5C // FAX_ERR_GROUP_IN_USE (7004)
	FaxErrRuleNotFound          uint32 = 0x00001B5D // FAX_ERR_RULE_NOT_FOUND (7005)
	FaxErrNotNTFS               uint32 = 0x00001B5E // FAX_ERR_NOT_NTFS (7006)
	FaxErrDirectoryInUse        uint32 = 0x00001B5F // FAX_ERR_DIRECTORY_IN_USE (7007)
	FaxErrFileAccessDenied      uint32 = 0x00001B60 // FAX_ERR_FILE_ACCESS_DENIED (7008)
	FaxErrMessageNotFound       uint32 = 0x00001B61 // FAX_ERR_MESSAGE_NOT_FOUND (7009)
	FaxErrDeviceNumLimit        uint32 = 0x00001B62 // FAX_ERR_DEVICE_NUM_LIMIT_EXCEEDED (7010)
	FaxErrNotSupportedOnThisSKU uint32 = 0x00001B63 // FAX_ERR_NOT_SUPPORTED_ON_THIS_SKU (7011)
	FaxErrVersionMismatch       uint32 = 0x00001B64 // FAX_ERR_VERSION_MISMATCH (7012)
	FaxErrRecipientsLimit       uint32 = 0x00001B65 // FAX_ERR_RECIPIENTS_LIMIT (7013)
)

// SyntaxID returns the fax abstract syntax identifier:
// ea0a3165-4834-11d2-a6f8-00c04fa346cc, version 4.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0xea0a3165, B: 0x4834, C: 0x11d2, D: 0xa6f8, E: 0x00c04fa346cc},
		MajorVersion: 4,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented status codes, otherwise the
// hex value.
func StatusString(status uint32) string {
	switch status {
	case StatusSuccess:
		return "ERROR_SUCCESS"
	case ErrorFileNotFound:
		return "ERROR_FILE_NOT_FOUND"
	case ErrorAccessDenied:
		return "ERROR_ACCESS_DENIED"
	case ErrorInvalidHandle:
		return "ERROR_INVALID_HANDLE"
	case ErrorNotEnoughMemory:
		return "ERROR_NOT_ENOUGH_MEMORY"
	case ErrorInvalidData:
		return "ERROR_INVALID_DATA"
	case ErrorNotSupported:
		return "ERROR_NOT_SUPPORTED"
	case ErrorInvalidParameter:
		return "ERROR_INVALID_PARAMETER"
	case ErrorBufferOverflow:
		return "ERROR_BUFFER_OVERFLOW"
	case ErrorInsufficientBuffer:
		return "ERROR_INSUFFICIENT_BUFFER"
	case ErrorInvalidLevel:
		return "ERROR_INVALID_LEVEL"
	case ErrorAlreadyExists:
		return "ERROR_ALREADY_EXISTS"
	case ErrorNoMoreItems:
		return "ERROR_NO_MORE_ITEMS"
	case FaxErrSrvOutOfMemory:
		return "FAX_ERR_SRV_OUTOFMEMORY"
	case FaxErrGroupNotFound:
		return "FAX_ERR_GROUP_NOT_FOUND"
	case FaxErrBadGroupConfiguration:
		return "FAX_ERR_BAD_GROUP_CONFIGURATION"
	case FaxErrGroupInUse:
		return "FAX_ERR_GROUP_IN_USE"
	case FaxErrRuleNotFound:
		return "FAX_ERR_RULE_NOT_FOUND"
	case FaxErrNotNTFS:
		return "FAX_ERR_NOT_NTFS"
	case FaxErrDirectoryInUse:
		return "FAX_ERR_DIRECTORY_IN_USE"
	case FaxErrFileAccessDenied:
		return "FAX_ERR_FILE_ACCESS_DENIED"
	case FaxErrMessageNotFound:
		return "FAX_ERR_MESSAGE_NOT_FOUND"
	case FaxErrDeviceNumLimit:
		return "FAX_ERR_DEVICE_NUM_LIMIT_EXCEEDED"
	case FaxErrNotSupportedOnThisSKU:
		return "FAX_ERR_NOT_SUPPORTED_ON_THIS_SKU"
	case FaxErrVersionMismatch:
		return "FAX_ERR_VERSION_MISMATCH"
	case FaxErrRecipientsLimit:
		return "FAX_ERR_RECIPIENTS_LIMIT"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumFAX_GetServicePrinters:              "FAX_GetServicePrinters",
	OpnumFAX_ConnectionRefCount:              "FAX_ConnectionRefCount",
	OpnumFAX_OpenPort:                        "FAX_OpenPort",
	OpnumFAX_ClosePort:                       "FAX_ClosePort",
	OpnumFAX_EnumJobs:                        "FAX_EnumJobs",
	OpnumFAX_GetJob:                          "FAX_GetJob",
	OpnumFAX_SetJob:                          "FAX_SetJob",
	OpnumFAX_GetPageData:                     "FAX_GetPageData",
	OpnumFAX_GetDeviceStatus:                 "FAX_GetDeviceStatus",
	OpnumFAX_Abort:                           "FAX_Abort",
	OpnumFAX_EnumPorts:                       "FAX_EnumPorts",
	OpnumFAX_GetPort:                         "FAX_GetPort",
	OpnumFAX_SetPort:                         "FAX_SetPort",
	OpnumFAX_EnumRoutingMethods:              "FAX_EnumRoutingMethods",
	OpnumFAX_EnableRoutingMethod:             "FAX_EnableRoutingMethod",
	OpnumFAX_GetRoutingInfo:                  "FAX_GetRoutingInfo",
	OpnumFAX_SetRoutingInfo:                  "FAX_SetRoutingInfo",
	OpnumFAX_EnumGlobalRoutingInfo:           "FAX_EnumGlobalRoutingInfo",
	OpnumFAX_SetGlobalRoutingInfo:            "FAX_SetGlobalRoutingInfo",
	OpnumFAX_GetConfiguration:                "FAX_GetConfiguration",
	OpnumFAX_SetConfiguration:                "FAX_SetConfiguration",
	OpnumFAX_GetLoggingCategories:            "FAX_GetLoggingCategories",
	OpnumFAX_SetLoggingCategories:            "FAX_SetLoggingCategories",
	OpnumFAX_GetSecurity:                     "FAX_GetSecurity",
	OpnumFAX_SetSecurity:                     "FAX_SetSecurity",
	OpnumFAX_AccessCheck:                     "FAX_AccessCheck",
	OpnumFAX_CheckServerProtSeq:              "FAX_CheckServerProtSeq",
	OpnumFAX_SendDocumentEx:                  "FAX_SendDocumentEx",
	OpnumFAX_EnumJobsEx:                      "FAX_EnumJobsEx",
	OpnumFAX_GetJobEx:                        "FAX_GetJobEx",
	OpnumFAX_GetCountryList:                  "FAX_GetCountryList",
	OpnumFAX_GetPersonalProfileInfo:          "FAX_GetPersonalProfileInfo",
	OpnumFAX_GetQueueStates:                  "FAX_GetQueueStates",
	OpnumFAX_SetQueue:                        "FAX_SetQueue",
	OpnumFAX_GetReceiptsConfiguration:        "FAX_GetReceiptsConfiguration",
	OpnumFAX_SetReceiptsConfiguration:        "FAX_SetReceiptsConfiguration",
	OpnumFAX_GetReceiptsOptions:              "FAX_GetReceiptsOptions",
	OpnumFAX_GetVersion:                      "FAX_GetVersion",
	OpnumFAX_GetOutboxConfiguration:          "FAX_GetOutboxConfiguration",
	OpnumFAX_SetOutboxConfiguration:          "FAX_SetOutboxConfiguration",
	OpnumFAX_GetPersonalCoverPagesOption:     "FAX_GetPersonalCoverPagesOption",
	OpnumFAX_GetArchiveConfiguration:         "FAX_GetArchiveConfiguration",
	OpnumFAX_SetArchiveConfiguration:         "FAX_SetArchiveConfiguration",
	OpnumFAX_GetActivityLoggingConfiguration: "FAX_GetActivityLoggingConfiguration",
	OpnumFAX_SetActivityLoggingConfiguration: "FAX_SetActivityLoggingConfiguration",
	OpnumFAX_EnumerateProviders:              "FAX_EnumerateProviders",
	OpnumFAX_GetPortEx:                       "FAX_GetPortEx",
	OpnumFAX_SetPortEx:                       "FAX_SetPortEx",
	OpnumFAX_EnumPortsEx:                     "FAX_EnumPortsEx",
	OpnumFAX_GetExtensionData:                "FAX_GetExtensionData",
	OpnumFAX_SetExtensionData:                "FAX_SetExtensionData",
	OpnumFAX_AddOutboundGroup:                "FAX_AddOutboundGroup",
	OpnumFAX_SetOutboundGroup:                "FAX_SetOutboundGroup",
	OpnumFAX_RemoveOutboundGroup:             "FAX_RemoveOutboundGroup",
	OpnumFAX_EnumOutboundGroups:              "FAX_EnumOutboundGroups",
	OpnumFAX_SetDeviceOrderInGroup:           "FAX_SetDeviceOrderInGroup",
	OpnumFAX_AddOutboundRule:                 "FAX_AddOutboundRule",
	OpnumFAX_RemoveOutboundRule:              "FAX_RemoveOutboundRule",
	OpnumFAX_SetOutboundRule:                 "FAX_SetOutboundRule",
	OpnumFAX_EnumOutboundRules:               "FAX_EnumOutboundRules",
	OpnumFAX_RegisterServiceProviderEx:       "FAX_RegisterServiceProviderEx",
	OpnumFAX_UnregisterServiceProviderEx:     "FAX_UnregisterServiceProviderEx",
	OpnumFAX_UnregisterRoutingExtension:      "FAX_UnregisterRoutingExtension",
	OpnumFAX_StartMessagesEnum:               "FAX_StartMessagesEnum",
	OpnumFAX_EndMessagesEnum:                 "FAX_EndMessagesEnum",
	OpnumFAX_EnumMessages:                    "FAX_EnumMessages",
	OpnumFAX_GetMessage:                      "FAX_GetMessage",
	OpnumFAX_RemoveMessage:                   "FAX_RemoveMessage",
	OpnumFAX_StartCopyToServer:               "FAX_StartCopyToServer",
	OpnumFAX_StartCopyMessageFromServer:      "FAX_StartCopyMessageFromServer",
	OpnumFAX_WriteFile:                       "FAX_WriteFile",
	OpnumFAX_ReadFile:                        "FAX_ReadFile",
	OpnumFAX_EndCopy:                         "FAX_EndCopy",
	OpnumFAX_StartServerNotification:         "FAX_StartServerNotification",
	OpnumFAX_StartServerNotificationEx:       "FAX_StartServerNotificationEx",
	OpnumFAX_EndServerNotification:           "FAX_EndServerNotification",
	OpnumFAX_GetServerActivity:               "FAX_GetServerActivity",
	OpnumFAX_SetConfigWizardUsed:             "FAX_SetConfigWizardUsed",
	OpnumFAX_EnumRoutingExtensions:           "FAX_EnumRoutingExtensions",
	OpnumFAX_ConnectFaxServer:                "FAX_ConnectFaxServer",
	OpnumFAX_GetSecurityEx:                   "FAX_GetSecurityEx",
	OpnumFAX_RefreshArchive:                  "FAX_RefreshArchive",
	OpnumFAX_SetRecipientsLimit:              "FAX_SetRecipientsLimit",
	OpnumFAX_GetRecipientsLimit:              "FAX_GetRecipientsLimit",
	OpnumFAX_GetServerSKU:                    "FAX_GetServerSKU",
	OpnumFAX_CheckValidFaxFolder:             "FAX_CheckValidFaxFolder",
	OpnumFAX_GetJobEx2:                       "FAX_GetJobEx2",
	OpnumFAX_EnumJobsEx2:                     "FAX_EnumJobsEx2",
	OpnumFAX_GetMessageEx:                    "FAX_GetMessageEx",
	OpnumFAX_StartMessagesEnumEx:             "FAX_StartMessagesEnumEx",
	OpnumFAX_EnumMessagesEx:                  "FAX_EnumMessagesEx",
	OpnumFAX_StartServerNotificationEx2:      "FAX_StartServerNotificationEx2",
	OpnumFAX_CreateAccount:                   "FAX_CreateAccount",
	OpnumFAX_DeleteAccount:                   "FAX_DeleteAccount",
	OpnumFAX_EnumAccounts:                    "FAX_EnumAccounts",
	OpnumFAX_GetAccountInfo:                  "FAX_GetAccountInfo",
	OpnumFAX_GetGeneralConfiguration:         "FAX_GetGeneralConfiguration",
	OpnumFAX_SetGeneralConfiguration:         "FAX_SetGeneralConfiguration",
	OpnumFAX_GetSecurityEx2:                  "FAX_GetSecurityEx2",
	OpnumFAX_SetSecurityEx2:                  "FAX_SetSecurityEx2",
	OpnumFAX_AccessCheckEx2:                  "FAX_AccessCheckEx2",
	OpnumFAX_ReAssignMessage:                 "FAX_ReAssignMessage",
	OpnumFAX_SetMessage:                      "FAX_SetMessage",
	OpnumFAX_GetConfigOption:                 "FAX_GetConfigOption",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
