package netbios

// Session message types
// Source: RFC 1002 page 30

type SESSION_MESSAGE_TYPE uint8

const (
	SESSION_MESSAGE           SESSION_MESSAGE_TYPE = 0x00
	SESSION_REQUEST           SESSION_MESSAGE_TYPE = 0x81
	SESSION_POSITIVE_RESPONSE SESSION_MESSAGE_TYPE = 0x82
	SESSION_NEGATIVE_RESPONSE SESSION_MESSAGE_TYPE = 0x83
	SESSION_RETARGET_RESPONSE SESSION_MESSAGE_TYPE = 0x84
	SESSION_KEEP_ALIVE        SESSION_MESSAGE_TYPE = 0x85
)

var SessionMessageTypeToString = map[SESSION_MESSAGE_TYPE]string{
	SESSION_MESSAGE:           "SESSION_MESSAGE",
	SESSION_REQUEST:           "SESSION_REQUEST",
	SESSION_POSITIVE_RESPONSE: "SESSION_POSITIVE_RESPONSE",
	SESSION_NEGATIVE_RESPONSE: "SESSION_NEGATIVE_RESPONSE",
	SESSION_RETARGET_RESPONSE: "SESSION_RETARGET_RESPONSE",
	SESSION_KEEP_ALIVE:        "SESSION_KEEP_ALIVE",
}

func (s SESSION_MESSAGE_TYPE) String() string {
	if str, exists := SessionMessageTypeToString[s]; exists {
		return str
	}
	return "UNKNOWN"
}
