// Package rpcinterface_86d3594983c94044b424db363231fd0c_1_0 is the descriptor for the ITaskSchedulerService RPC interface, abstract
// syntax 86d35949-83c9-4044-b424-db363231fd0c version 1.0 ([MS-TSCH]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName and the doc comments are not derivable from the IDL and were
// filled in and verified by hand ([MS-TSCH] 2.1, 3.2.5).
package rpcinterface_86d3594983c94044b424db363231fd0c_1_0

// IDL source: [MS-TSCH] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tsch/6fc1f51a-26ec-43fa-a8bd-1c364657f110
// A fetched copy is kept at ms-tsch.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/errors/hresult"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is retained for descriptor uniformity, but ITaskSchedulerService is NOT a
// named-pipe interface: per [MS-TSCH] 2.1 it is carried over ncacn_ip_tcp on a dynamic
// endpoint resolved through the RPC endpoint mapper ([MS-RPCE] / [C706]), so there is no
// well-known pipe. It is left empty so callers do not bind it over SMB by mistake.
const PipeName = ``

// Opnums for the on-the-wire methods.
const (
	OpnumSchRpcHighestVersion        uint16 = 0
	OpnumSchRpcRegisterTask          uint16 = 1
	OpnumSchRpcRetrieveTask          uint16 = 2
	OpnumSchRpcCreateFolder          uint16 = 3
	OpnumSchRpcSetSecurity           uint16 = 4
	OpnumSchRpcGetSecurity           uint16 = 5
	OpnumSchRpcEnumFolders           uint16 = 6
	OpnumSchRpcEnumTasks             uint16 = 7
	OpnumSchRpcEnumInstances         uint16 = 8
	OpnumSchRpcGetInstanceInfo       uint16 = 9
	OpnumSchRpcStopInstance          uint16 = 10
	OpnumSchRpcStop                  uint16 = 11
	OpnumSchRpcRun                   uint16 = 12
	OpnumSchRpcDelete                uint16 = 13
	OpnumSchRpcRename                uint16 = 14
	OpnumSchRpcScheduledRuntimes     uint16 = 15
	OpnumSchRpcGetLastRunInfo        uint16 = 16
	OpnumSchRpcGetTaskInfo           uint16 = 17
	OpnumSchRpcGetNumberOfMissedRuns uint16 = 18
	OpnumSchRpcEnableTask            uint16 = 19
)

// Every method of ITaskSchedulerService returns an HRESULT ([MS-TSCH] 3.2.5,
// [MS-ERREF] section 2.1). The HRESULT values themselves are not declared here: the
// whole of [MS-ERREF] 2.1.1 lives in
// github.com/TheManticoreProject/Manticore/windows/errors/hresult as the HRESULT
// type, and a subset repeated here would cover a fraction of that 2928-value table
// while drifting from it. Convert a returned status with hresult.HRESULT(status) and
// test it with hresult.HRESULT.IsSuccess, which reads a range rather than a value:
// bit 31 clear is success, so S_OK, S_FALSE and every SCHED_S_* informational code
// satisfy it.
//
// The three codes below are the exception. WinError.h defines SCHED_E_TASK_DISABLED,
// SCHED_E_TASK_NOT_V1_COMPAT and SCHED_E_START_ON_DEMAND, but the [MS-ERREF] 2.1.1
// SCHED_* block ends at SCHED_E_TASK_ATTEMPTED (0x80041324) and names none of the
// three, so the shared table cannot decode them and renders them as hex. These stay
// declared here and StatusString decodes them before deferring to the shared table
// for everything else.
const (
	SchedETaskDisabled    uint32 = 0x80041326 // SCHED_E_TASK_DISABLED
	SchedETaskNotV1Compat uint32 = 0x80041327 // SCHED_E_TASK_NOT_V1_COMPAT
	SchedEStartOnDemand   uint32 = 0x80041328 // SCHED_E_START_ON_DEMAND
)

// SyntaxID returns the ITaskSchedulerService abstract syntax identifier:
// 86d35949-83c9-4044-b424-db363231fd0c, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x86d35949, B: 0x83c9, C: 0x4044, D: 0xb424, E: 0xdb363231fd0c},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString names the three Task Scheduler HRESULTs WinError.h defines and
// [MS-ERREF] 2.1.1 omits, and defers every other status to the shared [MS-ERREF]
// 2.1.1 table, which names each value the specification defines, derives a name for
// the FACILITY_WIN32 values it wraps, and renders hex only for values it does not
// define.
func StatusString(status uint32) string {
	switch status {
	case SchedETaskDisabled:
		return "SCHED_E_TASK_DISABLED"
	case SchedETaskNotV1Compat:
		return "SCHED_E_TASK_NOT_V1_COMPAT"
	case SchedEStartOnDemand:
		return "SCHED_E_START_ON_DEMAND"
	default:
		return hresult.HRESULT(status).String()
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumSchRpcHighestVersion:        "SchRpcHighestVersion",
	OpnumSchRpcRegisterTask:          "SchRpcRegisterTask",
	OpnumSchRpcRetrieveTask:          "SchRpcRetrieveTask",
	OpnumSchRpcCreateFolder:          "SchRpcCreateFolder",
	OpnumSchRpcSetSecurity:           "SchRpcSetSecurity",
	OpnumSchRpcGetSecurity:           "SchRpcGetSecurity",
	OpnumSchRpcEnumFolders:           "SchRpcEnumFolders",
	OpnumSchRpcEnumTasks:             "SchRpcEnumTasks",
	OpnumSchRpcEnumInstances:         "SchRpcEnumInstances",
	OpnumSchRpcGetInstanceInfo:       "SchRpcGetInstanceInfo",
	OpnumSchRpcStopInstance:          "SchRpcStopInstance",
	OpnumSchRpcStop:                  "SchRpcStop",
	OpnumSchRpcRun:                   "SchRpcRun",
	OpnumSchRpcDelete:                "SchRpcDelete",
	OpnumSchRpcRename:                "SchRpcRename",
	OpnumSchRpcScheduledRuntimes:     "SchRpcScheduledRuntimes",
	OpnumSchRpcGetLastRunInfo:        "SchRpcGetLastRunInfo",
	OpnumSchRpcGetTaskInfo:           "SchRpcGetTaskInfo",
	OpnumSchRpcGetNumberOfMissedRuns: "SchRpcGetNumberOfMissedRuns",
	OpnumSchRpcEnableTask:            "SchRpcEnableTask",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
