// Package rpcinterface_86d3594983c94044b424db363231fd0c_1_0 is the descriptor for the ITaskSchedulerService RPC interface, abstract
// syntax 86d35949-83c9-4044-b424-db363231fd0c version 1.0 ([MS-TSCH]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName, the status-code table, and doc comments are not derivable from
// the IDL and were filled in and verified by hand ([MS-TSCH] 2.1, 3.2.5).
package rpcinterface_86d3594983c94044b424db363231fd0c_1_0

// IDL source: [MS-TSCH] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tsch/6fc1f51a-26ec-43fa-a8bd-1c364657f110
// A fetched copy is kept at ms-tsch.idl in the interface directory.

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is retained for descriptor uniformity, but ITaskSchedulerService is NOT a
// named-pipe interface: per [MS-TSCH] 2.1 it is carried over ncacn_ip_tcp on a dynamic
// endpoint resolved through the RPC endpoint mapper ([MS-RPCE] / [C706]), so there is no
// well-known pipe. It is left empty so callers do not bind it over SMB by mistake.
const PipeName = ``

// Opnums for the on-the-wire methods.
const (
	OpnumSchRpcHighestVersion        uint16 = 0
	OpnumSchRpcRegisterTask          uint16 = 1
	OpnumSchRpcRetrieveTask          uint16 = 2
	OpnumSchRpcCreateFolder          uint16 = 3
	OpnumSchRpcSetSecurity           uint16 = 4
	OpnumSchRpcGetSecurity           uint16 = 5
	OpnumSchRpcEnumFolders           uint16 = 6
	OpnumSchRpcEnumTasks             uint16 = 7
	OpnumSchRpcEnumInstances         uint16 = 8
	OpnumSchRpcGetInstanceInfo       uint16 = 9
	OpnumSchRpcStopInstance          uint16 = 10
	OpnumSchRpcStop                  uint16 = 11
	OpnumSchRpcRun                   uint16 = 12
	OpnumSchRpcDelete                uint16 = 13
	OpnumSchRpcRename                uint16 = 14
	OpnumSchRpcScheduledRuntimes     uint16 = 15
	OpnumSchRpcGetLastRunInfo        uint16 = 16
	OpnumSchRpcGetTaskInfo           uint16 = 17
	OpnumSchRpcGetNumberOfMissedRuns uint16 = 18
	OpnumSchRpcEnableTask            uint16 = 19
)

// HRESULT status codes returned by the methods of this interface ([MS-TSCH] 2.3.14,
// [MS-ERREF] 2.1/2.3). ITaskSchedulerService methods return an HRESULT; a value with the
// high bit clear is a success code (S_OK / S_FALSE / SCHED_S_*), otherwise it is a
// failure. StatusSuccess is S_OK.
const (
	StatusSuccess uint32 = 0x00000000 // S_OK
	StatusFalse   uint32 = 0x00000001 // S_FALSE — more data available (Enum* methods)

	// SCHED_S_* success/informational codes.
	SchedSTaskReady        uint32 = 0x00041300
	SchedSTaskRunning      uint32 = 0x00041301
	SchedSTaskHasNotRun    uint32 = 0x00041303
	SchedSTaskNoMoreRuns   uint32 = 0x00041304
	SchedSTaskNotScheduled uint32 = 0x00041305
	SchedSTaskDisabled     uint32 = 0x00041306

	// Common [MS-ERREF] failure codes.
	ErrorFileNotFound  uint32 = 0x80070002 // HRESULT_FROM_WIN32(ERROR_FILE_NOT_FOUND)
	ErrorAccessDenied  uint32 = 0x80070005 // E_ACCESSDENIED
	ErrorInvalidArg    uint32 = 0x80070057 // E_INVALIDARG
	ErrorAlreadyExists uint32 = 0x800700B7 // HRESULT_FROM_WIN32(ERROR_ALREADY_EXISTS)

	// SCHED_E_* failure codes.
	SchedETriggerNotFound          uint32 = 0x80041309
	SchedETaskNotReady             uint32 = 0x8004130A
	SchedETaskNotRunning           uint32 = 0x8004130B
	SchedEServiceNotInstalled      uint32 = 0x8004130C
	SchedECannotOpenTask           uint32 = 0x8004130D
	SchedEInvalidTask              uint32 = 0x8004130E
	SchedEAccountInformationNotSet uint32 = 0x8004130F
	SchedEAccountNameNotFound      uint32 = 0x80041310
	SchedEServiceNotRunning        uint32 = 0x80041315
	SchedEUnexpectedNode           uint32 = 0x80041316
	SchedENamespace                uint32 = 0x80041317
	SchedEInvalidValue             uint32 = 0x80041318
	SchedEMissingNode              uint32 = 0x80041319
	SchedEMalformedXML             uint32 = 0x8004131A
	SchedETooManyNodes             uint32 = 0x8004131B
	SchedEPastEndBoundary          uint32 = 0x8004131C
	SchedEAlreadyRunning           uint32 = 0x80041321
	SchedEUserNotLoggedOn          uint32 = 0x80041322
	SchedEInvalidTaskHash          uint32 = 0x80041323
	SchedEServiceNotAvailable      uint32 = 0x80041324
	SchedEServiceTooBusy           uint32 = 0x80041325
	SchedETaskAttempted            uint32 = 0x80041326
	SchedETaskDisabled             uint32 = 0x80041327
	SchedETaskNotV1Compat          uint32 = 0x80041328
	SchedEStartOnDemand            uint32 = 0x80041329
)

// SyntaxID returns the ITaskSchedulerService abstract syntax identifier:
// 86d35949-83c9-4044-b424-db363231fd0c, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x86d35949, B: 0x83c9, C: 0x4044, D: 0xb424, E: 0xdb363231fd0c},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented HRESULT codes, otherwise the hex
// value.
func StatusString(status uint32) string {
	switch status {
	case StatusSuccess:
		return "S_OK"
	case StatusFalse:
		return "S_FALSE"
	case SchedSTaskReady:
		return "SCHED_S_TASK_READY"
	case SchedSTaskRunning:
		return "SCHED_S_TASK_RUNNING"
	case SchedSTaskHasNotRun:
		return "SCHED_S_TASK_HAS_NOT_RUN"
	case SchedSTaskNoMoreRuns:
		return "SCHED_S_TASK_NO_MORE_RUNS"
	case SchedSTaskNotScheduled:
		return "SCHED_S_TASK_NOT_SCHEDULED"
	case SchedSTaskDisabled:
		return "SCHED_S_TASK_DISABLED"
	case ErrorFileNotFound:
		return "ERROR_FILE_NOT_FOUND"
	case ErrorAccessDenied:
		return "E_ACCESSDENIED"
	case ErrorInvalidArg:
		return "E_INVALIDARG"
	case ErrorAlreadyExists:
		return "ERROR_ALREADY_EXISTS"
	case SchedETriggerNotFound:
		return "SCHED_E_TRIGGER_NOT_FOUND"
	case SchedETaskNotReady:
		return "SCHED_E_TASK_NOT_READY"
	case SchedETaskNotRunning:
		return "SCHED_E_TASK_NOT_RUNNING"
	case SchedEServiceNotInstalled:
		return "SCHED_E_SERVICE_NOT_INSTALLED"
	case SchedECannotOpenTask:
		return "SCHED_E_CANNOT_OPEN_TASK"
	case SchedEInvalidTask:
		return "SCHED_E_INVALID_TASK"
	case SchedEAccountInformationNotSet:
		return "SCHED_E_ACCOUNT_INFORMATION_NOT_SET"
	case SchedEAccountNameNotFound:
		return "SCHED_E_ACCOUNT_NAME_NOT_FOUND"
	case SchedEServiceNotRunning:
		return "SCHED_E_SERVICE_NOT_RUNNING"
	case SchedEUnexpectedNode:
		return "SCHED_E_UNEXPECTEDNODE"
	case SchedENamespace:
		return "SCHED_E_NAMESPACE"
	case SchedEInvalidValue:
		return "SCHED_E_INVALIDVALUE"
	case SchedEMissingNode:
		return "SCHED_E_MISSINGNODE"
	case SchedEMalformedXML:
		return "SCHED_E_MALFORMEDXML"
	case SchedETooManyNodes:
		return "SCHED_E_TOO_MANY_NODES"
	case SchedEPastEndBoundary:
		return "SCHED_E_PAST_END_BOUNDARY"
	case SchedEAlreadyRunning:
		return "SCHED_E_ALREADY_RUNNING"
	case SchedEUserNotLoggedOn:
		return "SCHED_E_USER_NOT_LOGGED_ON"
	case SchedEInvalidTaskHash:
		return "SCHED_E_INVALID_TASK_HASH"
	case SchedEServiceNotAvailable:
		return "SCHED_E_SERVICE_NOT_AVAILABLE"
	case SchedEServiceTooBusy:
		return "SCHED_E_SERVICE_TOO_BUSY"
	case SchedETaskAttempted:
		return "SCHED_E_TASK_ATTEMPTED"
	case SchedETaskDisabled:
		return "SCHED_E_TASK_DISABLED"
	case SchedETaskNotV1Compat:
		return "SCHED_E_TASK_NOT_V1_COMPAT"
	case SchedEStartOnDemand:
		return "SCHED_E_START_ON_DEMAND"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// IsSuccess reports whether an HRESULT returned by this interface indicates success
// (high bit clear, e.g. S_OK, S_FALSE, or a SCHED_S_* informational code).
func IsSuccess(status uint32) bool {
	return status&0x80000000 == 0
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumSchRpcHighestVersion:        "SchRpcHighestVersion",
	OpnumSchRpcRegisterTask:          "SchRpcRegisterTask",
	OpnumSchRpcRetrieveTask:          "SchRpcRetrieveTask",
	OpnumSchRpcCreateFolder:          "SchRpcCreateFolder",
	OpnumSchRpcSetSecurity:           "SchRpcSetSecurity",
	OpnumSchRpcGetSecurity:           "SchRpcGetSecurity",
	OpnumSchRpcEnumFolders:           "SchRpcEnumFolders",
	OpnumSchRpcEnumTasks:             "SchRpcEnumTasks",
	OpnumSchRpcEnumInstances:         "SchRpcEnumInstances",
	OpnumSchRpcGetInstanceInfo:       "SchRpcGetInstanceInfo",
	OpnumSchRpcStopInstance:          "SchRpcStopInstance",
	OpnumSchRpcStop:                  "SchRpcStop",
	OpnumSchRpcRun:                   "SchRpcRun",
	OpnumSchRpcDelete:                "SchRpcDelete",
	OpnumSchRpcRename:                "SchRpcRename",
	OpnumSchRpcScheduledRuntimes:     "SchRpcScheduledRuntimes",
	OpnumSchRpcGetLastRunInfo:        "SchRpcGetLastRunInfo",
	OpnumSchRpcGetTaskInfo:           "SchRpcGetTaskInfo",
	OpnumSchRpcGetNumberOfMissedRuns: "SchRpcGetNumberOfMissedRuns",
	OpnumSchRpcEnableTask:            "SchRpcEnableTask",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
