// Package rpcinterface_0b1c217057324e0e8cd3d9b16f3b84d7_0_0 is the descriptor for the
// authzr (Remote Authorization API, RAZA) RPC interface, abstract syntax
// 0b1c2170-5732-4e0e-8cd3-d9b16f3b84d7 version 0.0 ([MS-RAA]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the transport, the status-code table, and doc comments are not derivable from
// the IDL and were filled in from [MS-RAA] and [MS-ERREF].
//
// Transport ([MS-RAA] 2.1): the Remote Authorization API Protocol is reached over RPC
// dynamic endpoints, protocol sequence ncacn_ip_tcp (RPC over TCP/IP), with the endpoint
// resolved through the RPC endpoint mapper — it is NOT exposed over a named pipe. The
// interface UUID is 0b1c2170-5732-4e0e-8cd3-d9b16f3b84d7; the protocol also defines the
// object UUIDs 9a81c2bd-a525-471d-a4ed-49907c0b23da and
// 5fc860e0-6f6e-4fc2-83cd-46324f25e90b. PipeName is therefore empty.
package rpcinterface_0b1c217057324e0e8cd3d9b16f3b84d7_0_0

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is unused for this interface: [MS-RAA] 2.1 uses ncacn_ip_tcp with a dynamic
// endpoint (endpoint-mapper resolved), not a named pipe. It is retained, empty, for
// descriptor uniformity across interfaces.
const PipeName = ``

// Opnums for the on-the-wire methods.
const (
	OpnumAuthzrFreeContext               uint16 = 0
	OpnumAuthzrInitializeContextFromSid  uint16 = 1
	OpnumAuthzrInitializeCompoundContext uint16 = 2
	OpnumAuthzrAccessCheck               uint16 = 3
	OpnumAuthzGetInformationFromContext  uint16 = 4
	OpnumAuthzrModifyClaims              uint16 = 5
	OpnumAuthzrModifySids                uint16 = 6
)

// Status codes returned by this interface. Every authzr method returns a Win32 error
// code ([MS-ERREF] 2.2, transmitted as the DWORD return value); ERROR_SUCCESS (0)
// indicates success. These are the codes [MS-RAA] (section 3.1.4) documents its methods
// returning.
const (
	StatusSuccess           uint32 = 0x00000000 // ERROR_SUCCESS
	ErrorAccessDenied       uint32 = 0x00000005 // ERROR_ACCESS_DENIED
	ErrorInvalidHandle      uint32 = 0x00000006 // ERROR_INVALID_HANDLE
	ErrorNotEnoughMemory    uint32 = 0x00000008 // ERROR_NOT_ENOUGH_MEMORY
	ErrorInvalidParameter   uint32 = 0x00000057 // ERROR_INVALID_PARAMETER
	ErrorInsufficientBuffer uint32 = 0x0000007A // ERROR_INSUFFICIENT_BUFFER
	ErrorInvalidServerState uint32 = 0x00000548 // ERROR_INVALID_SERVER_STATE
	ErrorNotSupported       uint32 = 0x00000032 // ERROR_NOT_SUPPORTED
)

// SyntaxID returns the authzr abstract syntax identifier:
// 0b1c2170-5732-4e0e-8cd3-d9b16f3b84d7, version 0.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x0b1c2170, B: 0x5732, C: 0x4e0e, D: 0x8cd3, E: 0xd9b16f3b84d7},
		MajorVersion: 0,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented status codes, otherwise the
// hex value.
func StatusString(status uint32) string {
	switch status {
	case StatusSuccess:
		return "ERROR_SUCCESS"
	case ErrorAccessDenied:
		return "ERROR_ACCESS_DENIED"
	case ErrorInvalidHandle:
		return "ERROR_INVALID_HANDLE"
	case ErrorNotEnoughMemory:
		return "ERROR_NOT_ENOUGH_MEMORY"
	case ErrorInvalidParameter:
		return "ERROR_INVALID_PARAMETER"
	case ErrorInsufficientBuffer:
		return "ERROR_INSUFFICIENT_BUFFER"
	case ErrorInvalidServerState:
		return "ERROR_INVALID_SERVER_STATE"
	case ErrorNotSupported:
		return "ERROR_NOT_SUPPORTED"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumAuthzrFreeContext:               "AuthzrFreeContext",
	OpnumAuthzrInitializeContextFromSid:  "AuthzrInitializeContextFromSid",
	OpnumAuthzrInitializeCompoundContext: "AuthzrInitializeCompoundContext",
	OpnumAuthzrAccessCheck:               "AuthzrAccessCheck",
	OpnumAuthzGetInformationFromContext:  "AuthzGetInformationFromContext",
	OpnumAuthzrModifyClaims:              "AuthzrModifyClaims",
	OpnumAuthzrModifySids:                "AuthzrModifySids",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
