// Package rpcinterface_91ae60209e3c11cf8d7c00aa00c091be_0_0 is the descriptor for the ICertPassage RPC interface, abstract
// syntax 91ae6020-9e3c-11cf-8d7c-00aa00c091be version 0.0 ([MS-ICPR]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName (MS-ICPR 2.1) and the status/disposition tables (MS-ICPR 3.2.4.1,
// MS-WCCE) are not carried by the IDL and were filled in by hand.
package rpcinterface_91ae60209e3c11cf8d7c00aa00c091be_0_0

// IDL source: [MS-WCCE] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-wcce/df709596-4a70-4a26-ada9-76781250700c
// A fetched copy is kept at ms-wcce.idl in the interface directory.

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the ICertPassage interface.
// The spec's Transport section (MS-ICPR 2.1) names the endpoint \PIPE\cert.
const PipeName = `\cert`

// Opnums for the on-the-wire methods.
const (
	OpnumCertServerRequest uint16 = 0
)

// Status codes returned by CertServerRequest ([MS-ICPR] 3.2.4.1). The method
// returns ERROR_SUCCESS on success; its error returns share the syntax and
// semantics of ICertRequestD::Request ([MS-WCCE] 3.2.2.6.2.1), so the value is
// a Win32/HRESULT code. The two errors MS-ICPR names explicitly are included.
const (
	StatusSuccess      uint32 = 0x00000000 // ERROR_SUCCESS
	StatusInvalidArg   uint32 = 0x80070057 // E_INVALIDARG (cb does not match string length)
	StatusAccessDenied uint32 = 0x80000009 // E_ACCESSDENIED (packet privacy required but not negotiated)
)

// Disposition values reported through pdwDisposition; the parameter shares the
// semantics of ICertRequestD::Request ([MS-WCCE] 3.2.1.4.2.1). These describe the
// outcome of the enrollment request independent of the RPC return value.
const (
	CR_DISP_INCOMPLETE         uint32 = 0x00000000
	CR_DISP_ERROR              uint32 = 0x00000001
	CR_DISP_DENIED             uint32 = 0x00000002
	CR_DISP_ISSUED             uint32 = 0x00000003
	CR_DISP_ISSUED_OUT_OF_BAND uint32 = 0x00000004
	CR_DISP_UNDER_SUBMISSION   uint32 = 0x00000005
	CR_DISP_REVOKED            uint32 = 0x00000006
)

// SyntaxID returns the ICertPassage abstract syntax identifier:
// 91ae6020-9e3c-11cf-8d7c-00aa00c091be, version 0.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x91ae6020, B: 0x9e3c, C: 0x11cf, D: 0x8d7c, E: 0x00aa00c091be},
		MajorVersion: 0,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented status codes, otherwise the
// hex value.
func StatusString(status uint32) string {
	switch status {
	case StatusSuccess:
		return "ERROR_SUCCESS"
	case StatusInvalidArg:
		return "E_INVALIDARG"
	case StatusAccessDenied:
		return "E_ACCESSDENIED"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumCertServerRequest: "CertServerRequest",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
