// Package rpcinterface_91ae60209e3c11cf8d7c00aa00c091be_0_0 is the descriptor for the ICertPassage RPC interface, abstract
// syntax 91ae6020-9e3c-11cf-8d7c-00aa00c091be version 0.0 ([MS-ICPR]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName (MS-ICPR 2.1) and the disposition table (MS-ICPR 3.2.4.1,
// MS-WCCE) are not carried by the IDL and were filled in by hand.
package rpcinterface_91ae60209e3c11cf8d7c00aa00c091be_0_0

// IDL source: [MS-WCCE] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-wcce/df709596-4a70-4a26-ada9-76781250700c
// A fetched copy is kept at ms-wcce.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/errors/hresult"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the ICertPassage interface.
// The spec's Transport section (MS-ICPR 2.1) names the endpoint \PIPE\cert.
const PipeName = `\cert`

// Opnums for the on-the-wire methods.
const (
	OpnumCertServerRequest uint16 = 0
)

// CertServerRequest is declared DWORD in the IDL but returns 0x00000000 on success and
// otherwise the HRESULT failures of ICertRequestD::Request, whose syntax and semantics its
// error returns share ([MS-ICPR] 3.2.4.1, [MS-WCCE] 3.2.2.6.2.1). Those values are not
// declared here, because the whole of [MS-ERREF] 2.1.1 lives in
// github.com/TheManticoreProject/Manticore/windows/errors/hresult as the HRESULT type;
// convert a returned status with hresult.HRESULT(status) and compare against
// hresult.S_OK. Zero is S_OK there, the name the HRESULT space gives it, where [MS-ICPR]
// 3.2.4.1 calls the same value ERROR_SUCCESS in Win32 terms. The malformed-attributes
// failure [MS-ICPR] names, E_INVALIDARG (0x80070057), is a row in the shared table and
// needs no declaration.
//
// The packet-privacy failure is the exception and stays local, because the name and the
// value [MS-ICPR] 3.2.4.1 pairs do not agree with [MS-ERREF] 2.1.1. That section says the
// CA "MUST refuse to establish a connection with the client by returning E_ACCESSDENIED
// (0x80000009)" when IF_ENFORCEENCRYPTICERTREQUEST is set and
// RPC_C_AUTHN_LEVEL_PKT_PRIVACY was not negotiated. 0x80000009 is the legacy OLE
// E_ACCESSDENIED of the 0x8000000X block, which [MS-ERREF] 2.1.1 does not list at all; the
// name E_ACCESSDENIED belongs there to 0x80070005, a different value. So the value must be
// kept verbatim to match what a CA actually returns, and it cannot be resolved through the
// shared table, which renders it as hex.
const (
	// StatusAccessDenied is what the CA returns when IF_ENFORCEENCRYPTICERTREQUEST is
	// configured and the client did not negotiate RPC_C_AUTHN_LEVEL_PKT_PRIVACY
	// ([MS-ICPR] 3.2.4.1). The specification calls it E_ACCESSDENIED, which is the legacy
	// OLE value for that name; [MS-ERREF] 2.1.1 defines no 0x80000009 and gives the name
	// E_ACCESSDENIED to 0x80070005 instead, which is why this is not resolved through the
	// shared table.
	StatusAccessDenied uint32 = 0x80000009
)

// Disposition values reported through pdwDisposition; the parameter shares the
// semantics of ICertRequestD::Request ([MS-WCCE] 3.2.1.4.2.1). These describe the
// outcome of the enrollment request independent of the RPC return value.
const (
	CR_DISP_INCOMPLETE         uint32 = 0x00000000
	CR_DISP_ERROR              uint32 = 0x00000001
	CR_DISP_DENIED             uint32 = 0x00000002
	CR_DISP_ISSUED             uint32 = 0x00000003
	CR_DISP_ISSUED_OUT_OF_BAND uint32 = 0x00000004
	CR_DISP_UNDER_SUBMISSION   uint32 = 0x00000005
	CR_DISP_REVOKED            uint32 = 0x00000006
)

// SyntaxID returns the ICertPassage abstract syntax identifier:
// 91ae6020-9e3c-11cf-8d7c-00aa00c091be, version 0.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x91ae6020, B: 0x9e3c, C: 0x11cf, D: 0x8d7c, E: 0x00aa00c091be},
		MajorVersion: 0,
		MinorVersion: 0,
	}
}

// StatusString names the one status whose value [MS-ERREF] 2.1.1 does not define, and
// defers every other status to the shared [MS-ERREF] 2.1.1 table, which names each value
// the specification defines and renders hex only for values it does not.
func StatusString(status uint32) string {
	switch status {
	case StatusAccessDenied:
		return "E_ACCESSDENIED"
	default:
		return hresult.HRESULT(status).String()
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumCertServerRequest: "CertServerRequest",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
