package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DSA_MSG_EXECUTE_SCRIPT_REQ_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DSA_MSG_EXECUTE_SCRIPT_REQ_V1 struct {
	Flags      ndr.DWORD
	CbPassword ndr.DWORD
	PbPassword []uint8 `ndr:"unique,size_is=CbPassword"`
}
