package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DSA_MSG_EXECUTE_SCRIPT_REPLY is a discriminated union ([MS-DRSR]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type DSA_MSG_EXECUTE_SCRIPT_REPLY struct {
	Tag ndr.DWORD                       `ndr:"switch"`
	V1  DSA_MSG_EXECUTE_SCRIPT_REPLY_V1 `ndr:"case=1"`
}
