// Package rpcinterface_811109bfa4e111d1ab5400a0c91e9b45_1_0 is the descriptor for the winsi2 RPC interface, abstract
// syntax 811109bf-a4e1-11d1-ab54-00a0c91e9b45 version 1.0 ([MS-RAIW]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName, the status-code table, and doc comments are not derivable from
// the IDL and must be confirmed by hand (see the TODO markers).
package rpcinterface_811109bfa4e111d1ab5400a0c91e9b45_1_0

// IDL source: [MS-RAIW] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-raiw/e59461f5-5486-4ec3-9ad6-14b784c1ecd6
// A fetched copy is kept at ms-raiw.idl in the interface directory.

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the winsi2 interface. WINS registers a
// single named pipe, \pipe\WinsPipe, shared with the winsif interface ([MS-RAIW] 2.1,
// Standards Assignments).
const PipeName = `\WinsPipe`

// Opnums for the on-the-wire methods.
const (
	OpnumR_WinsTombstoneDbRecs uint16 = 0
	OpnumR_WinsCheckAccess     uint16 = 1
)

// Status codes returned by this interface. Both winsi2 methods return a Win32 error
// code ([MS-ERREF] section 2.2): 0 (ERROR_SUCCESS) on success, otherwise a generic
// system error or one of the WINS-specific codes (0x00000FA0-0x00000FA6).
const (
	StatusSuccess uint32 = 0x00000000 // ERROR_SUCCESS

	ErrorAccessDenied     uint32 = 0x00000005 // ERROR_ACCESS_DENIED
	ErrorInvalidParameter uint32 = 0x00000057 // ERROR_INVALID_PARAMETER

	// WINS-specific error codes ([MS-ERREF] section 2.2, winerror.h 4000-4006).
	ErrorWinsInternal      uint32 = 0x00000FA0 // ERROR_WINS_INTERNAL
	ErrorCanNotDelLocalWin uint32 = 0x00000FA1 // ERROR_CAN_NOT_DEL_LOCAL_WINS
	ErrorStaticInit        uint32 = 0x00000FA2 // ERROR_STATIC_INIT
	ErrorIncBackup         uint32 = 0x00000FA3 // ERROR_INC_BACKUP
	ErrorFullBackup        uint32 = 0x00000FA4 // ERROR_FULL_BACKUP
	ErrorRecNonExistent    uint32 = 0x00000FA5 // ERROR_REC_NON_EXISTENT
	ErrorRplNotAllowed     uint32 = 0x00000FA6 // ERROR_RPL_NOT_ALLOWED
)

// SyntaxID returns the winsi2 abstract syntax identifier:
// 811109bf-a4e1-11d1-ab54-00a0c91e9b45, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x811109bf, B: 0xa4e1, C: 0x11d1, D: 0xab54, E: 0x00a0c91e9b45},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented status codes, otherwise the
// hex value.
func StatusString(status uint32) string {
	switch status {
	case StatusSuccess:
		return "ERROR_SUCCESS"
	case ErrorAccessDenied:
		return "ERROR_ACCESS_DENIED"
	case ErrorInvalidParameter:
		return "ERROR_INVALID_PARAMETER"
	case ErrorWinsInternal:
		return "ERROR_WINS_INTERNAL"
	case ErrorCanNotDelLocalWin:
		return "ERROR_CAN_NOT_DEL_LOCAL_WINS"
	case ErrorStaticInit:
		return "ERROR_STATIC_INIT"
	case ErrorIncBackup:
		return "ERROR_INC_BACKUP"
	case ErrorFullBackup:
		return "ERROR_FULL_BACKUP"
	case ErrorRecNonExistent:
		return "ERROR_REC_NON_EXISTENT"
	case ErrorRplNotAllowed:
		return "ERROR_RPL_NOT_ALLOWED"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumR_WinsTombstoneDbRecs: "R_WinsTombstoneDbRecs",
	OpnumR_WinsCheckAccess:     "R_WinsCheckAccess",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
