package msrprn

import (
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// CORE_PRINTER_DRIVER ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type CORE_PRINTER_DRIVER struct {
	CoreDriverGUID   guid.GUID
	FtDriverDate     FILETIME
	DwlDriverVersion DWORDLONG
	SzPackageID      [260]uint16
}
