package msrprn

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DEVMODE_CONTAINER ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type DEVMODE_CONTAINER struct {
	CbBuf    ndr.DWORD
	PDevMode []uint8 `ndr:"unique,size_is=CbBuf"`
}
