package msrprn

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DOC_INFO_CONTAINER ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type DOC_INFO_CONTAINER struct {
	Level   ndr.DWORD
	DocInfo DOC_INFO_CONTAINER_DocInfo
}

// DOC_INFO_CONTAINER_DocInfo is a discriminated union ([MS-RPRN]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type DOC_INFO_CONTAINER_DocInfo struct {
	Tag       ndr.DWORD   `ndr:"switch"`
	PDocInfo1 *DOC_INFO_1 `ndr:"case=1,unique"`
}
