package msrprn

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DOC_INFO_1 ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type DOC_INFO_1 struct {
	PDocName    *ndr.WSTR `ndr:"unique"`
	POutputFile *ndr.WSTR `ndr:"unique"`
	PDatatype   *ndr.WSTR `ndr:"unique"`
}
