package msrprn

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// JOB_INFO_3 ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type JOB_INFO_3 struct {
	JobId     ndr.DWORD
	NextJobId ndr.DWORD
	Reserved  ndr.DWORD
}
