package msrprn

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// PORT_INFO_2 ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type PORT_INFO_2 struct {
	PPortName    *ndr.WSTR `ndr:"unique"`
	PMonitorName *ndr.WSTR `ndr:"unique"`
	PDescription *ndr.WSTR `ndr:"unique"`
	FPortType    ndr.DWORD
	Reserved     ndr.DWORD
}
