package msrprn

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// PRINTER_INFO_9 ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type PRINTER_INFO_9 struct {
	PDevMode ndr.DWORD
}
