package msrprn

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// PRINTER_INFO_1 ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type PRINTER_INFO_1 struct {
	Flags        ndr.DWORD
	PDescription *ndr.WSTR `ndr:"unique"`
	PName        *ndr.WSTR `ndr:"unique"`
	PComment     *ndr.WSTR `ndr:"unique"`
}
