package msrprn

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_BranchOfficeJobDataPrinted ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_BranchOfficeJobDataPrinted struct {
	Status        ndr.DWORD
	PDocumentName *ndr.WSTR `ndr:"unique"`
	PUserName     *ndr.WSTR `ndr:"unique"`
	PMachineName  *ndr.WSTR `ndr:"unique"`
	PPrinterName  *ndr.WSTR `ndr:"unique"`
	PPortName     *ndr.WSTR `ndr:"unique"`
	Size          int64
	TotalPages    ndr.DWORD
}
