package msrprn

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_V2_NOTIFY_INFO ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_V2_NOTIFY_INFO struct {
	Version ndr.DWORD
	Flags   ndr.DWORD
	Count   ndr.DWORD
	AData   []RPC_V2_NOTIFY_INFO_DATA `ndr:"unique,size_is=Count"`
}
