package msrprn

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SPLCLIENT_INFO_3 ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type SPLCLIENT_INFO_3 struct {
	CbSize                 uint32
	DwFlags                ndr.DWORD
	DwSize                 ndr.DWORD
	PMachineName           *ndr.WSTR `ndr:"unique"`
	PUserName              *ndr.WSTR `ndr:"unique"`
	DwBuildNum             ndr.DWORD
	DwMajorVersion         ndr.DWORD
	DwMinorVersion         ndr.DWORD
	WProcessorArchitecture uint16
	HSplPrinter            uint64
}
