package msrprn

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SPLCLIENT_CONTAINER ([MS-RPRN]). Generated by tools/idlgen; verify pointer/array tags.
type SPLCLIENT_CONTAINER struct {
	Level      ndr.DWORD
	ClientInfo SPLCLIENT_CONTAINER_ClientInfo
}

// SPLCLIENT_CONTAINER_ClientInfo is a discriminated union ([MS-RPRN]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type SPLCLIENT_CONTAINER_ClientInfo struct {
	Tag          ndr.DWORD         `ndr:"switch"`
	PClientInfo1 *SPLCLIENT_INFO_1 `ndr:"case=1,unique"`
	PNotUsed1    *SPLCLIENT_INFO_2 `ndr:"case=2,unique"`
	PNotUsed2    *SPLCLIENT_INFO_3 `ndr:"case=3,unique"`
}
