// Package rpcinterface_f5cc5a184264101a8c5908002b2f8426_56_0 is the descriptor for the nspi RPC interface, abstract
// syntax f5cc5a18-4264-101a-8c59-08002b2f8426 version 56.0 ([MS-NSPI]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed and refined
// by hand: the PipeName (transport, [MS-NSPI] 2.1) and the status-code table
// ([MS-NSPI] 2.2.2 / [MS-OXCDATA]) are not derivable from the IDL.
package rpcinterface_f5cc5a184264101a8c5908002b2f8426_56_0

// IDL source: [MS-NSPI] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nspi/2554418c-a060-473a-950a-e009a53e33d9
// A fetched copy is kept at ms-nspi.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/errors/hresult"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is empty: NSPI has no well-known named-pipe endpoint. [MS-NSPI] section 2.1
// (Transport) binds this interface over RPC on dynamic endpoints ([C706] Part 4) across
// the ncacn_np, ncacn_http, and ncacn_ip_tcp protocol sequences; a client discovers the
// endpoint through the RPC endpoint mapper (or, for TCP, a server-configured static port),
// so there is no fixed IPC$-relative pipe. The interface is identified by its UUID/version.
const PipeName = ``

// Opnums for the on-the-wire methods. Opnums 15 are "not used on the wire"
// and are omitted.
const (
	OpnumNspiBind              uint16 = 0
	OpnumNspiUnbind            uint16 = 1
	OpnumNspiUpdateStat        uint16 = 2
	OpnumNspiQueryRows         uint16 = 3
	OpnumNspiSeekEntries       uint16 = 4
	OpnumNspiGetMatches        uint16 = 5
	OpnumNspiResortRestriction uint16 = 6
	OpnumNspiDNToMId           uint16 = 7
	OpnumNspiGetPropList       uint16 = 8
	OpnumNspiGetProps          uint16 = 9
	OpnumNspiCompareMIds       uint16 = 10
	OpnumNspiModProps          uint16 = 11
	OpnumNspiGetSpecialTable   uint16 = 12
	OpnumNspiGetTemplateInfo   uint16 = 13
	OpnumNspiModLinkAtt        uint16 = 14
	OpnumNspiQueryColumns      uint16 = 16
	OpnumNspiGetNamesFromIDs   uint16 = 17
	OpnumNspiGetIDsFromNames   uint16 = 18
	OpnumNspiResolveNames      uint16 = 19
	OpnumNspiResolveNamesW     uint16 = 20
)

// Status codes an NSPI method may return. NSPI methods return a LONG whose permitted
// values are the [MS-NSPI] section 2.2.2 "Permitted Error Code Values", defined in
// [MS-OXCDATA] section 2.4 (Error Codes) and 2.5 (Warning Codes). Those values are
// HRESULTs ([MS-ERREF] section 2.1), so severity is a range rather than a single value:
// Success and the ErrorsReturned warning both have the severity bit clear and are
// successes, and every other permitted value has it set. [MS-NSPI] also permits
// "TooBig", whose numeric value is defined in [MS-OXCDATA]; it is intentionally not
// hardcoded here.
//
// Five of the seventeen permitted values are generic HRESULTs that the whole of
// [MS-ERREF] 2.1.1 already carries in
// github.com/TheManticoreProject/Manticore/windows/errors/hresult under the HRESULT
// type, so they are not re-declared here. 0x00000000 is S_OK and 0x80004005 is E_FAIL,
// and the three FACILITY_WIN32 values 0x80070005, 0x8007000E and 0x80070057 are the
// HRESULT_FROM_WIN32 wrappings of ERROR_ACCESS_DENIED, ERROR_OUTOFMEMORY and
// ERROR_INVALID_PARAMETER ([MS-ERREF] 2.1.2), which the shared table names outright as
// E_ACCESSDENIED, E_OUTOFMEMORY and E_INVALIDARG and hresult.HRESULT.ToWin32 unwraps.
// Reference those from the shared package, converting a returned status with
// hresult.HRESULT(status) first. The wrapped code for 0x8007000E is ERROR_OUTOFMEMORY
// (0x0000000E), not the ERROR_NOT_ENOUGH_MEMORY (0x00000008) the value's former private
// name suggested; that code wraps to the different HRESULT 0x80070008.
//
// The twelve values below are the exception, and they cannot move. They are MAPI status
// values in FACILITY_ITF (0x004), the facility [MS-ERREF] 2.1 sets aside for meanings
// specific to the interface returning them, so the same number legitimately means
// different things in different interfaces. The shared table fills facility 4 with the
// OLE, drag-drop and class-registration names, and for two of these values it holds an
// unrelated row: it decodes 0x80040102 as DRAGDROP_E_INVALIDHWND where NSPI means
// MAPI_E_NO_SUPPORT, and 0x80040111 as CLASS_E_CLASSNOTAVAILABLE where NSPI means
// MAPI_E_LOGON_FAILED, so reading those out of it would report a failed address-book
// logon as a missing class factory. The other ten have no [MS-ERREF] 2.1.1 row at all.
// They stay declared here, and StatusString decodes them before deferring to the shared
// table for everything else.
const (
	StatusErrorsReturned     uint32 = 0x00040380 // ErrorsReturned (MAPI_W_ERRORS_RETURNED) — warning, no [MS-ERREF] 2.1.1 row
	StatusNotSupported       uint32 = 0x80040102 // NotSupported (MAPI_E_NO_SUPPORT); [MS-ERREF] 2.1.1 names this value DRAGDROP_E_INVALIDHWND
	StatusInvalidObject      uint32 = 0x80040108 // InvalidObject (MAPI_E_INVALID_OBJECT), no [MS-ERREF] 2.1.1 row
	StatusOutOfResources     uint32 = 0x8004010E // OutOfResources (MAPI_E_NOT_ENOUGH_RESOURCES), no [MS-ERREF] 2.1.1 row
	StatusNotFound           uint32 = 0x8004010F // NotFound (MAPI_E_NOT_FOUND), no [MS-ERREF] 2.1.1 row
	StatusLogonFailed        uint32 = 0x80040111 // LogonFailed (MAPI_E_LOGON_FAILED); [MS-ERREF] 2.1.1 names this value CLASS_E_CLASSNOTAVAILABLE
	StatusTooComplex         uint32 = 0x80040117 // TooComplex (MAPI_E_TOO_COMPLEX), no [MS-ERREF] 2.1.1 row
	StatusInvalidCodepage    uint32 = 0x8004011E // InvalidCodepage (MAPI_E_UNKNOWN_CPID), no [MS-ERREF] 2.1.1 row
	StatusInvalidLocale      uint32 = 0x8004011F // InvalidLocale (MAPI_E_UNKNOWN_LCID), no [MS-ERREF] 2.1.1 row
	StatusTableTooBig        uint32 = 0x80040403 // TableTooBig (MAPI_E_TABLE_TOO_BIG), no [MS-ERREF] 2.1.1 row
	StatusInvalidBookmark    uint32 = 0x80040405 // InvalidBookmark (MAPI_E_INVALID_BOOKMARK), no [MS-ERREF] 2.1.1 row
	StatusAmbiguousRecipient uint32 = 0x80040700 // AmbiguousRecipient (MAPI_E_AMBIGUOUS_RECIP), no [MS-ERREF] 2.1.1 row
)

// SyntaxID returns the nspi abstract syntax identifier:
// f5cc5a18-4264-101a-8c59-08002b2f8426, version 56.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0xf5cc5a18, B: 0x4264, C: 0x101a, D: 0x8c59, E: 0x08002b2f8426},
		MajorVersion: 56,
		MinorVersion: 0,
	}
}

// StatusString names the MAPI status values of [MS-NSPI] section 2.2.2 that sit in
// FACILITY_ITF, where [MS-ERREF] 2.1.1 either says nothing or names the same value for
// an unrelated OLE error, and defers every other status to the shared [MS-ERREF] 2.1
// table, which names each value the specification defines, derives a name for a
// FACILITY_WIN32 value from the Win32 code it wraps, and renders hex only for a value it
// cannot name. Deferring is right here because an NSPI return is itself an HRESULT; only
// the facility-4 block is interface-private.
func StatusString(status uint32) string {
	switch status {
	case StatusErrorsReturned:
		return "MAPI_W_ERRORS_RETURNED"
	case StatusNotSupported:
		return "MAPI_E_NO_SUPPORT"
	case StatusInvalidObject:
		return "MAPI_E_INVALID_OBJECT"
	case StatusOutOfResources:
		return "MAPI_E_NOT_ENOUGH_RESOURCES"
	case StatusNotFound:
		return "MAPI_E_NOT_FOUND"
	case StatusLogonFailed:
		return "MAPI_E_LOGON_FAILED"
	case StatusTooComplex:
		return "MAPI_E_TOO_COMPLEX"
	case StatusInvalidCodepage:
		return "MAPI_E_UNKNOWN_CPID"
	case StatusInvalidLocale:
		return "MAPI_E_UNKNOWN_LCID"
	case StatusTableTooBig:
		return "MAPI_E_TABLE_TOO_BIG"
	case StatusInvalidBookmark:
		return "MAPI_E_INVALID_BOOKMARK"
	case StatusAmbiguousRecipient:
		return "MAPI_E_AMBIGUOUS_RECIP"
	default:
		return hresult.HRESULT(status).String()
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumNspiBind:              "NspiBind",
	OpnumNspiUnbind:            "NspiUnbind",
	OpnumNspiUpdateStat:        "NspiUpdateStat",
	OpnumNspiQueryRows:         "NspiQueryRows",
	OpnumNspiSeekEntries:       "NspiSeekEntries",
	OpnumNspiGetMatches:        "NspiGetMatches",
	OpnumNspiResortRestriction: "NspiResortRestriction",
	OpnumNspiDNToMId:           "NspiDNToMId",
	OpnumNspiGetPropList:       "NspiGetPropList",
	OpnumNspiGetProps:          "NspiGetProps",
	OpnumNspiCompareMIds:       "NspiCompareMIds",
	OpnumNspiModProps:          "NspiModProps",
	OpnumNspiGetSpecialTable:   "NspiGetSpecialTable",
	OpnumNspiGetTemplateInfo:   "NspiGetTemplateInfo",
	OpnumNspiModLinkAtt:        "NspiModLinkAtt",
	OpnumNspiQueryColumns:      "NspiQueryColumns",
	OpnumNspiGetNamesFromIDs:   "NspiGetNamesFromIDs",
	OpnumNspiGetIDsFromNames:   "NspiGetIDsFromNames",
	OpnumNspiResolveNames:      "NspiResolveNames",
	OpnumNspiResolveNamesW:     "NspiResolveNamesW",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
