// Package rpcinterface_1a9134dd7b3945baad8844d01ca47f28_1_0 is the descriptor for the RemoteRead RPC interface, abstract
// syntax 1a9134dd-7b39-45ba-ad88-44d01ca47f28 version 1.0 ([MS-MQRR]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName, the status-code table, and doc comments are not derivable from
// the IDL and must be confirmed by hand (see the TODO markers).
package rpcinterface_1a9134dd7b3945baad8844d01ca47f28_1_0

// IDL source: [MS-MQMQ] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-mqmq/56cc73e0-f57a-4bd9-aa45-861be5b85049
// A fetched copy is kept at ms-mqmq.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/errors/hresult"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is empty: the RemoteRead interface is not reached over a named pipe. Per
// [MS-MQRR] section 2.1 the protocol uses RPC over ncacn_ip_tcp with a dynamically
// assigned endpoint; a client discovers the server's port via R_GetServerPort (opnum 0)
// or the RPC endpoint mapper. This mirrors its sibling MS-MQQP (qm2qm).
const PipeName = ``

// Opnums for the on-the-wire methods. Opnums 1 are "not used on the wire"
// and are omitted.
const (
	OpnumR_GetServerPort               uint16 = 0
	OpnumR_OpenQueue                   uint16 = 2
	OpnumR_CloseQueue                  uint16 = 3
	OpnumR_CreateCursor                uint16 = 4
	OpnumR_CloseCursor                 uint16 = 5
	OpnumR_PurgeQueue                  uint16 = 6
	OpnumR_StartReceive                uint16 = 7
	OpnumR_CancelReceive               uint16 = 8
	OpnumR_EndReceive                  uint16 = 9
	OpnumR_MoveMessage                 uint16 = 10
	OpnumR_OpenQueueForMove            uint16 = 11
	OpnumR_QMEnlistRemoteTransaction   uint16 = 12
	OpnumR_StartTransactionalReceive   uint16 = 13
	OpnumR_SetUserAcknowledgementClass uint16 = 14
	OpnumR_EndTransactionalReceive     uint16 = 15
)

// Status codes returned by the HRESULT-returning methods of this interface. The values are
// the Message Queuing result codes ([MS-MQMQ] section 2.4, mqerror.h). They are HRESULTs in
// FACILITY_MSMQ (0x00E), and [MS-ERREF] section 2.1.1 carries no row for that facility at
// all: the table names nothing in 0xC00E____ or 0x400E____ and no value whose name begins
// MQ_. So none of these can be read out of
// github.com/TheManticoreProject/Manticore/windows/errors/hresult, and they stay declared
// here, decoded by StatusString before it defers to the shared table.
//
// MQ_OK is the one exception, and it is gone from this block: its value is 0x00000000, which
// the shared package declares as hresult.S_OK, so the stubs compare a returned status against
// that constant. They compare for equality with it rather than testing IsSuccess, which
// preserves the behaviour they have always had — [MS-MQRR] documents MQ_OK as the success
// value of every one of these methods and requires the client to treat every other result
// identically, so a success-severity value that is not MQ_OK, such as one of the
// MQ_INFORMATION_* codes in 0x400E____, is still reported as a failure.
//
// Only the codes the [MS-MQRR] method sections enumerate for remote-read/cursor/transaction
// operations are listed here; StatusString defers every other value to the shared table.
//
// Note: R_GetServerPort (opnum 0) does NOT return an HRESULT — its DWORD result is the RPC
// port on which the server receives remote-read requests (0x00000000 signals failure).
const (
	MQ_ERROR                          uint32 = 0xC00E0001
	MQ_ERROR_QUEUE_NOT_FOUND          uint32 = 0xC00E0003
	MQ_ERROR_QUEUE_NOT_ACTIVE         uint32 = 0xC00E0004
	MQ_ERROR_INVALID_PARAMETER        uint32 = 0xC00E0006
	MQ_ERROR_INVALID_HANDLE           uint32 = 0xC00E0007
	MQ_ERROR_OPERATION_CANCELLED      uint32 = 0xC00E0008
	MQ_ERROR_SHARING_VIOLATION        uint32 = 0xC00E0009
	MQ_ERROR_SERVICE_NOT_AVAILABLE    uint32 = 0xC00E000B
	MQ_ERROR_IO_TIMEOUT               uint32 = 0xC00E001B
	MQ_ERROR_ILLEGAL_CURSOR_ACTION    uint32 = 0xC00E001C
	MQ_ERROR_MESSAGE_ALREADY_RECEIVED uint32 = 0xC00E001D
	MQ_ERROR_ACCESS_DENIED            uint32 = 0xC00E0025
	MQ_ERROR_PRIVILEGE_NOT_HELD       uint32 = 0xC00E0026
	MQ_ERROR_INSUFFICIENT_RESOURCES   uint32 = 0xC00E0027
	MQ_ERROR_TRANSACTION_USAGE        uint32 = 0xC00E0050
	MQ_ERROR_TRANSACTION_SEQUENCE     uint32 = 0xC00E0051
	MQ_ERROR_TRANSACTION_ENLIST       uint32 = 0xC00E0058
	MQ_ERROR_STALE_HANDLE             uint32 = 0xC00E0056
	MQ_ERROR_QUEUE_DELETED            uint32 = 0xC00E005A
	MQ_ERROR_ILLEGAL_CONTEXT          uint32 = 0xC00E005B
	MQ_ERROR_MESSAGE_NOT_FOUND        uint32 = 0xC00E0088
)

// SyntaxID returns the RemoteRead abstract syntax identifier:
// 1a9134dd-7b39-45ba-ad88-44d01ca47f28, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x1a9134dd, B: 0x7b39, C: 0x45ba, D: 0xad88, E: 0x44d01ca47f28},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString names the FACILITY_MSMQ result codes above, which [MS-ERREF] section 2.1.1
// does not carry, and defers every other status to the shared HRESULT table. The deferral is
// correct because an MSMQ result code genuinely is an HRESULT and only its facility is absent
// from the specification's table: 0x00000000 renders as S_OK, a FACILITY_WIN32 value renders
// through the Win32 code it wraps, and a value the table does not define renders as hex,
// exactly as it did before.
func StatusString(status uint32) string {
	switch status {
	case MQ_ERROR:
		return "MQ_ERROR"
	case MQ_ERROR_QUEUE_NOT_FOUND:
		return "MQ_ERROR_QUEUE_NOT_FOUND"
	case MQ_ERROR_QUEUE_NOT_ACTIVE:
		return "MQ_ERROR_QUEUE_NOT_ACTIVE"
	case MQ_ERROR_INVALID_PARAMETER:
		return "MQ_ERROR_INVALID_PARAMETER"
	case MQ_ERROR_INVALID_HANDLE:
		return "MQ_ERROR_INVALID_HANDLE"
	case MQ_ERROR_OPERATION_CANCELLED:
		return "MQ_ERROR_OPERATION_CANCELLED"
	case MQ_ERROR_SHARING_VIOLATION:
		return "MQ_ERROR_SHARING_VIOLATION"
	case MQ_ERROR_SERVICE_NOT_AVAILABLE:
		return "MQ_ERROR_SERVICE_NOT_AVAILABLE"
	case MQ_ERROR_IO_TIMEOUT:
		return "MQ_ERROR_IO_TIMEOUT"
	case MQ_ERROR_ILLEGAL_CURSOR_ACTION:
		return "MQ_ERROR_ILLEGAL_CURSOR_ACTION"
	case MQ_ERROR_MESSAGE_ALREADY_RECEIVED:
		return "MQ_ERROR_MESSAGE_ALREADY_RECEIVED"
	case MQ_ERROR_ACCESS_DENIED:
		return "MQ_ERROR_ACCESS_DENIED"
	case MQ_ERROR_PRIVILEGE_NOT_HELD:
		return "MQ_ERROR_PRIVILEGE_NOT_HELD"
	case MQ_ERROR_INSUFFICIENT_RESOURCES:
		return "MQ_ERROR_INSUFFICIENT_RESOURCES"
	case MQ_ERROR_TRANSACTION_USAGE:
		return "MQ_ERROR_TRANSACTION_USAGE"
	case MQ_ERROR_TRANSACTION_SEQUENCE:
		return "MQ_ERROR_TRANSACTION_SEQUENCE"
	case MQ_ERROR_TRANSACTION_ENLIST:
		return "MQ_ERROR_TRANSACTION_ENLIST"
	case MQ_ERROR_STALE_HANDLE:
		return "MQ_ERROR_STALE_HANDLE"
	case MQ_ERROR_QUEUE_DELETED:
		return "MQ_ERROR_QUEUE_DELETED"
	case MQ_ERROR_ILLEGAL_CONTEXT:
		return "MQ_ERROR_ILLEGAL_CONTEXT"
	case MQ_ERROR_MESSAGE_NOT_FOUND:
		return "MQ_ERROR_MESSAGE_NOT_FOUND"
	default:
		return hresult.HRESULT(status).String()
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumR_GetServerPort:               "R_GetServerPort",
	OpnumR_OpenQueue:                   "R_OpenQueue",
	OpnumR_CloseQueue:                  "R_CloseQueue",
	OpnumR_CreateCursor:                "R_CreateCursor",
	OpnumR_CloseCursor:                 "R_CloseCursor",
	OpnumR_PurgeQueue:                  "R_PurgeQueue",
	OpnumR_StartReceive:                "R_StartReceive",
	OpnumR_CancelReceive:               "R_CancelReceive",
	OpnumR_EndReceive:                  "R_EndReceive",
	OpnumR_MoveMessage:                 "R_MoveMessage",
	OpnumR_OpenQueueForMove:            "R_OpenQueueForMove",
	OpnumR_QMEnlistRemoteTransaction:   "R_QMEnlistRemoteTransaction",
	OpnumR_StartTransactionalReceive:   "R_StartTransactionalReceive",
	OpnumR_SetUserAcknowledgementClass: "R_SetUserAcknowledgementClass",
	OpnumR_EndTransactionalReceive:     "R_EndTransactionalReceive",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
