// Package rpcinterface_45f52c287f9f101ab52b08002b2efabe_1_0 is the descriptor for the winsif RPC interface, abstract
// syntax 45f52c28-7f9f-101a-b52b-08002b2efabe version 1.0 ([MS-RAIW]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName and the doc comments are not derivable from the IDL and must be
// confirmed by hand (see the TODO markers).
package rpcinterface_45f52c287f9f101ab52b08002b2efabe_1_0

// IDL source: [MS-RAIW] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-raiw/e59461f5-5486-4ec3-9ad6-14b784c1ecd6
// A fetched copy is kept at ms-raiw.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the winsif interface. WINS registers a
// single named pipe, \pipe\WinsPipe, shared with the winsi2 interface ([MS-RAIW] 2.1,
// Standards Assignments).
const PipeName = `\WinsPipe`

// Opnums for the on-the-wire methods.
const (
	OpnumR_WinsRecordAction        uint16 = 0
	OpnumR_WinsStatus              uint16 = 1
	OpnumR_WinsTrigger             uint16 = 2
	OpnumR_WinsDoStaticInit        uint16 = 3
	OpnumR_WinsDoScavenging        uint16 = 4
	OpnumR_WinsGetDbRecs           uint16 = 5
	OpnumR_WinsTerm                uint16 = 6
	OpnumR_WinsBackup              uint16 = 7
	OpnumR_WinsDelDbRecs           uint16 = 8
	OpnumR_WinsPullRange           uint16 = 9
	OpnumR_WinsSetPriorityClass    uint16 = 10
	OpnumR_WinsResetCounters       uint16 = 11
	OpnumR_WinsWorkerThdUpd        uint16 = 12
	OpnumR_WinsGetNameAndAdd       uint16 = 13
	OpnumR_WinsGetBrowserNames_Old uint16 = 14
	OpnumR_WinsDeleteWins          uint16 = 15
	OpnumR_WinsSetFlags            uint16 = 16
	OpnumR_WinsGetBrowserNames     uint16 = 17
	OpnumR_WinsGetDbRecsByName     uint16 = 18
	OpnumR_WinsStatusNew           uint16 = 19
	OpnumR_WinsStatusWHdl          uint16 = 20
	OpnumR_WinsDoScavengingNew     uint16 = 21
)

// The Win32 error codes winsif methods return ([MS-ERREF] 2.2, [MS-RAIW] 3.1.4) are not
// declared here. The whole of [MS-ERREF] 2.2 lives in
// github.com/TheManticoreProject/Manticore/windows/errors/win32 as the WIN32_ERROR type,
// and a subset repeated here would cover a fraction of that 2703-code table while drifting
// from it. Convert a returned status with win32.WIN32_ERROR(status) and compare against
// win32.ERROR_SUCCESS and the rest. The WINS-specific codes 0x00000FA0-0x00000FA6
// (ERROR_WINS_INTERNAL through ERROR_RPL_NOT_ALLOWED) are rows of that same table and
// need no local declaration either.

// SyntaxID returns the winsif abstract syntax identifier:
// 45f52c28-7f9f-101a-b52b-08002b2efabe, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x45f52c28, B: 0x7f9f, C: 0x101a, D: 0xb52b, E: 0x08002b2efabe},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumR_WinsRecordAction:        "R_WinsRecordAction",
	OpnumR_WinsStatus:              "R_WinsStatus",
	OpnumR_WinsTrigger:             "R_WinsTrigger",
	OpnumR_WinsDoStaticInit:        "R_WinsDoStaticInit",
	OpnumR_WinsDoScavenging:        "R_WinsDoScavenging",
	OpnumR_WinsGetDbRecs:           "R_WinsGetDbRecs",
	OpnumR_WinsTerm:                "R_WinsTerm",
	OpnumR_WinsBackup:              "R_WinsBackup",
	OpnumR_WinsDelDbRecs:           "R_WinsDelDbRecs",
	OpnumR_WinsPullRange:           "R_WinsPullRange",
	OpnumR_WinsSetPriorityClass:    "R_WinsSetPriorityClass",
	OpnumR_WinsResetCounters:       "R_WinsResetCounters",
	OpnumR_WinsWorkerThdUpd:        "R_WinsWorkerThdUpd",
	OpnumR_WinsGetNameAndAdd:       "R_WinsGetNameAndAdd",
	OpnumR_WinsGetBrowserNames_Old: "R_WinsGetBrowserNames_Old",
	OpnumR_WinsDeleteWins:          "R_WinsDeleteWins",
	OpnumR_WinsSetFlags:            "R_WinsSetFlags",
	OpnumR_WinsGetBrowserNames:     "R_WinsGetBrowserNames",
	OpnumR_WinsGetDbRecsByName:     "R_WinsGetDbRecsByName",
	OpnumR_WinsStatusNew:           "R_WinsStatusNew",
	OpnumR_WinsStatusWHdl:          "R_WinsStatusWHdl",
	OpnumR_WinsDoScavengingNew:     "R_WinsDoScavengingNew",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
