package msscmr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// ENUM_SERVICE_STATUS_PROCESSW ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type ENUM_SERVICE_STATUS_PROCESSW struct {
	LpServiceName        *ndr.WSTR `ndr:"unique"`
	LpDisplayName        *ndr.WSTR `ndr:"unique"`
	ServiceStatusProcess SERVICE_STATUS_PROCESS
}
