package msscmr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// ENUM_SERVICE_STATUSW ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type ENUM_SERVICE_STATUSW struct {
	LpServiceName *ndr.WSTR `ndr:"unique"`
	LpDisplayName *ndr.WSTR `ndr:"unique"`
	ServiceStatus SERVICE_STATUS
}
