package msscmr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// QUERY_SERVICE_LOCK_STATUSW ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type QUERY_SERVICE_LOCK_STATUSW struct {
	FIsLocked      ndr.DWORD
	LpLockOwner    *ndr.WSTR `ndr:"unique"`
	DwLockDuration ndr.DWORD
}
