package msscmr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SC_ACTION ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type SC_ACTION struct {
	Type  SC_ACTION_TYPE
	Delay ndr.DWORD
}
