package msscmr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SERVICE_FAILURE_ACTIONS_WOW64 ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type SERVICE_FAILURE_ACTIONS_WOW64 struct {
	DwResetPeriod     ndr.DWORD
	DwRebootMsgOffset ndr.DWORD
	DwCommandOffset   ndr.DWORD
	CActions          ndr.DWORD
	DwsaActionsOffset ndr.DWORD
}
