package msscmr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/dtyp"
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SERVICE_TRIGGER ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type SERVICE_TRIGGER struct {
	DwTriggerType   ndr.DWORD
	DwAction        ndr.DWORD
	PTriggerSubtype *dtyp.GUID `ndr:"unique"`
	CDataItems      ndr.DWORD
	PDataItems      []SERVICE_TRIGGER_SPECIFIC_DATA_ITEM `ndr:"unique,size_is=CDataItems"`
}
