package msscmr

// SERVICE_NOTIFY_STATUS_CHANGE_PARAMS is an alias for SERVICE_NOTIFY_STATUS_CHANGE_PARAMS_2 ([MS-SCMR]).
type SERVICE_NOTIFY_STATUS_CHANGE_PARAMS = SERVICE_NOTIFY_STATUS_CHANGE_PARAMS_2
