package msscmr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SERVICE_DESCRIPTION_WOW64 ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type SERVICE_DESCRIPTION_WOW64 struct {
	DwDescriptionOffset ndr.DWORD
}
