package msscmr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SERVICE_STATUS_PROCESS ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type SERVICE_STATUS_PROCESS struct {
	DwServiceType             ndr.DWORD
	DwCurrentState            ndr.DWORD
	DwControlsAccepted        ndr.DWORD
	DwWin32ExitCode           ndr.DWORD
	DwServiceSpecificExitCode ndr.DWORD
	DwCheckPoint              ndr.DWORD
	DwWaitHint                ndr.DWORD
	DwProcessId               ndr.DWORD
	DwServiceFlags            ndr.DWORD
}
