package msscmr

// SERVICE_PREFERRED_NODE_INFO ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type SERVICE_PREFERRED_NODE_INFO struct {
	UsPreferredNode uint16
	FDelete         bool
}
