package msscmr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SERVICE_REQUIRED_PRIVILEGES_INFO_WOW64 ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type SERVICE_REQUIRED_PRIVILEGES_INFO_WOW64 struct {
	DwRequiredPrivilegesOffset ndr.DWORD
}
