package mswkst

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	msdtyp "github.com/TheManticoreProject/Manticore/windows/ms-dtyp"
)

// STAT_WORKSTATION_0 ([MS-WKST]). Generated by tools/idlgen; verify pointer/array tags.
type STAT_WORKSTATION_0 struct {
	StatisticsStartTime          msdtyp.LARGE_INTEGER
	BytesReceived                msdtyp.LARGE_INTEGER
	SmbsReceived                 msdtyp.LARGE_INTEGER
	PagingReadBytesRequested     msdtyp.LARGE_INTEGER
	NonPagingReadBytesRequested  msdtyp.LARGE_INTEGER
	CacheReadBytesRequested      msdtyp.LARGE_INTEGER
	NetworkReadBytesRequested    msdtyp.LARGE_INTEGER
	BytesTransmitted             msdtyp.LARGE_INTEGER
	SmbsTransmitted              msdtyp.LARGE_INTEGER
	PagingWriteBytesRequested    msdtyp.LARGE_INTEGER
	NonPagingWriteBytesRequested msdtyp.LARGE_INTEGER
	CacheWriteBytesRequested     msdtyp.LARGE_INTEGER
	NetworkWriteBytesRequested   msdtyp.LARGE_INTEGER
	InitiallyFailedOperations    ndr.DWORD
	FailedCompletionOperations   ndr.DWORD
	ReadOperations               ndr.DWORD
	RandomReadOperations         ndr.DWORD
	ReadSmbs                     ndr.DWORD
	LargeReadSmbs                ndr.DWORD
	SmallReadSmbs                ndr.DWORD
	WriteOperations              ndr.DWORD
	RandomWriteOperations        ndr.DWORD
	WriteSmbs                    ndr.DWORD
	LargeWriteSmbs               ndr.DWORD
	SmallWriteSmbs               ndr.DWORD
	RawReadsDenied               ndr.DWORD
	RawWritesDenied              ndr.DWORD
	NetworkErrors                ndr.DWORD
	Sessions                     ndr.DWORD
	FailedSessions               ndr.DWORD
	Reconnects                   ndr.DWORD
	CoreConnects                 ndr.DWORD
	Lanman20Connects             ndr.DWORD
	Lanman21Connects             ndr.DWORD
	LanmanNtConnects             ndr.DWORD
	ServerDisconnects            ndr.DWORD
	HungSessions                 ndr.DWORD
	UseCount                     ndr.DWORD
	FailedUseCount               ndr.DWORD
	CurrentCommands              ndr.DWORD
}
