package mswkst

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/dtyp"
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// STAT_WORKSTATION_0 ([MS-WKST]). Generated by tools/idlgen; verify pointer/array tags.
type STAT_WORKSTATION_0 struct {
	StatisticsStartTime          dtyp.LARGE_INTEGER
	BytesReceived                dtyp.LARGE_INTEGER
	SmbsReceived                 dtyp.LARGE_INTEGER
	PagingReadBytesRequested     dtyp.LARGE_INTEGER
	NonPagingReadBytesRequested  dtyp.LARGE_INTEGER
	CacheReadBytesRequested      dtyp.LARGE_INTEGER
	NetworkReadBytesRequested    dtyp.LARGE_INTEGER
	BytesTransmitted             dtyp.LARGE_INTEGER
	SmbsTransmitted              dtyp.LARGE_INTEGER
	PagingWriteBytesRequested    dtyp.LARGE_INTEGER
	NonPagingWriteBytesRequested dtyp.LARGE_INTEGER
	CacheWriteBytesRequested     dtyp.LARGE_INTEGER
	NetworkWriteBytesRequested   dtyp.LARGE_INTEGER
	InitiallyFailedOperations    ndr.DWORD
	FailedCompletionOperations   ndr.DWORD
	ReadOperations               ndr.DWORD
	RandomReadOperations         ndr.DWORD
	ReadSmbs                     ndr.DWORD
	LargeReadSmbs                ndr.DWORD
	SmallReadSmbs                ndr.DWORD
	WriteOperations              ndr.DWORD
	RandomWriteOperations        ndr.DWORD
	WriteSmbs                    ndr.DWORD
	LargeWriteSmbs               ndr.DWORD
	SmallWriteSmbs               ndr.DWORD
	RawReadsDenied               ndr.DWORD
	RawWritesDenied              ndr.DWORD
	NetworkErrors                ndr.DWORD
	Sessions                     ndr.DWORD
	FailedSessions               ndr.DWORD
	Reconnects                   ndr.DWORD
	CoreConnects                 ndr.DWORD
	Lanman20Connects             ndr.DWORD
	Lanman21Connects             ndr.DWORD
	LanmanNtConnects             ndr.DWORD
	ServerDisconnects            ndr.DWORD
	HungSessions                 ndr.DWORD
	UseCount                     ndr.DWORD
	FailedUseCount               ndr.DWORD
	CurrentCommands              ndr.DWORD
}
