package mswkst

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// USE_INFO_2 ([MS-WKST]). Generated by tools/idlgen; verify pointer/array tags.
type USE_INFO_2 struct {
	Ui2_useinfo    USE_INFO_1
	Ui2_username   *ndr.WSTR `ndr:"unique"`
	Ui2_domainname *ndr.WSTR `ndr:"unique"`
}
