package mswkst

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// USE_INFO_0 ([MS-WKST]). Generated by tools/idlgen; verify pointer/array tags.
type USE_INFO_0 struct {
	Ui0_local  *ndr.WSTR `ndr:"unique"`
	Ui0_remote *ndr.WSTR `ndr:"unique"`
}
