package mswkst

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// USE_INFO_0_CONTAINER ([MS-WKST]). Generated by tools/idlgen; verify pointer/array tags.
type USE_INFO_0_CONTAINER struct {
	EntriesRead ndr.DWORD
	Buffer      *USE_INFO_0 `ndr:"unique"`
}
