package mswkst

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// WKSTA_TRANSPORT_ENUM_STRUCT ([MS-WKST]). Generated by tools/idlgen; verify pointer/array tags.
type WKSTA_TRANSPORT_ENUM_STRUCT struct {
	Level              ndr.DWORD
	WkstaTransportInfo WKSTA_TRANSPORT_ENUM_UNION
}

// WKSTA_TRANSPORT_ENUM_UNION is a discriminated union ([MS-WKST]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
// Every arm is a [unique] pointer container (LPWKSTA_TRANSPORT_INFO_0_CONTAINER), so the arm
// is a pointer field with `unique`; an inline-value arm would drop the container referent id.
type WKSTA_TRANSPORT_ENUM_UNION struct {
	Tag    ndr.DWORD                         `ndr:"switch"`
	Level0 *WKSTA_TRANSPORT_INFO_0_CONTAINER `ndr:"case=0,unique"`
}
