package mswkst

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// WKSTA_INFO_1018 ([MS-WKST]). Generated by tools/idlgen; verify pointer/array tags.
type WKSTA_INFO_1018 struct {
	Wki1018_sess_timeout ndr.DWORD
}
