package mswkst

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// WKSTA_USER_INFO_1_CONTAINER ([MS-WKST]). Generated by tools/idlgen; verify pointer/array tags.
type WKSTA_USER_INFO_1_CONTAINER struct {
	EntriesRead ndr.DWORD
	Buffer      []WKSTA_USER_INFO_1 `ndr:"unique,size_is=EntriesRead"`
}
