package mswkst

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// WKSTA_INFO_1013 ([MS-WKST]). Generated by tools/idlgen; verify pointer/array tags.
type WKSTA_INFO_1013 struct {
	Wki1013_keep_conn ndr.DWORD
}
