// Package rpcinterface_f6beaff71e194fbb9f8fb89e2018337c_1_0 is the descriptor for the IEventService RPC interface, abstract
// syntax f6beaff7-1e19-4fbb-9f8f-b89e2018337c version 1.0 ([MS-EVEN6]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed by hand:
// the PipeName (from the spec's Standards Assignments) is not derivable from the IDL and
// was filled in against [MS-EVEN6].
package rpcinterface_f6beaff71e194fbb9f8fb89e2018337c_1_0

// IDL source: [MS-EVEN6] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-even6/2d808edd-719a-4c69-b34a-df766adb5f0c
// A fetched copy is kept at ms-even6.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the IEventService interface. [MS-EVEN6]'s
// Standards Assignments give the RPC endpoint name "Eventlog"; the interface is reached
// over ncacn_np at \pipe\eventlog (and ncacn_ip_tcp with a dynamic endpoint).
const PipeName = `\eventlog`

// Opnums for the on-the-wire methods.
const (
	OpnumEvtRpcRegisterRemoteSubscription    uint16 = 0
	OpnumEvtRpcRemoteSubscriptionNextAsync   uint16 = 1
	OpnumEvtRpcRemoteSubscriptionNext        uint16 = 2
	OpnumEvtRpcRemoteSubscriptionWaitAsync   uint16 = 3
	OpnumEvtRpcRegisterControllableOperation uint16 = 4
	OpnumEvtRpcRegisterLogQuery              uint16 = 5
	OpnumEvtRpcClearLog                      uint16 = 6
	OpnumEvtRpcExportLog                     uint16 = 7
	OpnumEvtRpcLocalizeExportLog             uint16 = 8
	OpnumEvtRpcMessageRender                 uint16 = 9
	OpnumEvtRpcMessageRenderDefault          uint16 = 10
	OpnumEvtRpcQueryNext                     uint16 = 11
	OpnumEvtRpcQuerySeek                     uint16 = 12
	OpnumEvtRpcClose                         uint16 = 13
	OpnumEvtRpcCancel                        uint16 = 14
	OpnumEvtRpcAssertConfig                  uint16 = 15
	OpnumEvtRpcRetractConfig                 uint16 = 16
	OpnumEvtRpcOpenLogHandle                 uint16 = 17
	OpnumEvtRpcGetLogFileInfo                uint16 = 18
	OpnumEvtRpcGetChannelList                uint16 = 19
	OpnumEvtRpcGetChannelConfig              uint16 = 20
	OpnumEvtRpcPutChannelConfig              uint16 = 21
	OpnumEvtRpcGetPublisherList              uint16 = 22
	OpnumEvtRpcGetPublisherListForChannel    uint16 = 23
	OpnumEvtRpcGetPublisherMetadata          uint16 = 24
	OpnumEvtRpcGetPublisherResourceMetadata  uint16 = 25
	OpnumEvtRpcGetEventMetadataEnum          uint16 = 26
	OpnumEvtRpcGetNextEventMetadata          uint16 = 27
	OpnumEvtRpcGetClassicLogDisplayName      uint16 = 28
)

// The Win32 error codes IEventService methods return ([MS-ERREF] 2.2, [MS-EVEN6] 3.1.4) —
// every method returns error_status_t, including the ERROR_EVT_* range specific to the
// Windows Event Log — are not declared here. The whole of [MS-ERREF] 2.2 lives in
// github.com/TheManticoreProject/Manticore/windows/errors/win32 as the WIN32_ERROR type,
// and a subset repeated here would cover a fraction of that 2703-code table while drifting
// from it. Convert a returned status with win32.WIN32_ERROR(status) and compare against
// win32.ERROR_SUCCESS and the rest.

// SyntaxID returns the IEventService abstract syntax identifier:
// f6beaff7-1e19-4fbb-9f8f-b89e2018337c, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0xf6beaff7, B: 0x1e19, C: 0x4fbb, D: 0x9f8f, E: 0xb89e2018337c},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumEvtRpcRegisterRemoteSubscription:    "EvtRpcRegisterRemoteSubscription",
	OpnumEvtRpcRemoteSubscriptionNextAsync:   "EvtRpcRemoteSubscriptionNextAsync",
	OpnumEvtRpcRemoteSubscriptionNext:        "EvtRpcRemoteSubscriptionNext",
	OpnumEvtRpcRemoteSubscriptionWaitAsync:   "EvtRpcRemoteSubscriptionWaitAsync",
	OpnumEvtRpcRegisterControllableOperation: "EvtRpcRegisterControllableOperation",
	OpnumEvtRpcRegisterLogQuery:              "EvtRpcRegisterLogQuery",
	OpnumEvtRpcClearLog:                      "EvtRpcClearLog",
	OpnumEvtRpcExportLog:                     "EvtRpcExportLog",
	OpnumEvtRpcLocalizeExportLog:             "EvtRpcLocalizeExportLog",
	OpnumEvtRpcMessageRender:                 "EvtRpcMessageRender",
	OpnumEvtRpcMessageRenderDefault:          "EvtRpcMessageRenderDefault",
	OpnumEvtRpcQueryNext:                     "EvtRpcQueryNext",
	OpnumEvtRpcQuerySeek:                     "EvtRpcQuerySeek",
	OpnumEvtRpcClose:                         "EvtRpcClose",
	OpnumEvtRpcCancel:                        "EvtRpcCancel",
	OpnumEvtRpcAssertConfig:                  "EvtRpcAssertConfig",
	OpnumEvtRpcRetractConfig:                 "EvtRpcRetractConfig",
	OpnumEvtRpcOpenLogHandle:                 "EvtRpcOpenLogHandle",
	OpnumEvtRpcGetLogFileInfo:                "EvtRpcGetLogFileInfo",
	OpnumEvtRpcGetChannelList:                "EvtRpcGetChannelList",
	OpnumEvtRpcGetChannelConfig:              "EvtRpcGetChannelConfig",
	OpnumEvtRpcPutChannelConfig:              "EvtRpcPutChannelConfig",
	OpnumEvtRpcGetPublisherList:              "EvtRpcGetPublisherList",
	OpnumEvtRpcGetPublisherListForChannel:    "EvtRpcGetPublisherListForChannel",
	OpnumEvtRpcGetPublisherMetadata:          "EvtRpcGetPublisherMetadata",
	OpnumEvtRpcGetPublisherResourceMetadata:  "EvtRpcGetPublisherResourceMetadata",
	OpnumEvtRpcGetEventMetadataEnum:          "EvtRpcGetEventMetadataEnum",
	OpnumEvtRpcGetNextEventMetadata:          "EvtRpcGetNextEventMetadata",
	OpnumEvtRpcGetClassicLogDisplayName:      "EvtRpcGetClassicLogDisplayName",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
