package mscmrp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NOTIFY_FILTER_AND_TYPE_RPC ([MS-CMRP]). Generated by tools/idlgen; verify pointer/array tags.
type NOTIFY_FILTER_AND_TYPE_RPC struct {
	DwObjectType ndr.DWORD
	FilterFlags  int64
}
