package mscmrp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RESOURCE_ENUM_ENTRY ([MS-CMRP]). Generated by tools/idlgen; verify pointer/array tags.
type RESOURCE_ENUM_ENTRY struct {
	Name           *ndr.WSTR `ndr:"unique"`
	Id             *ndr.WSTR `ndr:"unique"`
	OwnerName      *ndr.WSTR `ndr:"unique"`
	OwnerId        *ndr.WSTR `ndr:"unique"`
	CbProperties   ndr.DWORD
	Properties     []uint8 `ndr:"unique,size_is=CbProperties"`
	CbRoProperties ndr.DWORD
	RoProperties   []uint8 `ndr:"unique,size_is=CbRoProperties"`
}
