package mscmrp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RESOURCE_ENUM_LIST ([MS-CMRP]). Generated by tools/idlgen; verify pointer/array tags.
type RESOURCE_ENUM_LIST struct {
	EntryCount ndr.DWORD
	Entry      []RESOURCE_ENUM_ENTRY `ndr:"conformant,size_is=EntryCount"`
}
