// Package rpcinterface_11899a432b684a7692e3a3d6ad8c26ce_1_0 is the descriptor for the TermSrvNotification RPC interface, abstract
// syntax 11899a43-2b68-4a76-92e3-a3d6ad8c26ce version 1.0 ([MS-TSTS]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName (from [MS-TSTS] 1.9) is not derivable from the IDL and was
// confirmed by hand.
package rpcinterface_11899a432b684a7692e3a3d6ad8c26ce_1_0

// IDL source: [MS-TSTS] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tsts/c43addc7-eebc-491b-9b01-2587262675e8
// A fetched copy is kept at ms-tsts.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the TermSrvNotification interface.
// The endpoint is assigned in [MS-TSTS] section 1.9 (Standards Assignments).
const PipeName = `\LSM_API_service`

// Opnums for the on-the-wire methods.
const (
	OpnumRpcWaitForSessionState         uint16 = 0
	OpnumRpcRegisterAsyncNotification   uint16 = 1
	OpnumRpcWaitAsyncNotification       uint16 = 2
	OpnumRpcUnRegisterAsyncNotification uint16 = 3
)

// The HRESULT values TermSrvNotification methods return ([MS-ERREF] 2.1, [MS-TSTS] 3.3.4.2) are not
// declared here. The whole of [MS-ERREF] 2.1.1 lives in
// github.com/TheManticoreProject/Manticore/windows/errors/hresult as the HRESULT type,
// and a subset repeated here would cover a fraction of that 2928-value table while
// drifting from it. Convert a returned status with hresult.HRESULT(status) and compare
// against hresult.S_OK and the rest. HRESULT success is a range rather than a single
// value — bit 31 clear means success — so hresult.HRESULT.IsSuccess admits S_FALSE and
// every other success-severity value, which a comparison against S_OK alone does not.

// SyntaxID returns the TermSrvNotification abstract syntax identifier:
// 11899a43-2b68-4a76-92e3-a3d6ad8c26ce, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x11899a43, B: 0x2b68, C: 0x4a76, D: 0x92e3, E: 0xa3d6ad8c26ce},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumRpcWaitForSessionState:         "RpcWaitForSessionState",
	OpnumRpcRegisterAsyncNotification:   "RpcRegisterAsyncNotification",
	OpnumRpcWaitAsyncNotification:       "RpcWaitAsyncNotification",
	OpnumRpcUnRegisterAsyncNotification: "RpcUnRegisterAsyncNotification",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
