// Package rpcinterface_11899a432b684a7692e3a3d6ad8c26ce_1_0 is the descriptor for the TermSrvNotification RPC interface, abstract
// syntax 11899a43-2b68-4a76-92e3-a3d6ad8c26ce version 1.0 ([MS-TSTS]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName (from [MS-TSTS] 1.9) and the status-code table are not derivable
// from the IDL and were completed by hand.
package rpcinterface_11899a432b684a7692e3a3d6ad8c26ce_1_0

// IDL source: [MS-TSTS] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tsts/c43addc7-eebc-491b-9b01-2587262675e8
// A fetched copy is kept at ms-tsts.idl in the interface directory.

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the TermSrvNotification interface.
// The endpoint is assigned in [MS-TSTS] section 1.9 (Standards Assignments).
const PipeName = `\LSM_API_service`

// Opnums for the on-the-wire methods.
const (
	OpnumRpcWaitForSessionState         uint16 = 0
	OpnumRpcRegisterAsyncNotification   uint16 = 1
	OpnumRpcWaitAsyncNotification       uint16 = 2
	OpnumRpcUnRegisterAsyncNotification uint16 = 3
)

// Status codes for this interface. Its methods return an HRESULT ([MS-ERREF] 2.1);
// success is S_OK (0x00000000). The values below are the common failures; StatusString
// falls back to the raw hex for any other value.
const (
	StatusSuccess  uint32 = 0x00000000 // S_OK
	E_ABORT        uint32 = 0x80004004
	E_FAIL         uint32 = 0x80004005
	E_OUTOFMEMORY  uint32 = 0x8007000e
	E_ACCESSDENIED uint32 = 0x80070005
	E_INVALIDARG   uint32 = 0x80070057
)

// SyntaxID returns the TermSrvNotification abstract syntax identifier:
// 11899a43-2b68-4a76-92e3-a3d6ad8c26ce, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x11899a43, B: 0x2b68, C: 0x4a76, D: 0x92e3, E: 0xa3d6ad8c26ce},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented status codes, otherwise the
// hex value.
func StatusString(status uint32) string {
	switch status {
	case StatusSuccess:
		return "S_OK"
	case E_ABORT:
		return "E_ABORT"
	case E_FAIL:
		return "E_FAIL"
	case E_OUTOFMEMORY:
		return "E_OUTOFMEMORY"
	case E_ACCESSDENIED:
		return "E_ACCESSDENIED"
	case E_INVALIDARG:
		return "E_INVALIDARG"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumRpcWaitForSessionState:         "RpcWaitForSessionState",
	OpnumRpcRegisterAsyncNotification:   "RpcRegisterAsyncNotification",
	OpnumRpcWaitAsyncNotification:       "RpcWaitAsyncNotification",
	OpnumRpcUnRegisterAsyncNotification: "RpcUnRegisterAsyncNotification",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
