package msfrs2

// FRS_RDC_PARAMETERS_FILTERMAX ([MS-FRS2]). Generated by tools/idlgen; verify pointer/array tags.
type FRS_RDC_PARAMETERS_FILTERMAX struct {
	HorizonSize uint16
	WindowSize  uint16
}
