package msfrs2

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FRS_ASYNC_VERSION_VECTOR_RESPONSE ([MS-FRS2]). Generated by tools/idlgen; verify pointer/array tags.
type FRS_ASYNC_VERSION_VECTOR_RESPONSE struct {
	VvGeneration       uint64
	VersionVectorCount ndr.DWORD
	VersionVector      []FRS_VERSION_VECTOR `ndr:"unique,size_is=VersionVectorCount"`
	EpoqueVectorCount  ndr.DWORD
	EpoqueVector       []FRS_EPOQUE_VECTOR `ndr:"unique,size_is=EpoqueVectorCount"`
}
