package msfrs2

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/dtyp"
)

// FRS_VERSION_VECTOR ([MS-FRS2]). Generated by tools/idlgen; verify pointer/array tags.
type FRS_VERSION_VECTOR struct {
	DbGuid dtyp.GUID
	Low    uint64
	High   uint64
}
