package msfrs2

// FRS_REQUESTED_STAGING_POLICY is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FRS2]).
type FRS_REQUESTED_STAGING_POLICY uint16

const (
	SERVER_DEFAULT     FRS_REQUESTED_STAGING_POLICY = 0
	STAGING_REQUIRED   FRS_REQUESTED_STAGING_POLICY = 1
	RESTAGING_REQUIRED FRS_REQUESTED_STAGING_POLICY = 2
)
