package msfrs2

// FRS_RDC_PARAMETERS_GENERIC ([MS-FRS2]). Generated by tools/idlgen; verify pointer/array tags.
type FRS_RDC_PARAMETERS_GENERIC struct {
	ChunkerType       uint16
	ChunkerParameters [64]uint8
}
