package msfrs2

// RDC_CHUNKER_ALGORITHM is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FRS2]).
type RDC_CHUNKER_ALGORITHM uint16

const (
	RDC_FILTERGENERIC RDC_CHUNKER_ALGORITHM = 0
	RDC_FILTERMAX     RDC_CHUNKER_ALGORITHM = 1
	RDC_FILTERPOINT   RDC_CHUNKER_ALGORITHM = 2
	RDC_MAXALGORITHM  RDC_CHUNKER_ALGORITHM = 3
)
