package msfrs2

// UPDATE_REQUEST_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FRS2]).
type UPDATE_REQUEST_TYPE uint16

const (
	UPDATE_REQUEST_ALL        UPDATE_REQUEST_TYPE = 0
	UPDATE_REQUEST_TOMBSTONES UPDATE_REQUEST_TYPE = 1
	UPDATE_REQUEST_LIVE       UPDATE_REQUEST_TYPE = 2
)
