package msfrs2

// VERSION_REQUEST_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FRS2]).
type VERSION_REQUEST_TYPE uint16

const (
	REQUEST_NORMAL_SYNC      VERSION_REQUEST_TYPE = 0
	REQUEST_SLOW_SYNC        VERSION_REQUEST_TYPE = 1
	REQUEST_SUBORDINATE_SYNC VERSION_REQUEST_TYPE = 2
)
