package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCPV6R_MIB_GET_OUTPUT_DATA ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCPV6R_MIB_GET_OUTPUT_DATA struct {
	IMGOD_TypeID  ndr.DWORD
	IMGOD_IfIndex ndr.DWORD
	IMGOD_Buffer  [1]uint8
}
