package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCPV6R_IF_CONFIG ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCPV6R_IF_CONFIG struct {
	IC_State          ndr.DWORD
	IC_RelayMode      ndr.DWORD
	IC_MaxHopCount    ndr.DWORD
	IC_MinElapsedTime ndr.DWORD
}
