package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DHCPV6R_MIB_GET_INPUT_DATA ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type DHCPV6R_MIB_GET_INPUT_DATA struct {
	IMGID_TypeID  ndr.DWORD
	IMGID_IfIndex ndr.DWORD
}
