package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FILTER_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type FILTER_INFO struct {
	DwSrcAddr  ndr.DWORD
	DwSrcMask  ndr.DWORD
	DwDstAddr  ndr.DWORD
	DwDstMask  ndr.DWORD
	DwProtocol ndr.DWORD
	FLateBound ndr.DWORD
	WSrcPort   uint16
	WDstPort   uint16
}
