package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FILTER_DESCRIPTOR_V6 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type FILTER_DESCRIPTOR_V6 struct {
	DwVersion       ndr.DWORD
	DwNumFilters    ndr.DWORD
	FaDefaultAction FORWARD_ACTION
	FiFilter        [1]FILTER_INFO_V6
}
