package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// GetDevConfigStruct ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type GetDevConfigStruct struct {
	Retcode    ndr.DWORD
	Devicetype [17]int8
	Size       ndr.DWORD
	Config     [1]uint8
}
