package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// GLOBAL_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type GLOBAL_INFO struct {
	BFilteringOn   ndr.BOOL
	DwLoggingLevel ndr.DWORD
}
