package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IGMP_MIB_GET_INPUT_DATA ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IGMP_MIB_GET_INPUT_DATA struct {
	TypeId        ndr.DWORD
	Flags         uint16
	Signature     uint16
	IfIndex       ndr.DWORD
	RasClientAddr ndr.DWORD
	GroupAddr     ndr.DWORD
	Count         ndr.DWORD
}
