package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IGMP_MIB_GROUP_IFS_LIST ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IGMP_MIB_GROUP_IFS_LIST struct {
	GroupAddr     ndr.DWORD
	NumInterfaces ndr.DWORD
	Buffer        [1]uint8
}
