package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IGMP_MIB_IF_BINDING ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IGMP_MIB_IF_BINDING struct {
	IfIndex   ndr.DWORD
	IfType    ndr.DWORD
	State     ndr.DWORD
	AddrCount ndr.DWORD
}
