package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IGMP_MIB_GROUP_SOURCE_INFO_V3 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IGMP_MIB_GROUP_SOURCE_INFO_V3 struct {
	Source           ndr.DWORD
	SourceExpiryTime ndr.DWORD
	SourceUpTime     ndr.DWORD
	Flags            ndr.DWORD
}
