package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IKEV2_TUNNEL_CONFIG_PARAMS_1 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IKEV2_TUNNEL_CONFIG_PARAMS_1 struct {
	DwIdleTimeout                ndr.DWORD
	DwNetworkBlackoutTime        ndr.DWORD
	DwSaLifeTime                 ndr.DWORD
	DwSaDataSizeForRenegotiation ndr.DWORD
	DwConfigOptions              ndr.DWORD
	DwTotalCertificates          ndr.DWORD
	CertificateNames             []CERT_BLOB_1 `ndr:"unique,size_is=DwTotalCertificates"`
}
