package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IKEV2_PROJECTION_INFO_1 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IKEV2_PROJECTION_INFO_1 struct {
	DwIPv4NegotiationError     ndr.DWORD
	WszAddress                 [16]uint16
	WszRemoteAddress           [16]uint16
	IPv4SubInterfaceIndex      uint64
	DwIPv6NegotiationError     ndr.DWORD
	BInterfaceIdentifier       [8]uint8
	BRemoteInterfaceIdentifier [8]uint8
	BPrefix                    [8]uint8
	DwPrefixLength             ndr.DWORD
	IPv6SubInterfaceIndex      uint64
	DwOptions                  ndr.DWORD
	DwAuthenticationProtocol   ndr.DWORD
	DwEapTypeId                ndr.DWORD
	DwCompressionAlgorithm     ndr.DWORD
	DwEncryptionMethod         ndr.DWORD
}
