package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IKEV2_CONFIG_PARAMS_1 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IKEV2_CONFIG_PARAMS_1 struct {
	DwNumPorts               ndr.DWORD
	DwPortFlags              ndr.DWORD
	DwTunnelConfigParamFlags ndr.DWORD
	TunnelConfigParams       IKEV2_TUNNEL_CONFIG_PARAMS_1
}
