package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IKEV2_TUNNEL_CONFIG_PARAMS_3 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IKEV2_TUNNEL_CONFIG_PARAMS_3 struct {
	DwIdleTimeout                ndr.DWORD
	DwNetworkBlackoutTime        ndr.DWORD
	DwSaLifeTime                 ndr.DWORD
	DwSaDataSizeForRenegotiation ndr.DWORD
	DwConfigOptions              ndr.DWORD
	DwTotalCertificates          ndr.DWORD
	CertificateNames             []CERT_BLOB_1 `ndr:"unique,size_is=DwTotalCertificates"`
	MachineCertificateName       CERT_BLOB_1
	DwEncryptionType             ndr.DWORD
	CustomPolicy                 *ROUTER_CUSTOM_IKEv2_POLICY_0 `ndr:"unique"`
	DwTotalEkus                  ndr.DWORD
	CertificateEKUs              []CERT_EKU_1 `ndr:"unique,size_is=DwTotalEkus"`
	MachineCertificateHash       CERT_BLOB_1
}
