package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IP_AUTO_DHCP_STATISTICS ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IP_AUTO_DHCP_STATISTICS struct {
	MessagesIgnored   ndr.DWORD
	BootpOffersSent   ndr.DWORD
	DiscoversReceived ndr.DWORD
	InformsReceived   ndr.DWORD
	OffersSent        ndr.DWORD
	RequestsReceived  ndr.DWORD
	AcksSent          ndr.DWORD
	NaksSent          ndr.DWORD
	DeclinesReceived  ndr.DWORD
	ReleasesReceived  ndr.DWORD
}
