package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IP_DNS_PROXY_MIB_QUERY ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IP_DNS_PROXY_MIB_QUERY struct {
	Oid ndr.DWORD
	// Index overlays the UCHAR Data arm (C union).
	Index ndr.DWORD
}
