package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IP_DNS_PROXY_INTERFACE_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IP_DNS_PROXY_INTERFACE_INFO struct {
	Flags ndr.DWORD
}
