package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IP_NAT_INTERFACE_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IP_NAT_INTERFACE_INFO struct {
	Index  ndr.DWORD
	Flags  ndr.DWORD
	Header RTR_INFO_BLOCK_HEADER
}
