package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IP_NAT_ADDRESS_RANGE ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IP_NAT_ADDRESS_RANGE struct {
	StartAddress ndr.DWORD
	EndAddress   ndr.DWORD
	SubnetMask   ndr.DWORD
}
