package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IP_NAT_INTERFACE_STATISTICS ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IP_NAT_INTERFACE_STATISTICS struct {
	TotalMappings   ndr.DWORD
	InboundMappings ndr.DWORD
	BytesForward    uint64
	BytesReverse    uint64
	PacketsForward  uint64
	PacketsReverse  uint64
	RejectsForward  uint64
	RejectsReverse  uint64
}
