package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPBOOTP_IP_ADDRESS ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPBOOTP_IP_ADDRESS struct {
	IA_Address ndr.DWORD
	IA_Netmask ndr.DWORD
}
