package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPBOOTP_IF_BINDING ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPBOOTP_IF_BINDING struct {
	IB_State     ndr.DWORD
	IB_AddrCount ndr.DWORD
}
