package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPINIP_CONFIG_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPINIP_CONFIG_INFO struct {
	DwRemoteAddress ndr.DWORD
	DwLocalAddress  ndr.DWORD
	ByTtl           uint8
}
