package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPRIP_MIB_GET_INPUT_DATA ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPRIP_MIB_GET_INPUT_DATA struct {
	IMGID_TypeID ndr.DWORD
	// IMGID overlays IMGID_IfIndex / IMGID_PeerAddress (C union).
	IMGID ndr.DWORD
}
