package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPRIP_MIB_GET_OUTPUT_DATA ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPRIP_MIB_GET_OUTPUT_DATA struct {
	IMGOD_TypeID ndr.DWORD
	// IMGOD overlays IMGOD_IfIndex / IMGOD_PeerAddress (C union).
	IMGOD        ndr.DWORD
	IMGOD_Buffer [1]uint8
}
