package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPRIP_PEER_STATS ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPRIP_PEER_STATS struct {
	PS_LastPeerRouteTag           ndr.DWORD
	PS_LastPeerUpdateTickCount    ndr.DWORD
	PS_LastPeerUpdateVersion      ndr.DWORD
	PS_BadResponsePacketsFromPeer ndr.DWORD
	PS_BadResponseEntriesFromPeer ndr.DWORD
}
