package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPRIP_ROUTE_FILTER ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPRIP_ROUTE_FILTER struct {
	RF_LoAddress ndr.DWORD
	RF_HiAddress ndr.DWORD
}
