package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPRIP_GLOBAL_CONFIG ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPRIP_GLOBAL_CONFIG struct {
	GC_LoggingLevel               ndr.DWORD
	GC_MaxRecvQueueSize           ndr.DWORD
	GC_MaxSendQueueSize           ndr.DWORD
	GC_MinTriggeredUpdateInterval ndr.DWORD
	GC_PeerFilterMode             ndr.DWORD
	GC_PeerFilterCount            ndr.DWORD
}
