package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPX_TRAFFIC_FILTER_GLOBAL_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPX_TRAFFIC_FILTER_GLOBAL_INFO struct {
	FilterAction ndr.DWORD
}
