package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPX_SERVICE ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPX_SERVICE struct {
	InterfaceIndex ndr.DWORD
	Protocol       ndr.DWORD
	Server         IPX_SERVER_ENTRY
}
