package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPX_ROUTE ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPX_ROUTE struct {
	InterfaceIndex    ndr.DWORD
	Protocol          ndr.DWORD
	Network           [4]uint8
	TickCount         uint16
	HopCount          uint16
	NextHopMacAddress [6]uint8
	Flags             ndr.DWORD
}
