package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPX_MIB_GET_INPUT_DATA ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPX_MIB_GET_INPUT_DATA struct {
	TableId  ndr.DWORD
	MibIndex IPX_MIB_INDEX
}
