package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPX_INTERFACE ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPX_INTERFACE struct {
	InterfaceIndex          ndr.DWORD
	AdministratorState      ndr.DWORD
	AdapterIndex            ndr.DWORD
	InterfaceName           [48]uint8
	InterfaceType           ndr.DWORD
	MediaType               ndr.DWORD
	NetNumber               [4]uint8
	MacAddress              [6]uint8
	Delay                   ndr.DWORD
	Throughput              ndr.DWORD
	NetbiosAccept           ndr.DWORD
	NetbiosDeliver          ndr.DWORD
	EnableIpxWanNegotiation ndr.DWORD
	IfStats                 IPX_IF_STATS
}
