package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPX_STATIC_NETBIOS_NAME_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPX_STATIC_NETBIOS_NAME_INFO struct {
	Field IPX_STATIC_NETBIOS_NAME_INFO_Field
}

// IPX_STATIC_NETBIOS_NAME_INFO_Field is a discriminated union ([MS-RRASM]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type IPX_STATIC_NETBIOS_NAME_INFO_Field struct {
	Tag        ndr.DWORD `ndr:"switch"`
	DwordAlign ndr.DWORD `ndr:"case=TODO"`
	Name       uint8     `ndr:"case=TODO"`
}
