package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPX_IF_STATS ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPX_IF_STATS struct {
	IfOperState     ndr.DWORD
	MaxPacketSize   ndr.DWORD
	InHdrErrors     ndr.DWORD
	InFiltered      ndr.DWORD
	InNoRoutes      ndr.DWORD
	InDiscards      ndr.DWORD
	InDelivers      ndr.DWORD
	OutFiltered     ndr.DWORD
	OutDiscards     ndr.DWORD
	OutDelivers     ndr.DWORD
	NetbiosReceived ndr.DWORD
	NetbiosSent     ndr.DWORD
}
