package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IPXMIB_BASE ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type IPXMIB_BASE struct {
	OperState        ndr.DWORD
	PrimaryNetNumber [4]uint8
	Node             [6]uint8
	SysName          [48]uint8
	MaxPathSplits    ndr.DWORD
	IfCount          ndr.DWORD
	DestCount        ndr.DWORD
	ServCount        ndr.DWORD
}
