package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MCAST_HBEAT_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MCAST_HBEAT_INFO struct {
	PwszGroup      [64]uint16
	BActive        ndr.BOOL
	UlDeadInterval ndr.DWORD
	ByProtocol     uint8
	WPort          uint16
}
