package msrrasm

// MIB_TCP_STATE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-RRASM]).
type MIB_TCP_STATE uint16

const (
	MIB_TCP_STATE_CLOSED     MIB_TCP_STATE = 1
	MIB_TCP_STATE_LISTEN     MIB_TCP_STATE = 2
	MIB_TCP_STATE_SYN_SENT   MIB_TCP_STATE = 3
	MIB_TCP_STATE_SYN_RCVD   MIB_TCP_STATE = 4
	MIB_TCP_STATE_ESTAB      MIB_TCP_STATE = 5
	MIB_TCP_STATE_FIN_WAIT1  MIB_TCP_STATE = 6
	MIB_TCP_STATE_FIN_WAIT2  MIB_TCP_STATE = 7
	MIB_TCP_STATE_CLOSE_WAIT MIB_TCP_STATE = 8
	MIB_TCP_STATE_CLOSING    MIB_TCP_STATE = 9
	MIB_TCP_STATE_LAST_ACK   MIB_TCP_STATE = 10
	MIB_TCP_STATE_TIME_WAIT  MIB_TCP_STATE = 11
	MIB_TCP_STATE_DELETE_TCB MIB_TCP_STATE = 12
)
