package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MIB_IFNUMBER ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MIB_IFNUMBER struct {
	DwValue ndr.DWORD
}
