package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MIB_PROXYARP ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MIB_PROXYARP struct {
	DwAddress ndr.DWORD
	DwMask    ndr.DWORD
	DwIfIndex ndr.DWORD
}
