package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MIB_IPFORWARDNUMBER ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MIB_IPFORWARDNUMBER struct {
	DwValue ndr.DWORD
}
