package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MIB_IPNETROW ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MIB_IPNETROW struct {
	DwIndex       ndr.DWORD
	DwPhysAddrLen ndr.DWORD
	BPhysAddr     [8]uint8
	DwAddr        ndr.DWORD
	DwType        ndr.DWORD
}
