package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MIB_BEST_IF ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MIB_BEST_IF struct {
	DwDestAddr ndr.DWORD
	DwIfIndex  ndr.DWORD
}
