package msrrasm

// MIB_IPFORWARD_PROTO is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-RRASM]).
type MIB_IPFORWARD_PROTO uint16

const (
	MIB_IPPROTO_OTHER             MIB_IPFORWARD_PROTO = 1
	MIB_IPPROTO_LOCAL             MIB_IPFORWARD_PROTO = 2
	MIB_IPPROTO_NETMGMT           MIB_IPFORWARD_PROTO = 3
	MIB_IPPROTO_ICMP              MIB_IPFORWARD_PROTO = 4
	MIB_IPPROTO_EGP               MIB_IPFORWARD_PROTO = 5
	MIB_IPPROTO_GGP               MIB_IPFORWARD_PROTO = 6
	MIB_IPPROTO_HELLO             MIB_IPFORWARD_PROTO = 7
	MIB_IPPROTO_RIP               MIB_IPFORWARD_PROTO = 8
	MIB_IPPROTO_IS_IS             MIB_IPFORWARD_PROTO = 9
	MIB_IPPROTO_ES_IS             MIB_IPFORWARD_PROTO = 10
	MIB_IPPROTO_CISCO             MIB_IPFORWARD_PROTO = 11
	MIB_IPPROTO_BBN               MIB_IPFORWARD_PROTO = 12
	MIB_IPPROTO_OSPF              MIB_IPFORWARD_PROTO = 13
	MIB_IPPROTO_BGP               MIB_IPFORWARD_PROTO = 14
	MIB_IPPROTO_NT_AUTOSTATIC     MIB_IPFORWARD_PROTO = 10002
	MIB_IPPROTO_NT_STATIC         MIB_IPFORWARD_PROTO = 10006
	MIB_IPPROTO_NT_STATIC_NON_DOD MIB_IPFORWARD_PROTO = 10007
)
