package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MIB_IPDESTROW ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MIB_IPDESTROW struct {
	ForwardRow          MIB_IPFORWARDROW
	DwForwardPreference ndr.DWORD
	DwForwardViewSet    ndr.DWORD
}
