package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MIB_IPMCAST_IF_TABLE ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MIB_IPMCAST_IF_TABLE struct {
	DwNumEntries ndr.DWORD
	Table        [1]MIB_IPMCAST_IF_ENTRY
}
