package msrrasm

// MIB_IPFORWARD_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-RRASM]).
type MIB_IPFORWARD_TYPE uint16

const (
	MIB_IPROUTE_TYPE_OTHER    MIB_IPFORWARD_TYPE = 1
	MIB_IPROUTE_TYPE_INVALID  MIB_IPFORWARD_TYPE = 2
	MIB_IPROUTE_TYPE_DIRECT   MIB_IPFORWARD_TYPE = 3
	MIB_IPROUTE_TYPE_INDIRECT MIB_IPFORWARD_TYPE = 4
)
