package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MPR_SERVER_1 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MPR_SERVER_1 struct {
	DwNumPptpPorts  ndr.DWORD
	DwPptpPortFlags ndr.DWORD
	DwNumL2tpPorts  ndr.DWORD
	DwL2tpPortFlags ndr.DWORD
}
