package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MPR_DEVICE_1 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MPR_DEVICE_1 struct {
	SzDeviceType       [17]uint16
	SzDeviceName       [129]uint16
	SzLocalPhoneNumber [129]uint16
	SzAlternates       *ndr.WSTR `ndr:"unique"`
}
