package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MPR_IF_CUSTOMINFOEX_0 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MPR_IF_CUSTOMINFOEX_0 struct {
	Header            MPRAPI_OBJECT_HEADER_IDL
	DwFlags           ndr.DWORD
	CustomIkev2Config ROUTER_IKEv2_IF_CUSTOM_CONFIG_0
}
