package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MPR_SERVER_0 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MPR_SERVER_0 struct {
	FLanOnlyMode ndr.BOOL
	DwUpTime     ndr.DWORD
	DwTotalPorts ndr.DWORD
	DwPortsInUse ndr.DWORD
}
