package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// MPR_FILTER_0 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MPR_FILTER_0 struct {
	FEnable ndr.BOOL
}
