package msrrasm

// MPRAPI_OBJECT_HEADER_IDL ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MPRAPI_OBJECT_HEADER_IDL struct {
	Revision uint8
	Type     uint8
	Size     uint16
}
