package msrrasm

// MPRAPI_TUNNEL_CONFIG_PARAMS_3 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MPRAPI_TUNNEL_CONFIG_PARAMS_3 struct {
	IkeConfigParams  IKEV2_CONFIG_PARAMS_3
	PptpConfigParams PPTP_CONFIG_PARAMS_1
	L2tpConfigParams L2TP_CONFIG_PARAMS_2
	SstpConfigParams SSTP_CONFIG_PARAMS_1
}
