package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// MPRI_INTERFACE_3 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type MPRI_INTERFACE_3 struct {
	WszInterfaceName           [257]uint16
	DwInterface                ndr.DWORD
	FEnabled                   ndr.BOOL
	DwIfType                   ROUTER_INTERFACE_TYPE
	DwConnectionState          ROUTER_CONNECTION_STATE
	FUnReachabilityReasons     ndr.DWORD
	DwLastError                ndr.DWORD
	DwfOptions                 ndr.DWORD
	SzLocalPhoneNumber         [129]uint16
	SzAlternates               *ndr.WSTR `ndr:"unique"`
	Ipaddr                     ndr.DWORD
	IpaddrDns                  ndr.DWORD
	IpaddrDnsAlt               ndr.DWORD
	IpaddrWins                 ndr.DWORD
	IpaddrWinsAlt              ndr.DWORD
	DwfNetProtocols            ndr.DWORD
	SzDeviceType               [17]uint16
	SzDeviceName               [129]uint16
	SzX25PadType               [33]uint16
	SzX25Address               [201]uint16
	SzX25Facilities            [201]uint16
	SzX25UserData              [201]uint16
	DwChannels                 ndr.DWORD
	DwSubEntries               ndr.DWORD
	DwDialMode                 ndr.DWORD
	DwDialExtraPercent         ndr.DWORD
	DwDialExtraSampleSeconds   ndr.DWORD
	DwHangUpExtraPercent       ndr.DWORD
	DwHangUpExtraSampleSeconds ndr.DWORD
	DwIdleDisconnectSeconds    ndr.DWORD
	DwType                     ndr.DWORD
	DwEncryptionType           ndr.DWORD
	DwCustomAuthKey            ndr.DWORD
	DwCustomAuthDataSize       ndr.DWORD
	LpbCustomAuthData          *uint8 `ndr:"unique"`
	GuidId                     guid.GUID
	DwVpnStrategy              ndr.DWORD
	AddressCount               ndr.DWORD
	Ipv6addrDns                IN6_ADDR
	Ipv6addrDnsAlt             IN6_ADDR
	Ipv6addr                   *IN6_ADDR `ndr:"unique"`
}
