package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// OSPF_ROUTE_FILTER_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type OSPF_ROUTE_FILTER_INFO struct {
	Type             ndr.DWORD
	OfaActionOnMatch OSPF_FILTER_ACTION
	DwNumFilters     ndr.DWORD
	PFilters         [1]OSPF_ROUTE_FILTER
}
