package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// OSPF_GLOBAL_PARAM ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type OSPF_GLOBAL_PARAM struct {
	Type      ndr.DWORD
	Create    ndr.DWORD
	Enable    ndr.DWORD
	RouterId  ndr.DWORD
	ASBrdrRtr ndr.DWORD
	LogLevel  ndr.DWORD
}
