package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// OSPF_INTERFACE_PARAM ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type OSPF_INTERFACE_PARAM struct {
	Type            ndr.DWORD
	Create          ndr.DWORD
	Enable          ndr.DWORD
	IntfIpAddr      ndr.DWORD
	IntfSubnetMask  ndr.DWORD
	AreaId          ndr.DWORD
	IntfType        ndr.DWORD
	RouterPriority  ndr.DWORD
	TransitDelay    ndr.DWORD
	RetransInterval ndr.DWORD
	HelloInterval   ndr.DWORD
	DeadInterval    ndr.DWORD
	PollInterval    ndr.DWORD
	MetricCost      ndr.DWORD
	Password        [8]uint8
	MtuSize         ndr.DWORD
}
