package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// PPP_PROJECTION_INFO_1 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type PPP_PROJECTION_INFO_1 struct {
	DwIPv4NegotiationError         ndr.DWORD
	WszAddress                     [16]uint16
	WszRemoteAddress               [16]uint16
	DwIPv4Options                  ndr.DWORD
	DwIPv4RemoteOptions            ndr.DWORD
	IPv4SubInterfaceIndex          uint64
	DwIPv6NegotiationError         ndr.DWORD
	BInterfaceIdentifier           [8]uint8
	BRemoteInterfaceIdentifier     [8]uint8
	BPrefix                        [8]uint8
	DwPrefixLength                 ndr.DWORD
	IPv6SubInterfaceIndex          uint64
	DwLcpError                     ndr.DWORD
	DwAuthenticationProtocol       ndr.DWORD
	DwAuthenticationData           ndr.DWORD
	DwRemoteAuthenticationProtocol ndr.DWORD
	DwRemoteAuthenticationData     ndr.DWORD
	DwLcpTerminateReason           ndr.DWORD
	DwLcpRemoteTerminateReason     ndr.DWORD
	DwLcpOptions                   ndr.DWORD
	DwLcpRemoteOptions             ndr.DWORD
	DwEapTypeId                    ndr.DWORD
	DwRemoteEapTypeId              ndr.DWORD
	DwCcpError                     ndr.DWORD
	DwCompressionAlgorithm         ndr.DWORD
	DwCcpOptions                   ndr.DWORD
	DwRemoteCompressionAlgorithm   ndr.DWORD
	DwCcpRemoteOptions             ndr.DWORD
}
