package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// PPP_IPXCP_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type PPP_IPXCP_INFO struct {
	DwError    ndr.DWORD
	WszAddress [16]uint16
}
