package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// PPP_LCP_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type PPP_LCP_INFO struct {
	DwError                        ndr.DWORD
	DwAuthenticationProtocol       ndr.DWORD
	DwAuthenticationData           ndr.DWORD
	DwRemoteAuthenticationProtocol ndr.DWORD
	DwRemoteAuthenticationData     ndr.DWORD
	DwTerminateReason              ndr.DWORD
	DwRemoteTerminateReason        ndr.DWORD
	DwOptions                      ndr.DWORD
	DwRemoteOptions                ndr.DWORD
	DwEapTypeId                    ndr.DWORD
	DwRemoteEapTypeId              ndr.DWORD
}
