package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// PPP_ATCP_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type PPP_ATCP_INFO struct {
	DwError    ndr.DWORD
	WszAddress [33]uint16
}
