package msrrasm

// PROJECTION_INFO_IDL_1 is a discriminated union ([MS-RRASM]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type PROJECTION_INFO_IDL_1 struct {
	Tag                 uint8                   `ndr:"switch"`
	PppProjectionInfo   PPP_PROJECTION_INFO_1   `ndr:"case=1"`
	Ikev2ProjectionInfo IKEV2_PROJECTION_INFO_1 `ndr:"case=2"`
}
