package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// PROTOCOL_METRIC_EX ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type PROTOCOL_METRIC_EX struct {
	DwProtocolId    ndr.DWORD
	DwSubProtocolId ndr.DWORD
	DwMetric        ndr.DWORD
}
