package msrrasm

// RAS_QUARANTINE_STATE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-RRASM]).
type RAS_QUARANTINE_STATE uint16

const (
	RAS_QUAR_STATE_NORMAL     RAS_QUARANTINE_STATE = 0
	RAS_QUAR_STATE_QUARANTINE RAS_QUARANTINE_STATE = 1
	RAS_QUAR_STATE_PROBATION  RAS_QUARANTINE_STATE = 2
	RAS_QUAR_STATE_UNKNOWN    RAS_QUARANTINE_STATE = 3
)
