package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RAS_UPDATE_CONNECTION_1_IDL ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RAS_UPDATE_CONNECTION_1_IDL struct {
	Header                   MPRAPI_OBJECT_HEADER_IDL
	DwIfIndex                ndr.DWORD
	WszRemoteEndpointAddress [65]uint16
}
