package msrrasm

// RAS_HARDWARE_CONDITION is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-RRASM]).
type RAS_HARDWARE_CONDITION uint16

const (
	RAS_HARDWARE_OPERATIONAL RAS_HARDWARE_CONDITION = 0
	RAS_HARDWARE_FAILURE     RAS_HARDWARE_CONDITION = 1
)
