package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RAS_CALLEDID_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RAS_CALLEDID_INFO struct {
	DwSize    ndr.DWORD
	BCalledId [1]uint8
}
