package msrrasm

// RAS_PORT_CONDITION is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-RRASM]).
type RAS_PORT_CONDITION uint16

const (
	RAS_PORT_NON_OPERATIONAL RAS_PORT_CONDITION = 0
	RAS_PORT_DISCONNECTED    RAS_PORT_CONDITION = 1
	RAS_PORT_CALLING_BACK    RAS_PORT_CONDITION = 2
	RAS_PORT_LISTENING       RAS_PORT_CONDITION = 3
	RAS_PORT_AUTHENTICATING  RAS_PORT_CONDITION = 4
	RAS_PORT_AUTHENTICATED   RAS_PORT_CONDITION = 5
	RAS_PORT_INITIALIZING    RAS_PORT_CONDITION = 6
)
