package msrrasm

// RAS_CONNECTION_EX_IDL is a discriminated union ([MS-RRASM]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type RAS_CONNECTION_EX_IDL struct {
	Tag            uint8                   `ndr:"switch"`
	RasConnection1 RAS_CONNECTION_EX_1_IDL `ndr:"case=1"`
}
