package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RASI_CONNECTION_1 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RASI_CONNECTION_1 struct {
	DwConnection          ndr.DWORD
	DwInterface           ndr.DWORD
	PppInfo               PPP_INFO
	DwBytesXmited         ndr.DWORD
	DwBytesRcved          ndr.DWORD
	DwFramesXmited        ndr.DWORD
	DwFramesRcved         ndr.DWORD
	DwCrcErr              ndr.DWORD
	DwTimeoutErr          ndr.DWORD
	DwAlignmentErr        ndr.DWORD
	DwHardwareOverrunErr  ndr.DWORD
	DwFramingErr          ndr.DWORD
	DwBufferOverrunErr    ndr.DWORD
	DwCompressionRatioIn  ndr.DWORD
	DwCompressionRatioOut ndr.DWORD
}
