package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RASI_CONNECTION_0 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RASI_CONNECTION_0 struct {
	DwConnection      ndr.DWORD
	DwInterface       ndr.DWORD
	DwConnectDuration ndr.DWORD
	DwInterfaceType   ROUTER_INTERFACE_TYPE
	DwConnectionFlags ndr.DWORD
	WszInterfaceName  [257]uint16
	WszUserName       [257]uint16
	WszLogonDomain    [16]uint16
	WszRemoteComputer [17]uint16
}
