package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// RASMAN_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RASMAN_INFO struct {
	RI_PortStatus           RASMAN_STATUS
	RI_ConnState            RASMAN_STATE
	RI_LinkSpeed            ndr.DWORD
	RI_LastError            ndr.DWORD
	RI_CurrentUsage         RASMAN_USAGE
	RI_DeviceTypeConnecting [16]int8
	RI_DeviceConnecting     [129]int8
	RI_szDeviceType         [16]int8
	RI_szDeviceName         [129]int8
	RI_szPortName           [17]int8
	RI_DisconnectType       RASMAN_DISCONNECT_TYPE
	RI_OwnershipFlag        ndr.DWORD
	RI_ConnectDuration      ndr.DWORD
	RI_BytesReceived        ndr.DWORD
	RI_Phonebook            [261]int8
	RI_PhoneEntry           [257]int8
	RI_ConnectionHandle     HANDLE
	RI_SubEntry             ndr.DWORD
	RI_rdtDeviceType        RASDEVICETYPE
	RI_GuidEntry            guid.GUID
	RI_dwSessionId          ndr.DWORD
	RI_dwFlags              ndr.DWORD
	RI_CorrelationGuid      guid.GUID
}
