package msrrasm

// RASMAN_DISCONNECT_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-RRASM]).
type RASMAN_DISCONNECT_TYPE uint16

const (
	USER_REQUESTED       RASMAN_DISCONNECT_TYPE = 0
	REMOTE_DISCONNECTION RASMAN_DISCONNECT_TYPE = 1
	HARDWARE_FAILURE     RASMAN_DISCONNECT_TYPE = 2
	NOT_DISCONNECTED     RASMAN_DISCONNECT_TYPE = 3
)
