package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RASRPC_PBUSER ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RASRPC_PBUSER struct {
	FOperatorDial             ndr.BOOL
	FPreviewPhoneNumber       ndr.BOOL
	FUseLocation              ndr.BOOL
	FShowLights               ndr.BOOL
	FShowConnectStatus        ndr.BOOL
	FCloseOnDial              ndr.BOOL
	FAllowLogonPhonebookEdits ndr.BOOL
	FAllowLogonLocationEdits  ndr.BOOL
	FSkipConnectComplete      ndr.BOOL
	FNewEntryWizard           ndr.BOOL
	DwRedialAttempts          ndr.DWORD
	DwRedialSeconds           ndr.DWORD
	DwIdleDisconnectSeconds   ndr.DWORD
	FRedialOnLinkFailure      ndr.BOOL
	FPopupOnTopWhenRedialing  ndr.BOOL
	FExpandAutoDialQuery      ndr.BOOL
	DwCallbackMode            ndr.DWORD
	PCallbacks                *RASRPC_CALLBACKLIST `ndr:"unique"`
	PszLastCallbackByCaller   [129]uint16
	DwPhonebookMode           ndr.DWORD
	PszPersonalFile           [260]uint16
	PszAlternatePath          [260]uint16
	PPhonebooks               *RASRPC_STRINGLIST `ndr:"unique"`
	PAreaCodes                *RASRPC_STRINGLIST `ndr:"unique"`
	FUseAreaAndCountry        ndr.BOOL
	PPrefixes                 *RASRPC_STRINGLIST   `ndr:"unique"`
	PSuffixes                 *RASRPC_STRINGLIST   `ndr:"unique"`
	PLocations                *RASRPC_LOCATIONLIST `ndr:"unique"`
	DwXPhonebook              ndr.DWORD
	DwYPhonebook              ndr.DWORD
	PszDefaultEntry           [257]uint16
	FInitialized              ndr.BOOL
	FDirty                    ndr.BOOL
}
