package msrrasm

// RASRPC_STRINGLIST ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RASRPC_STRINGLIST struct {
	Psz   [256]uint16
	PNext *RASRPC_STRINGLIST `ndr:"unique"`
}
