package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RASRPC_CALLBACKLIST ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RASRPC_CALLBACKLIST struct {
	PszPortName   [17]uint16
	PszDeviceName [129]uint16
	PszNumber     [129]uint16
	DwDeviceType  ndr.DWORD
	PNext         *RASRPC_CALLBACKLIST `ndr:"unique"`
}
