package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RequestBuffer ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RequestBuffer struct {
	RB_PCBIndex ndr.DWORD
	RB_Reqtype  ReqTypes
	RB_Dummy    ndr.DWORD
	RB_Done     ndr.DWORD
	Alignment   int64
	RB_Buffer   [1]uint8
}
