package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RIP_INTERFACE ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RIP_INTERFACE struct {
	InterfaceIndex ndr.DWORD
	RipIfInfo      RIP_IF_INFO
	RipIfStats     RIP_IF_STATS
}
