package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RIP_IF_FILTERS ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RIP_IF_FILTERS struct {
	SupplyFilterAction ndr.DWORD
	SupplyFilterCount  ndr.DWORD
	ListenFilterAction ndr.DWORD
	ListenFilterCount  ndr.DWORD
	RouteFilter        [1]RIP_ROUTE_FILTER_INFO
}
