package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RIP_MIB_SET_INPUT_DATA ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RIP_MIB_SET_INPUT_DATA struct {
	TableId      ndr.DWORD
	RipInterface RIP_INTERFACE
}
