package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RIP_IF_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RIP_IF_INFO struct {
	AdminState             ndr.DWORD
	UpdateMode             ndr.DWORD
	PacketType             ndr.DWORD
	Supply                 ndr.DWORD
	Listen                 ndr.DWORD
	PeriodicUpdateInterval ndr.DWORD
	AgeIntervalMultiplier  ndr.DWORD
}
