package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RIP_IF_STATS ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RIP_IF_STATS struct {
	RipIfOperState     ndr.DWORD
	RipIfInputPackets  ndr.DWORD
	RipIfOutputPackets ndr.DWORD
}
