package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// ROUTER_CUSTOM_IKEv2_POLICY_0 ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type ROUTER_CUSTOM_IKEv2_POLICY_0 struct {
	DwIntegrityMethod         ndr.DWORD
	DwEncryptionMethod        ndr.DWORD
	DwCipherTransformConstant ndr.DWORD
	DwAuthTransformConstant   ndr.DWORD
	DwPfsGroup                ndr.DWORD
	DwDhGroup                 ndr.DWORD
}

// ROUTER_CUSTOM_L2TP_POLICY_0 is an alias for ROUTER_CUSTOM_IKEv2_POLICY_0 (same IDL typedef).
type ROUTER_CUSTOM_L2TP_POLICY_0 = ROUTER_CUSTOM_IKEv2_POLICY_0
