package msrrasm

// ROUTER_CONNECTION_STATE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-RRASM]).
type ROUTER_CONNECTION_STATE uint16

const (
	ROUTER_IF_STATE_UNREACHABLE  ROUTER_CONNECTION_STATE = 0
	ROUTER_IF_STATE_DISCONNECTED ROUTER_CONNECTION_STATE = 1
	ROUTER_IF_STATE_CONNECTING   ROUTER_CONNECTION_STATE = 2
	ROUTER_IF_STATE_CONNECTED    ROUTER_CONNECTION_STATE = 3
)
