package msrrasm

// ROUTER_INTERFACE_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-RRASM]).
type ROUTER_INTERFACE_TYPE uint16

const (
	ROUTER_IF_TYPE_CLIENT      ROUTER_INTERFACE_TYPE = 0
	ROUTER_IF_TYPE_HOME_ROUTER ROUTER_INTERFACE_TYPE = 1
	ROUTER_IF_TYPE_FULL_ROUTER ROUTER_INTERFACE_TYPE = 2
	ROUTER_IF_TYPE_DEDICATED   ROUTER_INTERFACE_TYPE = 3
	ROUTER_IF_TYPE_INTERNAL    ROUTER_INTERFACE_TYPE = 4
	ROUTER_IF_TYPE_LOOPBACK    ROUTER_INTERFACE_TYPE = 5
	ROUTER_IF_TYPE_TUNNEL1     ROUTER_INTERFACE_TYPE = 6
	ROUTER_IF_TYPE_DIALOUT     ROUTER_INTERFACE_TYPE = 7
)
