package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RTR_TOC_ENTRY ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RTR_TOC_ENTRY struct {
	InfoType ndr.DWORD
	InfoSize ndr.DWORD
	Count    ndr.DWORD
	Offset   ndr.DWORD
}
