package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RTR_DISC_INFO ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type RTR_DISC_INFO struct {
	WMaxAdvtInterval uint16
	WMinAdvtInterval uint16
	WAdvtLifetime    uint16
	BAdvertise       ndr.BOOL
	LPrefLevel       int32
}
