package msrrasm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SAP_MIB_SET_INPUT_DATA ([MS-RRASM]). Generated by tools/idlgen; verify pointer/array tags.
type SAP_MIB_SET_INPUT_DATA struct {
	TableId      ndr.DWORD
	SapInterface SAP_INTERFACE
}
