// Package rpcinterface_894de0c00d5511d3a32200c04fa321a1_1_0 is the descriptor for the InitShutdown RPC interface, abstract
// syntax 894de0c0-0d55-11d3-a322-00c04fa321a1 version 1.0 ([MS-RSP]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName and the doc comments are not derivable from the IDL and must be
// confirmed by hand (see the TODO markers).
package rpcinterface_894de0c00d5511d3a32200c04fa321a1_1_0

// IDL source: [MS-RSP] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rsp/012b9c19-5a6f-4d4f-8dd1-a344123a3337
// A fetched copy is kept at ms-rsp.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the InitShutdown interface. Per
// [MS-RSP] section 2.1 the interface has the well-known endpoint \PIPE\InitShutdown
// over named pipes (ncacn_np).
const PipeName = `\InitShutdown`

// Opnums for the on-the-wire methods.
const (
	OpnumBaseInitiateShutdown   uint16 = 0
	OpnumBaseAbortShutdown      uint16 = 1
	OpnumBaseInitiateShutdownEx uint16 = 2
)

// The Win32 error codes the shutdown methods return ([MS-RSP] section 3.2.4,
// [MS-ERREF] 2.2: 0 on success, nonzero on failure) are not declared here. The whole
// of [MS-ERREF] 2.2 lives in
// github.com/TheManticoreProject/Manticore/windows/errors/win32 as the WIN32_ERROR
// type, and a subset repeated here would cover a fraction of that 2703-code table,
// render everything outside itself as an undecoded number, and drift from the
// specification as the table is regenerated. Convert a returned status with
// win32.WIN32_ERROR(status) and compare against win32.ERROR_SUCCESS and the rest.

// SyntaxID returns the InitShutdown abstract syntax identifier:
// 894de0c0-0d55-11d3-a322-00c04fa321a1, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x894de0c0, B: 0x0d55, C: 0x11d3, D: 0xa322, E: 0x00c04fa321a1},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumBaseInitiateShutdown:   "BaseInitiateShutdown",
	OpnumBaseAbortShutdown:      "BaseAbortShutdown",
	OpnumBaseInitiateShutdownEx: "BaseInitiateShutdownEx",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
