// Package rpcinterface_bde95fdfeee045de9e12e5a61cd0d4fe_1_0 is the descriptor for the RCMPublic RPC interface, abstract
// syntax bde95fdf-eee0-45de-9e12-e5a61cd0d4fe version 1.0 ([MS-TSTS]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName (from [MS-TSTS] 1.9) is not derivable from the IDL and was
// completed by hand.
package rpcinterface_bde95fdfeee045de9e12e5a61cd0d4fe_1_0

// IDL source: [MS-TSTS] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tsts/c43addc7-eebc-491b-9b01-2587262675e8
// A fetched copy is kept at ms-tsts.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the RCMPublic interface.
// The endpoint is assigned in [MS-TSTS] section 1.9 (Standards Assignments).
const PipeName = `\TermSrv_API_service`

// Opnums for the on-the-wire methods. Opnums 5, 6, 7 are "not used on the wire"
// and are omitted.
const (
	OpnumRpcGetClientData                   uint16 = 0
	OpnumRpcGetConfigData                   uint16 = 1
	OpnumRpcGetProtocolStatus               uint16 = 2
	OpnumRpcGetLastInputTime                uint16 = 3
	OpnumRpcGetRemoteAddress                uint16 = 4
	OpnumRpcGetAllListeners                 uint16 = 8
	OpnumRpcGetSessionProtocolLastInputTime uint16 = 9
	OpnumRpcGetUserCertificates             uint16 = 10
	OpnumRpcQuerySessionData                uint16 = 11
)

// The HRESULT values RCMPublic methods return ([MS-ERREF] 2.1) are not declared here.
// The whole of [MS-ERREF] 2.1.1 lives in
// github.com/TheManticoreProject/Manticore/windows/errors/hresult as the HRESULT type,
// and a subset repeated here would cover six of that 2928-value table while drifting
// from it. Convert a returned status with hresult.HRESULT(status) and compare against
// hresult.S_OK and the rest. Success is a range rather than a single value: every value
// with bit 31 clear succeeds, which is what hresult.HRESULT.IsSuccess reports.

// SyntaxID returns the RCMPublic abstract syntax identifier:
// bde95fdf-eee0-45de-9e12-e5a61cd0d4fe, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0xbde95fdf, B: 0xeee0, C: 0x45de, D: 0x9e12, E: 0xe5a61cd0d4fe},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumRpcGetClientData:                   "RpcGetClientData",
	OpnumRpcGetConfigData:                   "RpcGetConfigData",
	OpnumRpcGetProtocolStatus:               "RpcGetProtocolStatus",
	OpnumRpcGetLastInputTime:                "RpcGetLastInputTime",
	OpnumRpcGetRemoteAddress:                "RpcGetRemoteAddress",
	OpnumRpcGetAllListeners:                 "RpcGetAllListeners",
	OpnumRpcGetSessionProtocolLastInputTime: "RpcGetSessionProtocolLastInputTime",
	OpnumRpcGetUserCertificates:             "RpcGetUserCertificates",
	OpnumRpcQuerySessionData:                "RpcQuerySessionData",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
