// Package rpcinterface_da5a86c512c24943ab307f74a813d853_1_0 is the descriptor for the PerflibV2 RPC interface, abstract
// syntax da5a86c5-12c2-4943-ab30-7f74a813d853 version 1.0 ([MS-PCQ]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName and the doc comments are not derivable from the IDL and must be
// confirmed by hand (see the TODO markers).
package rpcinterface_da5a86c512c24943ab307f74a813d853_1_0

// IDL source: [MS-PCQ] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-pcq/dcee10e3-0512-495e-9566-26e56cc21c5c
// A fetched copy is kept at ms-pcq.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the PerflibV2 interface. [MS-PCQ] 2.1
// specifies the ncacn_np well-known endpoint \PIPE\winreg (shared with other interfaces
// multiplexed over that pipe; the interface is identified by its UUID, not the pipe).
const PipeName = `\winreg`

// Opnums for the on-the-wire methods.
const (
	OpnumPerflibV2EnumerateCounterSet             uint16 = 0
	OpnumPerflibV2QueryCounterSetRegistrationInfo uint16 = 1
	OpnumPerflibV2EnumerateCounterSetInstances    uint16 = 2
	OpnumPerflibV2OpenQueryHandle                 uint16 = 3
	OpnumPerflibV2CloseQueryHandle                uint16 = 4
	OpnumPerflibV2QueryCounterInfo                uint16 = 5
	OpnumPerflibV2QueryCounterData                uint16 = 6
	OpnumPerflibV2ValidateCounters                uint16 = 7
)

// Every method of this interface returns error_status_t, a Win32 error code from
// [MS-ERREF] section 2.2; the codes [MS-PCQ] documents explicitly for the PerflibV2
// methods (sections 3.1.4.1-3.1.4.8) are not declared here. The whole of [MS-ERREF] 2.2
// lives in github.com/TheManticoreProject/Manticore/windows/errors/win32 as the
// WIN32_ERROR type, and a subset repeated here would cover a fraction of that
// 2703-code table while drifting from it. Convert a returned status with
// win32.WIN32_ERROR(status) and compare against win32.ERROR_SUCCESS and the rest.
// Every value this interface used to declare has a row in [MS-ERREF] 2.2 under the name
// the declaration carried, so nothing is kept local. The one code that is not simply a
// failure is win32.ERROR_NOT_ENOUGH_MEMORY, which the size-probe form of the query
// methods returns alongside the required buffer size in pdwRtnSize.

// SyntaxID returns the PerflibV2 abstract syntax identifier:
// da5a86c5-12c2-4943-ab30-7f74a813d853, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0xda5a86c5, B: 0x12c2, C: 0x4943, D: 0xab30, E: 0x7f74a813d853},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumPerflibV2EnumerateCounterSet:             "PerflibV2EnumerateCounterSet",
	OpnumPerflibV2QueryCounterSetRegistrationInfo: "PerflibV2QueryCounterSetRegistrationInfo",
	OpnumPerflibV2EnumerateCounterSetInstances:    "PerflibV2EnumerateCounterSetInstances",
	OpnumPerflibV2OpenQueryHandle:                 "PerflibV2OpenQueryHandle",
	OpnumPerflibV2CloseQueryHandle:                "PerflibV2CloseQueryHandle",
	OpnumPerflibV2QueryCounterInfo:                "PerflibV2QueryCounterInfo",
	OpnumPerflibV2QueryCounterData:                "PerflibV2QueryCounterData",
	OpnumPerflibV2ValidateCounters:                "PerflibV2ValidateCounters",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
