// Package rpcinterface_708cca10956911d1b2a50060977d8118_1_0 is the descriptor for the dscomm2 RPC interface, abstract
// syntax 708cca10-9569-11d1-b2a5-0060977d8118 version 1.0 ([MS-MQDS]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName, the status-code table, and doc comments are not derivable from
// the IDL and must be confirmed by hand (see the TODO markers).
package rpcinterface_708cca10956911d1b2a50060977d8118_1_0

// IDL source: [MS-MQDS] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-mqds/7907bc25-e4e6-40ef-b990-9172d1808e94
// A fetched copy is kept at ms-mqds.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/errors/hresult"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is retained for descriptor uniformity, but dscomm2 is NOT a named-pipe
// interface: per [MS-MQDS] 2.1 the protocol is carried over ncacn_ip_tcp on an RPC
// dynamic endpoint (resolved through the endpoint mapper), with ncacn_spx as an optional
// legacy sequence. There is no fixed \pipe transport; the value below is only a stable
// short name for the interface.
const PipeName = `\dscomm2`

// Opnums for the on-the-wire methods. Opnums 7 are "not used on the wire"
// and are omitted.
const (
	OpnumS_DSGetComputerSites        uint16 = 0
	OpnumS_DSGetPropsEx              uint16 = 1
	OpnumS_DSGetPropsGuidEx          uint16 = 2
	OpnumS_DSBeginDeleteNotification uint16 = 3
	OpnumS_DSNotifyDelete            uint16 = 4
	OpnumS_DSEndDeleteNotification   uint16 = 5
	OpnumS_DSIsServerGC              uint16 = 6
	OpnumS_DSGetGCListInDomain       uint16 = 8
)

// Status codes returned by this interface. Most dscomm2 methods return an HRESULT — the
// Message Queuing result codes of [MS-MQMQ] 2.4, mqerror.h — while S_DSIsServerGC returns a
// Boolean-valued long and S_DSEndDeleteNotification returns nothing at all. The result codes
// are HRESULTs in FACILITY_MSMQ (0x00E), and [MS-ERREF] section 2.1.1 carries no row for
// that facility: the table names nothing in 0xC00E____ or 0x400E____ and no value whose name
// begins MQ_. So none of them can be read out of
// github.com/TheManticoreProject/Manticore/windows/errors/hresult, and they stay declared
// here, decoded by StatusString before it defers to the shared table.
//
// MQ_OK is the one exception, and it is gone from this block: its value is 0x00000000, which
// the shared package declares as hresult.S_OK, so the stubs compare a returned status against
// that constant. They compare for equality with it rather than testing IsSuccess, which
// preserves the behaviour they have always had — [MS-MQDS] documents MQ_OK as the success
// value of these methods and requires the client to treat every other result as a failure, so
// a success-severity value that is not MQ_OK, such as one of the MQ_INFORMATION_* codes in
// 0x400E____, is still reported as a failure.
//
// Only the codes most relevant to directory operations are enumerated here; StatusString
// defers every other value to the shared table.
const (
	MQ_ERROR                        uint32 = 0xC00E0001
	MQ_ERROR_PROPERTY               uint32 = 0xC00E0002
	MQ_ERROR_QUEUE_NOT_FOUND        uint32 = 0xC00E0003
	MQ_ERROR_INVALID_PARAMETER      uint32 = 0xC00E0006
	MQ_ERROR_INVALID_HANDLE         uint32 = 0xC00E0007
	MQ_ERROR_NO_DS                  uint32 = 0xC00E0013
	MQ_ERROR_ILLEGAL_QUEUE_PATHNAME uint32 = 0xC00E0014
	MQ_ERROR_ACCESS_DENIED          uint32 = 0xC00E0025
	MQ_ERROR_ILLEGAL_PROPID         uint32 = 0xC00E0039
	MQ_ERROR_ILLEGAL_PROPERTY_VALUE uint32 = 0xC00E003C
	MQ_ERROR_DS_ERROR               uint32 = 0xC00E0043
)

// SyntaxID returns the dscomm2 abstract syntax identifier:
// 708cca10-9569-11d1-b2a5-0060977d8118, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x708cca10, B: 0x9569, C: 0x11d1, D: 0xb2a5, E: 0x0060977d8118},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString names the FACILITY_MSMQ result codes above, which [MS-ERREF] section 2.1.1
// does not carry, and defers every other status to the shared HRESULT table. The deferral is
// correct because an MSMQ result code genuinely is an HRESULT and only its facility is absent
// from the specification's table: 0x00000000 renders as S_OK, a FACILITY_WIN32 value renders
// through the Win32 code it wraps, and a value the table does not define renders as hex,
// exactly as it did before.
func StatusString(status uint32) string {
	switch status {
	case MQ_ERROR:
		return "MQ_ERROR"
	case MQ_ERROR_PROPERTY:
		return "MQ_ERROR_PROPERTY"
	case MQ_ERROR_QUEUE_NOT_FOUND:
		return "MQ_ERROR_QUEUE_NOT_FOUND"
	case MQ_ERROR_INVALID_PARAMETER:
		return "MQ_ERROR_INVALID_PARAMETER"
	case MQ_ERROR_INVALID_HANDLE:
		return "MQ_ERROR_INVALID_HANDLE"
	case MQ_ERROR_NO_DS:
		return "MQ_ERROR_NO_DS"
	case MQ_ERROR_ILLEGAL_QUEUE_PATHNAME:
		return "MQ_ERROR_ILLEGAL_QUEUE_PATHNAME"
	case MQ_ERROR_ACCESS_DENIED:
		return "MQ_ERROR_ACCESS_DENIED"
	case MQ_ERROR_ILLEGAL_PROPID:
		return "MQ_ERROR_ILLEGAL_PROPID"
	case MQ_ERROR_ILLEGAL_PROPERTY_VALUE:
		return "MQ_ERROR_ILLEGAL_PROPERTY_VALUE"
	case MQ_ERROR_DS_ERROR:
		return "MQ_ERROR_DS_ERROR"
	default:
		return hresult.HRESULT(status).String()
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumS_DSGetComputerSites:        "S_DSGetComputerSites",
	OpnumS_DSGetPropsEx:              "S_DSGetPropsEx",
	OpnumS_DSGetPropsGuidEx:          "S_DSGetPropsGuidEx",
	OpnumS_DSBeginDeleteNotification: "S_DSBeginDeleteNotification",
	OpnumS_DSNotifyDelete:            "S_DSNotifyDelete",
	OpnumS_DSEndDeleteNotification:   "S_DSEndDeleteNotification",
	OpnumS_DSIsServerGC:              "S_DSIsServerGC",
	OpnumS_DSGetGCListInDomain:       "S_DSGetGCListInDomain",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
