// Package rpcinterface_5b821720f63b11d0aad200c04fc324db_1_0 is the descriptor for the dhcpsrv2 RPC interface, abstract
// syntax 5b821720-f63b-11d0-aad2-00c04fc324db version 1.0 ([MS-DHCPM]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName, the status-code table, and doc comments are not derivable from
// the IDL and must be confirmed by hand (see the TODO markers).
package rpcinterface_5b821720f63b11d0aad200c04fc324db_1_0

// IDL source: [MS-DHCPM] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-dhcpm/d1932d08-3249-44cb-90f1-8661f8fb5b90
// A fetched copy is kept at ms-dhcpm.idl in the interface directory.

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the dhcpsrv2 interface. The DHCP
// Server Management Protocol is reached over the \PIPE\dhcpserver named pipe
// ([MS-DHCPM] 2.1 Transport).
const PipeName = `\dhcpserver`

// Opnums for the on-the-wire methods.
const (
	OpnumR_DhcpEnumSubnetClientsV5                   uint16 = 0
	OpnumR_DhcpSetMScopeInfo                         uint16 = 1
	OpnumR_DhcpGetMScopeInfo                         uint16 = 2
	OpnumR_DhcpEnumMScopes                           uint16 = 3
	OpnumR_DhcpAddMScopeElement                      uint16 = 4
	OpnumR_DhcpEnumMScopeElements                    uint16 = 5
	OpnumR_DhcpRemoveMScopeElement                   uint16 = 6
	OpnumR_DhcpDeleteMScope                          uint16 = 7
	OpnumR_DhcpScanMDatabase                         uint16 = 8
	OpnumR_DhcpCreateMClientInfo                     uint16 = 9
	OpnumR_DhcpSetMClientInfo                        uint16 = 10
	OpnumR_DhcpGetMClientInfo                        uint16 = 11
	OpnumR_DhcpDeleteMClientInfo                     uint16 = 12
	OpnumR_DhcpEnumMScopeClients                     uint16 = 13
	OpnumR_DhcpCreateOptionV5                        uint16 = 14
	OpnumR_DhcpSetOptionInfoV5                       uint16 = 15
	OpnumR_DhcpGetOptionInfoV5                       uint16 = 16
	OpnumR_DhcpEnumOptionsV5                         uint16 = 17
	OpnumR_DhcpRemoveOptionV5                        uint16 = 18
	OpnumR_DhcpSetOptionValueV5                      uint16 = 19
	OpnumR_DhcpSetOptionValuesV5                     uint16 = 20
	OpnumR_DhcpGetOptionValueV5                      uint16 = 21
	OpnumR_DhcpEnumOptionValuesV5                    uint16 = 22
	OpnumR_DhcpRemoveOptionValueV5                   uint16 = 23
	OpnumR_DhcpCreateClass                           uint16 = 24
	OpnumR_DhcpModifyClass                           uint16 = 25
	OpnumR_DhcpDeleteClass                           uint16 = 26
	OpnumR_DhcpGetClassInfo                          uint16 = 27
	OpnumR_DhcpEnumClasses                           uint16 = 28
	OpnumR_DhcpGetAllOptions                         uint16 = 29
	OpnumR_DhcpGetAllOptionValues                    uint16 = 30
	OpnumR_DhcpGetMCastMibInfo                       uint16 = 31
	OpnumR_DhcpAuditLogSetParams                     uint16 = 32
	OpnumR_DhcpAuditLogGetParams                     uint16 = 33
	OpnumR_DhcpServerQueryAttribute                  uint16 = 34
	OpnumR_DhcpServerQueryAttributes                 uint16 = 35
	OpnumR_DhcpServerRedoAuthorization               uint16 = 36
	OpnumR_DhcpAddSubnetElementV5                    uint16 = 37
	OpnumR_DhcpEnumSubnetElementsV5                  uint16 = 38
	OpnumR_DhcpRemoveSubnetElementV5                 uint16 = 39
	OpnumR_DhcpGetServerBindingInfo                  uint16 = 40
	OpnumR_DhcpSetServerBindingInfo                  uint16 = 41
	OpnumR_DhcpQueryDnsRegCredentials                uint16 = 42
	OpnumR_DhcpSetDnsRegCredentials                  uint16 = 43
	OpnumR_DhcpBackupDatabase                        uint16 = 44
	OpnumR_DhcpRestoreDatabase                       uint16 = 45
	OpnumR_DhcpGetServerSpecificStrings              uint16 = 46
	OpnumR_DhcpCreateOptionV6                        uint16 = 47
	OpnumR_DhcpSetOptionInfoV6                       uint16 = 48
	OpnumR_DhcpGetOptionInfoV6                       uint16 = 49
	OpnumR_DhcpEnumOptionsV6                         uint16 = 50
	OpnumR_DhcpRemoveOptionV6                        uint16 = 51
	OpnumR_DhcpSetOptionValueV6                      uint16 = 52
	OpnumR_DhcpEnumOptionValuesV6                    uint16 = 53
	OpnumR_DhcpRemoveOptionValueV6                   uint16 = 54
	OpnumR_DhcpGetAllOptionsV6                       uint16 = 55
	OpnumR_DhcpGetAllOptionValuesV6                  uint16 = 56
	OpnumR_DhcpCreateSubnetV6                        uint16 = 57
	OpnumR_DhcpEnumSubnetsV6                         uint16 = 58
	OpnumR_DhcpAddSubnetElementV6                    uint16 = 59
	OpnumR_DhcpEnumSubnetElementsV6                  uint16 = 60
	OpnumR_DhcpRemoveSubnetElementV6                 uint16 = 61
	OpnumR_DhcpDeleteSubnetV6                        uint16 = 62
	OpnumR_DhcpGetSubnetInfoV6                       uint16 = 63
	OpnumR_DhcpEnumSubnetClientsV6                   uint16 = 64
	OpnumR_DhcpServerSetConfigV6                     uint16 = 65
	OpnumR_DhcpServerGetConfigV6                     uint16 = 66
	OpnumR_DhcpSetSubnetInfoV6                       uint16 = 67
	OpnumR_DhcpGetMibInfoV6                          uint16 = 68
	OpnumR_DhcpGetServerBindingInfoV6                uint16 = 69
	OpnumR_DhcpSetServerBindingInfoV6                uint16 = 70
	OpnumR_DhcpSetClientInfoV6                       uint16 = 71
	OpnumR_DhcpGetClientInfoV6                       uint16 = 72
	OpnumR_DhcpDeleteClientInfoV6                    uint16 = 73
	OpnumR_DhcpCreateClassV6                         uint16 = 74
	OpnumR_DhcpModifyClassV6                         uint16 = 75
	OpnumR_DhcpDeleteClassV6                         uint16 = 76
	OpnumR_DhcpEnumClassesV6                         uint16 = 77
	OpnumR_DhcpGetOptionValueV6                      uint16 = 78
	OpnumR_DhcpSetSubnetDelayOffer                   uint16 = 79
	OpnumR_DhcpGetSubnetDelayOffer                   uint16 = 80
	OpnumR_DhcpGetMibInfoV5                          uint16 = 81
	OpnumR_DhcpAddFilterV4                           uint16 = 82
	OpnumR_DhcpDeleteFilterV4                        uint16 = 83
	OpnumR_DhcpSetFilterV4                           uint16 = 84
	OpnumR_DhcpGetFilterV4                           uint16 = 85
	OpnumR_DhcpEnumFilterV4                          uint16 = 86
	OpnumR_DhcpSetDnsRegCredentialsV5                uint16 = 87
	OpnumR_DhcpEnumSubnetClientsFilterStatusInfo     uint16 = 88
	OpnumR_DhcpV4FailoverCreateRelationship          uint16 = 89
	OpnumR_DhcpV4FailoverSetRelationship             uint16 = 90
	OpnumR_DhcpV4FailoverDeleteRelationship          uint16 = 91
	OpnumR_DhcpV4FailoverGetRelationship             uint16 = 92
	OpnumR_DhcpV4FailoverEnumRelationship            uint16 = 93
	OpnumR_DhcpV4FailoverAddScopeToRelationship      uint16 = 94
	OpnumR_DhcpV4FailoverDeleteScopeFromRelationship uint16 = 95
	OpnumR_DhcpV4FailoverGetScopeRelationship        uint16 = 96
	OpnumR_DhcpV4FailoverGetScopeStatistics          uint16 = 97
	OpnumR_DhcpV4FailoverGetClientInfo               uint16 = 98
	OpnumR_DhcpV4FailoverGetSystemTime               uint16 = 99
	OpnumR_DhcpV4FailoverTriggerAddrAllocation       uint16 = 100
	OpnumR_DhcpV4SetOptionValue                      uint16 = 101
	OpnumR_DhcpV4SetOptionValues                     uint16 = 102
	OpnumR_DhcpV4GetOptionValue                      uint16 = 103
	OpnumR_DhcpV4RemoveOptionValue                   uint16 = 104
	OpnumR_DhcpV4GetAllOptionValues                  uint16 = 105
	OpnumR_DhcpV4QueryPolicyEnforcement              uint16 = 106
	OpnumR_DhcpV4SetPolicyEnforcement                uint16 = 107
	OpnumR_DhcpV4CreatePolicy                        uint16 = 108
	OpnumR_DhcpV4GetPolicy                           uint16 = 109
	OpnumR_DhcpV4SetPolicy                           uint16 = 110
	OpnumR_DhcpV4DeletePolicy                        uint16 = 111
	OpnumR_DhcpV4EnumPolicies                        uint16 = 112
	OpnumR_DhcpV4AddPolicyRange                      uint16 = 113
	OpnumR_DhcpV4RemovePolicyRange                   uint16 = 114
	OpnumR_DhcpV4EnumSubnetClients                   uint16 = 115
	OpnumR_DhcpV6SetStatelessStoreParams             uint16 = 116
	OpnumR_DhcpV6GetStatelessStoreParams             uint16 = 117
	OpnumR_DhcpV6GetStatelessStatistics              uint16 = 118
	OpnumR_DhcpV4EnumSubnetReservations              uint16 = 119
	OpnumR_DhcpV4GetFreeIPAddress                    uint16 = 120
	OpnumR_DhcpV6GetFreeIPAddress                    uint16 = 121
	OpnumR_DhcpV4CreateClientInfo                    uint16 = 122
	OpnumR_DhcpV4GetClientInfo                       uint16 = 123
	OpnumR_DhcpV6CreateClientInfo                    uint16 = 124
	OpnumR_DhcpV4FailoverGetAddressStatus            uint16 = 125
	OpnumR_DhcpV4CreatePolicyEx                      uint16 = 126
	OpnumR_DhcpV4GetPolicyEx                         uint16 = 127
	OpnumR_DhcpV4SetPolicyEx                         uint16 = 128
	OpnumR_DhcpV4EnumPoliciesEx                      uint16 = 129
	OpnumR_DhcpV4EnumSubnetClientsEx                 uint16 = 130
	OpnumR_DhcpV4CreateClientInfoEx                  uint16 = 131
	OpnumR_DhcpV4GetClientInfoEx                     uint16 = 132
)

// Status codes returned by this interface. The DHCP Server Management Protocol
// returns Win32 error codes: ERROR_SUCCESS on success, the generic Win32 errors
// for common failures, and the DHCP-specific ERROR_DHCP_* codes (base 20000 /
// 0x00004E20) documented in [MS-DHCPM] 2.2.1.2 and [MS-ERREF] 2.2. The Enum* and
// pagination methods additionally return ERROR_MORE_DATA / ERROR_NO_MORE_ITEMS,
// which callers treat as success (see StatusIsPagination).
const (
	StatusSuccess uint32 = 0x00000000 // ERROR_SUCCESS

	// Generic Win32 error codes ([MS-ERREF] 2.2).
	ErrorFileNotFound     uint32 = 0x00000002 // ERROR_FILE_NOT_FOUND
	ErrorAccessDenied     uint32 = 0x00000005 // ERROR_ACCESS_DENIED
	ErrorInvalidData      uint32 = 0x0000000D // ERROR_INVALID_DATA
	ErrorInvalidParameter uint32 = 0x00000057 // ERROR_INVALID_PARAMETER
	ErrorAlreadyExists    uint32 = 0x000000B7 // ERROR_ALREADY_EXISTS
	ErrorMoreData         uint32 = 0x000000EA // ERROR_MORE_DATA
	ErrorNoMoreItems      uint32 = 0x00000103 // ERROR_NO_MORE_ITEMS

	// DHCP-specific error codes ([MS-DHCPM] 2.2.1.2, base 0x00004E20 = 20000).
	ErrorDhcpRegistryInitFailed    uint32 = 0x00004E20 // ERROR_DHCP_REGISTRY_INIT_FAILED
	ErrorDhcpDatabaseInitFailed    uint32 = 0x00004E21 // ERROR_DHCP_DATABASE_INIT_FAILED
	ErrorDhcpRpcInitFailed         uint32 = 0x00004E22 // ERROR_DHCP_RPC_INIT_FAILED
	ErrorDhcpNetworkInitFailed     uint32 = 0x00004E23 // ERROR_DHCP_NETWORK_INIT_FAILED
	ErrorDhcpSubnetExists          uint32 = 0x00004E24 // ERROR_DHCP_SUBNET_EXISTS
	ErrorDhcpSubnetNotPresent      uint32 = 0x00004E25 // ERROR_DHCP_SUBNET_NOT_PRESENT
	ErrorDhcpPrimaryNotFound       uint32 = 0x00004E26 // ERROR_DHCP_PRIMARY_NOT_FOUND
	ErrorDhcpElementCantRemove     uint32 = 0x00004E27 // ERROR_DHCP_ELEMENT_CANT_REMOVE
	ErrorDhcpOptionExists          uint32 = 0x00004E29 // ERROR_DHCP_OPTION_EXISTS
	ErrorDhcpOptionNotPresent      uint32 = 0x00004E2A // ERROR_DHCP_OPTION_NOT_PRESENT
	ErrorDhcpAddressNotAvailable   uint32 = 0x00004E2B // ERROR_DHCP_ADDRESS_NOT_AVAILABLE
	ErrorDhcpRangeFull             uint32 = 0x00004E2C // ERROR_DHCP_RANGE_FULL
	ErrorDhcpJetError              uint32 = 0x00004E2D // ERROR_DHCP_JET_ERROR
	ErrorDhcpClientExists          uint32 = 0x00004E2E // ERROR_DHCP_CLIENT_EXISTS
	ErrorDhcpInvalidDhcpMessage    uint32 = 0x00004E2F // ERROR_DHCP_INVALID_DHCP_MESSAGE
	ErrorDhcpInvalidDhcpClient     uint32 = 0x00004E30 // ERROR_DHCP_INVALID_DHCP_CLIENT
	ErrorDhcpServicePaused         uint32 = 0x00004E31 // ERROR_DHCP_SERVICE_PAUSED
	ErrorDhcpNotReservedClient     uint32 = 0x00004E32 // ERROR_DHCP_NOT_RESERVED_CLIENT
	ErrorDhcpReservedClient        uint32 = 0x00004E33 // ERROR_DHCP_RESERVED_CLIENT
	ErrorDhcpRangeTooSmall         uint32 = 0x00004E34 // ERROR_DHCP_RANGE_TOO_SMALL
	ErrorDhcpIPRangeExists         uint32 = 0x00004E35 // ERROR_DHCP_IPRANGE_EXISTS
	ErrorDhcpReservedIPExists      uint32 = 0x00004E36 // ERROR_DHCP_RESERVEDIP_EXISTS
	ErrorDhcpInvalidRange          uint32 = 0x00004E37 // ERROR_DHCP_INVALID_RANGE
	ErrorDhcpRangeExtended         uint32 = 0x00004E38 // ERROR_DHCP_RANGE_EXTENDED
	ErrorDhcpSuperScopeNameTooLong uint32 = 0x00004E3E // ERROR_DHCP_SUPER_SCOPE_NAME_TOO_LONG
	ErrorDhcpClassNotFound         uint32 = 0x00004E4C // ERROR_DHCP_CLASS_NOT_FOUND
	ErrorDhcpClassAlreadyExists    uint32 = 0x00004E4D // ERROR_DHCP_CLASS_ALREADY_EXISTS
)

// statusNames maps the documented status codes to their [MS-ERREF] mnemonics.
var statusNames = map[uint32]string{
	StatusSuccess:                  "ERROR_SUCCESS",
	ErrorFileNotFound:              "ERROR_FILE_NOT_FOUND",
	ErrorAccessDenied:              "ERROR_ACCESS_DENIED",
	ErrorInvalidData:               "ERROR_INVALID_DATA",
	ErrorInvalidParameter:          "ERROR_INVALID_PARAMETER",
	ErrorAlreadyExists:             "ERROR_ALREADY_EXISTS",
	ErrorMoreData:                  "ERROR_MORE_DATA",
	ErrorNoMoreItems:               "ERROR_NO_MORE_ITEMS",
	ErrorDhcpRegistryInitFailed:    "ERROR_DHCP_REGISTRY_INIT_FAILED",
	ErrorDhcpDatabaseInitFailed:    "ERROR_DHCP_DATABASE_INIT_FAILED",
	ErrorDhcpRpcInitFailed:         "ERROR_DHCP_RPC_INIT_FAILED",
	ErrorDhcpNetworkInitFailed:     "ERROR_DHCP_NETWORK_INIT_FAILED",
	ErrorDhcpSubnetExists:          "ERROR_DHCP_SUBNET_EXISTS",
	ErrorDhcpSubnetNotPresent:      "ERROR_DHCP_SUBNET_NOT_PRESENT",
	ErrorDhcpPrimaryNotFound:       "ERROR_DHCP_PRIMARY_NOT_FOUND",
	ErrorDhcpElementCantRemove:     "ERROR_DHCP_ELEMENT_CANT_REMOVE",
	ErrorDhcpOptionExists:          "ERROR_DHCP_OPTION_EXISTS",
	ErrorDhcpOptionNotPresent:      "ERROR_DHCP_OPTION_NOT_PRESENT",
	ErrorDhcpAddressNotAvailable:   "ERROR_DHCP_ADDRESS_NOT_AVAILABLE",
	ErrorDhcpRangeFull:             "ERROR_DHCP_RANGE_FULL",
	ErrorDhcpJetError:              "ERROR_DHCP_JET_ERROR",
	ErrorDhcpClientExists:          "ERROR_DHCP_CLIENT_EXISTS",
	ErrorDhcpInvalidDhcpMessage:    "ERROR_DHCP_INVALID_DHCP_MESSAGE",
	ErrorDhcpInvalidDhcpClient:     "ERROR_DHCP_INVALID_DHCP_CLIENT",
	ErrorDhcpServicePaused:         "ERROR_DHCP_SERVICE_PAUSED",
	ErrorDhcpNotReservedClient:     "ERROR_DHCP_NOT_RESERVED_CLIENT",
	ErrorDhcpReservedClient:        "ERROR_DHCP_RESERVED_CLIENT",
	ErrorDhcpRangeTooSmall:         "ERROR_DHCP_RANGE_TOO_SMALL",
	ErrorDhcpIPRangeExists:         "ERROR_DHCP_IPRANGE_EXISTS",
	ErrorDhcpReservedIPExists:      "ERROR_DHCP_RESERVEDIP_EXISTS",
	ErrorDhcpInvalidRange:          "ERROR_DHCP_INVALID_RANGE",
	ErrorDhcpRangeExtended:         "ERROR_DHCP_RANGE_EXTENDED",
	ErrorDhcpSuperScopeNameTooLong: "ERROR_DHCP_SUPER_SCOPE_NAME_TOO_LONG",
	ErrorDhcpClassNotFound:         "ERROR_DHCP_CLASS_NOT_FOUND",
	ErrorDhcpClassAlreadyExists:    "ERROR_DHCP_CLASS_ALREADY_EXISTS",
}

// StatusIsPagination reports whether status is one of the pagination sentinels
// (ERROR_MORE_DATA / ERROR_NO_MORE_ITEMS) that the Enum* and Get* methods return
// alongside a valid result rather than to signal failure.
func StatusIsPagination(status uint32) bool {
	return status == ErrorMoreData || status == ErrorNoMoreItems
}

// SyntaxID returns the dhcpsrv2 abstract syntax identifier:
// 5b821720-f63b-11d0-aad2-00c04fc324db, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x5b821720, B: 0xf63b, C: 0x11d0, D: 0xaad2, E: 0x00c04fc324db},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented status codes, otherwise the
// hex value.
func StatusString(status uint32) string {
	if name, ok := statusNames[status]; ok {
		return name
	}
	return fmt.Sprintf("0x%08x", status)
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumR_DhcpEnumSubnetClientsV5:                   "R_DhcpEnumSubnetClientsV5",
	OpnumR_DhcpSetMScopeInfo:                         "R_DhcpSetMScopeInfo",
	OpnumR_DhcpGetMScopeInfo:                         "R_DhcpGetMScopeInfo",
	OpnumR_DhcpEnumMScopes:                           "R_DhcpEnumMScopes",
	OpnumR_DhcpAddMScopeElement:                      "R_DhcpAddMScopeElement",
	OpnumR_DhcpEnumMScopeElements:                    "R_DhcpEnumMScopeElements",
	OpnumR_DhcpRemoveMScopeElement:                   "R_DhcpRemoveMScopeElement",
	OpnumR_DhcpDeleteMScope:                          "R_DhcpDeleteMScope",
	OpnumR_DhcpScanMDatabase:                         "R_DhcpScanMDatabase",
	OpnumR_DhcpCreateMClientInfo:                     "R_DhcpCreateMClientInfo",
	OpnumR_DhcpSetMClientInfo:                        "R_DhcpSetMClientInfo",
	OpnumR_DhcpGetMClientInfo:                        "R_DhcpGetMClientInfo",
	OpnumR_DhcpDeleteMClientInfo:                     "R_DhcpDeleteMClientInfo",
	OpnumR_DhcpEnumMScopeClients:                     "R_DhcpEnumMScopeClients",
	OpnumR_DhcpCreateOptionV5:                        "R_DhcpCreateOptionV5",
	OpnumR_DhcpSetOptionInfoV5:                       "R_DhcpSetOptionInfoV5",
	OpnumR_DhcpGetOptionInfoV5:                       "R_DhcpGetOptionInfoV5",
	OpnumR_DhcpEnumOptionsV5:                         "R_DhcpEnumOptionsV5",
	OpnumR_DhcpRemoveOptionV5:                        "R_DhcpRemoveOptionV5",
	OpnumR_DhcpSetOptionValueV5:                      "R_DhcpSetOptionValueV5",
	OpnumR_DhcpSetOptionValuesV5:                     "R_DhcpSetOptionValuesV5",
	OpnumR_DhcpGetOptionValueV5:                      "R_DhcpGetOptionValueV5",
	OpnumR_DhcpEnumOptionValuesV5:                    "R_DhcpEnumOptionValuesV5",
	OpnumR_DhcpRemoveOptionValueV5:                   "R_DhcpRemoveOptionValueV5",
	OpnumR_DhcpCreateClass:                           "R_DhcpCreateClass",
	OpnumR_DhcpModifyClass:                           "R_DhcpModifyClass",
	OpnumR_DhcpDeleteClass:                           "R_DhcpDeleteClass",
	OpnumR_DhcpGetClassInfo:                          "R_DhcpGetClassInfo",
	OpnumR_DhcpEnumClasses:                           "R_DhcpEnumClasses",
	OpnumR_DhcpGetAllOptions:                         "R_DhcpGetAllOptions",
	OpnumR_DhcpGetAllOptionValues:                    "R_DhcpGetAllOptionValues",
	OpnumR_DhcpGetMCastMibInfo:                       "R_DhcpGetMCastMibInfo",
	OpnumR_DhcpAuditLogSetParams:                     "R_DhcpAuditLogSetParams",
	OpnumR_DhcpAuditLogGetParams:                     "R_DhcpAuditLogGetParams",
	OpnumR_DhcpServerQueryAttribute:                  "R_DhcpServerQueryAttribute",
	OpnumR_DhcpServerQueryAttributes:                 "R_DhcpServerQueryAttributes",
	OpnumR_DhcpServerRedoAuthorization:               "R_DhcpServerRedoAuthorization",
	OpnumR_DhcpAddSubnetElementV5:                    "R_DhcpAddSubnetElementV5",
	OpnumR_DhcpEnumSubnetElementsV5:                  "R_DhcpEnumSubnetElementsV5",
	OpnumR_DhcpRemoveSubnetElementV5:                 "R_DhcpRemoveSubnetElementV5",
	OpnumR_DhcpGetServerBindingInfo:                  "R_DhcpGetServerBindingInfo",
	OpnumR_DhcpSetServerBindingInfo:                  "R_DhcpSetServerBindingInfo",
	OpnumR_DhcpQueryDnsRegCredentials:                "R_DhcpQueryDnsRegCredentials",
	OpnumR_DhcpSetDnsRegCredentials:                  "R_DhcpSetDnsRegCredentials",
	OpnumR_DhcpBackupDatabase:                        "R_DhcpBackupDatabase",
	OpnumR_DhcpRestoreDatabase:                       "R_DhcpRestoreDatabase",
	OpnumR_DhcpGetServerSpecificStrings:              "R_DhcpGetServerSpecificStrings",
	OpnumR_DhcpCreateOptionV6:                        "R_DhcpCreateOptionV6",
	OpnumR_DhcpSetOptionInfoV6:                       "R_DhcpSetOptionInfoV6",
	OpnumR_DhcpGetOptionInfoV6:                       "R_DhcpGetOptionInfoV6",
	OpnumR_DhcpEnumOptionsV6:                         "R_DhcpEnumOptionsV6",
	OpnumR_DhcpRemoveOptionV6:                        "R_DhcpRemoveOptionV6",
	OpnumR_DhcpSetOptionValueV6:                      "R_DhcpSetOptionValueV6",
	OpnumR_DhcpEnumOptionValuesV6:                    "R_DhcpEnumOptionValuesV6",
	OpnumR_DhcpRemoveOptionValueV6:                   "R_DhcpRemoveOptionValueV6",
	OpnumR_DhcpGetAllOptionsV6:                       "R_DhcpGetAllOptionsV6",
	OpnumR_DhcpGetAllOptionValuesV6:                  "R_DhcpGetAllOptionValuesV6",
	OpnumR_DhcpCreateSubnetV6:                        "R_DhcpCreateSubnetV6",
	OpnumR_DhcpEnumSubnetsV6:                         "R_DhcpEnumSubnetsV6",
	OpnumR_DhcpAddSubnetElementV6:                    "R_DhcpAddSubnetElementV6",
	OpnumR_DhcpEnumSubnetElementsV6:                  "R_DhcpEnumSubnetElementsV6",
	OpnumR_DhcpRemoveSubnetElementV6:                 "R_DhcpRemoveSubnetElementV6",
	OpnumR_DhcpDeleteSubnetV6:                        "R_DhcpDeleteSubnetV6",
	OpnumR_DhcpGetSubnetInfoV6:                       "R_DhcpGetSubnetInfoV6",
	OpnumR_DhcpEnumSubnetClientsV6:                   "R_DhcpEnumSubnetClientsV6",
	OpnumR_DhcpServerSetConfigV6:                     "R_DhcpServerSetConfigV6",
	OpnumR_DhcpServerGetConfigV6:                     "R_DhcpServerGetConfigV6",
	OpnumR_DhcpSetSubnetInfoV6:                       "R_DhcpSetSubnetInfoV6",
	OpnumR_DhcpGetMibInfoV6:                          "R_DhcpGetMibInfoV6",
	OpnumR_DhcpGetServerBindingInfoV6:                "R_DhcpGetServerBindingInfoV6",
	OpnumR_DhcpSetServerBindingInfoV6:                "R_DhcpSetServerBindingInfoV6",
	OpnumR_DhcpSetClientInfoV6:                       "R_DhcpSetClientInfoV6",
	OpnumR_DhcpGetClientInfoV6:                       "R_DhcpGetClientInfoV6",
	OpnumR_DhcpDeleteClientInfoV6:                    "R_DhcpDeleteClientInfoV6",
	OpnumR_DhcpCreateClassV6:                         "R_DhcpCreateClassV6",
	OpnumR_DhcpModifyClassV6:                         "R_DhcpModifyClassV6",
	OpnumR_DhcpDeleteClassV6:                         "R_DhcpDeleteClassV6",
	OpnumR_DhcpEnumClassesV6:                         "R_DhcpEnumClassesV6",
	OpnumR_DhcpGetOptionValueV6:                      "R_DhcpGetOptionValueV6",
	OpnumR_DhcpSetSubnetDelayOffer:                   "R_DhcpSetSubnetDelayOffer",
	OpnumR_DhcpGetSubnetDelayOffer:                   "R_DhcpGetSubnetDelayOffer",
	OpnumR_DhcpGetMibInfoV5:                          "R_DhcpGetMibInfoV5",
	OpnumR_DhcpAddFilterV4:                           "R_DhcpAddFilterV4",
	OpnumR_DhcpDeleteFilterV4:                        "R_DhcpDeleteFilterV4",
	OpnumR_DhcpSetFilterV4:                           "R_DhcpSetFilterV4",
	OpnumR_DhcpGetFilterV4:                           "R_DhcpGetFilterV4",
	OpnumR_DhcpEnumFilterV4:                          "R_DhcpEnumFilterV4",
	OpnumR_DhcpSetDnsRegCredentialsV5:                "R_DhcpSetDnsRegCredentialsV5",
	OpnumR_DhcpEnumSubnetClientsFilterStatusInfo:     "R_DhcpEnumSubnetClientsFilterStatusInfo",
	OpnumR_DhcpV4FailoverCreateRelationship:          "R_DhcpV4FailoverCreateRelationship",
	OpnumR_DhcpV4FailoverSetRelationship:             "R_DhcpV4FailoverSetRelationship",
	OpnumR_DhcpV4FailoverDeleteRelationship:          "R_DhcpV4FailoverDeleteRelationship",
	OpnumR_DhcpV4FailoverGetRelationship:             "R_DhcpV4FailoverGetRelationship",
	OpnumR_DhcpV4FailoverEnumRelationship:            "R_DhcpV4FailoverEnumRelationship",
	OpnumR_DhcpV4FailoverAddScopeToRelationship:      "R_DhcpV4FailoverAddScopeToRelationship",
	OpnumR_DhcpV4FailoverDeleteScopeFromRelationship: "R_DhcpV4FailoverDeleteScopeFromRelationship",
	OpnumR_DhcpV4FailoverGetScopeRelationship:        "R_DhcpV4FailoverGetScopeRelationship",
	OpnumR_DhcpV4FailoverGetScopeStatistics:          "R_DhcpV4FailoverGetScopeStatistics",
	OpnumR_DhcpV4FailoverGetClientInfo:               "R_DhcpV4FailoverGetClientInfo",
	OpnumR_DhcpV4FailoverGetSystemTime:               "R_DhcpV4FailoverGetSystemTime",
	OpnumR_DhcpV4FailoverTriggerAddrAllocation:       "R_DhcpV4FailoverTriggerAddrAllocation",
	OpnumR_DhcpV4SetOptionValue:                      "R_DhcpV4SetOptionValue",
	OpnumR_DhcpV4SetOptionValues:                     "R_DhcpV4SetOptionValues",
	OpnumR_DhcpV4GetOptionValue:                      "R_DhcpV4GetOptionValue",
	OpnumR_DhcpV4RemoveOptionValue:                   "R_DhcpV4RemoveOptionValue",
	OpnumR_DhcpV4GetAllOptionValues:                  "R_DhcpV4GetAllOptionValues",
	OpnumR_DhcpV4QueryPolicyEnforcement:              "R_DhcpV4QueryPolicyEnforcement",
	OpnumR_DhcpV4SetPolicyEnforcement:                "R_DhcpV4SetPolicyEnforcement",
	OpnumR_DhcpV4CreatePolicy:                        "R_DhcpV4CreatePolicy",
	OpnumR_DhcpV4GetPolicy:                           "R_DhcpV4GetPolicy",
	OpnumR_DhcpV4SetPolicy:                           "R_DhcpV4SetPolicy",
	OpnumR_DhcpV4DeletePolicy:                        "R_DhcpV4DeletePolicy",
	OpnumR_DhcpV4EnumPolicies:                        "R_DhcpV4EnumPolicies",
	OpnumR_DhcpV4AddPolicyRange:                      "R_DhcpV4AddPolicyRange",
	OpnumR_DhcpV4RemovePolicyRange:                   "R_DhcpV4RemovePolicyRange",
	OpnumR_DhcpV4EnumSubnetClients:                   "R_DhcpV4EnumSubnetClients",
	OpnumR_DhcpV6SetStatelessStoreParams:             "R_DhcpV6SetStatelessStoreParams",
	OpnumR_DhcpV6GetStatelessStoreParams:             "R_DhcpV6GetStatelessStoreParams",
	OpnumR_DhcpV6GetStatelessStatistics:              "R_DhcpV6GetStatelessStatistics",
	OpnumR_DhcpV4EnumSubnetReservations:              "R_DhcpV4EnumSubnetReservations",
	OpnumR_DhcpV4GetFreeIPAddress:                    "R_DhcpV4GetFreeIPAddress",
	OpnumR_DhcpV6GetFreeIPAddress:                    "R_DhcpV6GetFreeIPAddress",
	OpnumR_DhcpV4CreateClientInfo:                    "R_DhcpV4CreateClientInfo",
	OpnumR_DhcpV4GetClientInfo:                       "R_DhcpV4GetClientInfo",
	OpnumR_DhcpV6CreateClientInfo:                    "R_DhcpV6CreateClientInfo",
	OpnumR_DhcpV4FailoverGetAddressStatus:            "R_DhcpV4FailoverGetAddressStatus",
	OpnumR_DhcpV4CreatePolicyEx:                      "R_DhcpV4CreatePolicyEx",
	OpnumR_DhcpV4GetPolicyEx:                         "R_DhcpV4GetPolicyEx",
	OpnumR_DhcpV4SetPolicyEx:                         "R_DhcpV4SetPolicyEx",
	OpnumR_DhcpV4EnumPoliciesEx:                      "R_DhcpV4EnumPoliciesEx",
	OpnumR_DhcpV4EnumSubnetClientsEx:                 "R_DhcpV4EnumSubnetClientsEx",
	OpnumR_DhcpV4CreateClientInfoEx:                  "R_DhcpV4CreateClientInfoEx",
	OpnumR_DhcpV4GetClientInfoEx:                     "R_DhcpV4GetClientInfoEx",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
