// Package rpcinterface_8f09f000b7ed11cebbd200001a181cad_0_0 is the descriptor for the dimsvc RPC interface, abstract
// syntax 8f09f000-b7ed-11ce-bbd2-00001a181cad version 0.0 ([MS-RRASM]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName and the doc comments are not derivable from the IDL and must be
// confirmed by hand (see the TODO markers).
package rpcinterface_8f09f000b7ed11cebbd200001a181cad_0_0

// IDL source: [MS-RRASM] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rrasm/8e6e89fb-9c80-4a9a-a222-d7d8948244bb
// A fetched copy is kept at ms-rrasm.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the dimsvc interface. The dimsvc and
// rasrpc interfaces are both reached over \PIPE\ROUTER ([MS-RRASM] 2.1 Transport).
const PipeName = `\ROUTER`

// Opnums for the on-the-wire methods.
const (
	OpnumRMprAdminServerGetInfo                 uint16 = 0
	OpnumRRasAdminConnectionEnum                uint16 = 1
	OpnumRRasAdminConnectionGetInfo             uint16 = 2
	OpnumRRasAdminConnectionClearStats          uint16 = 3
	OpnumRRasAdminPortEnum                      uint16 = 4
	OpnumRRasAdminPortGetInfo                   uint16 = 5
	OpnumRRasAdminPortClearStats                uint16 = 6
	OpnumRRasAdminPortReset                     uint16 = 7
	OpnumRRasAdminPortDisconnect                uint16 = 8
	OpnumRRouterInterfaceTransportSetGlobalInfo uint16 = 9
	OpnumRRouterInterfaceTransportGetGlobalInfo uint16 = 10
	OpnumRRouterInterfaceGetHandle              uint16 = 11
	OpnumRRouterInterfaceCreate                 uint16 = 12
	OpnumRRouterInterfaceGetInfo                uint16 = 13
	OpnumRRouterInterfaceSetInfo                uint16 = 14
	OpnumRRouterInterfaceDelete                 uint16 = 15
	OpnumRRouterInterfaceTransportRemove        uint16 = 16
	OpnumRRouterInterfaceTransportAdd           uint16 = 17
	OpnumRRouterInterfaceTransportGetInfo       uint16 = 18
	OpnumRRouterInterfaceTransportSetInfo       uint16 = 19
	OpnumRRouterInterfaceEnum                   uint16 = 20
	OpnumRRouterInterfaceConnect                uint16 = 21
	OpnumRRouterInterfaceDisconnect             uint16 = 22
	OpnumRRouterInterfaceUpdateRoutes           uint16 = 23
	OpnumRRouterInterfaceQueryUpdateResult      uint16 = 24
	OpnumRRouterInterfaceUpdatePhonebookInfo    uint16 = 25
	OpnumRMIBEntryCreate                        uint16 = 26
	OpnumRMIBEntryDelete                        uint16 = 27
	OpnumRMIBEntrySet                           uint16 = 28
	OpnumRMIBEntryGet                           uint16 = 29
	OpnumRMIBEntryGetFirst                      uint16 = 30
	OpnumRMIBEntryGetNext                       uint16 = 31
	OpnumRMIBGetTrapInfo                        uint16 = 32
	OpnumRMIBSetTrapInfo                        uint16 = 33
	OpnumRRasAdminConnectionNotification        uint16 = 34
	OpnumRRasAdminSendUserMessage               uint16 = 35
	OpnumRRouterDeviceEnum                      uint16 = 36
	OpnumRRouterInterfaceTransportCreate        uint16 = 37
	OpnumRRouterInterfaceDeviceGetInfo          uint16 = 38
	OpnumRRouterInterfaceDeviceSetInfo          uint16 = 39
	OpnumRRouterInterfaceSetCredentialsEx       uint16 = 40
	OpnumRRouterInterfaceGetCredentialsEx       uint16 = 41
	OpnumRRasAdminConnectionRemoveQuarantine    uint16 = 42
	OpnumRMprAdminServerSetInfo                 uint16 = 43
	OpnumRMprAdminServerGetInfoEx               uint16 = 44
	OpnumRRasAdminConnectionEnumEx              uint16 = 45
	OpnumRRasAdminConnectionGetInfoEx           uint16 = 46
	OpnumRMprAdminServerSetInfoEx               uint16 = 47
	OpnumRRasAdminUpdateConnection              uint16 = 48
	OpnumRRouterInterfaceSetCredentialsLocal    uint16 = 49
	OpnumRRouterInterfaceGetCredentialsLocal    uint16 = 50
	OpnumRRouterInterfaceGetCustomInfoEx        uint16 = 51
	OpnumRRouterInterfaceSetCustomInfoEx        uint16 = 52
)

// The Win32 error codes dimsvc methods return ([MS-ERREF] 2.2, [MS-RRASM] 3.1.4) are not
// declared here. The whole of [MS-ERREF] 2.2 lives in
// github.com/TheManticoreProject/Manticore/windows/errors/win32 as the WIN32_ERROR type,
// and a subset repeated here would cover a fraction of that 2703-code table while drifting
// from it. Convert a returned status with win32.WIN32_ERROR(status) and compare against
// win32.ERROR_SUCCESS and the rest.

// SyntaxID returns the dimsvc abstract syntax identifier:
// 8f09f000-b7ed-11ce-bbd2-00001a181cad, version 0.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x8f09f000, B: 0xb7ed, C: 0x11ce, D: 0xbbd2, E: 0x00001a181cad},
		MajorVersion: 0,
		MinorVersion: 0,
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumRMprAdminServerGetInfo:                 "RMprAdminServerGetInfo",
	OpnumRRasAdminConnectionEnum:                "RRasAdminConnectionEnum",
	OpnumRRasAdminConnectionGetInfo:             "RRasAdminConnectionGetInfo",
	OpnumRRasAdminConnectionClearStats:          "RRasAdminConnectionClearStats",
	OpnumRRasAdminPortEnum:                      "RRasAdminPortEnum",
	OpnumRRasAdminPortGetInfo:                   "RRasAdminPortGetInfo",
	OpnumRRasAdminPortClearStats:                "RRasAdminPortClearStats",
	OpnumRRasAdminPortReset:                     "RRasAdminPortReset",
	OpnumRRasAdminPortDisconnect:                "RRasAdminPortDisconnect",
	OpnumRRouterInterfaceTransportSetGlobalInfo: "RRouterInterfaceTransportSetGlobalInfo",
	OpnumRRouterInterfaceTransportGetGlobalInfo: "RRouterInterfaceTransportGetGlobalInfo",
	OpnumRRouterInterfaceGetHandle:              "RRouterInterfaceGetHandle",
	OpnumRRouterInterfaceCreate:                 "RRouterInterfaceCreate",
	OpnumRRouterInterfaceGetInfo:                "RRouterInterfaceGetInfo",
	OpnumRRouterInterfaceSetInfo:                "RRouterInterfaceSetInfo",
	OpnumRRouterInterfaceDelete:                 "RRouterInterfaceDelete",
	OpnumRRouterInterfaceTransportRemove:        "RRouterInterfaceTransportRemove",
	OpnumRRouterInterfaceTransportAdd:           "RRouterInterfaceTransportAdd",
	OpnumRRouterInterfaceTransportGetInfo:       "RRouterInterfaceTransportGetInfo",
	OpnumRRouterInterfaceTransportSetInfo:       "RRouterInterfaceTransportSetInfo",
	OpnumRRouterInterfaceEnum:                   "RRouterInterfaceEnum",
	OpnumRRouterInterfaceConnect:                "RRouterInterfaceConnect",
	OpnumRRouterInterfaceDisconnect:             "RRouterInterfaceDisconnect",
	OpnumRRouterInterfaceUpdateRoutes:           "RRouterInterfaceUpdateRoutes",
	OpnumRRouterInterfaceQueryUpdateResult:      "RRouterInterfaceQueryUpdateResult",
	OpnumRRouterInterfaceUpdatePhonebookInfo:    "RRouterInterfaceUpdatePhonebookInfo",
	OpnumRMIBEntryCreate:                        "RMIBEntryCreate",
	OpnumRMIBEntryDelete:                        "RMIBEntryDelete",
	OpnumRMIBEntrySet:                           "RMIBEntrySet",
	OpnumRMIBEntryGet:                           "RMIBEntryGet",
	OpnumRMIBEntryGetFirst:                      "RMIBEntryGetFirst",
	OpnumRMIBEntryGetNext:                       "RMIBEntryGetNext",
	OpnumRMIBGetTrapInfo:                        "RMIBGetTrapInfo",
	OpnumRMIBSetTrapInfo:                        "RMIBSetTrapInfo",
	OpnumRRasAdminConnectionNotification:        "RRasAdminConnectionNotification",
	OpnumRRasAdminSendUserMessage:               "RRasAdminSendUserMessage",
	OpnumRRouterDeviceEnum:                      "RRouterDeviceEnum",
	OpnumRRouterInterfaceTransportCreate:        "RRouterInterfaceTransportCreate",
	OpnumRRouterInterfaceDeviceGetInfo:          "RRouterInterfaceDeviceGetInfo",
	OpnumRRouterInterfaceDeviceSetInfo:          "RRouterInterfaceDeviceSetInfo",
	OpnumRRouterInterfaceSetCredentialsEx:       "RRouterInterfaceSetCredentialsEx",
	OpnumRRouterInterfaceGetCredentialsEx:       "RRouterInterfaceGetCredentialsEx",
	OpnumRRasAdminConnectionRemoveQuarantine:    "RRasAdminConnectionRemoveQuarantine",
	OpnumRMprAdminServerSetInfo:                 "RMprAdminServerSetInfo",
	OpnumRMprAdminServerGetInfoEx:               "RMprAdminServerGetInfoEx",
	OpnumRRasAdminConnectionEnumEx:              "RRasAdminConnectionEnumEx",
	OpnumRRasAdminConnectionGetInfoEx:           "RRasAdminConnectionGetInfoEx",
	OpnumRMprAdminServerSetInfoEx:               "RMprAdminServerSetInfoEx",
	OpnumRRasAdminUpdateConnection:              "RRasAdminUpdateConnection",
	OpnumRRouterInterfaceSetCredentialsLocal:    "RRouterInterfaceSetCredentialsLocal",
	OpnumRRouterInterfaceGetCredentialsLocal:    "RRouterInterfaceGetCredentialsLocal",
	OpnumRRouterInterfaceGetCustomInfoEx:        "RRouterInterfaceGetCustomInfoEx",
	OpnumRRouterInterfaceSetCustomInfoEx:        "RRouterInterfaceSetCustomInfoEx",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
