// Package rpcinterface_b9785960524f11df8b6d83dcded72085_1_0 is the descriptor for the ISDKey RPC interface, abstract
// syntax b9785960-524f-11df-8b6d-83dcded72085 version 1.0 ([MS-GKDI]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed by
// hand: the transport endpoint (PipeName) and the return-value semantics are
// not derivable from the IDL and were reconciled against [MS-GKDI] sections 2.1
// and 3.1.4.1.
package rpcinterface_b9785960524f11df8b6d83dcded72085_1_0

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the ISDKey interface.
//
// [MS-GKDI] section 2.1 mandates ncacn_ip_tcp with RPC dynamic endpoints and
// defines no named pipe. In practice the interface is also reachable over the
// \pipe\lsass SMB named pipe on domain controllers (the endpoint used by GKDI
// tooling), which is recorded here for callers binding over ncacn_np.
const PipeName = `\lsass`

// Opnums for the on-the-wire methods.
const (
	OpnumGetKey uint16 = 0
)

// GetKey returns an HRESULT ([MS-GKDI] section 3.1.4.1): zero on success,
// nonzero on failure. The specification enumerates no further status table, so
// only S_OK is named here; StatusString renders any other value as hex.
const (
	StatusSuccess uint32 = 0x00000000 // S_OK
)

// SyntaxID returns the ISDKey abstract syntax identifier:
// b9785960-524f-11df-8b6d-83dcded72085, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0xb9785960, B: 0x524f, C: 0x11df, D: 0x8b6d, E: 0x83dcded72085},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented status codes, otherwise the
// hex value.
func StatusString(status uint32) string {
	switch status {
	case StatusSuccess:
		return "S_OK"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumGetKey: "GetKey",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
