// Package rpcinterface_b9785960524f11df8b6d83dcded72085_1_0 is the descriptor for the ISDKey RPC interface, abstract
// syntax b9785960-524f-11df-8b6d-83dcded72085 version 1.0 ([MS-GKDI]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed by
// hand: the transport endpoint (PipeName) and the return-value semantics are
// not derivable from the IDL and were reconciled against [MS-GKDI] sections 2.1
// and 3.1.4.1.
package rpcinterface_b9785960524f11df8b6d83dcded72085_1_0

// IDL source: [MS-GKDI] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-gkdi/441a75fd-ab11-478c-881a-332e6f3a4bf7
// A fetched copy is kept at ms-gkdi.idl in the interface directory.

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the ISDKey interface.
//
// [MS-GKDI] section 2.1 mandates ncacn_ip_tcp with RPC dynamic endpoints and
// defines no named pipe. In practice the interface is also reachable over the
// \pipe\lsass SMB named pipe on domain controllers (the endpoint used by GKDI
// tooling), which is recorded here for callers binding over ncacn_np.
const PipeName = `\lsass`

// Opnums for the on-the-wire methods.
const (
	OpnumGetKey uint16 = 0
)

// GetKey returns an HRESULT ([MS-GKDI] section 3.1.4.1): zero on success,
// nonzero on failure. The specification enumerates no further status table, so
// only S_OK is named here; StatusString renders any other value as hex.
//
// This is an HRESULT, not a Win32 error code, so the code stays declared here
// rather than being referenced from
// github.com/TheManticoreProject/Manticore/windows/errors/win32 the way an
// interface that reports a WIN32_ERROR does. HRESULTs are [MS-ERREF] section
// 2.1; the WIN32_ERROR table is [MS-ERREF] section 2.2, and the two spaces
// disagree on both halves of the range. A failing GetKey returns a value with
// the severity bit set, typically an HRESULT_FROM_WIN32 wrapping in the
// 0x8007xxxx range ([MS-ERREF] 2.1.2), and the shared table's highest code is
// 0x00003BC3, so it can name no GKDI failure at all: routing this return
// through it would buy nothing. At the low end it would actively mislead. An
// HRESULT with the severity bit clear is a success code, S_FALSE being
// 0x00000001, and [MS-ERREF] 2.2 assigns that value to ERROR_INVALID_FUNCTION,
// "Incorrect function." Naming this interface's status out of that table would
// therefore report a successful key retrieval as an invalid-function failure.
// The fallback in StatusString stays hexadecimal for the same reason: 0x00000002
// reads as ERROR_FILE_NOT_FOUND there and has no such meaning here.
const (
	StatusSuccess uint32 = 0x00000000 // S_OK
)

// SyntaxID returns the ISDKey abstract syntax identifier:
// b9785960-524f-11df-8b6d-83dcded72085, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0xb9785960, B: 0x524f, C: 0x11df, D: 0x8b6d, E: 0x83dcded72085},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented status codes, otherwise the
// hex value. An unrecognized status stays hexadecimal rather than being resolved
// through windows/errors/win32, which would name an HRESULT out of the Win32
// table: 0x00000001 would read as ERROR_INVALID_FUNCTION where the HRESULT space
// means S_FALSE.
func StatusString(status uint32) string {
	switch status {
	case StatusSuccess:
		return "S_OK"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumGetKey: "GetKey",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
