package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_SECURITY_ATTRIBUTES ([MS-RRP]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_SECURITY_ATTRIBUTES struct {
	NLength               ndr.DWORD
	RpcSecurityDescriptor RPC_SECURITY_DESCRIPTOR
	BInheritHandle        bool
}
