// Package rpcinterface_afc07e2e311c4435808cc483ffeec7c9_1_0 is the descriptor for the lsacap RPC interface, abstract
// syntax afc07e2e-311c-4435-808c-c483ffeec7c9 version 1.0 ([MS-CAPR]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName and the doc comments are not derivable from the IDL and must be
// confirmed by hand (see the TODO markers).
package rpcinterface_afc07e2e311c4435808cc483ffeec7c9_1_0

// IDL source: [MS-CAPR] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-capr/3b30e288-7f4f-4d05-bcac-d8e33086d0cc
// A fetched copy is kept at ms-capr.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the lsacap interface. lsacap is
// served by the LSA (lsass) endpoint and is reached over the shared \lsarpc pipe
// ([MS-CAPR] 2.1 Transport), the same pipe that multiplexes MS-LSAD and MS-LSAT.
const PipeName = `\lsarpc`

// Opnums for the on-the-wire methods.
const (
	OpnumLsarGetAvailableCAPIDs uint16 = 0
)

// Status codes are not declared here. LsarGetAvailableCAPIDs returns
// NT_STATUS_SUCCESS on success and otherwise a nonzero [MS-ERREF] code
// ([MS-CAPR] 3.1.4.1), and the whole of [MS-ERREF] 2.3.1 lives in
// github.com/TheManticoreProject/Manticore/windows/errors/nt_status. A subset
// declared here would cover a fraction of that table and drift from it, so
// callers use nt_status.NT_STATUS directly.

// SyntaxID returns the lsacap abstract syntax identifier:
// afc07e2e-311c-4435-808c-c483ffeec7c9, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0xafc07e2e, B: 0x311c, C: 0x4435, D: 0x808c, E: 0xc483ffeec7c9},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumLsarGetAvailableCAPIDs: "LsarGetAvailableCAPIDs",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
