package msdfsnm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DFS_INFO_150 ([MS-DFSNM]). Generated by tools/idlgen; verify pointer/array tags.
type DFS_INFO_150 struct {
	SecurityDescriptorLength ndr.DWORD
	PSecurityDescriptor      []uint8 `ndr:"unique,size_is=SecurityDescriptorLength"`
}
