package msdfsnm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// DFS_INFO_8 ([MS-DFSNM]). Generated by tools/idlgen; verify pointer/array tags.
type DFS_INFO_8 struct {
	EntryPath                *ndr.WSTR `ndr:"unique"`
	Comment                  *ndr.WSTR `ndr:"unique"`
	State                    ndr.DWORD
	Timeout                  ndr.DWORD
	Guid                     guid.GUID
	PropertyFlags            ndr.DWORD
	MetadataSize             ndr.DWORD
	SecurityDescriptorLength ndr.DWORD
	PSecurityDescriptor      []uint8 `ndr:"unique,size_is=SecurityDescriptorLength"`
	NumberOfStorages         ndr.DWORD
}
