package msdfsnm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DFS_INFO_3 ([MS-DFSNM]). Generated by tools/idlgen; verify pointer/array tags.
type DFS_INFO_3 struct {
	EntryPath        *ndr.WSTR `ndr:"unique"`
	Comment          *ndr.WSTR `ndr:"unique"`
	State            ndr.DWORD
	NumberOfStorages ndr.DWORD
	Storage          []DFS_STORAGE_INFO `ndr:"unique,size_is=NumberOfStorages"`
}
