package msdfsnm

// DFS_NAMESPACE_VERSION_ORIGIN is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-DFSNM]).
type DFS_NAMESPACE_VERSION_ORIGIN uint16

const (
	DFS_NAMESPACE_VERSION_ORIGIN_COMBINED DFS_NAMESPACE_VERSION_ORIGIN = 0
	DFS_NAMESPACE_VERSION_ORIGIN_SERVER   DFS_NAMESPACE_VERSION_ORIGIN = 1
	DFS_NAMESPACE_VERSION_ORIGIN_DOMAIN   DFS_NAMESPACE_VERSION_ORIGIN = 2
)
