package msdfsnm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DFS_INFO_STRUCT is a discriminated union ([MS-DFSNM]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type DFS_INFO_STRUCT struct {
	Tag        ndr.DWORD     `ndr:"switch"`
	DfsInfo1   *DFS_INFO_1   `ndr:"case=1,unique"`
	DfsInfo2   *DFS_INFO_2   `ndr:"case=2,unique"`
	DfsInfo3   *DFS_INFO_3   `ndr:"case=3,unique"`
	DfsInfo4   *DFS_INFO_4   `ndr:"case=4,unique"`
	DfsInfo5   *DFS_INFO_5   `ndr:"case=5,unique"`
	DfsInfo6   *DFS_INFO_6   `ndr:"case=6,unique"`
	DfsInfo7   *DFS_INFO_7   `ndr:"case=7,unique"`
	DfsInfo8   *DFS_INFO_8   `ndr:"case=8,unique"`
	DfsInfo9   *DFS_INFO_9   `ndr:"case=9,unique"`
	DfsInfo50  *DFS_INFO_50  `ndr:"case=50,unique"`
	DfsInfo100 *DFS_INFO_100 `ndr:"case=100,unique"`
	DfsInfo101 *DFS_INFO_101 `ndr:"case=101,unique"`
	DfsInfo102 *DFS_INFO_102 `ndr:"case=102,unique"`
	DfsInfo103 *DFS_INFO_103 `ndr:"case=103,unique"`
	DfsInfo104 *DFS_INFO_104 `ndr:"case=104,unique"`
	DfsInfo105 *DFS_INFO_105 `ndr:"case=105,unique"`
	DfsInfo106 *DFS_INFO_106 `ndr:"case=106,unique"`
	DfsInfo107 *DFS_INFO_107 `ndr:"case=107,unique"`
	DfsInfo150 *DFS_INFO_150 `ndr:"case=150,unique"`
}
