package msdfsnm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DFS_INFO_2_CONTAINER ([MS-DFSNM]). Generated by tools/idlgen; verify pointer/array tags.
type DFS_INFO_2_CONTAINER struct {
	EntriesRead ndr.DWORD
	Buffer      []DFS_INFO_2 `ndr:"unique,size_is=EntriesRead"`
}
