package msdfsnm

import (
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// DFS_INFO_7 ([MS-DFSNM]). Generated by tools/idlgen; verify pointer/array tags.
type DFS_INFO_7 struct {
	GenerationGuid guid.GUID
}
