package msdfsnm

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DFS_INFO_100 ([MS-DFSNM]). Generated by tools/idlgen; verify pointer/array tags.
type DFS_INFO_100 struct {
	Comment *ndr.WSTR `ndr:"unique"`
}
