package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_ZONE_DATABASE_W2K ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_ZONE_DATABASE_W2K struct {
	FDsIntegrated ndr.DWORD
	PszFileName   *ndr.STR `ndr:"unique"`
}
