package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_IP_VALIDATE ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_IP_VALIDATE struct {
	DwRpcStructureVersion ndr.DWORD
	DwReserved0           ndr.DWORD
	DwContext             ndr.DWORD
	DwReserved1           ndr.DWORD
	PszContextName        *ndr.STR        `ndr:"unique"`
	AipValidateAddrs      *DNS_ADDR_ARRAY `ndr:"unique"`
}
