package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_SKD_LIST ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_SKD_LIST struct {
	DwRpcStructureVersion ndr.DWORD
	DwReserved0           ndr.DWORD
	DwCount               ndr.DWORD
	SkdArray              []*DNS_RPC_SKD `ndr:"conformant,size_is=DwCount,elem=unique"`
}
