package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_FORWARDERS_W2K ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_FORWARDERS_W2K struct {
	FRecurseAfterForwarding ndr.DWORD
	DwForwardTimeout        ndr.DWORD
	AipForwarders           *IP4_ARRAY `ndr:"unique"`
}
