package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_ZONE_W2K ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_ZONE_W2K struct {
	PszZoneName *ndr.WSTR `ndr:"unique"`
	Flags       ndr.DWORD
	ZoneType    uint8
	Version     uint8
}
