package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_DP_ENUM ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_DP_ENUM struct {
	DwRpcStructureVersion ndr.DWORD
	DwReserved0           ndr.DWORD
	PszDpFqdn             *ndr.STR `ndr:"unique"`
	DwFlags               ndr.DWORD
	DwZoneCount           ndr.DWORD
}
