package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_AUTOCONFIGURE ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_AUTOCONFIGURE struct {
	DwRpcStructureVersion ndr.DWORD
	DwReserved0           ndr.DWORD
	DwAutoConfigFlags     ndr.DWORD
	DwReserved1           ndr.DWORD
	PszNewDomainName      *ndr.STR `ndr:"unique"`
}
