package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_BUFFER ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_BUFFER struct {
	DwLength ndr.DWORD
	Buffer   []uint8 `ndr:"conformant,size_is=DwLength"`
}
