package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	msdtyp "github.com/TheManticoreProject/Manticore/windows/ms-dtyp"
)

// DNS_RPC_SKD_STATE ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_SKD_STATE struct {
	DwRpcStructureVersion   ndr.DWORD
	DwReserved0             ndr.DWORD
	Guid                    msdtyp.GUID
	FtLastRolloverTime      msdtyp.FILETIME
	FtNextRolloverTime      msdtyp.FILETIME
	DwState                 ndr.DWORD
	DwCurrentRolloverStatus ndr.DWORD
	PwszActiveKey           *ndr.WSTR `ndr:"unique"`
	PwszStandbyKey          *ndr.WSTR `ndr:"unique"`
	PwszNextKey             *ndr.WSTR `ndr:"unique"`
	DwReserved              ndr.DWORD
}
