package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_SERVER_INFO_LONGHORN ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_SERVER_INFO_LONGHORN struct {
	DwRpcStructureVersion       ndr.DWORD
	DwReserved0                 ndr.DWORD
	DwVersion                   ndr.DWORD
	FBootMethod                 uint8
	FAdminConfigured            bool
	FAllowUpdate                bool
	FDsAvailable                bool
	PszServerName               *ndr.STR        `ndr:"unique"`
	PszDsContainer              *ndr.WSTR       `ndr:"unique"`
	AipServerAddrs              *DNS_ADDR_ARRAY `ndr:"unique"`
	AipListenAddrs              *DNS_ADDR_ARRAY `ndr:"unique"`
	AipForwarders               *DNS_ADDR_ARRAY `ndr:"unique"`
	AipLogFilter                *DNS_ADDR_ARRAY `ndr:"unique"`
	PwszLogFilePath             *ndr.WSTR       `ndr:"unique"`
	PszDomainName               *ndr.STR        `ndr:"unique"`
	PszForestName               *ndr.STR        `ndr:"unique"`
	PszDomainDirectoryPartition *ndr.STR        `ndr:"unique"`
	PszForestDirectoryPartition *ndr.STR        `ndr:"unique"`
	PExtensions                 [6]*ndr.STR
	DwLogLevel                  ndr.DWORD
	DwDebugLevel                ndr.DWORD
	DwForwardTimeout            ndr.DWORD
	DwRpcProtocol               ndr.DWORD
	DwNameCheckFlag             ndr.DWORD
	CAddressAnswerLimit         ndr.DWORD
	DwRecursionRetry            ndr.DWORD
	DwRecursionTimeout          ndr.DWORD
	DwMaxCacheTtl               ndr.DWORD
	DwDsPollingInterval         ndr.DWORD
	DwLocalNetPriorityNetMask   ndr.DWORD
	DwScavengingInterval        ndr.DWORD
	DwDefaultRefreshInterval    ndr.DWORD
	DwDefaultNoRefreshInterval  ndr.DWORD
	DwLastScavengeTime          ndr.DWORD
	DwEventLogLevel             ndr.DWORD
	DwLogFileMaxSize            ndr.DWORD
	DwDsForestVersion           ndr.DWORD
	DwDsDomainVersion           ndr.DWORD
	DwDsDsaVersion              ndr.DWORD
	FReadOnlyDC                 bool
	DwReserveArray              [3]ndr.DWORD
	FAutoReverseZones           bool
	FAutoCacheUpdate            bool
	FRecurseAfterForwarding     bool
	FForwardDelegations         bool
	FNoRecursion                bool
	FSecureResponses            bool
	FRoundRobin                 bool
	FLocalNetPriority           bool
	FBindSecondaries            bool
	FWriteAuthorityNs           bool
	FStrictFileParsing          bool
	FLooseWildcarding           bool
	FDefaultAgingState          bool
	FReserveArray               [15]bool
}

// DNS_RPC_SERVER_INFO is an alias for DNS_RPC_SERVER_INFO_LONGHORN (same IDL typedef).
type DNS_RPC_SERVER_INFO = DNS_RPC_SERVER_INFO_LONGHORN
