package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_ZONE_SCOPE_CREATE_INFO_V1 ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_ZONE_SCOPE_CREATE_INFO_V1 struct {
	DwFlags       ndr.DWORD
	PwszScopeName *ndr.WSTR `ndr:"unique"`
}
