package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_ENUM_ZONE_SCOPE_LIST ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_ENUM_ZONE_SCOPE_LIST struct {
	DwRpcStructureVersion ndr.DWORD
	DwZoneScopeCount      ndr.DWORD
	ZoneScopeArray        [1]*ndr.WSTR
}
