package msdnsp

// DNS_RPC_TYPEID enumerates the type ids that discriminate DNSSRV_RPC_UNION ([MS-DNSP]
// 2.2.1.1.1). It is not itself transmitted on the wire: the union discriminant is the
// method's dwTypeId/dwTypeIn/pdwTypeId parameter, a DWORD ([MS-DNSP] 3.1.4). Modeled as
// a uint32 (not the usual 16-bit NDR enum) so the DNSSRV_TYPEID_ANY sentinel (-1) fits.
type DNS_RPC_TYPEID uint32

const (
	DNSSRV_TYPEID_ANY                          DNS_RPC_TYPEID = 0xFFFFFFFF
	DNSSRV_TYPEID_NULL                         DNS_RPC_TYPEID = 0
	DNSSRV_TYPEID_DWORD                        DNS_RPC_TYPEID = 1
	DNSSRV_TYPEID_LPSTR                        DNS_RPC_TYPEID = 2
	DNSSRV_TYPEID_LPWSTR                       DNS_RPC_TYPEID = 3
	DNSSRV_TYPEID_IPARRAY                      DNS_RPC_TYPEID = 4
	DNSSRV_TYPEID_BUFFER                       DNS_RPC_TYPEID = 5
	DNSSRV_TYPEID_SERVER_INFO_W2K              DNS_RPC_TYPEID = 6
	DNSSRV_TYPEID_STATS                        DNS_RPC_TYPEID = 7
	DNSSRV_TYPEID_FORWARDERS_W2K               DNS_RPC_TYPEID = 8
	DNSSRV_TYPEID_ZONE_W2K                     DNS_RPC_TYPEID = 9
	DNSSRV_TYPEID_ZONE_INFO_W2K                DNS_RPC_TYPEID = 10
	DNSSRV_TYPEID_ZONE_SECONDARIES_W2K         DNS_RPC_TYPEID = 11
	DNSSRV_TYPEID_ZONE_DATABASE_W2K            DNS_RPC_TYPEID = 12
	DNSSRV_TYPEID_ZONE_TYPE_RESET_W2K          DNS_RPC_TYPEID = 13
	DNSSRV_TYPEID_ZONE_CREATE_W2K              DNS_RPC_TYPEID = 14
	DNSSRV_TYPEID_NAME_AND_PARAM               DNS_RPC_TYPEID = 15
	DNSSRV_TYPEID_ZONE_LIST_W2K                DNS_RPC_TYPEID = 16
	DNSSRV_TYPEID_ZONE_RENAME                  DNS_RPC_TYPEID = 17
	DNSSRV_TYPEID_ZONE_EXPORT                  DNS_RPC_TYPEID = 18
	DNSSRV_TYPEID_SERVER_INFO_DOTNET           DNS_RPC_TYPEID = 19
	DNSSRV_TYPEID_FORWARDERS_DOTNET            DNS_RPC_TYPEID = 20
	DNSSRV_TYPEID_ZONE                         DNS_RPC_TYPEID = 21
	DNSSRV_TYPEID_ZONE_INFO_DOTNET             DNS_RPC_TYPEID = 22
	DNSSRV_TYPEID_ZONE_SECONDARIES_DOTNET      DNS_RPC_TYPEID = 23
	DNSSRV_TYPEID_ZONE_DATABASE                DNS_RPC_TYPEID = 24
	DNSSRV_TYPEID_ZONE_TYPE_RESET_DOTNET       DNS_RPC_TYPEID = 25
	DNSSRV_TYPEID_ZONE_CREATE_DOTNET           DNS_RPC_TYPEID = 26
	DNSSRV_TYPEID_ZONE_LIST                    DNS_RPC_TYPEID = 27
	DNSSRV_TYPEID_DP_ENUM                      DNS_RPC_TYPEID = 28
	DNSSRV_TYPEID_DP_INFO                      DNS_RPC_TYPEID = 29
	DNSSRV_TYPEID_DP_LIST                      DNS_RPC_TYPEID = 30
	DNSSRV_TYPEID_ENLIST_DP                    DNS_RPC_TYPEID = 31
	DNSSRV_TYPEID_ZONE_CHANGE_DP               DNS_RPC_TYPEID = 32
	DNSSRV_TYPEID_ENUM_ZONES_FILTER            DNS_RPC_TYPEID = 33
	DNSSRV_TYPEID_ADDRARRAY                    DNS_RPC_TYPEID = 34
	DNSSRV_TYPEID_SERVER_INFO                  DNS_RPC_TYPEID = 35
	DNSSRV_TYPEID_ZONE_INFO                    DNS_RPC_TYPEID = 36
	DNSSRV_TYPEID_FORWARDERS                   DNS_RPC_TYPEID = 37
	DNSSRV_TYPEID_ZONE_SECONDARIES             DNS_RPC_TYPEID = 38
	DNSSRV_TYPEID_ZONE_TYPE_RESET              DNS_RPC_TYPEID = 39
	DNSSRV_TYPEID_ZONE_CREATE                  DNS_RPC_TYPEID = 40
	DNSSRV_TYPEID_IP_VALIDATE                  DNS_RPC_TYPEID = 41
	DNSSRV_TYPEID_AUTOCONFIGURE                DNS_RPC_TYPEID = 42
	DNSSRV_TYPEID_UTF8_STRING_LIST             DNS_RPC_TYPEID = 43
	DNSSRV_TYPEID_UNICODE_STRING_LIST          DNS_RPC_TYPEID = 44
	DNSSRV_TYPEID_SKD                          DNS_RPC_TYPEID = 45
	DNSSRV_TYPEID_SKD_LIST                     DNS_RPC_TYPEID = 46
	DNSSRV_TYPEID_SKD_STATE                    DNS_RPC_TYPEID = 47
	DNSSRV_TYPEID_SIGNING_VALIDATION_ERROR     DNS_RPC_TYPEID = 48
	DNSSRV_TYPEID_TRUST_POINT_LIST             DNS_RPC_TYPEID = 49
	DNSSRV_TYPEID_TRUST_ANCHOR_LIST            DNS_RPC_TYPEID = 50
	DNSSRV_TYPEID_ZONE_SIGNING_SETTINGS        DNS_RPC_TYPEID = 51
	DNSSRV_TYPEID_ZONE_SCOPE_ENUM              DNS_RPC_TYPEID = 52
	DNSSRV_TYPEID_ZONE_STATS                   DNS_RPC_TYPEID = 53
	DNSSRV_TYPEID_ZONE_SCOPE_CREATE            DNS_RPC_TYPEID = 54
	DNSSRV_TYPEID_ZONE_SCOPE_INFO              DNS_RPC_TYPEID = 55
	DNSSRV_TYPEID_SCOPE_ENUM                   DNS_RPC_TYPEID = 56
	DNSSRV_TYPEID_CLIENT_SUBNET_RECORD         DNS_RPC_TYPEID = 57
	DNSSRV_TYPEID_POLICY                       DNS_RPC_TYPEID = 58
	DNSSRV_TYPEID_POLICY_NAME                  DNS_RPC_TYPEID = 59
	DNSSRV_TYPEID_POLICY_ENUM                  DNS_RPC_TYPEID = 60
	DNSSRV_TYPEID_RRL                          DNS_RPC_TYPEID = 61
	DNSSRV_TYPEID_VIRTUALIZATION_INSTANCE      DNS_RPC_TYPEID = 62
	DNSSRV_TYPEID_VIRTUALIZATION_INSTANCE_ENUM DNS_RPC_TYPEID = 63
	DNSSRV_TYPEID_ENCRYPTION_CONFIG            DNS_RPC_TYPEID = 64
)
