package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_POLICY_CONTENT ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_POLICY_CONTENT struct {
	PwszScopeName *ndr.WSTR `ndr:"unique"`
	DwWeight      ndr.DWORD
}
