package msdnsp

// DNS_ZONE_STATS_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-DNSP]).
type DNS_ZONE_STATS_TYPE uint16

const (
	ZONE_STATS_TYPE_RECORD_A      DNS_ZONE_STATS_TYPE = 0
	ZONE_STATS_TYPE_RECORD_AAAA   DNS_ZONE_STATS_TYPE = 1
	ZONE_STATS_TYPE_RECORD_PTR    DNS_ZONE_STATS_TYPE = 2
	ZONE_STATS_TYPE_RECORD_CNAME  DNS_ZONE_STATS_TYPE = 3
	ZONE_STATS_TYPE_RECORD_MX     DNS_ZONE_STATS_TYPE = 4
	ZONE_STATS_TYPE_RECORD_AFSDB  DNS_ZONE_STATS_TYPE = 5
	ZONE_STATS_TYPE_RECORD_ATMA   DNS_ZONE_STATS_TYPE = 6
	ZONE_STATS_TYPE_RECORD_DHCID  DNS_ZONE_STATS_TYPE = 7
	ZONE_STATS_TYPE_RECORD_DNAME  DNS_ZONE_STATS_TYPE = 8
	ZONE_STATS_TYPE_RECORD_HINFO  DNS_ZONE_STATS_TYPE = 9
	ZONE_STATS_TYPE_RECORD_ISDN   DNS_ZONE_STATS_TYPE = 10
	ZONE_STATS_TYPE_RECORD_MG     DNS_ZONE_STATS_TYPE = 11
	ZONE_STATS_TYPE_RECORD_MB     DNS_ZONE_STATS_TYPE = 12
	ZONE_STATS_TYPE_RECORD_MINFO  DNS_ZONE_STATS_TYPE = 13
	ZONE_STATS_TYPE_RECORD_NAPTR  DNS_ZONE_STATS_TYPE = 14
	ZONE_STATS_TYPE_RECORD_NXT    DNS_ZONE_STATS_TYPE = 15
	ZONE_STATS_TYPE_RECORD_KEY    DNS_ZONE_STATS_TYPE = 16
	ZONE_STATS_TYPE_RECORD_MR     DNS_ZONE_STATS_TYPE = 17
	ZONE_STATS_TYPE_RECORD_RP     DNS_ZONE_STATS_TYPE = 18
	ZONE_STATS_TYPE_RECORD_RT     DNS_ZONE_STATS_TYPE = 19
	ZONE_STATS_TYPE_RECORD_SRV    DNS_ZONE_STATS_TYPE = 20
	ZONE_STATS_TYPE_RECORD_SIG    DNS_ZONE_STATS_TYPE = 21
	ZONE_STATS_TYPE_RECORD_TEXT   DNS_ZONE_STATS_TYPE = 22
	ZONE_STATS_TYPE_RECORD_WKS    DNS_ZONE_STATS_TYPE = 23
	ZONE_STATS_TYPE_RECORD_X25    DNS_ZONE_STATS_TYPE = 24
	ZONE_STATS_TYPE_RECORD_DNSKEY DNS_ZONE_STATS_TYPE = 25
	ZONE_STATS_TYPE_RECORD_DS     DNS_ZONE_STATS_TYPE = 26
	ZONE_STATS_TYPE_RECORD_NS     DNS_ZONE_STATS_TYPE = 27
	ZONE_STATS_TYPE_RECORD_SOA    DNS_ZONE_STATS_TYPE = 28
	ZONE_STATS_TYPE_RECORD_TLSA   DNS_ZONE_STATS_TYPE = 29
	ZONE_STATS_TYPE_RECORD_ALL    DNS_ZONE_STATS_TYPE = 30
	ZONE_STATS_TYPE_RECORD_OTHERS DNS_ZONE_STATS_TYPE = 31
	ZONE_STATS_TYPE_TRANSFER_AXFR DNS_ZONE_STATS_TYPE = 32
	ZONE_STATS_TYPE_TRANSFER_IXFR DNS_ZONE_STATS_TYPE = 33
	ZONE_STATS_TYPE_UPDATE        DNS_ZONE_STATS_TYPE = 34
	ZONE_STATS_TYPE_RRL           DNS_ZONE_STATS_TYPE = 35
	MAX_ZONE_STATS_TYPES          DNS_ZONE_STATS_TYPE = 36
)
