package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_ZONE_DOTNET ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_ZONE_DOTNET struct {
	DwRpcStructureVersion ndr.DWORD
	DwReserved0           ndr.DWORD
	PszZoneName           *ndr.WSTR `ndr:"unique"`
	Flags                 ndr.DWORD
	ZoneType              uint8
	Version               uint8
	DwDpFlags             ndr.DWORD
	PszDpFqdn             *ndr.STR `ndr:"unique"`
}

// DNS_RPC_ZONE is an alias for DNS_RPC_ZONE_DOTNET (same IDL typedef).
type DNS_RPC_ZONE = DNS_RPC_ZONE_DOTNET
