package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_ENUM_VIRTUALIZATION_INSTANCE_LIST ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_ENUM_VIRTUALIZATION_INSTANCE_LIST struct {
	DwRpcStructureVersion         ndr.DWORD
	DwVirtualizationInstanceCount ndr.DWORD
	VirtualizationInstanceArray   [1]*DNS_RPC_VIRTUALIZATION_INSTANCE_INFO
}
