package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_ZONE_SECONDARIES_W2K ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_ZONE_SECONDARIES_W2K struct {
	FSecureSecondaries ndr.DWORD
	FNotifyLevel       ndr.DWORD
	AipSecondaries     *IP4_ARRAY `ndr:"unique"`
	AipNotify          *IP4_ARRAY `ndr:"unique"`
}
