package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_ZONE_CREATE_INFO_LONGHORN ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_ZONE_CREATE_INFO_LONGHORN struct {
	DwRpcStructureVersion   ndr.DWORD
	DwReserved0             ndr.DWORD
	PszZoneName             *ndr.STR `ndr:"unique"`
	DwZoneType              ndr.DWORD
	FAllowUpdate            ndr.DWORD
	FAging                  ndr.DWORD
	DwFlags                 ndr.DWORD
	PszDataFile             *ndr.STR `ndr:"unique"`
	FDsIntegrated           ndr.DWORD
	FLoadExisting           ndr.DWORD
	PszAdmin                *ndr.STR        `ndr:"unique"`
	AipMasters              *DNS_ADDR_ARRAY `ndr:"unique"`
	AipSecondaries          *DNS_ADDR_ARRAY `ndr:"unique"`
	FSecureSecondaries      ndr.DWORD
	FNotifyLevel            ndr.DWORD
	DwTimeout               ndr.DWORD
	FRecurseAfterForwarding ndr.DWORD
	DwDpFlags               ndr.DWORD
	PszDpFqdn               *ndr.STR `ndr:"unique"`
	DwReserved              [32]ndr.DWORD
}

// DNS_RPC_ZONE_CREATE_INFO is an alias for DNS_RPC_ZONE_CREATE_INFO_LONGHORN (same IDL typedef).
type DNS_RPC_ZONE_CREATE_INFO = DNS_RPC_ZONE_CREATE_INFO_LONGHORN
