package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/dtyp"
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_SIGNING_VALIDATION_ERROR ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_SIGNING_VALIDATION_ERROR struct {
	DwRpcStructureVersion       ndr.DWORD
	DwReserved0                 ndr.DWORD
	GuidSKD                     dtyp.GUID
	PwszSigningKeyPointerString *ndr.WSTR `ndr:"unique"`
	DwExtendedError             ndr.DWORD
	DwReserved                  ndr.DWORD
}
