package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_ZONE_CREATE_INFO_W2K ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_ZONE_CREATE_INFO_W2K struct {
	PszZoneName        *ndr.STR `ndr:"unique"`
	DwZoneType         ndr.DWORD
	FAllowUpdate       ndr.DWORD
	FAging             ndr.DWORD
	DwFlags            ndr.DWORD
	PszDataFile        *ndr.STR `ndr:"unique"`
	FDsIntegrated      ndr.DWORD
	FLoadExisting      ndr.DWORD
	PszAdmin           *ndr.STR   `ndr:"unique"`
	AipMasters         *IP4_ARRAY `ndr:"unique"`
	AipSecondaries     *IP4_ARRAY `ndr:"unique"`
	FSecureSecondaries ndr.DWORD
	FNotifyLevel       ndr.DWORD
	PvReserved1        *ndr.STR `ndr:"unique"`
	PvReserved2        *ndr.STR `ndr:"unique"`
	PvReserved3        *ndr.STR `ndr:"unique"`
	PvReserved4        *ndr.STR `ndr:"unique"`
	PvReserved5        *ndr.STR `ndr:"unique"`
	PvReserved6        *ndr.STR `ndr:"unique"`
	PvReserved7        *ndr.STR `ndr:"unique"`
	PvReserved8        *ndr.STR `ndr:"unique"`
	DwReserved1        ndr.DWORD
	DwReserved2        ndr.DWORD
	DwReserved3        ndr.DWORD
	DwReserved4        ndr.DWORD
	DwReserved5        ndr.DWORD
	DwReserved6        ndr.DWORD
	DwReserved7        ndr.DWORD
	DwReserved8        ndr.DWORD
}
