package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_DP_LIST ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_DP_LIST struct {
	DwRpcStructureVersion ndr.DWORD
	DwReserved0           ndr.DWORD
	DwDpCount             ndr.DWORD
	DpArray               []*DNS_RPC_DP_ENUM `ndr:"conformant,size_is=DwDpCount,elem=unique"`
}
