package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_SERVER_INFO_W2K ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_SERVER_INFO_W2K struct {
	DwVersion                  ndr.DWORD
	FBootMethod                uint8
	FAdminConfigured           bool
	FAllowUpdate               bool
	FDsAvailable               bool
	PszServerName              *ndr.STR   `ndr:"unique"`
	PszDsContainer             *ndr.WSTR  `ndr:"unique"`
	AipServerAddrs             *IP4_ARRAY `ndr:"unique"`
	AipListenAddrs             *IP4_ARRAY `ndr:"unique"`
	AipForwarders              *IP4_ARRAY `ndr:"unique"`
	PExtension1                *ndr.DWORD `ndr:"unique"`
	PExtension2                *ndr.DWORD `ndr:"unique"`
	PExtension3                *ndr.DWORD `ndr:"unique"`
	PExtension4                *ndr.DWORD `ndr:"unique"`
	PExtension5                *ndr.DWORD `ndr:"unique"`
	DwLogLevel                 ndr.DWORD
	DwDebugLevel               ndr.DWORD
	DwForwardTimeout           ndr.DWORD
	DwRpcProtocol              ndr.DWORD
	DwNameCheckFlag            ndr.DWORD
	CAddressAnswerLimit        ndr.DWORD
	DwRecursionRetry           ndr.DWORD
	DwRecursionTimeout         ndr.DWORD
	DwMaxCacheTtl              ndr.DWORD
	DwDsPollingInterval        ndr.DWORD
	DwScavengingInterval       ndr.DWORD
	DwDefaultRefreshInterval   ndr.DWORD
	DwDefaultNoRefreshInterval ndr.DWORD
	DwReserveArray             [10]ndr.DWORD
	FAutoReverseZones          bool
	FAutoCacheUpdate           bool
	FRecurseAfterForwarding    bool
	FForwardDelegations        bool
	FNoRecursion               bool
	FSecureResponses           bool
	FRoundRobin                bool
	FLocalNetPriority          bool
	FBindSecondaries           bool
	FWriteAuthorityNs          bool
	FStrictFileParsing         bool
	FLooseWildcarding          bool
	FDefaultAgingState         bool
	FReserveArray              [15]bool
}
