package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_CRITERIA ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_CRITERIA struct {
	Type      DNS_RPC_CRITERIA_ENUM
	PCriteria *ndr.WSTR `ndr:"unique"`
}
