package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_ZONE_SKD ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_ZONE_SKD struct {
	DwRpcStructureVersion ndr.DWORD
	DwReserved0           ndr.DWORD
	PSkd                  *DNS_RPC_SKD          `ndr:"unique"`
	PSkdState             *DNS_RPC_SKD_STATE    `ndr:"unique"`
	PSkdStateEx           *DNS_RPC_SKD_STATE_EX `ndr:"unique"`
}
