package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/dtyp"
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_SKD ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_SKD struct {
	DwRpcStructureVersion             ndr.DWORD
	DwReserved0                       ndr.DWORD
	Guid                              dtyp.GUID
	PwszKeyStorageProvider            *ndr.WSTR `ndr:"unique"`
	FStoreKeysInDirectory             ndr.BOOL
	FIsKSK                            ndr.BOOL
	BSigningAlgorithm                 uint8
	DwKeyLength                       ndr.DWORD
	DwInitialRolloverOffset           ndr.DWORD
	DwDNSKEYSignatureValidityPeriod   ndr.DWORD
	DwDSSignatureValidityPeriod       ndr.DWORD
	DwStandardSignatureValidityPeriod ndr.DWORD
	DwRolloverType                    ndr.DWORD
	DwRolloverPeriod                  ndr.DWORD
	DwNextRolloverAction              ndr.DWORD
	DwReserved                        ndr.DWORD
}
