package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_ENUM_SCOPE_LIST ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_ENUM_SCOPE_LIST struct {
	DwRpcStructureVersion ndr.DWORD
	DwScopeCount          ndr.DWORD
	ScopeArray            [1]*ndr.WSTR
}
