package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_DP_REPLICA ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_DP_REPLICA struct {
	PszReplicaDn *ndr.WSTR `ndr:"unique"`
}
