package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNS_RPC_POLICY_NAME ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNS_RPC_POLICY_NAME struct {
	PwszPolicyName  *ndr.WSTR `ndr:"unique"`
	AppliesOn       DNS_RPC_POLICY_TYPE
	FEnabled        ndr.BOOL
	ProcessingOrder ndr.DWORD
}
