package msdnsp

// DNSSRV_ZONE_TRANSFER_STATS ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNSSRV_ZONE_TRANSFER_STATS struct {
	TransferType     DNS_ZONE_STATS_TYPE
	RequestReceived  uint64
	RequestSent      uint64
	ResponseReceived uint64
	SuccessReceived  uint64
	SuccessSent      uint64
}
