package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DNSSRV_RRL_STATS ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type DNSSRV_RRL_STATS struct {
	Header                  DNSSRV_STAT_HEADER
	TotalResponsesSent      ndr.DWORD
	TotalResponsesDropped   ndr.DWORD
	TotalResponsesTruncated ndr.DWORD
	TotalResponsesLeaked    ndr.DWORD
}
