package msdnsp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// IP4_ARRAY ([MS-DNSP]). Generated by tools/idlgen; verify pointer/array tags.
type IP4_ARRAY struct {
	AddrCount ndr.DWORD
	AddrArray []ndr.DWORD `ndr:"conformant,size_is=AddrCount"`
}
