package msdnsp

// TRUSTANCHOR_STATE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-DNSP]).
type TRUSTANCHOR_STATE uint16

const (
	TRUSTANCHOR_STATE_INITIALIZED TRUSTANCHOR_STATE = 0
	TRUSTANCHOR_STATE_DSPENDING   TRUSTANCHOR_STATE = 1
	TRUSTANCHOR_STATE_DSINVALID   TRUSTANCHOR_STATE = 2
	TRUSTANCHOR_STATE_ADDPEND     TRUSTANCHOR_STATE = 3
	TRUSTANCHOR_STATE_VALID       TRUSTANCHOR_STATE = 4
	TRUSTANCHOR_STATE_MISSING     TRUSTANCHOR_STATE = 5
	TRUSTANCHOR_STATE_REVOKED     TRUSTANCHOR_STATE = 6
	TRUSTANCHOR_STATE_DELETED     TRUSTANCHOR_STATE = 7
)
