package msdnsp

// TRUSTPOINT_STATE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-DNSP]).
type TRUSTPOINT_STATE uint16

const (
	TRUSTPOINT_STATE_INITIALIZED    TRUSTPOINT_STATE = 0
	TRUSTPOINT_STATE_DSPENDING      TRUSTPOINT_STATE = 1
	TRUSTPOINT_STATE_ACTIVE         TRUSTPOINT_STATE = 2
	TRUSTPOINT_STATE_DELETE_PENDING TRUSTPOINT_STATE = 3
	TRUSTPOINT_STATE_DELETED        TRUSTPOINT_STATE = 4
)
