package msraa

// AUTHZ_SECURITY_ATTRIBUTE_OPERATION is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-RAA]).
type AUTHZ_SECURITY_ATTRIBUTE_OPERATION uint16

const (
	AUTHZ_SECURITY_ATTRIBUTE_OPERATION_NONE        AUTHZ_SECURITY_ATTRIBUTE_OPERATION = 0
	AUTHZ_SECURITY_ATTRIBUTE_OPERATION_REPLACE_ALL AUTHZ_SECURITY_ATTRIBUTE_OPERATION = 1
	AUTHZ_SECURITY_ATTRIBUTE_OPERATION_ADD         AUTHZ_SECURITY_ATTRIBUTE_OPERATION = 2
	AUTHZ_SECURITY_ATTRIBUTE_OPERATION_DELETE      AUTHZ_SECURITY_ATTRIBUTE_OPERATION = 3
	AUTHZ_SECURITY_ATTRIBUTE_OPERATION_REPLACE     AUTHZ_SECURITY_ATTRIBUTE_OPERATION = 4
)
