package msraa

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/dtyp"
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// AUTHZR_ACCESS_REQUEST ([MS-RAA]). Generated by tools/idlgen; verify pointer/array tags.
type AUTHZR_ACCESS_REQUEST struct {
	DesiredAccess        ndr.DWORD
	PrincipalSelfSid     *dtyp.RPC_SID `ndr:"unique"`
	ObjectTypeListLength ndr.DWORD
	ObjectTypeList       []OBJECT_TYPE_LIST `ndr:"unique,size_is=ObjectTypeListLength"`
}
