package msraa

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/dtyp"
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// AUTHZR_SID_AND_ATTRIBUTES ([MS-RAA]). Generated by tools/idlgen; verify pointer/array tags.
type AUTHZR_SID_AND_ATTRIBUTES struct {
	Sid        *dtyp.RPC_SID `ndr:"unique"`
	Attributes ndr.DWORD
}
