package msraa

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// AUTHZR_SECURITY_ATTRIBUTES_INFORMATION ([MS-RAA]). Generated by tools/idlgen; verify pointer/array tags.
type AUTHZR_SECURITY_ATTRIBUTES_INFORMATION struct {
	Version        uint16
	Reserved       uint16
	AttributeCount ndr.DWORD
	Attributes     []AUTHZR_SECURITY_ATTRIBUTE_V1 `ndr:"unique,size_is=AttributeCount"`
}
