package msraa

// AUTHZ_SID_OPERATION is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-RAA]).
type AUTHZ_SID_OPERATION uint16

const (
	AUTHZ_SID_OPERATION_NONE        AUTHZ_SID_OPERATION = 0
	AUTHZ_SID_OPERATION_REPLACE_ALL AUTHZ_SID_OPERATION = 1
	AUTHZ_SID_OPERATION_ADD         AUTHZ_SID_OPERATION = 2
	AUTHZ_SID_OPERATION_DELETE      AUTHZ_SID_OPERATION = 3
	AUTHZ_SID_OPERATION_REPLACE     AUTHZ_SID_OPERATION = 4
)
