package msraa

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SR_SD ([MS-RAA]). Generated by tools/idlgen; verify pointer/array tags.
type SR_SD struct {
	DwLength ndr.DWORD
	PSrSd    []uint8 `ndr:"unique,size_is=DwLength"`
}
