package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_ADDRESSES ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_ADDRESSES struct {
	DwV4AddressKeywords ndr.DWORD
	DwV6AddressKeywords ndr.DWORD
	V4SubNets           FW_IPV4_SUBNET_LIST
	V4Ranges            FW_IPV4_RANGE_LIST
	V6SubNets           FW_IPV6_SUBNET_LIST
	V6Ranges            FW_IPV6_RANGE_LIST
}
