package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_AUTH_SET2_10 ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_AUTH_SET2_10 struct {
	PNext              *FW_AUTH_SET2_10 `ndr:"unique"`
	WSchemaVersion     uint16
	IpSecPhase         FW_IPSEC_PHASE
	WszSetId           *ndr.WSTR `ndr:"unique"`
	WszName            *ndr.WSTR `ndr:"unique"`
	WszDescription     *ndr.WSTR `ndr:"unique"`
	WszEmbeddedContext *ndr.WSTR `ndr:"unique"`
	DwNumSuites        ndr.DWORD
	PSuites            []FW_AUTH_SUITE2_10 `ndr:"unique,size_is=DwNumSuites"`
	Origin             FW_RULE_ORIGIN_TYPE
	WszGPOName         *ndr.WSTR `ndr:"unique"`
	Status             FW_RULE_STATUS
	DwAuthSetFlags     ndr.DWORD
}
