package msfasp

// FW_AUTH_SUITE_FLAGS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_AUTH_SUITE_FLAGS uint16

const (
	FW_AUTH_SUITE_FLAGS_NONE                         FW_AUTH_SUITE_FLAGS = 0x0000
	FW_AUTH_SUITE_FLAGS_CERT_EXCLUDE_CA_NAME         FW_AUTH_SUITE_FLAGS = 0x0001
	FW_AUTH_SUITE_FLAGS_HEALTH_CERT                  FW_AUTH_SUITE_FLAGS = 0x0002
	FW_AUTH_SUITE_FLAGS_PERFORM_CERT_ACCOUNT_MAPPING FW_AUTH_SUITE_FLAGS = 0x0004
	FW_AUTH_SUITE_FLAGS_CERT_SIGNING_ECDSA256        FW_AUTH_SUITE_FLAGS = 0x0008
	FW_AUTH_SUITE_FLAGS_CERT_SIGNING_ECDSA384        FW_AUTH_SUITE_FLAGS = 0x0010
	FW_AUTH_SUITE_FLAGS_MAX_V2_1                     FW_AUTH_SUITE_FLAGS = 0x0020
	FW_AUTH_SUITE_FLAGS_INTERMEDIATE_CA              FW_AUTH_SUITE_FLAGS = 0x0020
	FW_AUTH_SUITE_FLAGS_MAX_V2_10                    FW_AUTH_SUITE_FLAGS = 0x0040
	FW_AUTH_SUITE_FLAGS_ALLOW_PROXY                  FW_AUTH_SUITE_FLAGS = 0x0040
	FW_AUTH_SUITE_FLAGS_MAX                          FW_AUTH_SUITE_FLAGS = 0x0080
)
