package msfasp

// FW_AUTH_METHOD is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_AUTH_METHOD uint16

const (
	FW_AUTH_METHOD_INVALID          FW_AUTH_METHOD = 0
	FW_AUTH_METHOD_ANONYMOUS        FW_AUTH_METHOD = 1
	FW_AUTH_METHOD_MACHINE_KERB     FW_AUTH_METHOD = 2
	FW_AUTH_METHOD_MACHINE_SHKEY    FW_AUTH_METHOD = 3
	FW_AUTH_METHOD_MACHINE_NTLM     FW_AUTH_METHOD = 4
	FW_AUTH_METHOD_MACHINE_CERT     FW_AUTH_METHOD = 5
	FW_AUTH_METHOD_USER_KERB        FW_AUTH_METHOD = 6
	FW_AUTH_METHOD_USER_CERT        FW_AUTH_METHOD = 7
	FW_AUTH_METHOD_USER_NTLM        FW_AUTH_METHOD = 8
	FW_AUTH_METHOD_MACHINE_RESERVED FW_AUTH_METHOD = 9
	FW_AUTH_METHOD_USER_RESERVED    FW_AUTH_METHOD = 10
	FW_AUTH_METHOD_MAX              FW_AUTH_METHOD = 11
	FW_AUTH_METHOD_MAX_2_10         FW_AUTH_METHOD = (FW_AUTH_METHOD_USER_NTLM + 1)
)
