package msfasp

// FW_AUTH_CERT_CRITERIA_FLAGS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_AUTH_CERT_CRITERIA_FLAGS uint16

const (
	FW_AUTH_CERT_CRITERIA_FLAGS_NONE           FW_AUTH_CERT_CRITERIA_FLAGS = 0x0000
	FW_AUTH_CERT_CRITERIA_FLAGS_FOLLOW_RENEWAL FW_AUTH_CERT_CRITERIA_FLAGS = 0x0001
	FW_AUTH_CERT_CRITERIA_FLAGS_MAX            FW_AUTH_CERT_CRITERIA_FLAGS = 0x0002
)
