package msfasp

// FW_ADDRESS_KEYWORD is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_ADDRESS_KEYWORD uint16

const (
	FW_ADDRESS_KEYWORD_NONE                     FW_ADDRESS_KEYWORD = 0x0000
	FW_ADDRESS_KEYWORD_LOCAL_SUBNET             FW_ADDRESS_KEYWORD = 0x0001
	FW_ADDRESS_KEYWORD_DNS                      FW_ADDRESS_KEYWORD = 0x0002
	FW_ADDRESS_KEYWORD_DHCP                     FW_ADDRESS_KEYWORD = 0x0004
	FW_ADDRESS_KEYWORD_WINS                     FW_ADDRESS_KEYWORD = 0x0008
	FW_ADDRESS_KEYWORD_DEFAULT_GATEWAY          FW_ADDRESS_KEYWORD = 0x0010
	FW_ADDRESS_KEYWORD_INTRANET                 FW_ADDRESS_KEYWORD = 0x0020
	FW_ADDRESS_KEYWORD_INTERNET                 FW_ADDRESS_KEYWORD = 0x0040
	FW_ADDRESS_KEYWORD_PLAYTO_RENDERERS         FW_ADDRESS_KEYWORD = 0x0080
	FW_ADDRESS_KEYWORD_REMOTE_INTRANET          FW_ADDRESS_KEYWORD = 0x0100
	FW_ADDRESS_KEYWORD_CAPTIVE_PORTAL           FW_ADDRESS_KEYWORD = 0x0200
	FW_ADDRESS_KEYWORD_INTERNAL_LOCAL_ADDRESSES FW_ADDRESS_KEYWORD = 0x0400
	FW_ADDRESS_KEYWORD_MAX_V2_10                FW_ADDRESS_KEYWORD = 0x0020
	FW_ADDRESS_KEYWORD_MAX_V2_29                FW_ADDRESS_KEYWORD = 0x0200
	FW_ADDRESS_KEYWORD_MAX_V2_33                FW_ADDRESS_KEYWORD = 0x0400
	FW_ADDRESS_KEYWORD_MAX                      FW_ADDRESS_KEYWORD = 0x0800
)
