package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_BYTE_BLOB ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_BYTE_BLOB struct {
	DwSize ndr.DWORD
	Blob   []uint8 `ndr:"unique,size_is=DwSize"`
}
