package msfasp

// FW_CRYPTO_KEY_EXCHANGE_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_CRYPTO_KEY_EXCHANGE_TYPE uint16

const (
	FW_CRYPTO_KEY_EXCHANGE_NONE      FW_CRYPTO_KEY_EXCHANGE_TYPE = 0
	FW_CRYPTO_KEY_EXCHANGE_DH1       FW_CRYPTO_KEY_EXCHANGE_TYPE = 1
	FW_CRYPTO_KEY_EXCHANGE_DH2       FW_CRYPTO_KEY_EXCHANGE_TYPE = 2
	FW_CRYPTO_KEY_EXCHANGE_ECDH256   FW_CRYPTO_KEY_EXCHANGE_TYPE = 3
	FW_CRYPTO_KEY_EXCHANGE_ECDH384   FW_CRYPTO_KEY_EXCHANGE_TYPE = 4
	FW_CRYPTO_KEY_EXCHANGE_DH2048    FW_CRYPTO_KEY_EXCHANGE_TYPE = 5
	FW_CRYPTO_KEY_EXCHANGE_DH24      FW_CRYPTO_KEY_EXCHANGE_TYPE = 6
	FW_CRYPTO_KEY_EXCHANGE_MAX       FW_CRYPTO_KEY_EXCHANGE_TYPE = 7
	FW_CRYPTO_KEY_EXCHANGE_DH14      FW_CRYPTO_KEY_EXCHANGE_TYPE = FW_CRYPTO_KEY_EXCHANGE_DH2048
	FW_CRYPTO_KEY_EXCHANGE_MAX_V2_10 FW_CRYPTO_KEY_EXCHANGE_TYPE = FW_CRYPTO_KEY_EXCHANGE_DH24
)
