package msfasp

// FW_CRYPTO_ENCRYPTION_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_CRYPTO_ENCRYPTION_TYPE uint16

const (
	FW_CRYPTO_ENCRYPTION_NONE       FW_CRYPTO_ENCRYPTION_TYPE = 0
	FW_CRYPTO_ENCRYPTION_DES        FW_CRYPTO_ENCRYPTION_TYPE = 1
	FW_CRYPTO_ENCRYPTION_3DES       FW_CRYPTO_ENCRYPTION_TYPE = 2
	FW_CRYPTO_ENCRYPTION_AES128     FW_CRYPTO_ENCRYPTION_TYPE = 3
	FW_CRYPTO_ENCRYPTION_AES192     FW_CRYPTO_ENCRYPTION_TYPE = 4
	FW_CRYPTO_ENCRYPTION_AES256     FW_CRYPTO_ENCRYPTION_TYPE = 5
	FW_CRYPTO_ENCRYPTION_AES_GCM128 FW_CRYPTO_ENCRYPTION_TYPE = 6
	FW_CRYPTO_ENCRYPTION_AES_GCM192 FW_CRYPTO_ENCRYPTION_TYPE = 7
	FW_CRYPTO_ENCRYPTION_AES_GCM256 FW_CRYPTO_ENCRYPTION_TYPE = 8
	FW_CRYPTO_ENCRYPTION_MAX        FW_CRYPTO_ENCRYPTION_TYPE = 9
	FW_CRYPTO_ENCRYPTION_MAX_V2_0   FW_CRYPTO_ENCRYPTION_TYPE = FW_CRYPTO_ENCRYPTION_AES_GCM128
)
