package msfasp

// FW_CRYPTO_PROTOCOL_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_CRYPTO_PROTOCOL_TYPE uint16

const (
	FW_CRYPTO_PROTOCOL_INVALID       FW_CRYPTO_PROTOCOL_TYPE = 0
	FW_CRYPTO_PROTOCOL_AH            FW_CRYPTO_PROTOCOL_TYPE = 1
	FW_CRYPTO_PROTOCOL_ESP           FW_CRYPTO_PROTOCOL_TYPE = 2
	FW_CRYPTO_PROTOCOL_BOTH          FW_CRYPTO_PROTOCOL_TYPE = 3
	FW_CRYPTO_PROTOCOL_AUTH_NO_ENCAP FW_CRYPTO_PROTOCOL_TYPE = 4
	FW_CRYPTO_PROTOCOL_MAX           FW_CRYPTO_PROTOCOL_TYPE = 5
	FW_CRYPTO_PROTOCOL_MAX_2_1       FW_CRYPTO_PROTOCOL_TYPE = (FW_CRYPTO_PROTOCOL_BOTH + 1)
)
