package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_CERT_INFO ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_CERT_INFO struct {
	SubjectName FW_BYTE_BLOB
	DwCertFlags ndr.DWORD
}
