package msfasp

// FW_CRYPTO_HASH_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_CRYPTO_HASH_TYPE uint16

const (
	FW_CRYPTO_HASH_NONE        FW_CRYPTO_HASH_TYPE = 0
	FW_CRYPTO_HASH_MD5         FW_CRYPTO_HASH_TYPE = 1
	FW_CRYPTO_HASH_SHA1        FW_CRYPTO_HASH_TYPE = 2
	FW_CRYPTO_HASH_SHA256      FW_CRYPTO_HASH_TYPE = 3
	FW_CRYPTO_HASH_SHA384      FW_CRYPTO_HASH_TYPE = 4
	FW_CRYPTO_HASH_AES_GMAC128 FW_CRYPTO_HASH_TYPE = 5
	FW_CRYPTO_HASH_AES_GMAC192 FW_CRYPTO_HASH_TYPE = 6
	FW_CRYPTO_HASH_AES_GMAC256 FW_CRYPTO_HASH_TYPE = 7
	FW_CRYPTO_HASH_MAX         FW_CRYPTO_HASH_TYPE = 8
	FW_CRYPTO_HASH_MAX_V2_0    FW_CRYPTO_HASH_TYPE = FW_CRYPTO_HASH_SHA256
)
