package msfasp

// FW_CS_RULE_ACTION is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_CS_RULE_ACTION uint16

const (
	FW_CS_RULE_ACTION_INVALID       FW_CS_RULE_ACTION = 0
	FW_CS_RULE_ACTION_SECURE_SERVER FW_CS_RULE_ACTION = 1
	FW_CS_RULE_ACTION_BOUNDARY      FW_CS_RULE_ACTION = 2
	FW_CS_RULE_ACTION_SECURE        FW_CS_RULE_ACTION = 3
	FW_CS_RULE_ACTION_DO_NOT_SECURE FW_CS_RULE_ACTION = 4
	FW_CS_RULE_ACTION_MAX           FW_CS_RULE_ACTION = 5
)
