package msfasp

// FW_CERT_CRITERIA_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_CERT_CRITERIA_TYPE uint16

const (
	FW_CERT_CRITERIA_TYPE_BOTH       FW_CERT_CRITERIA_TYPE = 0
	FW_CERT_CRITERIA_TYPE_SELECTION  FW_CERT_CRITERIA_TYPE = 1
	FW_CERT_CRITERIA_TYPE_VALIDATION FW_CERT_CRITERIA_TYPE = 2
	FW_CERT_CRITERIA_TYPE_MAX        FW_CERT_CRITERIA_TYPE = 3
)
