package msfasp

// FW_CERT_CRITERIA_NAME_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_CERT_CRITERIA_NAME_TYPE uint16

const (
	FW_CERT_CRITERIA_NAME_NONE   FW_CERT_CRITERIA_NAME_TYPE = 0
	FW_CERT_CRITERIA_NAME_DNS    FW_CERT_CRITERIA_NAME_TYPE = 1
	FW_CERT_CRITERIA_NAME_UPN    FW_CERT_CRITERIA_NAME_TYPE = 2
	FW_CERT_CRITERIA_NAME_RFC822 FW_CERT_CRITERIA_NAME_TYPE = 3
	FW_CERT_CRITERIA_NAME_CN     FW_CERT_CRITERIA_NAME_TYPE = 4
	FW_CERT_CRITERIA_NAME_OU     FW_CERT_CRITERIA_NAME_TYPE = 5
	FW_CERT_CRITERIA_NAME_O      FW_CERT_CRITERIA_NAME_TYPE = 6
	FW_CERT_CRITERIA_NAME_DC     FW_CERT_CRITERIA_NAME_TYPE = 7
	FW_CERT_CRITERIA_NAME_MAX    FW_CERT_CRITERIA_NAME_TYPE = 8
)
