package msfasp

// FW_CS_RULE_FLAGS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_CS_RULE_FLAGS uint16

const (
	FW_CS_RULE_FLAGS_NONE                          FW_CS_RULE_FLAGS = 0x00
	FW_CS_RULE_FLAGS_ACTIVE                        FW_CS_RULE_FLAGS = 0x01
	FW_CS_RULE_FLAGS_DTM                           FW_CS_RULE_FLAGS = 0x02
	FW_CS_RULE_FLAGS_TUNNEL_BYPASS_IF_ENCRYPTED    FW_CS_RULE_FLAGS = 0x08
	FW_CS_RULE_FLAGS_OUTBOUND_CLEAR                FW_CS_RULE_FLAGS = 0x10
	FW_CS_RULE_FLAGS_APPLY_AUTHZ                   FW_CS_RULE_FLAGS = 0x20
	FW_CS_RULE_FLAGS_KEY_MANAGER_ALLOW_DICTATE_KEY FW_CS_RULE_FLAGS = 0x40
	FW_CS_RULE_FLAGS_KEY_MANAGER_ALLOW_NOTIFY_KEY  FW_CS_RULE_FLAGS = 0x80
	FW_CS_RULE_FLAGS_SECURITY_REALM                FW_CS_RULE_FLAGS = 0x100
	FW_CS_RULE_FLAGS_TUNNEL_TYPE_POINT_TO_SITE     FW_CS_RULE_FLAGS = 0x200
	FW_CS_RULE_FLAGS_MAX                           FW_CS_RULE_FLAGS = 0x400
	FW_CS_RULE_FLAGS_MAX_V2_1                      FW_CS_RULE_FLAGS = 0x02
	FW_CS_RULE_FLAGS_MAX_V2_8                      FW_CS_RULE_FLAGS = 0x04
	FW_CS_RULE_FLAGS_MAX_V2_10                     FW_CS_RULE_FLAGS = 0x40
	FW_CS_RULE_FLAGS_MAX_V2_20                     FW_CS_RULE_FLAGS = 0x100
)
