package msfasp

// FW_DYNAMIC_KEYWORD_ORIGIN_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_DYNAMIC_KEYWORD_ORIGIN_TYPE uint16

const (
	FW_DYNAMIC_KEYWORD_ORIGIN_INVALID FW_DYNAMIC_KEYWORD_ORIGIN_TYPE = 0
	FW_DYNAMIC_KEYWORD_ORIGIN_LOCAL   FW_DYNAMIC_KEYWORD_ORIGIN_TYPE = 1
	FW_DYNAMIC_KEYWORD_ORIGIN_MDM     FW_DYNAMIC_KEYWORD_ORIGIN_TYPE = 2
	FW_DYNAMIC_KEYWORD_ORIGIN_MAX     FW_DYNAMIC_KEYWORD_ORIGIN_TYPE = 3
)
