package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// FW_DYNAMIC_KEYWORD_ADDRESS_ID_LIST ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_DYNAMIC_KEYWORD_ADDRESS_ID_LIST struct {
	DwNumIds ndr.DWORD
	Ids      []guid.GUID `ndr:"unique,size_is=DwNumIds"`
}
