package msfasp

// FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS uint16

const (
	FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS_NONE             FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS = 0x0000
	FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS_AUTO_RESOLVE     FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS = 0x0001
	FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS_NON_AUTO_RESOLVE FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS = 0x0002
	FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS_ALL              FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS = 0x0003
	FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS_MAX              FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS = 0x0004
)
