package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_DIAG_APP ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_DIAG_APP struct {
	PszAppPath *ndr.WSTR `ndr:"unique"`
}
