package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_ENDPOINTS ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_ENDPOINTS struct {
	IpVersion              FW_IP_VERSION
	DwSourceV4Address      ndr.DWORD
	DwDestinationV4Address ndr.DWORD
	SourceV6Address        [16]uint8
	DestinationV6Address   [16]uint8
}
