package msfasp

// FW_ENFORCEMENT_STATE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_ENFORCEMENT_STATE uint16

const (
	FW_ENFORCEMENT_STATE_INVALID                                  FW_ENFORCEMENT_STATE = 0
	FW_ENFORCEMENT_STATE_FULL                                     FW_ENFORCEMENT_STATE = 1
	FW_ENFORCEMENT_STATE_WF_OFF_IN_PROFILE                        FW_ENFORCEMENT_STATE = 2
	FW_ENFORCEMENT_STATE_CATEGORY_OFF                             FW_ENFORCEMENT_STATE = 3
	FW_ENFORCEMENT_STATE_DISABLED_OBJECT                          FW_ENFORCEMENT_STATE = 4
	FW_ENFORCEMENT_STATE_INACTIVE_PROFILE                         FW_ENFORCEMENT_STATE = 5
	FW_ENFORCEMENT_STATE_LOCAL_ADDRESS_RESOLUTION_EMPTY           FW_ENFORCEMENT_STATE = 6
	FW_ENFORCEMENT_STATE_REMOTE_ADDRESS_RESOLUTION_EMPTY          FW_ENFORCEMENT_STATE = 7
	FW_ENFORCEMENT_STATE_LOCAL_PORT_RESOLUTION_EMPTY              FW_ENFORCEMENT_STATE = 8
	FW_ENFORCEMENT_STATE_REMOTE_PORT_RESOLUTION_EMPTY             FW_ENFORCEMENT_STATE = 9
	FW_ENFORCEMENT_STATE_INTERFACE_RESOLUTION_EMPTY               FW_ENFORCEMENT_STATE = 10
	FW_ENFORCEMENT_STATE_APPLICATION_RESOLUTION_EMPTY             FW_ENFORCEMENT_STATE = 11
	FW_ENFORCEMENT_STATE_REMOTE_MACHINE_EMPTY                     FW_ENFORCEMENT_STATE = 12
	FW_ENFORCEMENT_STATE_REMOTE_USER_EMPTY                        FW_ENFORCEMENT_STATE = 13
	FW_ENFORCEMENT_STATE_LOCAL_GLOBAL_OPEN_PORTS_DISALLOWED       FW_ENFORCEMENT_STATE = 14
	FW_ENFORCEMENT_STATE_LOCAL_AUTHORIZED_APPLICATIONS_DISALLOWED FW_ENFORCEMENT_STATE = 15
	FW_ENFORCEMENT_STATE_LOCAL_FIREWALL_RULES_DISALLOWED          FW_ENFORCEMENT_STATE = 16
	FW_ENFORCEMENT_STATE_LOCAL_CONSEC_RULES_DISALLOWED            FW_ENFORCEMENT_STATE = 17
	FW_ENFORCEMENT_STATE_MISMATCHED_PLATFORM                      FW_ENFORCEMENT_STATE = 18
	FW_ENFORCEMENT_STATE_OPTIMIZED_OUT                            FW_ENFORCEMENT_STATE = 19
	FW_ENFORCEMENT_STATE_LOCAL_USER_EMPTY                         FW_ENFORCEMENT_STATE = 20
	FW_ENFORCEMENT_STATE_TRANSPORT_MACHINE_SD_EMPTY               FW_ENFORCEMENT_STATE = 21
	FW_ENFORCEMENT_STATE_TRANSPORT_USER_SD_EMPTY                  FW_ENFORCEMENT_STATE = 22
	FW_ENFORCEMENT_STATE_TUPLE_RESOLUTION_EMPTY                   FW_ENFORCEMENT_STATE = 23
	FW_ENFORCEMENT_STATE_NETNAME_RESOLUTION_EMPTY                 FW_ENFORCEMENT_STATE = 24
	FW_ENFORCEMENT_STATE_DUPLICATE                                FW_ENFORCEMENT_STATE = 25
	FW_ENFORCEMENT_STATE_MAX                                      FW_ENFORCEMENT_STATE = 26
)
