package msfasp

// FW_ENUM_RULES_FLAGS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_ENUM_RULES_FLAGS uint16

const (
	FW_ENUM_RULES_FLAG_NONE                FW_ENUM_RULES_FLAGS = 0x0000
	FW_ENUM_RULES_FLAG_RESOLVE_NAME        FW_ENUM_RULES_FLAGS = 0x0001
	FW_ENUM_RULES_FLAG_RESOLVE_DESCRIPTION FW_ENUM_RULES_FLAGS = 0x0002
	FW_ENUM_RULES_FLAG_RESOLVE_APPLICATION FW_ENUM_RULES_FLAGS = 0x0004
	FW_ENUM_RULES_FLAG_RESOLVE_KEYWORD     FW_ENUM_RULES_FLAGS = 0x0008
	FW_ENUM_RULES_FLAG_RESOLVE_GPO_NAME    FW_ENUM_RULES_FLAGS = 0x0010
	FW_ENUM_RULES_FLAG_EFFECTIVE           FW_ENUM_RULES_FLAGS = 0x0020
	FW_ENUM_RULES_FLAG_INCLUDE_METADATA    FW_ENUM_RULES_FLAGS = 0x0040
	FW_ENUM_RULES_FLAG_MAX                 FW_ENUM_RULES_FLAGS = 0x0080
)
