package msfasp

// FW_GLOBAL_CONFIG_IPSEC_THROUGH_NAT_VALUES is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_GLOBAL_CONFIG_IPSEC_THROUGH_NAT_VALUES uint16

const (
	FW_GLOBAL_CONFIG_IPSEC_THROUGH_NAT_NEVER                        FW_GLOBAL_CONFIG_IPSEC_THROUGH_NAT_VALUES = 0
	FW_GLOBAL_CONFIG_IPSEC_THROUGH_NAT_SERVER_BEHIND_NAT            FW_GLOBAL_CONFIG_IPSEC_THROUGH_NAT_VALUES = 1
	FW_GLOBAL_CONFIG_IPSEC_THROUGH_NAT_SERVER_AND_CLIENT_BEHIND_NAT FW_GLOBAL_CONFIG_IPSEC_THROUGH_NAT_VALUES = 2
	FW_GLOBAL_CONFIG_IPSEC_THROUGH_NAT_MAX                          FW_GLOBAL_CONFIG_IPSEC_THROUGH_NAT_VALUES = 3
)
