package msfasp

// FW_GLOBAL_CONFIG_IPSEC_EXEMPT_VALUES is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_GLOBAL_CONFIG_IPSEC_EXEMPT_VALUES uint16

const (
	FW_GLOBAL_CONFIG_IPSEC_EXEMPT_NONE              FW_GLOBAL_CONFIG_IPSEC_EXEMPT_VALUES = 0x0000
	FW_GLOBAL_CONFIG_IPSEC_EXEMPT_NEIGHBOR_DISC     FW_GLOBAL_CONFIG_IPSEC_EXEMPT_VALUES = 0x0001
	FW_GLOBAL_CONFIG_IPSEC_EXEMPT_ICMP              FW_GLOBAL_CONFIG_IPSEC_EXEMPT_VALUES = 0x0002
	FW_GLOBAL_CONFIG_IPSEC_EXEMPT_ROUTER_DISC       FW_GLOBAL_CONFIG_IPSEC_EXEMPT_VALUES = 0x0004
	FW_GLOBAL_CONFIG_IPSEC_EXEMPT_NEIGHBOR_DISC_RFC FW_GLOBAL_CONFIG_IPSEC_EXEMPT_VALUES = 0x0005
	FW_GLOBAL_CONFIG_IPSEC_EXEMPT_DHCP              FW_GLOBAL_CONFIG_IPSEC_EXEMPT_VALUES = 0x0008
	FW_GLOBAL_CONFIG_IPSEC_EXEMPT_MAX               FW_GLOBAL_CONFIG_IPSEC_EXEMPT_VALUES = 0x0010
)
