package msfasp

// FW_GLOBAL_CONFIG_PRESHARED_KEY_ENCODING_VALUES is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_GLOBAL_CONFIG_PRESHARED_KEY_ENCODING_VALUES uint16

const (
	FW_GLOBAL_CONFIG_PRESHARED_KEY_ENCODING_NONE  FW_GLOBAL_CONFIG_PRESHARED_KEY_ENCODING_VALUES = 0
	FW_GLOBAL_CONFIG_PRESHARED_KEY_ENCODING_UTF_8 FW_GLOBAL_CONFIG_PRESHARED_KEY_ENCODING_VALUES = 1
	FW_GLOBAL_CONFIG_PRESHARED_KEY_ENCODING_MAX   FW_GLOBAL_CONFIG_PRESHARED_KEY_ENCODING_VALUES = 2
)
