package msfasp

// FW_GLOBAL_CONFIG is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_GLOBAL_CONFIG uint16

const (
	FW_GLOBAL_CONFIG_INVALID                                           FW_GLOBAL_CONFIG = 0
	FW_GLOBAL_CONFIG_POLICY_VERSION_SUPPORTED                          FW_GLOBAL_CONFIG = 1
	FW_GLOBAL_CONFIG_CURRENT_PROFILE                                   FW_GLOBAL_CONFIG = 2
	FW_GLOBAL_CONFIG_DISABLE_STATEFUL_FTP                              FW_GLOBAL_CONFIG = 3
	FW_GLOBAL_CONFIG_DISABLE_STATEFUL_PPTP                             FW_GLOBAL_CONFIG = 4
	FW_GLOBAL_CONFIG_SA_IDLE_TIME                                      FW_GLOBAL_CONFIG = 5
	FW_GLOBAL_CONFIG_PRESHARED_KEY_ENCODING                            FW_GLOBAL_CONFIG = 6
	FW_GLOBAL_CONFIG_IPSEC_EXEMPT                                      FW_GLOBAL_CONFIG = 7
	FW_GLOBAL_CONFIG_CRL_CHECK                                         FW_GLOBAL_CONFIG = 8
	FW_GLOBAL_CONFIG_IPSEC_THROUGH_NAT                                 FW_GLOBAL_CONFIG = 9
	FW_GLOBAL_CONFIG_POLICY_VERSION                                    FW_GLOBAL_CONFIG = 10
	FW_GLOBAL_CONFIG_BINARY_VERSION_SUPPORTED                          FW_GLOBAL_CONFIG = 11
	FW_GLOBAL_CONFIG_IPSEC_TUNNEL_REMOTE_MACHINE_AUTHORIZATION_LIST    FW_GLOBAL_CONFIG = 12
	FW_GLOBAL_CONFIG_IPSEC_TUNNEL_REMOTE_USER_AUTHORIZATION_LIST       FW_GLOBAL_CONFIG = 13
	FW_GLOBAL_CONFIG_OPPORTUNISTICALLY_MATCH_AUTH_SET_PER_KM           FW_GLOBAL_CONFIG = 14
	FW_GLOBAL_CONFIG_IPSEC_TRANSPORT_REMOTE_MACHINE_AUTHORIZATION_LIST FW_GLOBAL_CONFIG = 15
	FW_GLOBAL_CONFIG_IPSEC_TRANSPORT_REMOTE_USER_AUTHORIZATION_LIST    FW_GLOBAL_CONFIG = 16
	FW_GLOBAL_CONFIG_ENABLE_PACKET_QUEUE                               FW_GLOBAL_CONFIG = 17
	FW_GLOBAL_CONFIG_MAX                                               FW_GLOBAL_CONFIG = 18
)
