package msfasp

// FW_GLOBAL_CONFIG_ENABLE_PACKET_QUEUE_FLAGS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_GLOBAL_CONFIG_ENABLE_PACKET_QUEUE_FLAGS uint16

const (
	FW_GLOBAL_CONFIG_PACKET_QUEUE_NONE    FW_GLOBAL_CONFIG_ENABLE_PACKET_QUEUE_FLAGS = 0
	FW_GLOBAL_CONFIG_PACKET_QUEUE_INBOUND FW_GLOBAL_CONFIG_ENABLE_PACKET_QUEUE_FLAGS = 1
	FW_GLOBAL_CONFIG_PACKET_QUEUE_FORWARD FW_GLOBAL_CONFIG_ENABLE_PACKET_QUEUE_FLAGS = 2
	FW_GLOBAL_CONFIG_PACKET_QUEUE_MAX     FW_GLOBAL_CONFIG_ENABLE_PACKET_QUEUE_FLAGS = 3
)
