package msfasp

// FW_HYPERV_RULE_STATUS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_HYPERV_RULE_STATUS uint16

const (
	FW_HYPERV_RULE_STATUS_INVALID             FW_HYPERV_RULE_STATUS = 0
	FW_HYPERV_RULE_STATUS_OK                  FW_HYPERV_RULE_STATUS = 1
	FW_HYPERV_RULE_STATUS_PARTIALLY_ENFORCED  FW_HYPERV_RULE_STATUS = 2
	FW_HYPERV_RULE_STATUS_NO_APPLICABLE_PORTS FW_HYPERV_RULE_STATUS = 3
	FW_HYPERV_RULE_STATUS_PARSING_ERROR       FW_HYPERV_RULE_STATUS = 4
	FW_HYPERV_RULE_STATUS_ERROR               FW_HYPERV_RULE_STATUS = 5
	FW_HYPERV_RULE_STATUS_MAX                 FW_HYPERV_RULE_STATUS = 6
)
