package msfasp

// FW_HYPERV_RULE_FLAGS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_HYPERV_RULE_FLAGS uint16

const (
	FW_HYPERV_RULE_FLAGS_NONE                  FW_HYPERV_RULE_FLAGS = 0x0000
	FW_HYPERV_RULE_FLAGS_ACTIVE                FW_HYPERV_RULE_FLAGS = 0x0001 // = FW_RULE_FLAGS_ACTIVE
	FW_HYPERV_RULE_FLAGS_CONSTRAINED_INTERFACE FW_HYPERV_RULE_FLAGS = 0x0002
	FW_HYPERV_RULE_FLAGS_MAX_V2_32             FW_HYPERV_RULE_FLAGS = 0x0004
	FW_HYPERV_RULE_FLAGS_INTERNAL_MIN_PRIORITY FW_HYPERV_RULE_FLAGS = 0x0004
	FW_HYPERV_RULE_FLAGS_MAX_V2_33             FW_HYPERV_RULE_FLAGS = 0x0008
	FW_HYPERV_RULE_FLAGS_MAX                   FW_HYPERV_RULE_FLAGS = 0x0008
)
