package msfasp

// FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE uint16

const (
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_INVALID                                           FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 0
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_ENFORCED                                          FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 1
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_ERROR                                             FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 2
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_ENFORCED_EMPTY_RESOLUTION                         FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 3
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_PORT_NOT_FOUND                                    FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 4
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_RULE_INACTIVE                                     FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 5
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_VM_CREATOR_NOT_APPLICABLE                         FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 6
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_PROFILE_NOT_APPLICABLE                            FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 7
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_PROFILE_DISABLED                                  FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 8
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_PROFILE_LOCAL_RULES_DISALLOWED                    FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 9
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_CONSTRAINED_INTERFACE_NOT_APPLICABLE              FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 10
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_NAT_INBOUND_NOT_APPLICABLE                        FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 11
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_NAT_LOCAL_ADDRESS_NOT_SUPPORTED                   FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 12
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_HOST_POLICY_MERGE_DISABLED                        FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 13
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_HOST_FIREWALL_PROFILE_DISABLED                    FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 14
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_HOST_FIREWALL_DEFAULT_ACTION_CONFLICT             FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 15
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_HOST_FIREWALL_PROFILE_LOCAL_POLICY_MERGE_DISABLED FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 16
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_HOST_FIREWALL_RULE_CATEGORY_DISABLED              FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 17
	FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE_MAX                                               FW_HYPERV_RULE_PORT_ENFORCEMENT_STATE = 18
)
