package msfasp

// FW_HYPERV_PROFILE_CONFIG is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_HYPERV_PROFILE_CONFIG uint16

const (
	FW_HYPERV_PROFILE_CONFIG_INVALID                  FW_HYPERV_PROFILE_CONFIG = 0
	FW_HYPERV_PROFILE_CONFIG_ENABLED                  FW_HYPERV_PROFILE_CONFIG = 1
	FW_HYPERV_PROFILE_CONFIG_ALLOW_LOCAL_POLICY_MERGE FW_HYPERV_PROFILE_CONFIG = 2
	FW_HYPERV_PROFILE_CONFIG_MAX                      FW_HYPERV_PROFILE_CONFIG = 3
)
