package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// FW_HYPERV_PORT1 ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_HYPERV_PORT1 struct {
	Next                      *FW_HYPERV_PORT1 `ndr:"unique"`
	SwitchName                *ndr.WSTR        `ndr:"unique"`
	PortName                  *ndr.WSTR        `ndr:"unique"`
	VmCreatorId               guid.GUID
	InterfaceGuid             guid.GUID
	PartitionGuid             guid.GUID
	Flags                     ndr.DWORD
	ProfileType               FW_PROFILE_TYPE
	NetworkType               FW_HYPERV_NETWORK_TYPE
	ConstrainedInterfaceAlias *ndr.WSTR `ndr:"unique"`
}
