package msfasp

// FW_HYPERV_NETWORK_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_HYPERV_NETWORK_TYPE uint16

const (
	FW_HYPERV_NETWORK_TYPE_INVALID FW_HYPERV_NETWORK_TYPE = 0x0
	FW_HYPERV_NETWORK_TYPE_FSE     FW_HYPERV_NETWORK_TYPE = 0x1
	FW_HYPERV_NETWORK_TYPE_NAT     FW_HYPERV_NETWORK_TYPE = 0x2
	FW_HYPERV_NETWORK_TYPE_MAX     FW_HYPERV_NETWORK_TYPE = 0x4
)
