package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_IPV4_ADDRESS_RANGE ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_IPV4_ADDRESS_RANGE struct {
	DwBegin ndr.DWORD
	DwEnd   ndr.DWORD
}
