package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_IPV6_RANGE_LIST ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_IPV6_RANGE_LIST struct {
	DwNumEntries ndr.DWORD
	PRanges      []FW_IPV6_ADDRESS_RANGE `ndr:"unique,size_is=DwNumEntries"`
}
