package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// FW_INTERFACE_LUIDS ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_INTERFACE_LUIDS struct {
	DwNumLUIDs ndr.DWORD
	PLUIDs     []guid.GUID `ndr:"unique,size_is=DwNumLUIDs"`
}
