package msfasp

// FW_INTERFACE_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_INTERFACE_TYPE uint16

const (
	FW_INTERFACE_TYPE_ALL           FW_INTERFACE_TYPE = 0x0000
	FW_INTERFACE_TYPE_LAN           FW_INTERFACE_TYPE = 0x0001
	FW_INTERFACE_TYPE_WIRELESS      FW_INTERFACE_TYPE = 0x0002
	FW_INTERFACE_TYPE_REMOTE_ACCESS FW_INTERFACE_TYPE = 0x0004
	FW_INTERFACE_TYPE_MOBILE_BBAND  FW_INTERFACE_TYPE = 0x0008
	FW_INTERFACE_TYPE_MAX           FW_INTERFACE_TYPE = 0x0010
	FW_INTERFACE_TYPE_MAX_V2_23     FW_INTERFACE_TYPE = 0x0008
)
