package msfasp

// FW_MATCH_KEY is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_MATCH_KEY uint16

const (
	FW_MATCH_KEY_PROFILE               FW_MATCH_KEY = 0
	FW_MATCH_KEY_STATUS                FW_MATCH_KEY = 1
	FW_MATCH_KEY_OBJECTID              FW_MATCH_KEY = 2
	FW_MATCH_KEY_FILTERID              FW_MATCH_KEY = 3
	FW_MATCH_KEY_APP_PATH              FW_MATCH_KEY = 4
	FW_MATCH_KEY_PROTOCOL              FW_MATCH_KEY = 5
	FW_MATCH_KEY_LOCAL_PORT            FW_MATCH_KEY = 6
	FW_MATCH_KEY_REMOTE_PORT           FW_MATCH_KEY = 7
	FW_MATCH_KEY_GROUP                 FW_MATCH_KEY = 8
	FW_MATCH_KEY_SVC_NAME              FW_MATCH_KEY = 9
	FW_MATCH_KEY_DIRECTION             FW_MATCH_KEY = 10
	FW_MATCH_KEY_LOCAL_USER_OWNER      FW_MATCH_KEY = 11
	FW_MATCH_KEY_PACKAGE_ID            FW_MATCH_KEY = 12
	FW_MATCH_KEY_FQBN                  FW_MATCH_KEY = 13
	FW_MATCH_KEY_COMPARTMENT_ID        FW_MATCH_KEY = 14
	FW_MATCH_KEY_REMOTE_USER_AUTH_LIST FW_MATCH_KEY = 15
	FW_MATCH_KEY_PACKAGE_FAMILY_NAME   FW_MATCH_KEY = 16
	FW_MATCH_KEY_MAX                   FW_MATCH_KEY = 17
)
