package msfasp

import "github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"

// FW_MATCH_VALUE ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_MATCH_VALUE struct {
	Type  FW_DATA_TYPE
	Field FW_MATCH_VALUE_Field
}

// FW_MATCH_VALUE_Field is the type-discriminated union of FW_MATCH_VALUE
// ([MS-FASP] 2.2.101): integer arms for UINT8..UINT64, a string arm for
// FW_DATA_TYPE_UNICODE_STRING (5), and an empty ([case] FW_DATA_TYPE_EMPTY=0) arm.
type FW_MATCH_VALUE_Field struct {
	Tag    FW_DATA_TYPE          `ndr:"switch,enum"`
	UInt8  UINT8                 `ndr:"case=1"`
	UInt16 UINT16                `ndr:"case=2"`
	UInt32 UINT32                `ndr:"case=3"`
	UInt64 UINT64                `ndr:"case=4"`
	Str    FW_MATCH_VALUE_STRING `ndr:"case=5"`
}

// FW_MATCH_VALUE_STRING is the Unicode-string arm of FW_MATCH_VALUE_Field ([MS-FASP] 2.2.101).
type FW_MATCH_VALUE_STRING struct {
	WszString *ndr.WSTR `ndr:"unique"`
}
