package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_NETWORK_NAMES ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_NETWORK_NAMES struct {
	DwNumEntries ndr.DWORD
	WszNames     []*ndr.WSTR `ndr:"unique,size_is=DwNumEntries,elem=unique"`
}
