package msfasp

// FW_OS_PLATFORM_OP is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_OS_PLATFORM_OP uint16

const (
	FW_OS_PLATFORM_OP_EQ         FW_OS_PLATFORM_OP = 0
	FW_OS_PLATFORM_OP_GTEQ       FW_OS_PLATFORM_OP = 1
	FW_OS_PLATFORM_OP_MAX        FW_OS_PLATFORM_OP = 2
	FW_OS_PLATFORM_OP_FIELD_SIZE FW_OS_PLATFORM_OP = 5
	FW_OS_PLATFORM_OP_FIELD_MASK FW_OS_PLATFORM_OP = 0xF8
)
