package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_OBJECT_METADATA ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_OBJECT_METADATA struct {
	QwFilterContextID  UINT64
	DwNumEntries       ndr.DWORD
	PEnforcementStates []FW_ENFORCEMENT_STATE `ndr:"unique,size_is=DwNumEntries"`
}
