package msfasp

// FW_PHASE1_KEY_MODULE_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_PHASE1_KEY_MODULE_TYPE uint16

const (
	FW_PHASE1_KEY_MODULE_INVALID FW_PHASE1_KEY_MODULE_TYPE = 0
	FW_PHASE1_KEY_MODULE_IKE     FW_PHASE1_KEY_MODULE_TYPE = 1
	FW_PHASE1_KEY_MODULE_AUTH_IP FW_PHASE1_KEY_MODULE_TYPE = 2
	FW_PHASE1_KEY_MODULE_IKEV2   FW_PHASE1_KEY_MODULE_TYPE = 3
	FW_PHASE1_KEY_MODULE_MAX     FW_PHASE1_KEY_MODULE_TYPE = 4
)
