package msfasp

// FW_POLICY_STORE_FLAGS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_POLICY_STORE_FLAGS uint16

const (
	FW_POLICY_STORE_FLAGS_NONE                             FW_POLICY_STORE_FLAGS = 0x0000
	FW_POLICY_STORE_FLAGS_DELETE_DYNAMIC_RULES_AFTER_CLOSE FW_POLICY_STORE_FLAGS = 0x0001
	FW_POLICY_STORE_FLAGS_OPEN_GP_CACHE                    FW_POLICY_STORE_FLAGS = 0x0002
	FW_POLICY_STORE_FLAGS_USE_GP_CACHE                     FW_POLICY_STORE_FLAGS = 0x0004
	FW_POLICY_STORE_FLAGS_SAVE_GP_CACHE                    FW_POLICY_STORE_FLAGS = 0x0008
	FW_POLICY_STORE_FLAGS_NOT_USED_VALUE_16                FW_POLICY_STORE_FLAGS = 0x0010
	FW_POLICY_STORE_FLAGS_MAX                              FW_POLICY_STORE_FLAGS = 0x0020
)
