package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_PHASE2_CRYPTO_SUITE ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_PHASE2_CRYPTO_SUITE struct {
	Protocol             FW_CRYPTO_PROTOCOL_TYPE
	AhHash               FW_CRYPTO_HASH_TYPE
	EspHash              FW_CRYPTO_HASH_TYPE
	Encryption           FW_CRYPTO_ENCRYPTION_TYPE
	DwTimeoutMinutes     ndr.DWORD
	DwTimeoutKBytes      ndr.DWORD
	DwP2CryptoSuiteFlags ndr.DWORD
}
