package msfasp

// FW_PORT_KEYWORD is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_PORT_KEYWORD uint16

const (
	FW_PORT_KEYWORD_NONE              FW_PORT_KEYWORD = 0x00
	FW_PORT_KEYWORD_DYNAMIC_RPC_PORTS FW_PORT_KEYWORD = 0x01
	FW_PORT_KEYWORD_RPC_EP            FW_PORT_KEYWORD = 0x02
	FW_PORT_KEYWORD_TEREDO_PORT       FW_PORT_KEYWORD = 0x04
	FW_PORT_KEYWORD_IP_TLS_IN         FW_PORT_KEYWORD = 0x08
	FW_PORT_KEYWORD_IP_TLS_OUT        FW_PORT_KEYWORD = 0x10
	FW_PORT_KEYWORD_DHCP              FW_PORT_KEYWORD = 0x20
	FW_PORT_KEYWORD_PLAYTO_DISCOVERY  FW_PORT_KEYWORD = 0x40
	FW_PORT_KEYWORD_MDNS              FW_PORT_KEYWORD = 0x80
	FW_PORT_KEYWORD_CORTANA_OUT       FW_PORT_KEYWORD = 0x100
	FW_PORT_KEYWORD_PROXIMAL_TCP_CDP  FW_PORT_KEYWORD = 0x200
	FW_PORT_KEYWORD_MAX               FW_PORT_KEYWORD = 0x400
	FW_PORT_KEYWORD_MAX_V2_1          FW_PORT_KEYWORD = 0x08
	FW_PORT_KEYWORD_MAX_V2_10         FW_PORT_KEYWORD = 0x20
	FW_PORT_KEYWORD_MAX_V2_20         FW_PORT_KEYWORD = 0x80
	FW_PORT_KEYWORD_MAX_V2_24         FW_PORT_KEYWORD = 0x100
	FW_PORT_KEYWORD_MAX_V2_25         FW_PORT_KEYWORD = 0x200
)
