package msfasp

// FW_PROFILE_CONFIG is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_PROFILE_CONFIG uint16

const (
	FW_PROFILE_CONFIG_INVALID                                             FW_PROFILE_CONFIG = 0
	FW_PROFILE_CONFIG_ENABLE_FW                                           FW_PROFILE_CONFIG = 1
	FW_PROFILE_CONFIG_DISABLE_STEALTH_MODE                                FW_PROFILE_CONFIG = 2
	FW_PROFILE_CONFIG_SHIELDED                                            FW_PROFILE_CONFIG = 3
	FW_PROFILE_CONFIG_DISABLE_UNICAST_RESPONSES_TO_MULTICAST_BROADCAST    FW_PROFILE_CONFIG = 4
	FW_PROFILE_CONFIG_LOG_DROPPED_PACKETS                                 FW_PROFILE_CONFIG = 5
	FW_PROFILE_CONFIG_LOG_SUCCESS_CONNECTIONS                             FW_PROFILE_CONFIG = 6
	FW_PROFILE_CONFIG_LOG_IGNORED_RULES                                   FW_PROFILE_CONFIG = 7
	FW_PROFILE_CONFIG_LOG_MAX_FILE_SIZE                                   FW_PROFILE_CONFIG = 8
	FW_PROFILE_CONFIG_LOG_FILE_PATH                                       FW_PROFILE_CONFIG = 9
	FW_PROFILE_CONFIG_DISABLE_INBOUND_NOTIFICATIONS                       FW_PROFILE_CONFIG = 10
	FW_PROFILE_CONFIG_AUTH_APPS_ALLOW_USER_PREF_MERGE                     FW_PROFILE_CONFIG = 11
	FW_PROFILE_CONFIG_GLOBAL_PORTS_ALLOW_USER_PREF_MERGE                  FW_PROFILE_CONFIG = 12
	FW_PROFILE_CONFIG_ALLOW_LOCAL_POLICY_MERGE                            FW_PROFILE_CONFIG = 13
	FW_PROFILE_CONFIG_ALLOW_LOCAL_IPSEC_POLICY_MERGE                      FW_PROFILE_CONFIG = 14
	FW_PROFILE_CONFIG_DISABLED_INTERFACES                                 FW_PROFILE_CONFIG = 15
	FW_PROFILE_CONFIG_DEFAULT_OUTBOUND_ACTION                             FW_PROFILE_CONFIG = 16
	FW_PROFILE_CONFIG_DEFAULT_INBOUND_ACTION                              FW_PROFILE_CONFIG = 17
	FW_PROFILE_CONFIG_DISABLE_STEALTH_MODE_IPSEC_SECURED_PACKET_EXEMPTION FW_PROFILE_CONFIG = 18
	FW_PROFILE_CONFIG_MAX                                                 FW_PROFILE_CONFIG = 19
)
