package msfasp

// FW_PHASE1_CRYPTO_FLAGS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_PHASE1_CRYPTO_FLAGS uint16

const (
	FW_PHASE1_CRYPTO_FLAGS_NONE           FW_PHASE1_CRYPTO_FLAGS = 0x00
	FW_PHASE1_CRYPTO_FLAGS_DO_NOT_SKIP_DH FW_PHASE1_CRYPTO_FLAGS = 0x01
	FW_PHASE1_CRYPTO_FLAGS_MAX            FW_PHASE1_CRYPTO_FLAGS = 0x02
)
