package msfasp

// FW_POLICY_ACCESS_RIGHT is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_POLICY_ACCESS_RIGHT uint16

const (
	FW_POLICY_ACCESS_RIGHT_INVALID    FW_POLICY_ACCESS_RIGHT = 0
	FW_POLICY_ACCESS_RIGHT_READ       FW_POLICY_ACCESS_RIGHT = 1
	FW_POLICY_ACCESS_RIGHT_READ_WRITE FW_POLICY_ACCESS_RIGHT = 2
	FW_POLICY_ACCESS_RIGHT_MAX        FW_POLICY_ACCESS_RIGHT = 3
)
