package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_PHASE1_CRYPTO_SUITE ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_PHASE1_CRYPTO_SUITE struct {
	KeyExchange          FW_CRYPTO_KEY_EXCHANGE_TYPE
	Encryption           FW_CRYPTO_ENCRYPTION_TYPE
	Hash                 FW_CRYPTO_HASH_TYPE
	DwP1CryptoSuiteFlags ndr.DWORD
}
