package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_PRODUCT ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_PRODUCT struct {
	DwFlags                   ndr.DWORD
	DwNumRuleCategories       ndr.DWORD
	PRuleCategories           []FW_RULE_CATEGORY `ndr:"unique,size_is=DwNumRuleCategories"`
	PszDisplayName            *ndr.WSTR          `ndr:"unique"`
	PszPathToSignedProductExe *ndr.WSTR          `ndr:"unique"`
}
