package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// FW_PHASE2_SA_DETAILS ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_PHASE2_SA_DETAILS struct {
	SaId              UINT64
	Direction         FW_DIRECTION
	Endpoints         FW_ENDPOINTS
	WLocalPort        uint16
	WRemotePort       uint16
	WIpProtocol       uint16
	SelectedProposal  FW_PHASE2_CRYPTO_SUITE
	Pfs               FW_PHASE2_CRYPTO_PFS
	TransportFilterId guid.GUID
	DwP2SaFlags       ndr.DWORD
}
