package msfasp

// FW_PHASE2_CRYPTO_PFS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_PHASE2_CRYPTO_PFS uint16

const (
	FW_PHASE2_CRYPTO_PFS_INVALID   FW_PHASE2_CRYPTO_PFS = 0
	FW_PHASE2_CRYPTO_PFS_DISABLE   FW_PHASE2_CRYPTO_PFS = 1
	FW_PHASE2_CRYPTO_PFS_PHASE1    FW_PHASE2_CRYPTO_PFS = 2
	FW_PHASE2_CRYPTO_PFS_DH1       FW_PHASE2_CRYPTO_PFS = 3
	FW_PHASE2_CRYPTO_PFS_DH2       FW_PHASE2_CRYPTO_PFS = 4
	FW_PHASE2_CRYPTO_PFS_DH2048    FW_PHASE2_CRYPTO_PFS = 5
	FW_PHASE2_CRYPTO_PFS_ECDH256   FW_PHASE2_CRYPTO_PFS = 6
	FW_PHASE2_CRYPTO_PFS_ECDH384   FW_PHASE2_CRYPTO_PFS = 7
	FW_PHASE2_CRYPTO_PFS_DH24      FW_PHASE2_CRYPTO_PFS = 8
	FW_PHASE2_CRYPTO_PFS_MAX       FW_PHASE2_CRYPTO_PFS = 9
	FW_PHASE2_CRYPTO_PFS_MAX_V2_10 FW_PHASE2_CRYPTO_PFS = FW_PHASE2_CRYPTO_PFS_DH24
)
