package msfasp

// FW_PHASE2_TRAFFIC_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_PHASE2_TRAFFIC_TYPE uint16

const (
	FW_PHASE2_TRAFFIC_TYPE_INVALID   FW_PHASE2_TRAFFIC_TYPE = 0
	FW_PHASE2_TRAFFIC_TYPE_TRANSPORT FW_PHASE2_TRAFFIC_TYPE = 1
	FW_PHASE2_TRAFFIC_TYPE_TUNNEL    FW_PHASE2_TRAFFIC_TYPE = 2
	FW_PHASE2_TRAFFIC_TYPE_MAX       FW_PHASE2_TRAFFIC_TYPE = 3
)
