package msfasp

// FW_PROFILE_TYPE is an NDR enum, transmitted as a 4-byte v1_enum value ([C706] 14.3.6.4, [MS-FASP]).
type FW_PROFILE_TYPE uint32

const (
	FW_PROFILE_TYPE_INVALID  FW_PROFILE_TYPE = 0
	FW_PROFILE_TYPE_DOMAIN   FW_PROFILE_TYPE = 0x001
	FW_PROFILE_TYPE_STANDARD FW_PROFILE_TYPE = 0x002
	FW_PROFILE_TYPE_PRIVATE  FW_PROFILE_TYPE = FW_PROFILE_TYPE_STANDARD
	FW_PROFILE_TYPE_PUBLIC   FW_PROFILE_TYPE = 0x004
	FW_PROFILE_TYPE_ALL      FW_PROFILE_TYPE = 0x7FFFFFFF
	FW_PROFILE_TYPE_CURRENT  FW_PROFILE_TYPE = 0x80000000
	FW_PROFILE_TYPE_NONE     FW_PROFILE_TYPE = FW_PROFILE_TYPE_CURRENT + 1
)
