package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_QUERY_CONDITIONS ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_QUERY_CONDITIONS struct {
	DwNumEntries    ndr.DWORD
	AndedConditions []FW_QUERY_CONDITION `ndr:"unique,size_is=DwNumEntries"`
}
