package msfasp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FW_RULE2_10 ([MS-FASP]). Generated by tools/idlgen; verify pointer/array tags.
type FW_RULE2_10 struct {
	PNext                             *FW_RULE2_10 `ndr:"unique"`
	WSchemaVersion                    uint16
	WszRuleId                         *ndr.WSTR `ndr:"unique"`
	WszName                           *ndr.WSTR `ndr:"unique"`
	WszDescription                    *ndr.WSTR `ndr:"unique"`
	DwProfiles                        ndr.DWORD
	Direction                         FW_DIRECTION
	WIpProtocol                       uint16
	Field                             FW_RULE2_10_Field
	LocalAddresses                    FW_ADDRESSES
	RemoteAddresses                   FW_ADDRESSES
	LocalInterfaceIds                 FW_INTERFACE_LUIDS
	DwLocalInterfaceTypes             ndr.DWORD
	WszLocalApplication               *ndr.WSTR `ndr:"unique"`
	WszLocalService                   *ndr.WSTR `ndr:"unique"`
	Action                            FW_RULE_ACTION
	WFlags                            uint16
	WszRemoteMachineAuthorizationList *ndr.WSTR `ndr:"unique"`
	WszRemoteUserAuthorizationList    *ndr.WSTR `ndr:"unique"`
	WszEmbeddedContext                *ndr.WSTR `ndr:"unique"`
	PlatformValidityList              FW_OS_PLATFORM_LIST
	Status                            FW_RULE_STATUS
	Origin                            FW_RULE_ORIGIN_TYPE
	WszGPOName                        *ndr.WSTR `ndr:"unique"`
	Reserved                          ndr.DWORD
	PMetaData                         []FW_OBJECT_METADATA `ndr:"unique,conformant"`
}

// FW_RULE2_10_Field is the wIpProtocol-discriminated union ([MS-FASP] 2.2.36 FW_RULE): the port
// list arm is selected for TCP (6) and UDP (17); the ICMP type/code list for ICMPv4 (1)
// and ICMPv6 (58); all other protocols select the empty ([default]) arm. switch_type is
// WORD, so the inline discriminant Tag is a uint16 ([C706] 14.3.8).
type FW_RULE2_10_Field struct {
	Tag            uint16                 `ndr:"switch"`
	PortsTCP       FW_RULE_PROTOCOL_PORTS `ndr:"case=6"`
	PortsUDP       FW_RULE_PROTOCOL_PORTS `ndr:"case=17"`
	V4TypeCodeList FW_ICMP_TYPE_CODE_LIST `ndr:"case=1"`
	V6TypeCodeList FW_ICMP_TYPE_CODE_LIST `ndr:"case=58"`
}
