package msfasp

// FW_RULE_CATEGORY is an NDR enum, transmitted as a 4-byte v1_enum value ([C706] 14.3.6.4, [MS-FASP]).
type FW_RULE_CATEGORY uint32

const (
	FW_RULE_CATEGORY_BOOT     FW_RULE_CATEGORY = 0
	FW_RULE_CATEGORY_STEALTH  FW_RULE_CATEGORY = 1
	FW_RULE_CATEGORY_FIREWALL FW_RULE_CATEGORY = 2
	FW_RULE_CATEGORY_CONSEC   FW_RULE_CATEGORY = 3
	FW_RULE_CATEGORY_MAX      FW_RULE_CATEGORY = 4
)
