package msfasp

// FW_RULE_ORIGIN_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_RULE_ORIGIN_TYPE uint16

const (
	FW_RULE_ORIGIN_INVALID      FW_RULE_ORIGIN_TYPE = 0
	FW_RULE_ORIGIN_LOCAL        FW_RULE_ORIGIN_TYPE = 1
	FW_RULE_ORIGIN_GP           FW_RULE_ORIGIN_TYPE = 2
	FW_RULE_ORIGIN_DYNAMIC      FW_RULE_ORIGIN_TYPE = 3
	FW_RULE_ORIGIN_AUTOGEN      FW_RULE_ORIGIN_TYPE = 4
	FW_RULE_ORIGIN_HARDCODED    FW_RULE_ORIGIN_TYPE = 5
	FW_RULE_ORIGIN_MDM          FW_RULE_ORIGIN_TYPE = 6
	FW_RULE_ORIGIN_MAX          FW_RULE_ORIGIN_TYPE = 7
	FW_RULE_ORIGIN_HOST_LOCAL   FW_RULE_ORIGIN_TYPE = 8
	FW_RULE_ORIGIN_HOST_GP      FW_RULE_ORIGIN_TYPE = 9
	FW_RULE_ORIGIN_HOST_DYNAMIC FW_RULE_ORIGIN_TYPE = 10
	FW_RULE_ORIGIN_HOST_MDM     FW_RULE_ORIGIN_TYPE = 11
	FW_RULE_ORIGIN_HOST_MAX     FW_RULE_ORIGIN_TYPE = 12
)
