package msfasp

// FW_RULE_DUPLICATE_STATUS_FLAGS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_RULE_DUPLICATE_STATUS_FLAGS uint16

const (
	FW_DUPLICATE_STATUS_FLAGS_EVALUATING    FW_RULE_DUPLICATE_STATUS_FLAGS = 0x0001
	FW_DUPLICATE_STATUS_FLAGS_HAS_DUPLICATE FW_RULE_DUPLICATE_STATUS_FLAGS = 0x0002
	FW_DUPLICATE_STATUS_FLAGS_IS_ENFORCED   FW_RULE_DUPLICATE_STATUS_FLAGS = 0x0004
)
