package msfasp

// FW_RULE_STATUS_CLASS is an NDR enum, transmitted as a 4-byte v1_enum value ([C706] 14.3.6.4, [MS-FASP]).
type FW_RULE_STATUS_CLASS uint32

const (
	FW_RULE_STATUS_CLASS_OK                FW_RULE_STATUS_CLASS = FW_RULE_STATUS_CLASS(FW_RULE_STATUS_OK)
	FW_RULE_STATUS_CLASS_PARTIALLY_IGNORED FW_RULE_STATUS_CLASS = FW_RULE_STATUS_CLASS(FW_RULE_STATUS_PARTIALLY_IGNORED)
	FW_RULE_STATUS_CLASS_IGNORED           FW_RULE_STATUS_CLASS = FW_RULE_STATUS_CLASS(FW_RULE_STATUS_IGNORED)
	FW_RULE_STATUS_CLASS_PARSING_ERROR     FW_RULE_STATUS_CLASS = FW_RULE_STATUS_CLASS(FW_RULE_STATUS_PARSING_ERROR)
	FW_RULE_STATUS_CLASS_SEMANTIC_ERROR    FW_RULE_STATUS_CLASS = FW_RULE_STATUS_CLASS(FW_RULE_STATUS_SEMANTIC_ERROR)
	FW_RULE_STATUS_CLASS_RUNTIME_ERROR     FW_RULE_STATUS_CLASS = FW_RULE_STATUS_CLASS(FW_RULE_STATUS_RUNTIME_ERROR)
	FW_RULE_STATUS_CLASS_ERROR             FW_RULE_STATUS_CLASS = FW_RULE_STATUS_CLASS(FW_RULE_STATUS_ERROR)
	FW_RULE_STATUS_CLASS_ALL               FW_RULE_STATUS_CLASS = FW_RULE_STATUS_CLASS(FW_RULE_STATUS_ALL)
)
