package msfasp

// FW_RULE_FLAGS is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_RULE_FLAGS uint16

const (
	FW_RULE_FLAGS_NONE                                FW_RULE_FLAGS = 0x0000
	FW_RULE_FLAGS_ACTIVE                              FW_RULE_FLAGS = 0x0001
	FW_RULE_FLAGS_AUTHENTICATE                        FW_RULE_FLAGS = 0x0002
	FW_RULE_FLAGS_AUTHENTICATE_WITH_ENCRYPTION        FW_RULE_FLAGS = 0x0004
	FW_RULE_FLAGS_ROUTEABLE_ADDRS_TRAVERSE            FW_RULE_FLAGS = 0x0008
	FW_RULE_FLAGS_LOOSE_SOURCE_MAPPED                 FW_RULE_FLAGS = 0x00010
	FW_RULE_FLAGS_MAX_V2_1                            FW_RULE_FLAGS = 0x0020
	FW_RULE_FLAGS_AUTH_WITH_NO_ENCAPSULATION          FW_RULE_FLAGS = 0x0020
	FW_RULE_FLAGS_MAX_V2_9                            FW_RULE_FLAGS = 0x0040
	FW_RULE_FLAGS_AUTH_WITH_ENC_NEGOTIATE             FW_RULE_FLAGS = 0x0040
	FW_RULE_FLAGS_ROUTEABLE_ADDRS_TRAVERSE_DEFER_APP  FW_RULE_FLAGS = 0x0080
	FW_RULE_FLAGS_ROUTEABLE_ADDRS_TRAVERSE_DEFER_USER FW_RULE_FLAGS = 0x0100
	FW_RULE_FLAGS_AUTHENTICATE_BYPASS_OUTBOUND        FW_RULE_FLAGS = 0x0200
	FW_RULE_FLAGS_MAX_V2_10                           FW_RULE_FLAGS = 0x0400
	FW_RULE_FLAGS_ALLOW_PROFILE_CROSSING              FW_RULE_FLAGS = 0x0400
	FW_RULE_FLAGS_LOCAL_ONLY_MAPPED                   FW_RULE_FLAGS = 0x0800
	FW_RULE_FLAGS_MAX_V2_20                           FW_RULE_FLAGS = 0x1000
	FW_RULE_FLAGS_LUA_CONDITIONAL_ACE                 FW_RULE_FLAGS = 0x1000
	FW_RULE_FLAGS_BIND_TO_INTERFACE                   FW_RULE_FLAGS = 0x2000
	FW_RULE_FLAGS_MAX                                 FW_RULE_FLAGS = 0x4000
)
