package msfasp

// FW_STORE_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_STORE_TYPE uint16

const (
	FW_STORE_TYPE_INVALID           FW_STORE_TYPE = 0
	FW_STORE_TYPE_GP_RSOP           FW_STORE_TYPE = 1
	FW_STORE_TYPE_LOCAL             FW_STORE_TYPE = 2
	FW_STORE_TYPE_NOT_USED_VALUE_3  FW_STORE_TYPE = 3
	FW_STORE_TYPE_NOT_USED_VALUE_4  FW_STORE_TYPE = 4
	FW_STORE_TYPE_DYNAMIC           FW_STORE_TYPE = 5
	FW_STORE_TYPE_GPO               FW_STORE_TYPE = 6
	FW_STORE_TYPE_DEFAULTS          FW_STORE_TYPE = 7
	FW_STORE_TYPE_NOT_USED_VALUE_8  FW_STORE_TYPE = 8
	FW_STORE_TYPE_NOT_USED_VALUE_9  FW_STORE_TYPE = 9
	FW_STORE_TYPE_NOT_USED_VALUE_10 FW_STORE_TYPE = 10
	FW_STORE_TYPE_NOT_USED_VALUE_11 FW_STORE_TYPE = 11
	FW_STORE_TYPE_NOT_USED_VALUE_12 FW_STORE_TYPE = 12
	FW_STORE_TYPE_MAX               FW_STORE_TYPE = 13
)
