package msfasp

// FW_TRANSACTIONAL_STATE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_TRANSACTIONAL_STATE uint16

const (
	FW_TRANSACTIONAL_STATE_NONE     FW_TRANSACTIONAL_STATE = 0
	FW_TRANSACTIONAL_STATE_NO_FLUSH FW_TRANSACTIONAL_STATE = 1
	FW_TRANSACTIONAL_STATE_MAX      FW_TRANSACTIONAL_STATE = 2
)
