package msfasp

// FW_TRUST_TUPLE_KEYWORD is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-FASP]).
type FW_TRUST_TUPLE_KEYWORD uint16

const (
	FW_TRUST_TUPLE_KEYWORD_NONE              FW_TRUST_TUPLE_KEYWORD = 0x0000
	FW_TRUST_TUPLE_KEYWORD_PROXIMITY         FW_TRUST_TUPLE_KEYWORD = 0x0001
	FW_TRUST_TUPLE_KEYWORD_PROXIMITY_SHARING FW_TRUST_TUPLE_KEYWORD = 0x0002
	FW_TRUST_TUPLE_KEYWORD_WFD_PRINT         FW_TRUST_TUPLE_KEYWORD = 0x0004
	FW_TRUST_TUPLE_KEYWORD_WFD_DISPLAY       FW_TRUST_TUPLE_KEYWORD = 0x0008
	FW_TRUST_TUPLE_KEYWORD_WFD_DEVICES       FW_TRUST_TUPLE_KEYWORD = 0x0010
	FW_TRUST_TUPLE_KEYWORD_WFD_KM_DRIVER     FW_TRUST_TUPLE_KEYWORD = 0x0020
	FW_TRUST_TUPLE_KEYWORD_UPNP              FW_TRUST_TUPLE_KEYWORD = 0x0040
	FW_TRUST_TUPLE_KEYWORD_WFD_CDP           FW_TRUST_TUPLE_KEYWORD = 0x0080
	FW_TRUST_TUPLE_KEYWORD_MAX               FW_TRUST_TUPLE_KEYWORD = 0x0100
	FW_TRUST_TUPLE_KEYWORD_MAX_V2_20         FW_TRUST_TUPLE_KEYWORD = 0x0004
	FW_TRUST_TUPLE_KEYWORD_MAX_V2_26         FW_TRUST_TUPLE_KEYWORD = 0x0020
	FW_TRUST_TUPLE_KEYWORD_MAX_V2_27         FW_TRUST_TUPLE_KEYWORD = 0x0080
)
