package ldap_attributes

// msPKI-Enrollment-Flag Attribute
// Src: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-crtd/ec71fd43-61c2-407b-83c9-b52272dec8a1
const (
	MSPKI_ENROLLMENT_FLAG_INCLUDE_SYMMETRIC_ALGORITHMS                                  = 0x00000001
	MSPKI_ENROLLMENT_FLAG_PEND_ALL_REQUESTS                                             = 0x00000002
	MSPKI_ENROLLMENT_FLAG_PUBLISH_TO_KRA_CONTAINER                                      = 0x00000004
	MSPKI_ENROLLMENT_FLAG_PUBLISH_TO_DS                                                 = 0x00000008
	MSPKI_ENROLLMENT_FLAG_AUTO_ENROLLMENT_CHECK_USER_DS_CERTIFICATE                     = 0x00000010
	MSPKI_ENROLLMENT_FLAG_AUTO_ENROLLMENT                                               = 0x00000020
	MSPKI_ENROLLMENT_FLAG_PREVIOUS_APPROVAL_VALIDATE_REENROLLMENT                       = 0x00000040
	MSPKI_ENROLLMENT_FLAG_USER_INTERACTION_REQUIRED                                     = 0x00000100
	MSPKI_ENROLLMENT_FLAG_REMOVE_INVALID_CERTIFICATE_FROM_PERSONAL_STORE                = 0x00000400
	MSPKI_ENROLLMENT_FLAG_ALLOW_ENROLL_ON_BEHALF_OF                                     = 0x00000800
	MSPKI_ENROLLMENT_FLAG_ADD_OCSP_NOCHECK                                              = 0x00001000
	MSPKI_ENROLLMENT_FLAG_ENABLE_KEY_REUSE_ON_NT_TOKEN_KEYSET_STORAGE_FULL              = 0x00002000
	MSPKI_ENROLLMENT_FLAG_NOREVOCATIONINFOINISSUEDCERTS                                 = 0x00004000
	MSPKI_ENROLLMENT_FLAG_INCLUDE_BASIC_CONSTRAINTS_FOR_EE_CERTS                        = 0x00008000
	MSPKI_ENROLLMENT_FLAG_ALLOW_PREVIOUS_APPROVAL_KEYBASEDRENEWAL_VALIDATE_REENROLLMENT = 0x00010000
	MSPKI_ENROLLMENT_FLAG_ISSUANCE_POLICIES_FROM_REQUEST                                = 0x00020000
	MSPKI_ENROLLMENT_FLAG_SKIP_AUTO_RENEWAL                                             = 0x00040000
	MSPKI_ENROLLMENT_FLAG_NO_SECURITY_EXTENSION                                         = 0x00080000
)
