package mstsgu

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// TSG_PACKET_CAPABILITIES ([MS-TSGU]). Generated by tools/idlgen; verify pointer/array tags.
type TSG_PACKET_CAPABILITIES struct {
	CapabilityType ndr.DWORD
	TSGPacket      TSG_CAPABILITIES_UNION
}
