package mstsgu

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// TSG_PACKET_MSG_REQUEST ([MS-TSGU]). Generated by tools/idlgen; verify pointer/array tags.
type TSG_PACKET_MSG_REQUEST struct {
	MaxMessagesPerBatch ndr.DWORD
}
