package mstsgu

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// TSG_PACKET_VERSIONCAPS ([MS-TSGU]). Generated by tools/idlgen; verify pointer/array tags.
type TSG_PACKET_VERSIONCAPS struct {
	TsgHeader              TSG_PACKET_HEADER
	TSGCaps                []TSG_PACKET_CAPABILITIES `ndr:"unique,size_is=NumCapabilities"`
	NumCapabilities        ndr.DWORD
	MajorVersion           uint16
	MinorVersion           uint16
	QuarantineCapabilities uint16
}
