package mststs

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// EXECENVDATA ([MS-TSTS]). Generated by tools/idlgen; verify pointer/array tags.
type EXECENVDATA struct {
	Level ndr.DWORD
	Data  ExecEnvData
}
