package mststs

// EXECENVDATA_LEVEL2 ([MS-TSTS]). Generated by tools/idlgen; verify pointer/array tags.
type EXECENVDATA_LEVEL2 struct {
	ExecEnvId    int32
	State        int32
	SessionName  [33]uint16
	AbsSessionId int32
	HostName     [33]uint16
	UserName     [33]uint16
	DomainName   [33]uint16
	FarmName     [33]uint16
}
