package mststs

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// ExecEnvData is a discriminated union ([MS-TSTS]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type ExecEnvData struct {
	Tag                ndr.DWORD          `ndr:"switch"`
	ExecEnvEnum_Level1 EXECENVDATA_LEVEL1 `ndr:"case=1"`
	ExecEnvEnum_Level2 EXECENVDATA_LEVEL2 `ndr:"case=2"`
}
