package mststs

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// LISTENERENUM ([MS-TSTS]). Generated by tools/idlgen; verify pointer/array tags.
type LISTENERENUM struct {
	Level ndr.DWORD
	Data  ListenerInfo
}
