package mststs

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// LISTENERENUM_LEVEL1 ([MS-TSTS]). Generated by tools/idlgen; verify pointer/array tags.
type LISTENERENUM_LEVEL1 struct {
	Id         int32
	BListening ndr.BOOL
	Name       [33]uint16
}
