package mststs

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// ListenerInfo is a discriminated union ([MS-TSTS]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type ListenerInfo struct {
	Tag                 ndr.DWORD           `ndr:"switch"`
	ListenerEnum_Level1 LISTENERENUM_LEVEL1 `ndr:"case=1"`
}
