package mststs

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// LSMSESSIONINFORMATION ([MS-TSTS]). Generated by tools/idlgen; verify pointer/array tags.
type LSMSESSIONINFORMATION struct {
	PszUserName     *ndr.WSTR `ndr:"unique"`
	PszDomain       *ndr.WSTR `ndr:"unique"`
	PszTerminalName *ndr.WSTR `ndr:"unique"`
	SessionState    int32
	DesktopLocked   ndr.BOOL
	ConnectTime     int64
	DisconnectTime  int64
	LogonTime       int64
}
