package mststs

// PROTOCOLSTATUS_INFO_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-TSTS]).
type PROTOCOLSTATUS_INFO_TYPE uint16

const (
	PROTOCOLSTATUS_INFO_BASIC    PROTOCOLSTATUS_INFO_TYPE = 0
	PROTOCOLSTATUS_INFO_EXTENDED PROTOCOLSTATUS_INFO_TYPE = 1
)
