package mststs

// QUERY_SESSION_DATA_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-TSTS]).
type QUERY_SESSION_DATA_TYPE uint16

const (
	QUERY_SESSION_DATA_MODULE             QUERY_SESSION_DATA_TYPE = 0
	QUERY_SESSION_DATA_WDCONFIG           QUERY_SESSION_DATA_TYPE = 1
	QUERY_SESSION_DATA_VIRTUALDATA        QUERY_SESSION_DATA_TYPE = 2
	QUERY_SESSION_DATA_LICENSE            QUERY_SESSION_DATA_TYPE = 3
	QUERY_SESSION_DATA_DEVICEID           QUERY_SESSION_DATA_TYPE = 4
	QUERY_SESSION_DATA_LICENSE_VALIDATION QUERY_SESSION_DATA_TYPE = 5
)
