package mststs

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// SESSIONENUM_LEVEL2 ([MS-TSTS]). Generated by tools/idlgen; verify pointer/array tags.
type SESSIONENUM_LEVEL2 struct {
	SessionId    int32
	State        int32
	Name         [33]uint16
	Source       ndr.DWORD
	BFullDesktop ndr.BOOL
	SessionType  guid.GUID
}
