package mststs

// SHADOW_PERMISSION_REQUEST selects whether the shadow target is prompted for permission
// ([MS-TSTS] 2.2.1.5, SessEnvRpc.idl). NDR transmits an enum as a 16-bit value.
type SHADOW_PERMISSION_REQUEST uint16

const (
	SHADOW_PERMISSION_REQUEST_SILENT            SHADOW_PERMISSION_REQUEST = 0
	SHADOW_PERMISSION_REQUEST_REQUESTPERMISSION SHADOW_PERMISSION_REQUEST = 1
	SHADOW_PERMISSION_REQUEST_Count             SHADOW_PERMISSION_REQUEST = 2
)
