package mststs

// SHADOW_REQUEST_RESPONSE reports the outcome of a shadow request ([MS-TSTS] 2.2.1.6,
// SessEnvRpc.idl). NDR transmits an enum as a 16-bit value.
type SHADOW_REQUEST_RESPONSE uint16

const (
	SHADOW_REQUEST_RESPONSE_ALLOW                                SHADOW_REQUEST_RESPONSE = 0
	SHADOW_REQUEST_RESPONSE_DECLINE                              SHADOW_REQUEST_RESPONSE = 1
	SHADOW_REQUEST_RESPONSE_POLICY_PERMISSION_REQUIRED           SHADOW_REQUEST_RESPONSE = 2
	SHADOW_REQUEST_RESPONSE_POLICY_DISABLED                      SHADOW_REQUEST_RESPONSE = 3
	SHADOW_REQUEST_RESPONSE_POLICY_VIEW_ONLY                     SHADOW_REQUEST_RESPONSE = 4
	SHADOW_REQUEST_RESPONSE_POLICY_VIEW_ONLY_PERMISSION_REQUIRED SHADOW_REQUEST_RESPONSE = 5
	SHADOW_REQUEST_RESPONSE_SESSION_ALREADY_CONTROLLED           SHADOW_REQUEST_RESPONSE = 6
)
