package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// QUERY_SERVICE_CONFIGW ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type QUERY_SERVICE_CONFIGW struct {
	DwServiceType      ndr.DWORD
	DwStartType        ndr.DWORD
	DwErrorControl     ndr.DWORD
	LpBinaryPathName   *ndr.WSTR `ndr:"unique"`
	LpLoadOrderGroup   *ndr.WSTR `ndr:"unique"`
	DwTagId            ndr.DWORD
	LpDependencies     *ndr.WSTR `ndr:"unique"`
	LpServiceStartName *ndr.WSTR `ndr:"unique"`
	LpDisplayName      *ndr.WSTR `ndr:"unique"`
}
