package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SC_RPC_NOTIFY_PARAMS ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type SC_RPC_NOTIFY_PARAMS struct {
	DwInfoLevel ndr.DWORD
	Field       SC_RPC_NOTIFY_PARAMS_Field
}

// SC_RPC_NOTIFY_PARAMS_Field is the [switch_is(dwInfoLevel)] union of SC_RPC_NOTIFY_PARAMS.
// Both IDL arms are [unique] pointers (P*), so each arm emits a referent id with its body
// deferred ([C706] 14.3.8). Tag is the inline 4-byte discriminant.
type SC_RPC_NOTIFY_PARAMS_Field struct {
	Tag                 ndr.DWORD                              `ndr:"switch"`
	PStatusChangeParam1 *SERVICE_NOTIFY_STATUS_CHANGE_PARAMS_1 `ndr:"case=1,unique"`
	PStatusChangeParams *SERVICE_NOTIFY_STATUS_CHANGE_PARAMS_2 `ndr:"case=2,unique"`
}
