package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SERVICE_NOTIFY_STATUS_CHANGE_PARAMS_1 ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type SERVICE_NOTIFY_STATUS_CHANGE_PARAMS_1 struct {
	UllThreadId               uint64
	DwNotifyMask              ndr.DWORD
	CallbackAddressArray      [16]uint8
	CallbackParamAddressArray [16]uint8
	ServiceStatus             SERVICE_STATUS_PROCESS
	DwNotificationStatus      ndr.DWORD
	DwSequence                ndr.DWORD
}
