package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SERVICE_CONTROL_STATUS_REASON_IN_PARAMSW ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type SERVICE_CONTROL_STATUS_REASON_IN_PARAMSW struct {
	DwReason   ndr.DWORD
	PszComment *ndr.WSTR `ndr:"unique"`
}
