package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SERVICE_SID_INFO ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type SERVICE_SID_INFO struct {
	DwServiceSidType ndr.DWORD
}
