package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SERVICE_FAILURE_ACTIONS_FLAG ([MS-SCMR]). Generated by tools/idlgen; verify pointer/array tags.
type SERVICE_FAILURE_ACTIONS_FLAG struct {
	FFailureActionsOnNonCrashFailures ndr.BOOL
}
