package structures

import (
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// ADDENTRY_REPLY_INFO ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type ADDENTRY_REPLY_INFO struct {
	ObjGuid guid.GUID
	ObjSid  NT4SID
}
