package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// ATTRBLOCK ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type ATTRBLOCK struct {
	AttrCount ndr.DWORD
	PAttr     []ATTR `ndr:"unique,size_is=AttrCount"`
}
