package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_QUERYSITESREPLY_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_QUERYSITESREPLY_V1 struct {
	CToSites   ndr.DWORD
	RgCostInfo []DRS_MSG_QUERYSITESREPLYELEMENT_V1 `ndr:"unique,size_is=CToSites"`
	DwFlags    ndr.DWORD
}
