package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_GETREPLINFO_REPLY is a discriminated union ([MS-DRSR]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type DRS_MSG_GETREPLINFO_REPLY struct {
	Tag                  ndr.DWORD                       `ndr:"switch"`
	PNeighbors           *DS_REPL_NEIGHBORSW             `ndr:"case=0,unique"`
	PCursors             *DS_REPL_CURSORS                `ndr:"case=1,unique"`
	PObjMetaData         *DS_REPL_OBJ_META_DATA          `ndr:"case=2,unique"`
	PConnectFailures     *DS_REPL_KCC_DSA_FAILURESW      `ndr:"case=3,unique"`
	PLinkFailures        *DS_REPL_KCC_DSA_FAILURESW      `ndr:"case=4,unique"`
	PPendingOps          *DS_REPL_PENDING_OPSW           `ndr:"case=5,unique"`
	PAttrValueMetaData   *DS_REPL_ATTR_VALUE_META_DATA   `ndr:"case=6,unique"`
	PCursors2            *DS_REPL_CURSORS_2              `ndr:"case=7,unique"`
	PCursors3            *DS_REPL_CURSORS_3W             `ndr:"case=8,unique"`
	PObjMetaData2        *DS_REPL_OBJ_META_DATA_2        `ndr:"case=9,unique"`
	PAttrValueMetaData2  *DS_REPL_ATTR_VALUE_META_DATA_2 `ndr:"case=10,unique"`
	PServerOutgoingCalls *DS_REPL_SERVER_OUTGOING_CALLS  `ndr:"case=4294967290,unique"`
	PUpToDateVec         *UPTODATE_VECTOR_V1_EXT         `ndr:"case=4294967291,unique"`
	PClientContexts      *DS_REPL_CLIENT_CONTEXTS        `ndr:"case=4294967292,unique"`
	PRepsTo              *DS_REPL_NEIGHBORSW             `ndr:"case=4294967294,unique"`
}
