package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_EXISTREPLY_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_EXISTREPLY_V1 struct {
	DwStatusFlags ndr.DWORD
	CNumGuids     ndr.DWORD
	RgGuids       []UUID `ndr:"unique,size_is=CNumGuids"`
}
