package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_EXISTREQ_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_EXISTREQ_V1 struct {
	GuidStart            UUID
	CGuids               ndr.DWORD
	PNC                  *DSNAME                 `ndr:"unique"`
	PUpToDateVecCommonV1 *UPTODATE_VECTOR_V1_EXT `ndr:"unique"`
	Md5Digest            [16]uint8
}
