package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// DRS_MSG_ADDENTRYREPLY_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_ADDENTRYREPLY_V1 struct {
	Guid         guid.GUID
	Sid          NT4SID
	ErrCode      ndr.DWORD
	Dsid         ndr.DWORD
	ExtendedErr  ndr.DWORD
	ExtendedData ndr.DWORD
	Problem      uint16
}
