package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_REPADD_V3 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_REPADD_V3 struct {
	PNC                 *DSNAME   `ndr:"unique"`
	PSourceDsaDN        *DSNAME   `ndr:"unique"`
	PTransportDN        *DSNAME   `ndr:"unique"`
	PszSourceDsaAddress *ndr.WSTR `ndr:"unique"`
	RtSchedule          REPLTIMES
	UlOptions           ndr.DWORD
	CorrelationID       UUID
	PReservedBuffer     *VAR_SIZE_BUFFER_WITH_VERSION `ndr:"unique"`
}
