package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_WRITENGCKEYREQ_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_WRITENGCKEYREQ_V1 struct {
	PwszAccount *ndr.WSTR `ndr:"unique"`
	CNgcKey     ndr.DWORD
	PNgcKey     []uint8 `ndr:"unique,size_is=CNgcKey"`
}
