package structures

// DRS_MSG_GETCHGREQ_V7 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_GETCHGREQ_V7 struct {
	UuidTransportObj  UUID
	PmtxReturnAddress *MTX_ADDR `ndr:"unique"`
	V3                DRS_MSG_GETCHGREQ_V3
	PPartialAttrSet   *PARTIAL_ATTR_VECTOR_V1_EXT `ndr:"unique"`
	PPartialAttrSetEx *PARTIAL_ATTR_VECTOR_V1_EXT `ndr:"unique"`
	PrefixTableDest   SCHEMA_PREFIX_TABLE
}
