package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_MOVEREPLY is a discriminated union ([MS-DRSR]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type DRS_MSG_MOVEREPLY struct {
	Tag ndr.DWORD            `ndr:"switch"`
	V1  DRS_MSG_MOVEREPLY_V1 `ndr:"case=1"`
	V2  DRS_MSG_MOVEREPLY_V2 `ndr:"case=2"`
}
