package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DS_REPL_CLIENT_CONTEXTS ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DS_REPL_CLIENT_CONTEXTS struct {
	CNumContexts ndr.DWORD
	DwReserved   ndr.DWORD
	RgContext    []DS_REPL_CLIENT_CONTEXT `ndr:"unique,size_is=CNumContexts"`
}
