package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DS_REPL_SERVER_OUTGOING_CALLS ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DS_REPL_SERVER_OUTGOING_CALLS struct {
	CNumCalls  ndr.DWORD
	DwReserved ndr.DWORD
	RgCall     []DS_REPL_SERVER_OUTGOING_CALL `ndr:"unique,size_is=CNumCalls"`
}
