package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DS_REPL_NEIGHBORSW ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DS_REPL_NEIGHBORSW struct {
	CNumNeighbors ndr.DWORD
	DwReserved    ndr.DWORD
	RgNeighbor    []DS_REPL_NEIGHBORW `ndr:"unique,size_is=CNumNeighbors"`
}
