package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DS_REPL_ATTR_VALUE_META_DATA_2 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DS_REPL_ATTR_VALUE_META_DATA_2 struct {
	CNumEntries          ndr.DWORD
	DwEnumerationContext ndr.DWORD
	RgMetaData           []DS_REPL_VALUE_META_DATA_2 `ndr:"unique,size_is=CNumEntries"`
}
