package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DS_REPL_CURSOR_3W ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DS_REPL_CURSOR_3W struct {
	UuidSourceDsaInvocationID UUID
	UsnAttributeFilter        int64
	FtimeLastSyncSuccess      FILETIME
	PszSourceDsaDN            *ndr.WSTR `ndr:"unique"`
}
