package structures

// DS_REPL_CURSOR_2 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DS_REPL_CURSOR_2 struct {
	UuidSourceDsaInvocationID UUID
	UsnAttributeFilter        int64
	FtimeLastSyncSuccess      FILETIME
}
