package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DS_REPL_CURSORS ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DS_REPL_CURSORS struct {
	CNumCursors ndr.DWORD
	DwReserved  ndr.DWORD
	RgCursor    []DS_REPL_CURSOR `ndr:"conformant,size_is=CNumCursors"`
}
