package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DS_REPL_OBJ_META_DATA ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DS_REPL_OBJ_META_DATA struct {
	CNumEntries ndr.DWORD
	DwReserved  ndr.DWORD
	RgMetaData  []DS_REPL_ATTR_META_DATA `ndr:"unique,size_is=CNumEntries"`
}
