package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DS_REPL_CURSORS_2 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DS_REPL_CURSORS_2 struct {
	CNumCursors          ndr.DWORD
	DwEnumerationContext ndr.DWORD
	RgCursor             []DS_REPL_CURSOR_2 `ndr:"conformant,size_is=CNumCursors"`
}
