package structures

// DS_REPL_OP_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-DRSR]).
type DS_REPL_OP_TYPE uint16

const (
	DS_REPL_OP_TYPE_SYNC        DS_REPL_OP_TYPE = 0
	DS_REPL_OP_TYPE_ADD         DS_REPL_OP_TYPE = 1
	DS_REPL_OP_TYPE_DELETE      DS_REPL_OP_TYPE = 2
	DS_REPL_OP_TYPE_MODIFY      DS_REPL_OP_TYPE = 3
	DS_REPL_OP_TYPE_UPDATE_REFS DS_REPL_OP_TYPE = 4
)
