package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NAMERR_DRS_WIRE_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type NAMERR_DRS_WIRE_V1 struct {
	Dsid         ndr.DWORD
	ExtendedErr  ndr.DWORD
	ExtendedData ndr.DWORD
	Problem      uint16
	PMatched     *DSNAME `ndr:"unique"`
}
