package structures

// NAMERESOP_DRS_WIRE_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type NAMERESOP_DRS_WIRE_V1 struct {
	NameRes   uint8
	UnusedPad uint8
	NextRDN   uint16
}
