package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// PROPERTY_META_DATA_EXT ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type PROPERTY_META_DATA_EXT struct {
	DwVersion          ndr.DWORD
	TimeChanged        int64
	UuidDsaOriginating UUID
	UsnOriginating     int64
}
