package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// REFERR_DRS_WIRE_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type REFERR_DRS_WIRE_V1 struct {
	Dsid         ndr.DWORD
	ExtendedErr  ndr.DWORD
	ExtendedData ndr.DWORD
	Refer        CONTREF_DRS_WIRE_V1
}
