package structures

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// VALUE_META_DATA_EXT_V3 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type VALUE_META_DATA_EXT_V3 struct {
	TimeCreated int64
	MetaData    PROPERTY_META_DATA_EXT
	Unused1     ndr.DWORD
	Unused2     ndr.DWORD
	Unused3     ndr.DWORD
	TimeExpired int64
}
