package msnspi

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// AndRestriction_r ([MS-NSPI]). Generated by tools/idlgen; verify pointer/array tags.
type AndRestriction_r struct {
	CRes  ndr.DWORD
	LpRes []Restriction_r `ndr:"unique,size_is=CRes"`
}

// OrRestriction_r is an alias for AndRestriction_r (same IDL typedef).
type OrRestriction_r = AndRestriction_r
