package msnspi

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DateTimeArray_r ([MS-NSPI]). Generated by tools/idlgen; verify pointer/array tags.
type DateTimeArray_r struct {
	CValues ndr.DWORD
	Lpft    []FILETIME `ndr:"unique,size_is=CValues"`
}
