package msnspi

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// PropertyRestriction_r ([MS-NSPI]). Generated by tools/idlgen; verify pointer/array tags.
type PropertyRestriction_r struct {
	Relop     ndr.DWORD
	UlPropTag ndr.DWORD
	LpProp    *PropertyValue_r `ndr:"unique"`
}
