package msnspi

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SizeRestriction_r ([MS-NSPI]). Generated by tools/idlgen; verify pointer/array tags.
type SizeRestriction_r struct {
	Relop     ndr.DWORD
	UlPropTag ndr.DWORD
	Cb        ndr.DWORD
}
