package msnspi

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SubRestriction_r ([MS-NSPI]). Generated by tools/idlgen; verify pointer/array tags.
type SubRestriction_r struct {
	UlSubObject ndr.DWORD
	LpRes       *Restriction_r `ndr:"unique"`
}
