// Package rpcinterface_4fc742e04a1011cf827300aa004ae673_3_0 is the descriptor for the netdfs RPC interface, abstract
// syntax 4fc742e0-4a10-11cf-8273-00aa004ae673 version 3.0 ([MS-DFSNM]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed by hand:
// the PipeName (\PIPE\netdfs, [MS-DFSNM] 2.1) is not carried by the IDL and was filled
// in from the spec. The NET_API_STATUS values the methods return are Win32 error codes
// decoded through windows/errors/win32, not redeclared here.
package rpcinterface_4fc742e04a1011cf827300aa004ae673_3_0

// IDL source: [MS-DFSNM] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-dfsnm/b471e023-618d-4c48-877f-f30c3005320c
// A fetched copy is kept at ms-dfsnm.idl in the interface directory.

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the netdfs interface. DFS servers
// use the well-known endpoint \PIPE\netdfs ([MS-DFSNM] 2.1 Transport).
const PipeName = `\netdfs`

// Opnums for the on-the-wire methods. Opnums 7, 8, 9 are "not used on the wire"
// and are omitted.
const (
	OpnumNetrDfsManagerGetVersion            uint16 = 0
	OpnumNetrDfsAdd                          uint16 = 1
	OpnumNetrDfsRemove                       uint16 = 2
	OpnumNetrDfsSetInfo                      uint16 = 3
	OpnumNetrDfsGetInfo                      uint16 = 4
	OpnumNetrDfsEnum                         uint16 = 5
	OpnumNetrDfsMove                         uint16 = 6
	OpnumNetrDfsAddFtRoot                    uint16 = 10
	OpnumNetrDfsRemoveFtRoot                 uint16 = 11
	OpnumNetrDfsAddStdRoot                   uint16 = 12
	OpnumNetrDfsRemoveStdRoot                uint16 = 13
	OpnumNetrDfsManagerInitialize            uint16 = 14
	OpnumNetrDfsAddStdRootForced             uint16 = 15
	OpnumNetrDfsGetDcAddress                 uint16 = 16
	OpnumNetrDfsSetDcAddress                 uint16 = 17
	OpnumNetrDfsFlushFtTable                 uint16 = 18
	OpnumNetrDfsAdd2                         uint16 = 19
	OpnumNetrDfsRemove2                      uint16 = 20
	OpnumNetrDfsEnumEx                       uint16 = 21
	OpnumNetrDfsSetInfo2                     uint16 = 22
	OpnumNetrDfsAddRootTarget                uint16 = 23
	OpnumNetrDfsRemoveRootTarget             uint16 = 24
	OpnumNetrDfsGetSupportedNamespaceVersion uint16 = 25
)

// The NET_API_STATUS codes netdfs methods return ([MS-DFSNM] 2.2 and the per-method
// "Return Values" tables) are not declared here. A NET_API_STATUS is a 32-bit Win32
// error rather than an NTSTATUS, and the whole of [MS-ERREF] 2.2 lives in
// [github.com/TheManticoreProject/Manticore/windows/errors/win32] as the
// win32.WIN32_ERROR type: a subset repeated here would cover a fraction of that
// 2703-code table, would render everything outside itself as an undecoded number, and
// would drift from the specification as the table is regenerated. Compare a returned
// status against win32.NERR_Success and the rest, and render it with
// win32.WIN32_ERROR.String.

// SyntaxID returns the netdfs abstract syntax identifier:
// 4fc742e0-4a10-11cf-8273-00aa004ae673, version 3.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x4fc742e0, B: 0x4a10, C: 0x11cf, D: 0x8273, E: 0x00aa004ae673},
		MajorVersion: 3,
		MinorVersion: 0,
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumNetrDfsManagerGetVersion:            "NetrDfsManagerGetVersion",
	OpnumNetrDfsAdd:                          "NetrDfsAdd",
	OpnumNetrDfsRemove:                       "NetrDfsRemove",
	OpnumNetrDfsSetInfo:                      "NetrDfsSetInfo",
	OpnumNetrDfsGetInfo:                      "NetrDfsGetInfo",
	OpnumNetrDfsEnum:                         "NetrDfsEnum",
	OpnumNetrDfsMove:                         "NetrDfsMove",
	OpnumNetrDfsAddFtRoot:                    "NetrDfsAddFtRoot",
	OpnumNetrDfsRemoveFtRoot:                 "NetrDfsRemoveFtRoot",
	OpnumNetrDfsAddStdRoot:                   "NetrDfsAddStdRoot",
	OpnumNetrDfsRemoveStdRoot:                "NetrDfsRemoveStdRoot",
	OpnumNetrDfsManagerInitialize:            "NetrDfsManagerInitialize",
	OpnumNetrDfsAddStdRootForced:             "NetrDfsAddStdRootForced",
	OpnumNetrDfsGetDcAddress:                 "NetrDfsGetDcAddress",
	OpnumNetrDfsSetDcAddress:                 "NetrDfsSetDcAddress",
	OpnumNetrDfsFlushFtTable:                 "NetrDfsFlushFtTable",
	OpnumNetrDfsAdd2:                         "NetrDfsAdd2",
	OpnumNetrDfsRemove2:                      "NetrDfsRemove2",
	OpnumNetrDfsEnumEx:                       "NetrDfsEnumEx",
	OpnumNetrDfsSetInfo2:                     "NetrDfsSetInfo2",
	OpnumNetrDfsAddRootTarget:                "NetrDfsAddRootTarget",
	OpnumNetrDfsRemoveRootTarget:             "NetrDfsRemoveRootTarget",
	OpnumNetrDfsGetSupportedNamespaceVersion: "NetrDfsGetSupportedNamespaceVersion",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
