package commands

import (
	"encoding/binary"
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/smb/smb_v20/capabilities"
	"github.com/TheManticoreProject/Manticore/network/smb/smb_v20/dialects"
	"github.com/TheManticoreProject/Manticore/network/smb/smb_v20/message/commands/codes"
	"github.com/TheManticoreProject/Manticore/network/smb/smb_v20/message/commands/command_interface"
	"github.com/TheManticoreProject/Manticore/network/smb/smb_v20/securitymode"
	"github.com/TheManticoreProject/Manticore/network/smb/smb_v20/types"
)

const (
	// NegotiateRequestStructureSize is the fixed StructureSize value the client
	// MUST set for an SMB2 NEGOTIATE Request, regardless of the number of dialects.
	NegotiateRequestStructureSize = 36

	// negotiateRequestFixedSize is the size, in bytes, of the fixed portion of
	// the body that precedes the variable Dialects array.
	negotiateRequestFixedSize = 36
)

// NegotiateRequest is the SMB2 NEGOTIATE Request body, used by the client to
// notify the server which SMB 2 Protocol dialects it understands.
//
// Source: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/e14db7ff-763a-4263-8b10-0c3944f52fc5
type NegotiateRequest struct {
	command_interface.Command

	// SecurityMode (2 bytes): Whether SMB signing is enabled or required at the client.
	SecurityMode securitymode.SecurityMode

	// Reserved (2 bytes): The client MUST set this to 0.
	Reserved types.USHORT

	// Capabilities (4 bytes): Client capabilities (0 unless the SMB 3.x family is implemented).
	Capabilities capabilities.Capabilities

	// ClientGuid (16 bytes): A GUID generated by the client.
	ClientGuid [16]byte

	// ClientStartTime (8 bytes): MUST NOT be used; the client sets this to 0. In
	// the SMB 3.1.1 dialect this 8-byte span is reinterpreted as the negotiate
	// context offset (4 bytes) + count (2 bytes) + reserved (2 bytes); when
	// Contexts is non-empty those fields are written instead of ClientStartTime.
	ClientStartTime types.UINT64

	// Dialects (variable): The 16-bit dialect revision numbers supported by the
	// client. DialectCount is derived from this slice on marshal.
	Dialects []dialects.Dialect

	// Contexts holds the SMB 3.1.1 negotiate contexts (pre-auth integrity,
	// encryption, ...) appended after the dialects array. Empty for dialects
	// below 3.1.1.
	Contexts []*NegotiateContext
}

// NewNegotiateRequest creates a new SMB2 NEGOTIATE Request.
func NewNegotiateRequest() *NegotiateRequest {
	c := &NegotiateRequest{Dialects: []dialects.Dialect{}}
	c.SetCommandCode(codes.SMB2_NEGOTIATE)
	c.StructureSize = NegotiateRequestStructureSize
	return c
}

// AddDialect appends a dialect revision number to the request.
func (c *NegotiateRequest) AddDialect(dialect dialects.Dialect) {
	c.Dialects = append(c.Dialects, dialect)
}

// Marshal serializes the NEGOTIATE Request body.
func (c *NegotiateRequest) Marshal() ([]byte, error) {
	buf := make([]byte, negotiateRequestFixedSize)
	binary.LittleEndian.PutUint16(buf[0:2], NegotiateRequestStructureSize)
	binary.LittleEndian.PutUint16(buf[2:4], uint16(len(c.Dialects)))
	binary.LittleEndian.PutUint16(buf[4:6], uint16(c.SecurityMode))
	binary.LittleEndian.PutUint16(buf[6:8], c.Reserved)
	binary.LittleEndian.PutUint32(buf[8:12], uint32(c.Capabilities))
	copy(buf[12:28], c.ClientGuid[:])
	binary.LittleEndian.PutUint64(buf[28:36], c.ClientStartTime)

	for _, dialect := range c.Dialects {
		d := make([]byte, 2)
		binary.LittleEndian.PutUint16(d, uint16(dialect))
		buf = append(buf, d...)
	}

	// SMB 3.1.1: append the negotiate contexts and record their header-relative
	// offset and count in the reinterpreted ClientStartTime span.
	if len(c.Contexts) > 0 {
		ctxBytes, firstOffset := marshalNegotiateContexts(len(buf), c.Contexts)
		binary.LittleEndian.PutUint32(buf[28:32], uint32(firstOffset))
		binary.LittleEndian.PutUint16(buf[32:34], uint16(len(c.Contexts)))
		binary.LittleEndian.PutUint16(buf[34:36], 0) // Reserved2
		buf = append(buf, ctxBytes...)
	}

	return buf, nil
}

// Unmarshal deserializes the NEGOTIATE Request body.
func (c *NegotiateRequest) Unmarshal(data []byte) (int, error) {
	if len(data) < negotiateRequestFixedSize {
		return 0, fmt.Errorf("data too short to unmarshal SMB2 NEGOTIATE Request: have %d bytes, need at least %d", len(data), negotiateRequestFixedSize)
	}

	c.StructureSize = binary.LittleEndian.Uint16(data[0:2])
	dialectCount := int(binary.LittleEndian.Uint16(data[2:4]))
	c.SecurityMode = securitymode.SecurityMode(binary.LittleEndian.Uint16(data[4:6]))
	c.Reserved = binary.LittleEndian.Uint16(data[6:8])
	c.Capabilities = capabilities.Capabilities(binary.LittleEndian.Uint32(data[8:12]))
	copy(c.ClientGuid[:], data[12:28])
	c.ClientStartTime = binary.LittleEndian.Uint64(data[28:36])

	offset := negotiateRequestFixedSize
	if len(data) < offset+dialectCount*2 {
		return 0, fmt.Errorf("data too short for %d dialects: have %d bytes from offset %d", dialectCount, len(data)-offset, offset)
	}
	c.Dialects = make([]dialects.Dialect, dialectCount)
	for i := 0; i < dialectCount; i++ {
		c.Dialects[i] = dialects.Dialect(binary.LittleEndian.Uint16(data[offset : offset+2]))
		offset += 2
	}

	// SMB 3.1.1: the reinterpreted ClientStartTime span carries the negotiate
	// context offset and count. Parse the contexts when present.
	contextOffset := int(binary.LittleEndian.Uint32(data[28:32]))
	contextCount := int(binary.LittleEndian.Uint16(data[32:34]))
	if contextCount > 0 {
		contexts, err := parseNegotiateContexts(data, contextOffset, contextCount)
		if err != nil {
			return 0, err
		}
		c.Contexts = contexts
	}

	return offset, nil
}
