package mstsch

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// TASK_USER_CRED ([MS-TSCH]). Generated by tools/idlgen; verify pointer/array tags.
type TASK_USER_CRED struct {
	UserId   *ndr.WSTR `ndr:"unique"`
	Password *ndr.WSTR `ndr:"unique"`
	Flags    ndr.DWORD
}
