package msirp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// INET_INFO_SITE_ENTRY ([MS-IRP]). Generated by tools/idlgen; verify pointer/array tags.
type INET_INFO_SITE_ENTRY struct {
	PszComment *ndr.WSTR `ndr:"unique"`
	DwInstance ndr.DWORD
}
