package msirp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// INET_INFO_SITE_LIST ([MS-IRP]). Generated by tools/idlgen; verify pointer/array tags.
type INET_INFO_SITE_LIST struct {
	CEntries   ndr.DWORD
	ASiteEntry []INET_INFO_SITE_ENTRY `ndr:"conformant,size_is=CEntries"`
}
