package msirp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// INET_INFO_IP_SEC_ENTRY ([MS-IRP]). Generated by tools/idlgen; verify pointer/array tags.
type INET_INFO_IP_SEC_ENTRY struct {
	DwMask    ndr.DWORD
	DwNetwork ndr.DWORD
}
