package msirp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// INET_INFO_STATISTICS_0 ([MS-IRP]). Generated by tools/idlgen; verify pointer/array tags.
type INET_INFO_STATISTICS_0 struct {
	CacheCtrs    INETA_CACHE_STATISTICS
	AtqCtrs      INETA_ATQ_STATISTICS
	NAuxCounters ndr.DWORD
	RgCounters   [20]ndr.DWORD
}
