package msirp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// INET_INFO_CAP_FLAGS ([MS-IRP]). Generated by tools/idlgen; verify pointer/array tags.
type INET_INFO_CAP_FLAGS struct {
	Flag ndr.DWORD
	Mask ndr.DWORD
}
