package msirp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// INET_LOG_CONFIGURATION ([MS-IRP]). Generated by tools/idlgen; verify pointer/array tags.
type INET_LOG_CONFIGURATION struct {
	InetLogType          ndr.DWORD
	IlPeriod             ndr.DWORD
	RgchLogFileDirectory [260]uint16
	CbSizeForTruncation  ndr.DWORD
	RgchDataSource       [260]uint16
	RgchTableName        [30]uint16
	RgchUserName         [257]uint16
	RgchPassword         [257]uint16
}
