package msirp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// INET_INFO_STATISTICS_INFO is a discriminated union ([MS-IRP]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type INET_INFO_STATISTICS_INFO struct {
	Tag        ndr.DWORD               `ndr:"switch"`
	InetStats0 *INET_INFO_STATISTICS_0 `ndr:"case=0,unique"`
}
