package msirp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// INETA_ATQ_STATISTICS ([MS-IRP]). Generated by tools/idlgen; verify pointer/array tags.
type INETA_ATQ_STATISTICS struct {
	TotalBlockedRequests   ndr.DWORD
	TotalRejectedRequests  ndr.DWORD
	TotalAllowedRequests   ndr.DWORD
	CurrentBlockedRequests ndr.DWORD
	MeasuredBandwidth      ndr.DWORD
}
