package msirp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// INET_INFO_VIRTUAL_ROOT_ENTRY ([MS-IRP]). Generated by tools/idlgen; verify pointer/array tags.
type INET_INFO_VIRTUAL_ROOT_ENTRY struct {
	PszRoot         *ndr.WSTR `ndr:"unique"`
	PszAddress      *ndr.WSTR `ndr:"unique"`
	PszDirectory    *ndr.WSTR `ndr:"unique"`
	DwMask          ndr.DWORD
	PszAccountName  *ndr.WSTR `ndr:"unique"`
	AccountPassword [257]uint16
	DwError         ndr.DWORD
}
