package msirp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// INET_INFO_VIRTUAL_ROOT_LIST ([MS-IRP]). Generated by tools/idlgen; verify pointer/array tags.
type INET_INFO_VIRTUAL_ROOT_LIST struct {
	CEntries       ndr.DWORD
	AVirtRootEntry []INET_INFO_VIRTUAL_ROOT_ENTRY `ndr:"conformant,size_is=CEntries"`
}
