package msirp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// INET_INFO_IP_SEC_LIST ([MS-IRP]). Generated by tools/idlgen; verify pointer/array tags.
type INET_INFO_IP_SEC_LIST struct {
	CEntries    ndr.DWORD
	AIPSecEntry []INET_INFO_IP_SEC_ENTRY `ndr:"conformant,size_is=CEntries"`
}
