package msirp

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// W3_STATISTICS_STRUCT is a discriminated union ([MS-IRP]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type W3_STATISTICS_STRUCT struct {
	Tag       ndr.DWORD        `ndr:"switch"`
	StatInfo1 *W3_STATISTICS_1 `ndr:"case=0,unique"`
}
