package msefsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	msdtyp "github.com/TheManticoreProject/Manticore/windows/ms-dtyp"
)

// ENCRYPTION_PROTECTOR ([MS-EFSR]). Generated by tools/idlgen; verify pointer/array tags.
type ENCRYPTION_PROTECTOR struct {
	CbTotalLength         ndr.DWORD
	UserSid               *msdtyp.RPC_SID `ndr:"unique"`
	LpProtectorDescriptor *ndr.WSTR       `ndr:"unique"`
}
