package msefsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// ENCRYPTION_CERTIFICATE_HASH_LIST ([MS-EFSR]). Generated by tools/idlgen; verify pointer/array tags.
type ENCRYPTION_CERTIFICATE_HASH_LIST struct {
	NCert_Hash ndr.DWORD
	Users      []*ENCRYPTION_CERTIFICATE_HASH `ndr:"elem=unique,unique,conformant"`
}
