// Package rpcinterface_378e52b0c0a911cf822d00aa0051e40f_1_0 is the descriptor for the sasec RPC interface, abstract
// syntax 378e52b0-c0a9-11cf-822d-00aa0051e40f version 1.0 ([MS-TSCH]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName, the status-code table, and doc comments are not derivable from
// the IDL and were filled in and verified by hand ([MS-TSCH] 2.1, 3.2.5).
package rpcinterface_378e52b0c0a911cf822d00aa0051e40f_1_0

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the sasec interface. Per [MS-TSCH] 2.1
// the ATSvc and SASec interfaces share the well-known ncacn_np endpoint \PIPE\atsvc.
const PipeName = `\atsvc`

// Opnums for the on-the-wire methods.
const (
	OpnumSASetAccountInformation   uint16 = 0
	OpnumSASetNSAccountInformation uint16 = 1
	OpnumSAGetNSAccountInformation uint16 = 2
	OpnumSAGetAccountInformation   uint16 = 3
)

// HRESULT status codes returned by the SASec methods ([MS-TSCH] 3.2.5.3, [MS-ERREF] 2.1).
// SASec methods return an HRESULT: a value with the high bit clear (S_OK) is success,
// otherwise a failure. Most failures are HRESULT_FROM_WIN32 forms of Win32 errors.
const (
	StatusSuccess     uint32 = 0x00000000 // S_OK
	ErrorFileNotFound uint32 = 0x80070002 // HRESULT_FROM_WIN32(ERROR_FILE_NOT_FOUND)
	ErrorAccessDenied uint32 = 0x80070005 // E_ACCESSDENIED
	ErrorInvalidData  uint32 = 0x8007000D // HRESULT_FROM_WIN32(ERROR_INVALID_DATA)
	ErrorInvalidArg   uint32 = 0x80070057 // E_INVALIDARG
	ErrorLogonFailure uint32 = 0x8007052E // HRESULT_FROM_WIN32(ERROR_LOGON_FAILURE)
)

// SyntaxID returns the sasec abstract syntax identifier:
// 378e52b0-c0a9-11cf-822d-00aa0051e40f, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x378e52b0, B: 0xc0a9, C: 0x11cf, D: 0x822d, E: 0x00aa0051e40f},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented status codes, otherwise the
// hex value.
func StatusString(status uint32) string {
	switch status {
	case StatusSuccess:
		return "S_OK"
	case ErrorFileNotFound:
		return "ERROR_FILE_NOT_FOUND"
	case ErrorAccessDenied:
		return "E_ACCESSDENIED"
	case ErrorInvalidData:
		return "ERROR_INVALID_DATA"
	case ErrorInvalidArg:
		return "E_INVALIDARG"
	case ErrorLogonFailure:
		return "ERROR_LOGON_FAILURE"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// IsSuccess reports whether an HRESULT returned by this interface indicates success
// (high bit clear, e.g. S_OK).
func IsSuccess(status uint32) bool {
	return status&0x80000000 == 0
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumSASetAccountInformation:   "SASetAccountInformation",
	OpnumSASetNSAccountInformation: "SASetNSAccountInformation",
	OpnumSAGetNSAccountInformation: "SAGetNSAccountInformation",
	OpnumSAGetAccountInformation:   "SAGetAccountInformation",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
