// Package rpcinterface_484809d64239471bb5bc61df8c23ac48_1_0 is the descriptor for the TermSrvSession RPC interface, abstract
// syntax 484809d6-4239-471b-b5bc-61df8c23ac48 version 1.0 ([MS-TSTS]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName (from [MS-TSTS] 1.9) and the status-code table are not derivable
// from the IDL and were completed by hand.
package rpcinterface_484809d64239471bb5bc61df8c23ac48_1_0

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the IPC$-relative named pipe for the TermSrvSession interface.
// The endpoint is assigned in [MS-TSTS] section 1.9 (Standards Assignments).
const PipeName = `\LSM_API_service`

// Opnums for the on-the-wire methods. Opnums 13, 14, 18, 19, 20 are "not used on the wire"
// and are omitted.
const (
	OpnumRpcOpenSession             uint16 = 0
	OpnumRpcCloseSession            uint16 = 1
	OpnumRpcConnect                 uint16 = 2
	OpnumRpcDisconnect              uint16 = 3
	OpnumRpcLogoff                  uint16 = 4
	OpnumRpcGetUserName             uint16 = 5
	OpnumRpcGetTerminalName         uint16 = 6
	OpnumRpcGetState                uint16 = 7
	OpnumRpcIsSessionDesktopLocked  uint16 = 8
	OpnumRpcShowMessageBox          uint16 = 9
	OpnumRpcGetTimes                uint16 = 10
	OpnumRpcGetSessionCounters      uint16 = 11
	OpnumRpcGetSessionInformation   uint16 = 12
	OpnumRpcGetLoggedOnCount        uint16 = 15
	OpnumRpcGetSessionType          uint16 = 16
	OpnumRpcGetSessionInformationEx uint16 = 17
	OpnumRpcGetActivityId           uint16 = 21
)

// Status codes for this interface. Its methods return an HRESULT ([MS-ERREF] 2.1);
// success is S_OK (0x00000000). The values below are the common failures; StatusString
// falls back to the raw hex for any other value.
const (
	StatusSuccess  uint32 = 0x00000000 // S_OK
	E_ABORT        uint32 = 0x80004004
	E_FAIL         uint32 = 0x80004005
	E_OUTOFMEMORY  uint32 = 0x8007000e
	E_ACCESSDENIED uint32 = 0x80070005
	E_INVALIDARG   uint32 = 0x80070057
)

// SyntaxID returns the TermSrvSession abstract syntax identifier:
// 484809d6-4239-471b-b5bc-61df8c23ac48, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x484809d6, B: 0x4239, C: 0x471b, D: 0xb5bc, E: 0x61df8c23ac48},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented status codes, otherwise the
// hex value.
func StatusString(status uint32) string {
	switch status {
	case StatusSuccess:
		return "S_OK"
	case E_ABORT:
		return "E_ABORT"
	case E_FAIL:
		return "E_FAIL"
	case E_OUTOFMEMORY:
		return "E_OUTOFMEMORY"
	case E_ACCESSDENIED:
		return "E_ACCESSDENIED"
	case E_INVALIDARG:
		return "E_INVALIDARG"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumRpcOpenSession:             "RpcOpenSession",
	OpnumRpcCloseSession:            "RpcCloseSession",
	OpnumRpcConnect:                 "RpcConnect",
	OpnumRpcDisconnect:              "RpcDisconnect",
	OpnumRpcLogoff:                  "RpcLogoff",
	OpnumRpcGetUserName:             "RpcGetUserName",
	OpnumRpcGetTerminalName:         "RpcGetTerminalName",
	OpnumRpcGetState:                "RpcGetState",
	OpnumRpcIsSessionDesktopLocked:  "RpcIsSessionDesktopLocked",
	OpnumRpcShowMessageBox:          "RpcShowMessageBox",
	OpnumRpcGetTimes:                "RpcGetTimes",
	OpnumRpcGetSessionCounters:      "RpcGetSessionCounters",
	OpnumRpcGetSessionInformation:   "RpcGetSessionInformation",
	OpnumRpcGetLoggedOnCount:        "RpcGetLoggedOnCount",
	OpnumRpcGetSessionType:          "RpcGetSessionType",
	OpnumRpcGetSessionInformationEx: "RpcGetSessionInformationEx",
	OpnumRpcGetActivityId:           "RpcGetActivityId",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
