// Package rpcinterface_82ad4280036b11cf972c00aa006887b0_2_0 is the descriptor for the inetinfo RPC interface, abstract
// syntax 82ad4280-036b-11cf-972c-00aa006887b0 version 2.0 ([MS-IRP]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName, the status-code table, and doc comments are not derivable from
// the IDL and must be confirmed by hand (see the TODO markers).
package rpcinterface_82ad4280036b11cf972c00aa006887b0_2_0

// IDL source: [MS-IRP] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-irp/ed7e5940-9700-4a1f-8555-de29f99fe115
// A fetched copy is kept at ms-irp.idl in the interface directory.

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is the named pipe for the inetinfo interface. The IDL carries no endpoint
// attribute; [MS-IRP] section 2.1.1 (Server) specifies the RPC well-known endpoint
// \PIPE\inetinfo over ncacn_np.
const PipeName = `\PIPE\inetinfo`

// Opnums for the on-the-wire methods. Opnums 16, 17 are "not used on the wire"
// and are omitted.
const (
	OpnumR_InetInfoGetVersion                uint16 = 0
	OpnumR_InetInfoGetAdminInformation       uint16 = 1
	OpnumR_InetInfoGetSites                  uint16 = 2
	OpnumR_InetInfoSetAdminInformation       uint16 = 3
	OpnumR_InetInfoGetGlobalAdminInformation uint16 = 4
	OpnumR_InetInfoSetGlobalAdminInformation uint16 = 5
	OpnumR_InetInfoQueryStatistics           uint16 = 6
	OpnumR_InetInfoClearStatistics           uint16 = 7
	OpnumR_InetInfoFlushMemoryCache          uint16 = 8
	OpnumR_InetInfoGetServerCapabilities     uint16 = 9
	OpnumR_W3QueryStatistics2                uint16 = 10
	OpnumR_W3ClearStatistics2                uint16 = 11
	OpnumR_FtpQueryStatistics2               uint16 = 12
	OpnumR_FtpClearStatistics2               uint16 = 13
	OpnumR_IISEnumerateUsers                 uint16 = 14
	OpnumR_IISDisconnectUser                 uint16 = 15
)

// Return codes. Every method of this interface returns a DWORD Win32 error code
// ([MS-ERREF] 2.2): ERROR_SUCCESS on success, otherwise an implementation-specific
// nonzero Win32 error ([MS-IRP] section 3.1.4). [MS-IRP] does not enumerate a fixed
// per-method code set, so only ERROR_SUCCESS is named here; StatusString renders any
// other value as hex.
const (
	ErrorSuccess uint32 = 0x00000000
)

// SyntaxID returns the inetinfo abstract syntax identifier:
// 82ad4280-036b-11cf-972c-00aa006887b0, version 2.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x82ad4280, B: 0x036b, C: 0x11cf, D: 0x972c, E: 0x00aa006887b0},
		MajorVersion: 2,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented return codes, otherwise the
// hex value.
func StatusString(status uint32) string {
	switch status {
	case ErrorSuccess:
		return "ERROR_SUCCESS"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumR_InetInfoGetVersion:                "R_InetInfoGetVersion",
	OpnumR_InetInfoGetAdminInformation:       "R_InetInfoGetAdminInformation",
	OpnumR_InetInfoGetSites:                  "R_InetInfoGetSites",
	OpnumR_InetInfoSetAdminInformation:       "R_InetInfoSetAdminInformation",
	OpnumR_InetInfoGetGlobalAdminInformation: "R_InetInfoGetGlobalAdminInformation",
	OpnumR_InetInfoSetGlobalAdminInformation: "R_InetInfoSetGlobalAdminInformation",
	OpnumR_InetInfoQueryStatistics:           "R_InetInfoQueryStatistics",
	OpnumR_InetInfoClearStatistics:           "R_InetInfoClearStatistics",
	OpnumR_InetInfoFlushMemoryCache:          "R_InetInfoFlushMemoryCache",
	OpnumR_InetInfoGetServerCapabilities:     "R_InetInfoGetServerCapabilities",
	OpnumR_W3QueryStatistics2:                "R_W3QueryStatistics2",
	OpnumR_W3ClearStatistics2:                "R_W3ClearStatistics2",
	OpnumR_FtpQueryStatistics2:               "R_FtpQueryStatistics2",
	OpnumR_FtpClearStatistics2:               "R_FtpClearStatistics2",
	OpnumR_IISEnumerateUsers:                 "R_IISEnumerateUsers",
	OpnumR_IISDisconnectUser:                 "R_IISDisconnectUser",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
