package mspar

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DEVMODE ([MS-PAR]). Generated by tools/idlgen; verify pointer/array tags.
type DEVMODE struct {
	DmDeviceName    [32]uint16
	DmSpecVersion   uint16
	DmDriverVersion uint16
	DmSize          uint16
	DmDriverExtra   uint16
	DmFields        ndr.DWORD
	DmOrientation   int16
	DmPaperSize     int16
	DmPaperLength   int16
	DmPaperWidth    int16
	DmScale         int16
	DmCopies        int16
	DmDefaultSource int16
	DmPrintQuality  int16
	DmColor         int16
	DmDuplex        int16
	DmYResolution   int16
	DmTTOption      int16
	DmCollate       int16
	DmFormName      [32]uint16
	Reserved0       uint16
	Reserved1       ndr.DWORD
	Reserved2       ndr.DWORD
	Reserved3       ndr.DWORD
	DmNup           ndr.DWORD
	Reserved4       ndr.DWORD
	DmICMMethod     ndr.DWORD
	DmICMIntent     ndr.DWORD
	DmMediaType     ndr.DWORD
	DmDitherType    ndr.DWORD
	Reserved5       ndr.DWORD
	Reserved6       ndr.DWORD
	Reserved7       ndr.DWORD
	Reserved8       ndr.DWORD
}
