package mspar

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// FORM_INFO_1 ([MS-PAR]). Generated by tools/idlgen; verify pointer/array tags.
type FORM_INFO_1 struct {
	Flags         ndr.DWORD
	PName         *ndr.WSTR `ndr:"unique"`
	Size          SIZE
	ImageableArea RECTL
}
