package mspar

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// JOB_INFO_1 ([MS-PAR]). Generated by tools/idlgen; verify pointer/array tags.
type JOB_INFO_1 struct {
	JobId        ndr.DWORD
	PPrinterName *ndr.WSTR `ndr:"unique"`
	PMachineName *ndr.WSTR `ndr:"unique"`
	PUserName    *ndr.WSTR `ndr:"unique"`
	PDocument    *ndr.WSTR `ndr:"unique"`
	PDatatype    *ndr.WSTR `ndr:"unique"`
	PStatus      *ndr.WSTR `ndr:"unique"`
	Status       ndr.DWORD
	Priority     ndr.DWORD
	Position     ndr.DWORD
	TotalPages   ndr.DWORD
	PagesPrinted ndr.DWORD
	Submitted    SYSTEMTIME
}
