package mspar

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_V2_NOTIFY_OPTIONS ([MS-PAR]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_V2_NOTIFY_OPTIONS struct {
	Version  ndr.DWORD
	Reserved ndr.DWORD
	Count    ndr.DWORD
	PTypes   []RPC_V2_NOTIFY_OPTIONS_TYPE `ndr:"unique,size_is=Count"`
}
