package mspar

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_BranchOfficeJobDataError ([MS-PAR]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_BranchOfficeJobDataError struct {
	LastError         ndr.DWORD
	PDocumentName     *ndr.WSTR `ndr:"unique"`
	PUserName         *ndr.WSTR `ndr:"unique"`
	PPrinterName      *ndr.WSTR `ndr:"unique"`
	PDataType         *ndr.WSTR `ndr:"unique"`
	TotalSize         int64
	PrintedSize       int64
	TotalPages        ndr.DWORD
	PrintedPages      ndr.DWORD
	PMachineName      *ndr.WSTR `ndr:"unique"`
	PJobError         *ndr.WSTR `ndr:"unique"`
	PErrorDescription *ndr.WSTR `ndr:"unique"`
}
