package mspar

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RPC_V2_NOTIFY_INFO_DATA_DATA is a discriminated union ([MS-PAR]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type RPC_V2_NOTIFY_INFO_DATA_DATA struct {
	Tag                ndr.DWORD            `ndr:"switch"`
	String             STRING_CONTAINER     `ndr:"case=TABLE_STRING"`
	DwData             ndr.DWORD            `ndr:"case=TABLE_DWORD"`
	SystemTime         SYSTEMTIME_CONTAINER `ndr:"case=TABLE_TIME"`
	DevMode            DEVMODE_CONTAINER    `ndr:"case=TABLE_DEVMODE"`
	SecurityDescriptor SECURITY_CONTAINER   `ndr:"case=TABLE_SECURITYDESCRIPTOR"`
}
