package mspar

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// SYSTEMTIME_CONTAINER ([MS-PAR]). Generated by tools/idlgen; verify pointer/array tags.
type SYSTEMTIME_CONTAINER struct {
	CbBuf       ndr.DWORD
	PSystemTime *SYSTEMTIME `ndr:"unique"`
}
