package msrpcl

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NSI_BINDING_T ([MS-RPCL]). Generated by tools/idlgen; verify pointer/array tags.
type NSI_BINDING_T struct {
	String            *ndr.WSTR `ndr:"unique"`
	Entry_name_syntax ndr.DWORD
	Entry_name        *ndr.WSTR `ndr:"unique"`
}
