package msrpcl

import (
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// RPC_SYNTAX_IDENTIFIER ([MS-RPCL]). Generated by tools/idlgen; verify pointer/array tags.
type RPC_SYNTAX_IDENTIFIER struct {
	SyntaxGUID    guid.GUID
	SyntaxVersion RPC_VERSION
}
