// Package rpcinterface_897e2e5f93f343769c9cfd2277495c27_1_0 is the descriptor for the FrsTransport RPC interface, abstract
// syntax 897e2e5f-93f3-4376-9c9c-fd2277495c27 version 1.0 ([MS-FRS2]).
//
// Generated by tools/idlgen (descriptor phase) from the IDL, then reviewed:
// the PipeName, the status-code table, and doc comments are not derivable from
// the IDL and must be confirmed by hand (see the TODO markers).
package rpcinterface_897e2e5f93f343769c9cfd2277495c27_1_0

// IDL source: [MS-FRS2] — this interface is translated from and verified
// against the protocol's authoritative IDL. Full IDL (Appendix A):
//   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-frs2/39bd498b-2a94-41b7-914e-10921d543912
// A fetched copy is kept at ms-frs2.idl in the interface directory.

import (
	"fmt"

	"github.com/TheManticoreProject/Manticore/network/dcerpc/syntax"
	"github.com/TheManticoreProject/Manticore/windows/guid"
)

// PipeName is retained for descriptor uniformity, but FrsTransport is NOT a named-pipe
// interface: [MS-FRS2] section 2.1 binds it over RPC-on-TCP (ncacn_ip_tcp) with a
// dynamic endpoint registered through the endpoint mapper, so there is no IPC$-relative
// pipe. It is left empty deliberately.
const PipeName = ``

// Opnums for the on-the-wire methods. Opnum 14 is "not used on the wire"
// and is omitted.
const (
	OpnumCheckConnectivity            uint16 = 0
	OpnumEstablishConnection          uint16 = 1
	OpnumEstablishSession             uint16 = 2
	OpnumRequestUpdates               uint16 = 3
	OpnumRequestVersionVector         uint16 = 4
	OpnumAsyncPoll                    uint16 = 5
	OpnumRequestRecords               uint16 = 6
	OpnumUpdateCancel                 uint16 = 7
	OpnumRawGetFileData               uint16 = 8
	OpnumRdcGetSignatures             uint16 = 9
	OpnumRdcPushSourceNeeds           uint16 = 10
	OpnumRdcGetFileData               uint16 = 11
	OpnumRdcClose                     uint16 = 12
	OpnumInitializeFileTransferAsync  uint16 = 13
	OpnumRawGetFileDataAsync          uint16 = 15
	OpnumRdcGetFileDataAsync          uint16 = 16
	OpnumRdcFileDataTransferKeepAlive uint16 = 17
)

// Status codes returned by the FrsTransport methods ([MS-FRS2] section 2.2.2 and the
// per-method Return Values tables). Methods return 0 on success or a nonzero Win32/FRS
// error on failure; the codes below are the FRS-specific ones documented across the
// method definitions. Additional generic Win32 errors from [MS-ERREF] may also occur.
const (
	StatusSuccess uint32 = 0x00000000

	// FRS_ERROR_CONNECTION_INVALID indicates the connection is invalid ([MS-FRS2] 3.3.4.1/3.3.4.2).
	FRS_ERROR_CONNECTION_INVALID uint32 = 0x00002342
	// FRS_ERROR_INCOMPATIBLE_VERSION indicates the client and server DFS-R protocol
	// versions are not compatible ([MS-FRS2] 3.3.4.1).
	FRS_ERROR_INCOMPATIBLE_VERSION uint32 = 0x0000235A
	// FRS_ERROR_CONTENTSET_READ_ONLY indicates the replicated folder is read-only ([MS-FRS2] 3.3.4.2).
	FRS_ERROR_CONTENTSET_READ_ONLY uint32 = 0x00002375
)

// SyntaxID returns the FrsTransport abstract syntax identifier:
// 897e2e5f-93f3-4376-9c9c-fd2277495c27, version 1.0.
func SyntaxID() syntax.SyntaxID {
	return syntax.SyntaxID{
		UUID:         guid.GUID{A: 0x897e2e5f, B: 0x93f3, C: 0x4376, D: 0x9c9c, E: 0xfd2277495c27},
		MajorVersion: 1,
		MinorVersion: 0,
	}
}

// StatusString returns a mnemonic for the documented status codes, otherwise the
// hex value.
func StatusString(status uint32) string {
	switch status {
	case StatusSuccess:
		return "ERROR_SUCCESS"
	case FRS_ERROR_CONNECTION_INVALID:
		return "FRS_ERROR_CONNECTION_INVALID"
	case FRS_ERROR_INCOMPATIBLE_VERSION:
		return "FRS_ERROR_INCOMPATIBLE_VERSION"
	case FRS_ERROR_CONTENTSET_READ_ONLY:
		return "FRS_ERROR_CONTENTSET_READ_ONLY"
	default:
		return fmt.Sprintf("0x%08x", status)
	}
}

// OpnumToName maps each on-the-wire opnum to its method name; the single source of
// truth.
var OpnumToName = map[uint16]string{
	OpnumCheckConnectivity:            "CheckConnectivity",
	OpnumEstablishConnection:          "EstablishConnection",
	OpnumEstablishSession:             "EstablishSession",
	OpnumRequestUpdates:               "RequestUpdates",
	OpnumRequestVersionVector:         "RequestVersionVector",
	OpnumAsyncPoll:                    "AsyncPoll",
	OpnumRequestRecords:               "RequestRecords",
	OpnumUpdateCancel:                 "UpdateCancel",
	OpnumRawGetFileData:               "RawGetFileData",
	OpnumRdcGetSignatures:             "RdcGetSignatures",
	OpnumRdcPushSourceNeeds:           "RdcPushSourceNeeds",
	OpnumRdcGetFileData:               "RdcGetFileData",
	OpnumRdcClose:                     "RdcClose",
	OpnumInitializeFileTransferAsync:  "InitializeFileTransferAsync",
	OpnumRawGetFileDataAsync:          "RawGetFileDataAsync",
	OpnumRdcGetFileDataAsync:          "RdcGetFileDataAsync",
	OpnumRdcFileDataTransferKeepAlive: "RdcFileDataTransferKeepAlive",
}

// NameToOpnum is the reverse of OpnumToName, built at init so the two never drift.
var NameToOpnum = func() map[string]uint16 {
	m := make(map[string]uint16, len(OpnumToName))
	for op, name := range OpnumToName {
		m[name] = op
	}
	return m
}()
