package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DOMAIN_NAME_BUFFER ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type DOMAIN_NAME_BUFFER struct {
	DomainNameByteCount ndr.DWORD
	DomainNames         []uint8 `ndr:"unique,size_is=DomainNameByteCount"`
}
