package msnrpc

import (
	msdtyp "github.com/TheManticoreProject/Manticore/windows/ms-dtyp"
)

// LSA_FOREST_TRUST_DOMAIN_INFO ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type LSA_FOREST_TRUST_DOMAIN_INFO struct {
	Sid         *msdtyp.RPC_SID `ndr:"unique"`
	DnsName     LSA_UNICODE_STRING
	NetbiosName LSA_UNICODE_STRING
}
