package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// LSA_FOREST_TRUST_INFORMATION ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type LSA_FOREST_TRUST_INFORMATION struct {
	RecordCount ndr.DWORD
	Entries     []*LSA_FOREST_TRUST_RECORD `ndr:"elem=unique,unique,size_is=RecordCount"`
}
