package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// LSA_FOREST_TRUST_BINARY_DATA ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type LSA_FOREST_TRUST_BINARY_DATA struct {
	Length ndr.DWORD
	Buffer []uint8 `ndr:"unique,size_is=Length"`
}
