package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_DELTA_DELETE_GROUP ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_DELTA_DELETE_GROUP struct {
	AccountName  *ndr.WSTR `ndr:"unique"`
	DummyString1 UNICODE_STRING
	DummyString2 UNICODE_STRING
	DummyString3 UNICODE_STRING
	DummyString4 UNICODE_STRING
	DummyLong1   ndr.DWORD
	DummyLong2   ndr.DWORD
	DummyLong3   ndr.DWORD
	DummyLong4   ndr.DWORD
}
