package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_TICKET_LOGON_INFO ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_TICKET_LOGON_INFO struct {
	Identity               NETLOGON_LOGON_IDENTITY_INFO
	RequestOptions         uint64
	ServiceTicketLength    ndr.DWORD
	ServiceTicket          []uint8 `ndr:"unique,size_is=ServiceTicketLength"`
	AdditionalTicketLength ndr.DWORD
	AdditionalTicket       []uint8 `ndr:"unique,size_is=AdditionalTicketLength"`
}
