package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	msdtyp "github.com/TheManticoreProject/Manticore/windows/ms-dtyp"
)

// NETLOGON_SID_AND_ATTRIBUTES ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_SID_AND_ATTRIBUTES struct {
	Sid        *msdtyp.RPC_SID `ndr:"unique"`
	Attributes ndr.DWORD
}
