package msnrpc

// NETLOGON_DELTA_ENUM ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_DELTA_ENUM struct {
	DeltaType  NETLOGON_DELTA_TYPE
	DeltaID    NETLOGON_DELTA_ID_UNION
	DeltaUnion NETLOGON_DELTA_UNION
}
