package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_VALIDATION_TICKET_LOGON ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_VALIDATION_TICKET_LOGON struct {
	Results            uint64
	KerberosStatus     ndr.DWORD
	NetlogonStatus     ndr.DWORD
	SourceOfStatus     UNICODE_STRING
	UserInformation    *NETLOGON_VALIDATION_SAM_INFO4 `ndr:"unique"`
	DeviceInformation  *NETLOGON_VALIDATION_SAM_INFO4 `ndr:"unique"`
	UserClaimsLength   ndr.DWORD
	UserClaims         []uint8 `ndr:"unique,size_is=UserClaimsLength"`
	DeviceClaimsLength ndr.DWORD
	DeviceClaims       []uint8 `ndr:"unique,size_is=DeviceClaimsLength"`
}
