package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_INFO_2 ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_INFO_2 struct {
	Netlog2_flags                 ndr.DWORD
	Netlog2_pdc_connection_status ndr.DWORD
	Netlog2_trusted_dc_name       *ndr.WSTR `ndr:"unique"`
	Netlog2_tc_connection_status  ndr.DWORD
}
