package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_DOMAIN_INFO ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_DOMAIN_INFO struct {
	PrimaryDomain      NETLOGON_ONE_DOMAIN_INFO
	TrustedDomainCount ndr.DWORD
	TrustedDomains     []NETLOGON_ONE_DOMAIN_INFO `ndr:"unique,size_is=TrustedDomainCount"`
	LsaPolicy          NETLOGON_LSA_POLICY_INFO
	DnsHostNameInDs    UNICODE_STRING
	DummyString2       UNICODE_STRING
	DummyString3       UNICODE_STRING
	DummyString4       UNICODE_STRING
	WorkstationFlags   ndr.DWORD
	SupportedEncTypes  ndr.DWORD
	DummyLong3         ndr.DWORD
	DummyLong4         ndr.DWORD
}
