package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_GENERIC_INFO ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_GENERIC_INFO struct {
	Identity    NETLOGON_LOGON_IDENTITY_INFO
	PackageName UNICODE_STRING
	DataLength  ndr.DWORD
	LogonData   []uint8 `ndr:"unique,size_is=DataLength"`
}
