package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_WORKSTATION_INFORMATION is a discriminated union ([MS-NRPC]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type NETLOGON_WORKSTATION_INFORMATION struct {
	Tag             ndr.DWORD                 `ndr:"switch"`
	WorkstationInfo NETLOGON_WORKSTATION_INFO `ndr:"case=1"`
	LsaPolicyInfo   NETLOGON_WORKSTATION_INFO `ndr:"case=2"`
}
