package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_INFO_1 ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_INFO_1 struct {
	Netlog1_flags                 ndr.DWORD
	Netlog1_pdc_connection_status ndr.DWORD
}
