package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/dtyp"
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_VALIDATION_SAM_INFO2 ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_VALIDATION_SAM_INFO2 struct {
	LogonTime          OLD_LARGE_INTEGER
	LogoffTime         OLD_LARGE_INTEGER
	KickOffTime        OLD_LARGE_INTEGER
	PasswordLastSet    OLD_LARGE_INTEGER
	PasswordCanChange  OLD_LARGE_INTEGER
	PasswordMustChange OLD_LARGE_INTEGER
	EffectiveName      UNICODE_STRING
	FullName           UNICODE_STRING
	LogonScript        UNICODE_STRING
	ProfilePath        UNICODE_STRING
	HomeDirectory      UNICODE_STRING
	HomeDirectoryDrive UNICODE_STRING
	LogonCount         uint16
	BadPasswordCount   uint16
	UserId             ndr.DWORD
	PrimaryGroupId     ndr.DWORD
	GroupCount         ndr.DWORD
	GroupIds           []GROUP_MEMBERSHIP `ndr:"unique,size_is=GroupCount"`
	UserFlags          ndr.DWORD
	UserSessionKey     USER_SESSION_KEY
	LogonServer        UNICODE_STRING
	LogonDomainName    UNICODE_STRING
	LogonDomainId      *dtyp.RPC_SID `ndr:"unique"`
	ExpansionRoom      [10]ndr.DWORD
	SidCount           ndr.DWORD
	ExtraSids          []NETLOGON_SID_AND_ATTRIBUTES `ndr:"unique,size_is=SidCount"`
}
