package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_DELTA_DOMAIN ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_DELTA_DOMAIN struct {
	DomainName               UNICODE_STRING
	OemInformation           UNICODE_STRING
	ForceLogoff              OLD_LARGE_INTEGER
	MinPasswordLength        uint16
	PasswordHistoryLength    uint16
	MaxPasswordAge           OLD_LARGE_INTEGER
	MinPasswordAge           OLD_LARGE_INTEGER
	DomainModifiedCount      OLD_LARGE_INTEGER
	DomainCreationTime       OLD_LARGE_INTEGER
	SecurityInformation      ndr.DWORD
	SecuritySize             ndr.DWORD
	SecurityDescriptor       []uint8 `ndr:"unique,size_is=SecuritySize"`
	DomainLockoutInformation UNICODE_STRING
	DummyString2             UNICODE_STRING
	DummyString3             UNICODE_STRING
	DummyString4             UNICODE_STRING
	PasswordProperties       ndr.DWORD
	DummyLong2               ndr.DWORD
	DummyLong3               ndr.DWORD
	DummyLong4               ndr.DWORD
}
