package msnrpc

// NETLOGON_DELTA_UNION is a discriminated union ([MS-NRPC]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type NETLOGON_DELTA_UNION struct {
	Tag                   NETLOGON_DELTA_TYPE            `ndr:"switch"`
	DeltaDomain           NETLOGON_DELTA_DOMAIN          `ndr:"case=1"`
	DeltaGroup            NETLOGON_DELTA_GROUP           `ndr:"case=2"`
	DeltaRenameGroup      NETLOGON_RENAME_GROUP          `ndr:"case=4"`
	DeltaUser             NETLOGON_DELTA_USER            `ndr:"case=5"`
	DeltaRenameUser       NETLOGON_RENAME_USER           `ndr:"case=7"`
	DeltaGroupMember      NETLOGON_DELTA_GROUP_MEMBER    `ndr:"case=8"`
	DeltaAlias            NETLOGON_DELTA_ALIAS           `ndr:"case=9"`
	DeltaRenameAlias      NETLOGON_RENAME_ALIAS          `ndr:"case=11"`
	DeltaAliasMember      NETLOGON_DELTA_ALIAS_MEMBER    `ndr:"case=12"`
	DeltaPolicy           NETLOGON_DELTA_POLICY          `ndr:"case=13"`
	DeltaTDomains         NETLOGON_DELTA_TRUSTED_DOMAINS `ndr:"case=14"`
	DeltaAccounts         NETLOGON_DELTA_ACCOUNTS        `ndr:"case=16"`
	DeltaSecret           NETLOGON_DELTA_SECRET          `ndr:"case=18"`
	DeltaDeleteGroup      NETLOGON_DELTA_DELETE_GROUP    `ndr:"case=20"`
	DeltaDeleteUser       NETLOGON_DELTA_DELETE_USER     `ndr:"case=21"`
	DeltaSerialNumberSkip NLPR_MODIFIED_COUNT            `ndr:"case=22"`
}
