package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_DELTA_ACCOUNTS ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_DELTA_ACCOUNTS struct {
	PrivilegeEntries    ndr.DWORD
	PrivilegeControl    ndr.DWORD
	PrivilegeAttributes []ndr.DWORD      `ndr:"unique,size_is=PrivilegeEntries"`
	PrivilegeNames      []UNICODE_STRING `ndr:"unique,size_is=PrivilegeEntries"`
	QuotaLimits         NLPR_QUOTA_LIMITS
	SystemAccessFlags   ndr.DWORD
	SecurityInformation ndr.DWORD
	SecuritySize        ndr.DWORD
	SecurityDescriptor  []uint8 `ndr:"unique,size_is=SecuritySize"`
	DummyString1        UNICODE_STRING
	DummyString2        UNICODE_STRING
	DummyString3        UNICODE_STRING
	DummyString4        UNICODE_STRING
	DummyLong1          ndr.DWORD
	DummyLong2          ndr.DWORD
	DummyLong3          ndr.DWORD
	DummyLong4          ndr.DWORD
}
