package msnrpc

// NETLOGON_NETWORK_INFO ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_NETWORK_INFO struct {
	Identity            NETLOGON_LOGON_IDENTITY_INFO
	LmChallenge         LM_CHALLENGE
	NtChallengeResponse STRING
	LmChallengeResponse STRING
}
