package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_TRUSTED_DOMAIN_ARRAY ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_TRUSTED_DOMAIN_ARRAY struct {
	DomainCount ndr.DWORD
	Domains     []DS_DOMAIN_TRUSTSW `ndr:"unique,size_is=DomainCount"`
}
