package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_LSA_POLICY_INFO ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_LSA_POLICY_INFO struct {
	LsaPolicySize ndr.DWORD
	LsaPolicy     []uint8 `ndr:"unique,size_is=LsaPolicySize"`
}
