package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_VALIDATION_UAS_INFO ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_VALIDATION_UAS_INFO struct {
	Usrlog1_eff_name       *ndr.WSTR `ndr:"unique"`
	Usrlog1_priv           ndr.DWORD
	Usrlog1_auth_flags     ndr.DWORD
	Usrlog1_num_logons     ndr.DWORD
	Usrlog1_bad_pw_count   ndr.DWORD
	Usrlog1_last_logon     ndr.DWORD
	Usrlog1_last_logoff    ndr.DWORD
	Usrlog1_logoff_time    ndr.DWORD
	Usrlog1_kickoff_time   ndr.DWORD
	Usrlog1_password_age   ndr.DWORD
	Usrlog1_pw_can_change  ndr.DWORD
	Usrlog1_pw_must_change ndr.DWORD
	Usrlog1_computer       *ndr.WSTR `ndr:"unique"`
	Usrlog1_domain         *ndr.WSTR `ndr:"unique"`
	Usrlog1_script_path    *ndr.WSTR `ndr:"unique"`
	Usrlog1_reserved1      ndr.DWORD
}
