package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_DOMAIN_INFORMATION is a discriminated union ([MS-NRPC]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type NETLOGON_DOMAIN_INFORMATION struct {
	Tag           ndr.DWORD                `ndr:"switch"`
	DomainInfo    NETLOGON_DOMAIN_INFO     `ndr:"case=1"`
	LsaPolicyInfo NETLOGON_LSA_POLICY_INFO `ndr:"case=2"`
}
