package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_CONTROL_QUERY_INFORMATION is a discriminated union ([MS-NRPC]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type NETLOGON_CONTROL_QUERY_INFORMATION struct {
	Tag           ndr.DWORD       `ndr:"switch"`
	NetlogonInfo1 NETLOGON_INFO_1 `ndr:"case=1"`
	NetlogonInfo2 NETLOGON_INFO_2 `ndr:"case=2"`
	NetlogonInfo3 NETLOGON_INFO_3 `ndr:"case=3"`
	NetlogonInfo4 NETLOGON_INFO_4 `ndr:"case=4"`
}
