package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/dtyp"
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NETLOGON_VALIDATION_SAM_INFO4 ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_VALIDATION_SAM_INFO4 struct {
	LogonTime            OLD_LARGE_INTEGER
	LogoffTime           OLD_LARGE_INTEGER
	KickOffTime          OLD_LARGE_INTEGER
	PasswordLastSet      OLD_LARGE_INTEGER
	PasswordCanChange    OLD_LARGE_INTEGER
	PasswordMustChange   OLD_LARGE_INTEGER
	EffectiveName        UNICODE_STRING
	FullName             UNICODE_STRING
	LogonScript          UNICODE_STRING
	ProfilePath          UNICODE_STRING
	HomeDirectory        UNICODE_STRING
	HomeDirectoryDrive   UNICODE_STRING
	LogonCount           uint16
	BadPasswordCount     uint16
	UserId               ndr.DWORD
	PrimaryGroupId       ndr.DWORD
	GroupCount           ndr.DWORD
	GroupIds             []GROUP_MEMBERSHIP `ndr:"unique,size_is=GroupCount"`
	UserFlags            ndr.DWORD
	UserSessionKey       USER_SESSION_KEY
	LogonServer          UNICODE_STRING
	LogonDomainName      UNICODE_STRING
	LogonDomainId        *dtyp.RPC_SID `ndr:"unique"`
	LMKey                [8]uint8
	UserAccountControl   ndr.DWORD
	SubAuthStatus        ndr.DWORD
	LastSuccessfulILogon OLD_LARGE_INTEGER
	LastFailedILogon     OLD_LARGE_INTEGER
	FailedILogonCount    ndr.DWORD
	Reserved4            [1]ndr.DWORD
	SidCount             ndr.DWORD
	ExtraSids            []NETLOGON_SID_AND_ATTRIBUTES `ndr:"unique,size_is=SidCount"`
	DnsLogonDomainName   UNICODE_STRING
	Upn                  UNICODE_STRING
	ExpansionString1     UNICODE_STRING
	ExpansionString2     UNICODE_STRING
	ExpansionString3     UNICODE_STRING
	ExpansionString4     UNICODE_STRING
	ExpansionString5     UNICODE_STRING
	ExpansionString6     UNICODE_STRING
	ExpansionString7     UNICODE_STRING
	ExpansionString8     UNICODE_STRING
	ExpansionString9     UNICODE_STRING
	ExpansionString10    UNICODE_STRING
}
