package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
	msdtyp "github.com/TheManticoreProject/Manticore/windows/ms-dtyp"
)

// NETLOGON_DELTA_POLICY ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_DELTA_POLICY struct {
	MaximumLogSize         ndr.DWORD
	AuditRetentionPeriod   OLD_LARGE_INTEGER
	AuditingMode           uint8
	MaximumAuditEventCount ndr.DWORD
	EventAuditingOptions   []ndr.DWORD `ndr:"unique,conformant"`
	PrimaryDomainName      UNICODE_STRING
	PrimaryDomainSid       *msdtyp.RPC_SID `ndr:"unique"`
	QuotaLimits            NLPR_QUOTA_LIMITS
	ModifiedId             OLD_LARGE_INTEGER
	DatabaseCreationTime   OLD_LARGE_INTEGER
	SecurityInformation    ndr.DWORD
	SecuritySize           ndr.DWORD
	SecurityDescriptor     []uint8 `ndr:"unique,size_is=SecuritySize"`
	DummyString1           UNICODE_STRING
	DummyString2           UNICODE_STRING
	DummyString3           UNICODE_STRING
	DummyString4           UNICODE_STRING
	DummyLong1             ndr.DWORD
	DummyLong2             ndr.DWORD
	DummyLong3             ndr.DWORD
	DummyLong4             ndr.DWORD
}
