package msnrpc

// NETLOGON_INTERACTIVE_INFO ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NETLOGON_INTERACTIVE_INFO struct {
	Identity      NETLOGON_LOGON_IDENTITY_INFO
	LmOwfPassword LM_OWF_PASSWORD
	NtOwfPassword NT_OWF_PASSWORD
}
