package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NL_DNS_NAME_INFO ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NL_DNS_NAME_INFO struct {
	Type              ndr.DWORD
	DnsDomainInfo     *ndr.WSTR `ndr:"unique"`
	DnsDomainInfoType ndr.DWORD
	Priority          ndr.DWORD
	Weight            ndr.DWORD
	Port              ndr.DWORD
	Register          uint8
	Status            ndr.DWORD
}
