package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NL_OSVERSIONINFO_V1 ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NL_OSVERSIONINFO_V1 struct {
	DwOSVersionInfoSize ndr.DWORD
	DwMajorVersion      ndr.DWORD
	DwMinorVersion      ndr.DWORD
	DwBuildNumber       ndr.DWORD
	DwPlatformId        ndr.DWORD
	SzCSDVersion        [128]uint16
	WServicePackMajor   uint16
	WServicePackMinor   uint16
	WSuiteMask          uint16
	WProductType        uint8
	WReserved           uint8
}
