package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NL_OUT_CHAIN_SET_CLIENT_ATTRIBUTES is a discriminated union ([MS-NRPC]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type NL_OUT_CHAIN_SET_CLIENT_ATTRIBUTES struct {
	Tag ndr.DWORD                             `ndr:"switch"`
	V1  NL_OUT_CHAIN_SET_CLIENT_ATTRIBUTES_V1 `ndr:"case=1"`
}
