package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NL_PASSWORD_VERSION ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NL_PASSWORD_VERSION struct {
	ReservedField          ndr.DWORD
	PasswordVersionNumber  ndr.DWORD
	PasswordVersionPresent ndr.DWORD
}
