package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NL_SITE_NAME_ARRAY ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NL_SITE_NAME_ARRAY struct {
	EntryCount ndr.DWORD
	SiteNames  []UNICODE_STRING `ndr:"unique,size_is=EntryCount"`
}
