package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NLPR_CR_CIPHER_VALUE ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NLPR_CR_CIPHER_VALUE struct {
	Length        ndr.DWORD
	MaximumLength ndr.DWORD
	Buffer        []uint8 `ndr:"unique,size_is=MaximumLength,varying,length_is=Length"`
}
