package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NLPR_SID_ARRAY ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NLPR_SID_ARRAY struct {
	Count ndr.DWORD
	Sids  []NLPR_SID_INFORMATION `ndr:"unique,size_is=Count"`
}
