package msnrpc

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// NLPR_QUOTA_LIMITS ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type NLPR_QUOTA_LIMITS struct {
	PagedPoolLimit        ndr.DWORD
	NonPagedPoolLimit     ndr.DWORD
	MinimumWorkingSetSize ndr.DWORD
	MaximumWorkingSetSize ndr.DWORD
	PagefileLimit         ndr.DWORD
	Reserved              OLD_LARGE_INTEGER
}
