package msnrpc

// STRING ([MS-NRPC]). Generated by tools/idlgen; verify pointer/array tags.
type STRING struct {
	Length        uint16
	MaximumLength uint16
	Buffer        []int8 `ndr:"unique,size_is=MaximumLength,varying,length_is=Length"`
}
