package mseven6

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// BooleanArray ([MS-EVEN6]). Generated by tools/idlgen; verify pointer/array tags.
type BooleanArray struct {
	Count ndr.DWORD
	Ptr   []bool `ndr:"unique,size_is=Count"`
}
