package mseven6

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// RpcInfo ([MS-EVEN6]). Generated by tools/idlgen; verify pointer/array tags.
type RpcInfo struct {
	M_error       ndr.DWORD
	M_subErr      ndr.DWORD
	M_subErrParam ndr.DWORD
}
