package mseven6

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// StringArray ([MS-EVEN6]). Generated by tools/idlgen; verify pointer/array tags.
type StringArray struct {
	Count ndr.DWORD
	Ptr   []*ndr.WSTR `ndr:"elem=unique,unique,size_is=Count"`
}
