package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// ATTRVAL ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type ATTRVAL struct {
	ValLen ndr.DWORD
	PVal   []uint8 `ndr:"unique,size_is=ValLen"`
}
