package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_ADDENTRYREPLY_V3 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_ADDENTRYREPLY_V3 struct {
	PdsErrObject  *DSNAME `ndr:"unique"`
	DwErrVer      ndr.DWORD
	PErrData      *DRS_ERROR_DATA `ndr:"unique"`
	CObjectsAdded ndr.DWORD
	InfoList      []ADDENTRY_REPLY_INFO `ndr:"unique,size_is=CObjectsAdded"`
}
