package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_UPDREFS_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_UPDREFS_V1 struct {
	PNC            *DSNAME   `ndr:"unique"`
	PszDsaDest     *ndr.WSTR `ndr:"unique"`
	UuidDsaObjDest UUID
	UlOptions      ndr.DWORD
}
