package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_ADDCLONEDCREPLY_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_ADDCLONEDCREPLY_V1 struct {
	PwszCloneDCName         *ndr.WSTR `ndr:"unique"`
	PwszSite                *ndr.WSTR `ndr:"unique"`
	CPasswordLength         ndr.DWORD
	PwsNewDCAccountPassword []uint16 `ndr:"unique,size_is=CPasswordLength"`
}
