package msdrsr

// DRS_COMP_ALG_TYPE is an NDR enum, transmitted as a 16-bit value ([C706] 14.3.6, [MS-DRSR]).
type DRS_COMP_ALG_TYPE uint16

const (
	DRS_COMP_ALG_NONE   DRS_COMP_ALG_TYPE = 0
	DRS_COMP_ALG_UNUSED DRS_COMP_ALG_TYPE = 1
	DRS_COMP_ALG_MSZIP  DRS_COMP_ALG_TYPE = 2
	DRS_COMP_ALG_WIN2K3 DRS_COMP_ALG_TYPE = 3
)
