package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_REPADD_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_REPADD_V1 struct {
	PNC        *DSNAME   `ndr:"unique"`
	PszDsaSrc  *ndr.WSTR `ndr:"unique"`
	RtSchedule REPLTIMES
	UlOptions  ndr.DWORD
}
