package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_GETCHGREQ is a discriminated union ([MS-DRSR]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type DRS_MSG_GETCHGREQ struct {
	Tag ndr.DWORD             `ndr:"switch"`
	V4  DRS_MSG_GETCHGREQ_V4  `ndr:"case=4"`
	V5  DRS_MSG_GETCHGREQ_V5  `ndr:"case=5"`
	V7  DRS_MSG_GETCHGREQ_V7  `ndr:"case=7"`
	V8  DRS_MSG_GETCHGREQ_V8  `ndr:"case=8"`
	V10 DRS_MSG_GETCHGREQ_V10 `ndr:"case=10"`
	V11 DRS_MSG_GETCHGREQ_V11 `ndr:"case=11"`
}
