package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_QUERYSITESREQ is a discriminated union ([MS-DRSR]); the discriminant precedes the
// selected arm ([C706] 14.3.8). Generated by tools/idlgen — verify case values.
type DRS_MSG_QUERYSITESREQ struct {
	Tag ndr.DWORD                `ndr:"switch"`
	V1  DRS_MSG_QUERYSITESREQ_V1 `ndr:"case=1"`
}
