package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_QUERYSITESREQ_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_QUERYSITESREQ_V1 struct {
	PwszFromSite *ndr.WSTR `ndr:"unique"`
	CToSites     ndr.DWORD
	RgszToSites  []*ndr.WSTR `ndr:"unique,size_is=CToSites"` // IDL: [string] WCHAR **rgszToSites (array of strings)
	DwFlags      ndr.DWORD
}
