package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_GETCHGREQ_V3 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_GETCHGREQ_V3 struct {
	UuidDsaObjDest        UUID
	UuidInvocIdSrc        UUID
	PNC                   *DSNAME `ndr:"unique"`
	UsnvecFrom            USN_VECTOR
	PUpToDateVecDestV1    *UPTODATE_VECTOR_V1_EXT     `ndr:"unique"`
	PPartialAttrVecDestV1 *PARTIAL_ATTR_VECTOR_V1_EXT `ndr:"unique"`
	PrefixTableDest       SCHEMA_PREFIX_TABLE
	UlFlags               ndr.DWORD
	CMaxObjects           ndr.DWORD
	CMaxBytes             ndr.DWORD
	UlExtendedOp          ndr.DWORD
}
