package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_ADDSIDREQ_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_ADDSIDREQ_V1 struct {
	Flags                  ndr.DWORD
	SrcDomain              *ndr.WSTR `ndr:"unique"`
	SrcPrincipal           *ndr.WSTR `ndr:"unique"`
	SrcDomainController    *ndr.WSTR `ndr:"unique"`
	SrcCredsUserLength     ndr.DWORD
	SrcCredsUser           []uint16 `ndr:"unique,size_is=SrcCredsUserLength"`
	SrcCredsDomainLength   ndr.DWORD
	SrcCredsDomain         []uint16 `ndr:"unique,size_is=SrcCredsDomainLength"`
	SrcCredsPasswordLength ndr.DWORD
	SrcCredsPassword       []uint16  `ndr:"unique,size_is=SrcCredsPasswordLength"`
	DstDomain              *ndr.WSTR `ndr:"unique"`
	DstPrincipal           *ndr.WSTR `ndr:"unique"`
}
