package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_RMDMNREPLY_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_RMDMNREPLY_V1 struct {
	Reserved ndr.DWORD
}
