package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_MSG_UPDREFS_V2 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_MSG_UPDREFS_V2 struct {
	PNC             *DSNAME   `ndr:"unique"`
	PszDsaDest      *ndr.WSTR `ndr:"unique"`
	UuidDsaObjDest  UUID
	UlOptions       ndr.DWORD
	CorrelationID   UUID
	PReservedBuffer *VAR_SIZE_BUFFER_WITH_VERSION `ndr:"unique"`
}
