package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DRS_ERROR_DATA_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DRS_ERROR_DATA_V1 struct {
	DwRepError ndr.DWORD
	ErrCode    ndr.DWORD
	PErrInfo   *DIRERR_DRS_WIRE_V1 `ndr:"unique"`
}
