package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DS_DOMAIN_CONTROLLER_INFO_FFFFFFFFW ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DS_DOMAIN_CONTROLLER_INFO_FFFFFFFFW struct {
	IPAddress         ndr.DWORD
	NotificationCount ndr.DWORD
	SecTimeConnected  ndr.DWORD
	Flags             ndr.DWORD
	TotalRequests     ndr.DWORD
	Reserved1         ndr.DWORD
	UserName          *ndr.WSTR `ndr:"unique"`
}
