package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DS_DOMAIN_CONTROLLER_INFO_1W ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DS_DOMAIN_CONTROLLER_INFO_1W struct {
	NetbiosName        *ndr.WSTR `ndr:"unique"`
	DnsHostName        *ndr.WSTR `ndr:"unique"`
	SiteName           *ndr.WSTR `ndr:"unique"`
	ComputerObjectName *ndr.WSTR `ndr:"unique"`
	ServerObjectName   *ndr.WSTR `ndr:"unique"`
	FIsPdc             ndr.BOOL
	FDsEnabled         ndr.BOOL
}
