package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/ndr"
)

// DS_REPL_SERVER_OUTGOING_CALL ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DS_REPL_SERVER_OUTGOING_CALL struct {
	PszServerName        *ndr.WSTR `ndr:"unique"`
	FIsHandleBound       ndr.BOOL
	FIsHandleFromCache   ndr.BOOL
	FIsHandleInCache     ndr.BOOL
	DwThreadId           ndr.DWORD
	DwBindingTimeoutMins ndr.DWORD
	DstimeCreated        int64
	DwCallType           ndr.DWORD
}
