package msdrsr

import (
	"github.com/TheManticoreProject/Manticore/network/dcerpc/dtyp"
)

// DSA_ADDRESS_LIST_DRS_WIRE_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type DSA_ADDRESS_LIST_DRS_WIRE_V1 struct {
	PNextAddress *DSA_ADDRESS_LIST_DRS_WIRE_V1 `ndr:"unique"`
	PAddress     *dtyp.RPC_UNICODE_STRING      `ndr:"unique"`
}
