package msdrsr

import (
	msdtyp "github.com/TheManticoreProject/Manticore/windows/ms-dtyp"
)

// NT4_REPLICATION_STATE ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type NT4_REPLICATION_STATE struct {
	SamSerialNumber     msdtyp.LARGE_INTEGER
	SamCreationTime     msdtyp.LARGE_INTEGER
	BuiltinSerialNumber msdtyp.LARGE_INTEGER
	BuiltinCreationTime msdtyp.LARGE_INTEGER
	LsaSerialNumber     msdtyp.LARGE_INTEGER
	LsaCreationTime     msdtyp.LARGE_INTEGER
}
