package msdrsr

// PROBLEMLIST_DRS_WIRE_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type PROBLEMLIST_DRS_WIRE_V1 struct {
	PNextProblem *PROBLEMLIST_DRS_WIRE_V1 `ndr:"unique"`
	Intprob      INTFORMPROB_DRS_WIRE_V1
}
