package msdrsr

// VALUE_META_DATA_EXT_V1 ([MS-DRSR]). Generated by tools/idlgen; verify pointer/array tags.
type VALUE_META_DATA_EXT_V1 struct {
	TimeCreated int64
	MetaData    PROPERTY_META_DATA_EXT
}
